"""OpenMaxFire - open tooling for Bixby MaxFire 110/115."""

from .audit import AuditEvent, AuditSpan, AuditTrail

from .checkout import (
    CHECKOUT_TESTS,
    CheckoutOutcome,
    CheckoutPlan,
    CheckoutReport,
    CheckoutResult,
    CheckoutTestDefinition,
    checkout_test,
    plan_checkout_test,
)
from .client import CommandReceipt, MaxFireClient, StoveIdentity
from .configuration import (
    ConfigurationChange,
    ConfigurationField,
    ConfigurationImage,
    ConfigurationPlan,
    ConfigurationSchema,
    ConfigurationValidation,
    configuration_schema,
    plan_configuration_restore,
    plan_configuration_update,
)
from .control import (
    ControlAction,
    ControlOutcome,
    ControlPlan,
    ControlResult,
    plan_control,
)
from .discovery import (
    DetectionResult,
    DetectionStatus,
    DiscoveryReport,
    detect_controller,
    detect_controllers,
)
from .errors import (
    CapabilityUnavailableError,
    LoaderUnavailableError,
    OpenMaxFireError,
    SafetyInterlockError,
    UnsupportedControllerError,
    VerificationError,
)
from .firmware import (
    FirmwareCompatibility,
    FirmwareImage,
    FirmwareImageError,
    FirmwareVariant,
    IntelHexImage,
    ProgramBlock,
    assess_firmware_compatibility,
    build_program_blocks,
    loader_state_machine_supported,
    parse_intel_hex,
)
from .firmware_catalog import (
    FIRMWARE_CORPUS,
    FirmwareCorpusEntry,
    FirmwareCorpusReport,
    FirmwareCorpusValidation,
    validate_firmware_corpus,
)
from .loader import (
    LoaderBlockReceipt,
    LoaderPlan,
    LoaderPolicy,
    LoaderResult,
    LoaderState,
    build_loader_plan,
    execute_loader_plan,
    live_loader_supported,
    loader_simulation_supported,
)
from .models import (
    AlarmState,
    PanelButtons,
    PhysicalInputs,
    StoveSnapshot,
    TelemetryMeasurements,
    decode_stove_snapshot,
)
from .monitor import MonitorState, replay_capture
from .profiles import (
    Capability,
    CapabilityState,
    ControllerCapabilities,
    ControllerProfile,
    PROFILES,
    PROFILES_BY_KEY,
    TelemetryLayout,
    profile_for_data_format,
    select_profile,
)
from .protocol import (
    IgniterState,
    OperatingState,
    RemoteButton,
    combine_telemetry_word,
    decode_igniter_state,
    decode_operating_state,
    encode_read_register,
    encode_write_register,
)
from .transactions import (
    TransactionOperation,
    TransactionPlan,
    execute_transaction,
    load_transaction_plan,
    parse_transaction_plan,
)
from .simulator import (
    SimulatedController,
    SimulatedLoaderFaults,
    SimulatedLoaderTransport,
    SimulatedTransport,
    SimulatedTransportFactory,
    SimulationFaults,
)
from .session import ConnectionInfo, ControllerSession
from .services import (
    READ_ONLY_CHECKOUT_TESTS,
    ConfigurationExecutionOutcome,
    ConfigurationExecutionResult,
    ReadOnlyCheckoutRunner,
    execute_configuration_plan,
    execute_control,
    execute_simulated_checkout,
)

__all__ = [
    "AuditEvent",
    "AuditSpan",
    "AuditTrail",
    "CommandReceipt",
    "Capability",
    "CapabilityState",
    "ControllerCapabilities",
    "ControllerProfile",
    "PROFILES",
    "PROFILES_BY_KEY",
    "TelemetryLayout",
    "profile_for_data_format",
    "select_profile",
    "DetectionResult",
    "DetectionStatus",
    "DiscoveryReport",
    "detect_controller",
    "detect_controllers",
    "OpenMaxFireError",
    "UnsupportedControllerError",
    "CapabilityUnavailableError",
    "SafetyInterlockError",
    "VerificationError",
    "LoaderUnavailableError",
    "MaxFireClient",
    "MonitorState",
    "StoveIdentity",
    "IgniterState",
    "OperatingState",
    "RemoteButton",
    "combine_telemetry_word",
    "decode_igniter_state",
    "decode_operating_state",
    "encode_read_register",
    "encode_write_register",
    "TransactionOperation",
    "TransactionPlan",
    "execute_transaction",
    "load_transaction_plan",
    "parse_transaction_plan",
    "replay_capture",
    "AlarmState",
    "PanelButtons",
    "PhysicalInputs",
    "StoveSnapshot",
    "TelemetryMeasurements",
    "decode_stove_snapshot",
    "ConfigurationChange",
    "ConfigurationField",
    "ConfigurationImage",
    "ConfigurationPlan",
    "ConfigurationSchema",
    "ConfigurationValidation",
    "configuration_schema",
    "plan_configuration_restore",
    "plan_configuration_update",
    "ControlAction",
    "ControlOutcome",
    "ControlPlan",
    "ControlResult",
    "plan_control",
    "CHECKOUT_TESTS",
    "CheckoutOutcome",
    "CheckoutPlan",
    "CheckoutReport",
    "CheckoutResult",
    "CheckoutTestDefinition",
    "checkout_test",
    "plan_checkout_test",
    "FirmwareCompatibility",
    "FirmwareImage",
    "FirmwareImageError",
    "FirmwareVariant",
    "IntelHexImage",
    "ProgramBlock",
    "assess_firmware_compatibility",
    "build_program_blocks",
    "loader_state_machine_supported",
    "parse_intel_hex",
    "FIRMWARE_CORPUS",
    "FirmwareCorpusEntry",
    "FirmwareCorpusReport",
    "FirmwareCorpusValidation",
    "validate_firmware_corpus",
    "LoaderBlockReceipt",
    "LoaderPlan",
    "LoaderPolicy",
    "LoaderResult",
    "LoaderState",
    "build_loader_plan",
    "execute_loader_plan",
    "live_loader_supported",
    "loader_simulation_supported",
    "SimulatedController",
    "SimulatedLoaderFaults",
    "SimulatedLoaderTransport",
    "SimulatedTransport",
    "SimulatedTransportFactory",
    "SimulationFaults",
    "ConnectionInfo",
    "ControllerSession",
    "READ_ONLY_CHECKOUT_TESTS",
    "ReadOnlyCheckoutRunner",
    "ConfigurationExecutionOutcome",
    "ConfigurationExecutionResult",
    "execute_configuration_plan",
    "execute_control",
    "execute_simulated_checkout",
]

__version__ = "0.7.0"
