# Data logging and report workflow core
# BixCheck 5.5.01; generated by tools/analyze_bixcheck.py
# Exact GNU objdump Intel-syntax excerpts; addresses are build-specific.

# source=Bixby110dlg.cpp
# va=0x0040F870 size=0xC10
0x0040F870 <bixby110control::GenerateReport(char*)>:
  40f870:	55                   	push   ebp
  40f871:	b9 03 00 00 00       	mov    ecx,0x3
  40f876:	89 e5                	mov    ebp,esp
  40f878:	57                   	push   edi
  40f879:	8d bd d8 fd ff ff    	lea    edi,[ebp-0x228]
  40f87f:	56                   	push   esi
  40f880:	53                   	push   ebx
  40f881:	81 ec ac 05 00 00    	sub    esp,0x5ac
  40f887:	8b 5d 08             	mov    ebx,DWORD PTR [ebp+0x8]
  40f88a:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  40f88e:	8b 75 0c             	mov    esi,DWORD PTR [ebp+0xc]
  40f891:	8d bd d8 fc ff ff    	lea    edi,[ebp-0x328]
  40f897:	89 9d 90 fa ff ff    	mov    DWORD PTR [ebp-0x570],ebx
  40f89d:	81 c3 38 15 00 00    	add    ebx,0x1538
  40f8a3:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  40f8a7:	89 9d 78 fa ff ff    	mov    DWORD PTR [ebp-0x588],ebx
  40f8ad:	89 1c 24             	mov    DWORD PTR [esp],ebx
  40f8b0:	8d 9d d8 fb ff ff    	lea    ebx,[ebp-0x428]
  40f8b6:	e8 f5 a3 ff ff       	call   409cb0 <bixby110io::getUnit0Data(unsigned char, char*)>
  40f8bb:	8d 85 d8 fd ff ff    	lea    eax,[ebp-0x228]
  40f8c1:	8d 95 d8 fe ff ff    	lea    edx,[ebp-0x128]
  40f8c7:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  40f8cb:	89 14 24             	mov    DWORD PTR [esp],edx
  40f8ce:	e8 ed 30 02 00       	call   4329c0 <strcpy>
  40f8d3:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  40f8d7:	89 1c 24             	mov    DWORD PTR [esp],ebx
  40f8da:	e8 e1 30 02 00       	call   4329c0 <strcpy>
  40f8df:	89 1c 24             	mov    DWORD PTR [esp],ebx
  40f8e2:	ba 1f 49 44 00       	mov    edx,0x44491f
  40f8e7:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  40f8eb:	e8 20 31 02 00       	call   432a10 <strstr>
  40f8f0:	c7 00 42 69 78 44    	mov    DWORD PTR [eax],0x44786942
  40f8f6:	31 c9                	xor    ecx,ecx
  40f8f8:	ba 03 00 00 00       	mov    edx,0x3
  40f8fd:	66 c7 40 04 61 74    	mov    WORD PTR [eax+0x4],0x7461
  40f903:	b8 80 00 00 00       	mov    eax,0x80
  40f908:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  40f90c:	31 c9                	xor    ecx,ecx
  40f90e:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  40f912:	b8 01 00 00 00       	mov    eax,0x1
  40f917:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  40f91b:	ba 00 00 00 40       	mov    edx,0x40000000
  40f920:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  40f924:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40f928:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  40f92c:	89 1c 24             	mov    DWORD PTR [esp],ebx
  40f92f:	e8 ac 34 02 00       	call   432de0 <CreateFileA@28>
  40f934:	83 ec 1c             	sub    esp,0x1c
  40f937:	83 f8 ff             	cmp    eax,0xffffffff
  40f93a:	74 4e                	je     40f98a <bixby110control::GenerateReport(char*)+0x11a>
  40f93c:	89 04 24             	mov    DWORD PTR [esp],eax
  40f93f:	e8 cc 34 02 00       	call   432e10 <CloseHandle@4>
  40f944:	83 ec 04             	sub    esp,0x4
  40f947:	ba 28 49 44 00       	mov    edx,0x444928
  40f94c:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  40f950:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  40f954:	89 3c 24             	mov    DWORD PTR [esp],edi
  40f957:	e8 34 30 02 00       	call   432990 <sprintf>
  40f95c:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  40f960:	b9 24 00 00 00       	mov    ecx,0x24
  40f965:	b8 64 49 44 00       	mov    eax,0x444964
  40f96a:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  40f96e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40f972:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  40f979:	e8 12 32 02 00       	call   432b90 <MessageBoxA@16>
  40f97e:	83 ec 10             	sub    esp,0x10
  40f981:	83 f8 06             	cmp    eax,0x6
  40f984:	0f 85 49 ff ff ff    	jne    40f8d3 <bixby110control::GenerateReport(char*)+0x63>
  40f98a:	89 1c 24             	mov    DWORD PTR [esp],ebx
  40f98d:	31 f6                	xor    esi,esi
  40f98f:	31 c0                	xor    eax,eax
  40f991:	89 74 24 18          	mov    DWORD PTR [esp+0x18],esi
  40f995:	ba 80 00 00 00       	mov    edx,0x80
  40f99a:	b9 02 00 00 00       	mov    ecx,0x2
  40f99f:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  40f9a3:	bf 01 00 00 00       	mov    edi,0x1
  40f9a8:	be 00 00 00 40       	mov    esi,0x40000000
  40f9ad:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  40f9b1:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  40f9b5:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  40f9b9:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  40f9bd:	e8 1e 34 02 00       	call   432de0 <CreateFileA@28>
  40f9c2:	89 85 70 fa ff ff    	mov    DWORD PTR [ebp-0x590],eax
  40f9c8:	83 ec 1c             	sub    esp,0x1c
  40f9cb:	40                   	inc    eax
  40f9cc:	0f 84 75 0a 00 00    	je     410447 <bixby110control::GenerateReport(char*)+0xbd7>
  40f9d2:	8b 85 90 fa ff ff    	mov    eax,DWORD PTR [ebp-0x570]
  40f9d8:	8d 95 d8 fe ff ff    	lea    edx,[ebp-0x128]
  40f9de:	be 7b 49 44 00       	mov    esi,0x44497b
  40f9e3:	89 14 24             	mov    DWORD PTR [esp],edx
  40f9e6:	8d bd d8 fe ff ff    	lea    edi,[ebp-0x128]
  40f9ec:	31 db                	xor    ebx,ebx
  40f9ee:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  40f9f2:	05 c0 1f 00 00       	add    eax,0x1fc0
  40f9f7:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40f9fb:	e8 90 2f 02 00       	call   432990 <sprintf>
  40fa00:	89 3c 24             	mov    DWORD PTR [esp],edi
  40fa03:	8d 7d d8             	lea    edi,[ebp-0x28]
  40fa06:	e8 a5 2f 02 00       	call   4329b0 <strlen>
  40fa0b:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fa0f:	8b b5 70 fa ff ff    	mov    esi,DWORD PTR [ebp-0x590]
  40fa15:	8d 8d c4 fa ff ff    	lea    ecx,[ebp-0x53c]
  40fa1b:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  40fa1f:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  40fa25:	89 5c 24 10          	mov    DWORD PTR [esp+0x10],ebx
  40fa29:	8d 9d d8 fd ff ff    	lea    ebx,[ebp-0x228]
  40fa2f:	89 34 24             	mov    DWORD PTR [esp],esi
  40fa32:	8d b5 d8 fe ff ff    	lea    esi,[ebp-0x128]
  40fa38:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  40fa3c:	e8 0f 34 02 00       	call   432e50 <WriteFile@20>
  40fa41:	83 ec 14             	sub    esp,0x14
  40fa44:	89 3c 24             	mov    DWORD PTR [esp],edi
  40fa47:	e8 24 34 02 00       	call   432e70 <GetLocalTime@4>
  40fa4c:	83 ec 04             	sub    esp,0x4
  40fa4f:	8d 95 d8 fd ff ff    	lea    edx,[ebp-0x228]
  40fa55:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  40fa59:	89 3c 24             	mov    DWORD PTR [esp],edi
  40fa5c:	8d bd c0 fa ff ff    	lea    edi,[ebp-0x540]
  40fa62:	e8 69 88 ff ff       	call   4082d0 <FormatTime(_SYSTEMTIME*, char*)>
  40fa67:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  40fa6b:	b9 80 49 44 00       	mov    ecx,0x444980
  40fa70:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  40fa76:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  40fa7a:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  40fa80:	89 04 24             	mov    DWORD PTR [esp],eax
  40fa83:	e8 08 2f 02 00       	call   432990 <sprintf>
  40fa88:	89 34 24             	mov    DWORD PTR [esp],esi
  40fa8b:	e8 20 2f 02 00       	call   4329b0 <strlen>
  40fa90:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fa94:	8b 8d 70 fa ff ff    	mov    ecx,DWORD PTR [ebp-0x590]
  40fa9a:	31 d2                	xor    edx,edx
  40fa9c:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  40faa0:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  40faa4:	89 0c 24             	mov    DWORD PTR [esp],ecx
  40faa7:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  40faab:	bb 0c 00 00 00       	mov    ebx,0xc
  40fab0:	e8 9b 33 02 00       	call   432e50 <WriteFile@20>
  40fab5:	8b b5 78 fa ff ff    	mov    esi,DWORD PTR [ebp-0x588]
  40fabb:	83 ec 14             	sub    esp,0x14
  40fabe:	b8 0e 00 00 00       	mov    eax,0xe
  40fac3:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  40fac7:	89 34 24             	mov    DWORD PTR [esp],esi
  40faca:	e8 11 9b ff ff       	call   4095e0 <bixby110io::getCMDbuf(unsigned char)>
  40facf:	8b bd 78 fa ff ff    	mov    edi,DWORD PTR [ebp-0x588]
  40fad5:	ba 0d 00 00 00       	mov    edx,0xd
  40fada:	0f b6 f0             	movzx  esi,al
  40fadd:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  40fae1:	89 3c 24             	mov    DWORD PTR [esp],edi
  40fae4:	e8 f7 9a ff ff       	call   4095e0 <bixby110io::getCMDbuf(unsigned char)>
  40fae9:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  40faed:	8b 8d 78 fa ff ff    	mov    ecx,DWORD PTR [ebp-0x588]
  40faf3:	0f b6 f8             	movzx  edi,al
  40faf6:	89 0c 24             	mov    DWORD PTR [esp],ecx
  40faf9:	e8 e2 9a ff ff       	call   4095e0 <bixby110io::getCMDbuf(unsigned char)>
  40fafe:	8b 95 78 fa ff ff    	mov    edx,DWORD PTR [ebp-0x588]
  40fb04:	0f b6 d8             	movzx  ebx,al
  40fb07:	b8 0b 00 00 00       	mov    eax,0xb
  40fb0c:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  40fb10:	89 14 24             	mov    DWORD PTR [esp],edx
  40fb13:	e8 c8 9a ff ff       	call   4095e0 <bixby110io::getCMDbuf(unsigned char)>
  40fb18:	89 74 24 14          	mov    DWORD PTR [esp+0x14],esi
  40fb1c:	0f b6 c8             	movzx  ecx,al
  40fb1f:	8d b5 d8 fe ff ff    	lea    esi,[ebp-0x128]
  40fb25:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  40fb29:	b8 90 49 44 00       	mov    eax,0x444990
  40fb2e:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  40fb34:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  40fb38:	89 7c 24 10          	mov    DWORD PTR [esp+0x10],edi
  40fb3c:	8d bd d8 fe ff ff    	lea    edi,[ebp-0x128]
  40fb42:	89 1c 24             	mov    DWORD PTR [esp],ebx
  40fb45:	8d 9d d8 fd ff ff    	lea    ebx,[ebp-0x228]
  40fb4b:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  40fb4f:	e8 3c 2e 02 00       	call   432990 <sprintf>
  40fb54:	89 34 24             	mov    DWORD PTR [esp],esi
  40fb57:	31 f6                	xor    esi,esi
  40fb59:	e8 52 2e 02 00       	call   4329b0 <strlen>
  40fb5e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fb62:	8b 85 70 fa ff ff    	mov    eax,DWORD PTR [ebp-0x590]
  40fb68:	31 d2                	xor    edx,edx
  40fb6a:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  40fb6e:	8d 8d bc fa ff ff    	lea    ecx,[ebp-0x544]
  40fb74:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  40fb78:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  40fb7c:	8d bd d8 fe ff ff    	lea    edi,[ebp-0x128]
  40fb82:	89 04 24             	mov    DWORD PTR [esp],eax
  40fb85:	e8 c6 32 02 00       	call   432e50 <WriteFile@20>
  40fb8a:	8b 95 78 fa ff ff    	mov    edx,DWORD PTR [ebp-0x588]
  40fb90:	83 ec 14             	sub    esp,0x14
  40fb93:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  40fb97:	31 db                	xor    ebx,ebx
  40fb99:	89 14 24             	mov    DWORD PTR [esp],edx
  40fb9c:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  40fba0:	8d b5 b8 fa ff ff    	lea    esi,[ebp-0x548]
  40fba6:	e8 05 a1 ff ff       	call   409cb0 <bixby110io::getUnit0Data(unsigned char, char*)>
  40fbab:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fbaf:	b9 af 49 44 00       	mov    ecx,0x4449af
  40fbb4:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  40fbb8:	89 3c 24             	mov    DWORD PTR [esp],edi
  40fbbb:	8d bd d8 fd ff ff    	lea    edi,[ebp-0x228]
  40fbc1:	e8 ca 2d 02 00       	call   432990 <sprintf>
  40fbc6:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  40fbcc:	89 04 24             	mov    DWORD PTR [esp],eax
  40fbcf:	e8 dc 2d 02 00       	call   4329b0 <strlen>
  40fbd4:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fbd8:	8b 8d 70 fa ff ff    	mov    ecx,DWORD PTR [ebp-0x590]
  40fbde:	8d 95 d8 fe ff ff    	lea    edx,[ebp-0x128]
  40fbe4:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  40fbe8:	89 5c 24 10          	mov    DWORD PTR [esp+0x10],ebx
  40fbec:	bb 08 00 00 00       	mov    ebx,0x8
  40fbf1:	89 0c 24             	mov    DWORD PTR [esp],ecx
  40fbf4:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  40fbf8:	e8 53 32 02 00       	call   432e50 <WriteFile@20>
  40fbfd:	8b b5 78 fa ff ff    	mov    esi,DWORD PTR [ebp-0x588]
  40fc03:	83 ec 14             	sub    esp,0x14
  40fc06:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  40fc0a:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  40fc0e:	8d 9d b4 fa ff ff    	lea    ebx,[ebp-0x54c]
  40fc14:	89 34 24             	mov    DWORD PTR [esp],esi
  40fc17:	8d b5 d8 fe ff ff    	lea    esi,[ebp-0x128]
  40fc1d:	e8 3e a2 ff ff       	call   409e60 <bixby110io::getCmdData(unsigned char, char*)>
  40fc22:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fc26:	8d 95 d8 fe ff ff    	lea    edx,[ebp-0x128]
  40fc2c:	b8 c0 49 44 00       	mov    eax,0x4449c0
  40fc31:	89 14 24             	mov    DWORD PTR [esp],edx
  40fc34:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  40fc38:	e8 53 2d 02 00       	call   432990 <sprintf>
  40fc3d:	8d 8d d8 fe ff ff    	lea    ecx,[ebp-0x128]
  40fc43:	89 0c 24             	mov    DWORD PTR [esp],ecx
  40fc46:	e8 65 2d 02 00       	call   4329b0 <strlen>
  40fc4b:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fc4f:	8b 85 70 fa ff ff    	mov    eax,DWORD PTR [ebp-0x590]
  40fc55:	31 ff                	xor    edi,edi
  40fc57:	89 7c 24 10          	mov    DWORD PTR [esp+0x10],edi
  40fc5b:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  40fc5f:	8d 9d d8 fd ff ff    	lea    ebx,[ebp-0x228]
  40fc65:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  40fc69:	be d4 49 44 00       	mov    esi,0x4449d4
  40fc6e:	89 04 24             	mov    DWORD PTR [esp],eax
  40fc71:	e8 da 31 02 00       	call   432e50 <WriteFile@20>
  40fc76:	8b bd 78 fa ff ff    	mov    edi,DWORD PTR [ebp-0x588]
  40fc7c:	83 ec 14             	sub    esp,0x14
  40fc7f:	b9 03 00 00 00       	mov    ecx,0x3
  40fc84:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  40fc88:	8d 95 d8 fd ff ff    	lea    edx,[ebp-0x228]
  40fc8e:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  40fc92:	89 3c 24             	mov    DWORD PTR [esp],edi
  40fc95:	8d bd b0 fa ff ff    	lea    edi,[ebp-0x550]
  40fc9b:	e8 10 a0 ff ff       	call   409cb0 <bixby110io::getUnit0Data(unsigned char, char*)>
  40fca0:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  40fca4:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  40fcaa:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  40fcb0:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  40fcb4:	89 04 24             	mov    DWORD PTR [esp],eax
  40fcb7:	e8 d4 2c 02 00       	call   432990 <sprintf>
  40fcbc:	8d 95 d8 fe ff ff    	lea    edx,[ebp-0x128]
  40fcc2:	89 14 24             	mov    DWORD PTR [esp],edx
  40fcc5:	e8 e6 2c 02 00       	call   4329b0 <strlen>
  40fcca:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fcce:	8b b5 70 fa ff ff    	mov    esi,DWORD PTR [ebp-0x590]
  40fcd4:	31 c9                	xor    ecx,ecx
  40fcd6:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  40fcda:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  40fcde:	8d bd d8 fd ff ff    	lea    edi,[ebp-0x228]
  40fce4:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  40fce8:	bb e8 49 44 00       	mov    ebx,0x4449e8
  40fced:	89 34 24             	mov    DWORD PTR [esp],esi
  40fcf0:	8d b5 d8 fe ff ff    	lea    esi,[ebp-0x128]
  40fcf6:	e8 55 31 02 00       	call   432e50 <WriteFile@20>
  40fcfb:	8b 8d 78 fa ff ff    	mov    ecx,DWORD PTR [ebp-0x588]
  40fd01:	83 ec 14             	sub    esp,0x14
  40fd04:	ba 0b 00 00 00       	mov    edx,0xb
  40fd09:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  40fd0d:	8d 85 d8 fd ff ff    	lea    eax,[ebp-0x228]
  40fd13:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fd17:	89 0c 24             	mov    DWORD PTR [esp],ecx
  40fd1a:	e8 91 9f ff ff       	call   409cb0 <bixby110io::getUnit0Data(unsigned char, char*)>
  40fd1f:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  40fd23:	8d bd d8 fe ff ff    	lea    edi,[ebp-0x128]
  40fd29:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  40fd2d:	89 34 24             	mov    DWORD PTR [esp],esi
  40fd30:	8d b5 d8 fd ff ff    	lea    esi,[ebp-0x228]
  40fd36:	e8 55 2c 02 00       	call   432990 <sprintf>
  40fd3b:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  40fd41:	89 04 24             	mov    DWORD PTR [esp],eax
  40fd44:	e8 67 2c 02 00       	call   4329b0 <strlen>
  40fd49:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fd4d:	8b 9d 70 fa ff ff    	mov    ebx,DWORD PTR [ebp-0x590]
  40fd53:	31 d2                	xor    edx,edx
  40fd55:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  40fd59:	8d 8d ac fa ff ff    	lea    ecx,[ebp-0x554]
  40fd5f:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  40fd63:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  40fd67:	bf fe 49 44 00       	mov    edi,0x4449fe
  40fd6c:	89 1c 24             	mov    DWORD PTR [esp],ebx
  40fd6f:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  40fd75:	e8 d6 30 02 00       	call   432e50 <WriteFile@20>
  40fd7a:	8b 8d 78 fa ff ff    	mov    ecx,DWORD PTR [ebp-0x588]
  40fd80:	83 ec 14             	sub    esp,0x14
  40fd83:	ba 13 00 00 00       	mov    edx,0x13
  40fd88:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  40fd8c:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  40fd90:	8d b5 d8 fe ff ff    	lea    esi,[ebp-0x128]
  40fd96:	89 0c 24             	mov    DWORD PTR [esp],ecx
  40fd99:	e8 12 9f ff ff       	call   409cb0 <bixby110io::getUnit0Data(unsigned char, char*)>
  40fd9e:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  40fda2:	8d 85 d8 fd ff ff    	lea    eax,[ebp-0x228]
  40fda8:	89 1c 24             	mov    DWORD PTR [esp],ebx
  40fdab:	31 db                	xor    ebx,ebx
  40fdad:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fdb1:	e8 da 2b 02 00       	call   432990 <sprintf>
  40fdb6:	89 34 24             	mov    DWORD PTR [esp],esi
  40fdb9:	e8 f2 2b 02 00       	call   4329b0 <strlen>
  40fdbe:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fdc2:	8b bd 70 fa ff ff    	mov    edi,DWORD PTR [ebp-0x590]
  40fdc8:	31 d2                	xor    edx,edx
  40fdca:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  40fdce:	8d 8d a8 fa ff ff    	lea    ecx,[ebp-0x558]
  40fdd4:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  40fdda:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  40fdde:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  40fde2:	89 3c 24             	mov    DWORD PTR [esp],edi
  40fde5:	e8 66 30 02 00       	call   432e50 <WriteFile@20>
  40fdea:	89 9d 8c fa ff ff    	mov    DWORD PTR [ebp-0x574],ebx
  40fdf0:	83 ec 14             	sub    esp,0x14
  40fdf3:	c6 85 da fe ff ff 00 	mov    BYTE PTR [ebp-0x126],0x0
  40fdfa:	b9 0d 0a 00 00       	mov    ecx,0xa0d
  40fdff:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  40fe05:	66 89 8d d8 fe ff ff 	mov    WORD PTR [ebp-0x128],cx
  40fe0c:	31 f6                	xor    esi,esi
  40fe0e:	8d bd d8 fe ff ff    	lea    edi,[ebp-0x128]
  40fe14:	89 04 24             	mov    DWORD PTR [esp],eax
  40fe17:	e8 94 2b 02 00       	call   4329b0 <strlen>
  40fe1c:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40fe20:	8b 9d 70 fa ff ff    	mov    ebx,DWORD PTR [ebp-0x590]
  40fe26:	8d 95 a4 fa ff ff    	lea    edx,[ebp-0x55c]
  40fe2c:	89 74 24 10          	mov    DWORD PTR [esp+0x10],esi
  40fe30:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  40fe34:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  40fe38:	89 1c 24             	mov    DWORD PTR [esp],ebx
  40fe3b:	e8 10 30 02 00       	call   432e50 <WriteFile@20>
  40fe40:	8b 8d 8c fa ff ff    	mov    ecx,DWORD PTR [ebp-0x574]
  40fe46:	83 ec 14             	sub    esp,0x14
  40fe49:	85 c9                	test   ecx,ecx
  40fe4b:	0f 85 76 05 00 00    	jne    4103c7 <bixby110control::GenerateReport(char*)+0xb57>
  40fe51:	c6 85 87 fa ff ff 00 	mov    BYTE PTR [ebp-0x579],0x0
  40fe58:	bb 20 41 3a 00       	mov    ebx,0x3a4120
  40fe5d:	89 9d c8 fb ff ff    	mov    DWORD PTR [ebp-0x438],ebx
  40fe63:	bb 46 61 6e 20       	mov    ebx,0x206e6146
  40fe68:	b9 4c 65 76 65       	mov    ecx,0x6576654c
  40fe6d:	b8 6c 73 20 00       	mov    eax,0x20736c
  40fe72:	89 9d d8 fe ff ff    	mov    DWORD PTR [ebp-0x128],ebx
  40fe78:	8d 95 d8 fe ff ff    	lea    edx,[ebp-0x128]
  40fe7e:	bb 40 00 00 00       	mov    ebx,0x40
  40fe83:	89 8d dc fe ff ff    	mov    DWORD PTR [ebp-0x124],ecx
  40fe89:	8d b5 c8 fb ff ff    	lea    esi,[ebp-0x438]
  40fe8f:	89 85 e0 fe ff ff    	mov    DWORD PTR [ebp-0x120],eax
  40fe95:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  40fe99:	89 14 24             	mov    DWORD PTR [esp],edx
  40fe9c:	e8 4f 2b 02 00       	call   4329f0 <strcat>
  40fea1:	eb 25                	jmp    40fec8 <bixby110control::GenerateReport(char*)+0x658>
  40fea3:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  40fea9:	43                   	inc    ebx
  40feaa:	89 04 24             	mov    DWORD PTR [esp],eax
  40fead:	e8 fe 2a 02 00       	call   4329b0 <strlen>
  40feb2:	b9 2c 00 00 00       	mov    ecx,0x2c
  40feb7:	83 fb 47             	cmp    ebx,0x47
  40feba:	66 89 8c 28 d8 fe ff 	mov    WORD PTR [eax+ebp*1-0x128],cx
  40fec1:	ff
  40fec2:	0f 8f 92 00 00 00    	jg     40ff5a <bixby110control::GenerateReport(char*)+0x6ea>
  40fec8:	0f b6 95 87 fa ff ff 	movzx  edx,BYTE PTR [ebp-0x579]
  40fecf:	8d b5 d8 fd ff ff    	lea    esi,[ebp-0x228]
  40fed5:	8b 8d 78 fa ff ff    	mov    ecx,DWORD PTR [ebp-0x588]
  40fedb:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  40fedf:	8d b5 d8 fd ff ff    	lea    esi,[ebp-0x228]
  40fee5:	00 da                	add    dl,bl
  40fee7:	89 0c 24             	mov    DWORD PTR [esp],ecx
  40feea:	0f b6 fa             	movzx  edi,dl
  40feed:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  40fef1:	8d bd d8 fe ff ff    	lea    edi,[ebp-0x128]
  40fef7:	e8 b4 9d ff ff       	call   409cb0 <bixby110io::getUnit0Data(unsigned char, char*)>
  40fefc:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40ff00:	b8 0a 4a 44 00       	mov    eax,0x444a0a
  40ff05:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  40ff09:	89 34 24             	mov    DWORD PTR [esp],esi
  40ff0c:	e8 7f 2a 02 00       	call   432990 <sprintf>
  40ff11:	89 3c 24             	mov    DWORD PTR [esp],edi
  40ff14:	8d 95 d8 fd ff ff    	lea    edx,[ebp-0x228]
  40ff1a:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  40ff1e:	e8 cd 2a 02 00       	call   4329f0 <strcat>
  40ff23:	83 fb 47             	cmp    ebx,0x47
  40ff26:	0f 85 77 ff ff ff    	jne    40fea3 <bixby110control::GenerateReport(char*)+0x633>
  40ff2c:	8d b5 d8 fe ff ff    	lea    esi,[ebp-0x128]
  40ff32:	43                   	inc    ebx
  40ff33:	bf 0d 0a 00 00       	mov    edi,0xa0d
  40ff38:	89 34 24             	mov    DWORD PTR [esp],esi
  40ff3b:	e8 70 2a 02 00       	call   4329b0 <strlen>
  40ff40:	66 89 bc 28 d8 fe ff 	mov    WORD PTR [eax+ebp*1-0x128],di
  40ff47:	ff
  40ff48:	31 d2                	xor    edx,edx
  40ff4a:	83 fb 47             	cmp    ebx,0x47
  40ff4d:	88 94 28 da fe ff ff 	mov    BYTE PTR [eax+ebp*1-0x126],dl
  40ff54:	0f 8e 6e ff ff ff    	jle    40fec8 <bixby110control::GenerateReport(char*)+0x658>
  40ff5a:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  40ff60:	bf 46 65 65 64       	mov    edi,0x64656546
  40ff65:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  40ff6b:	89 04 24             	mov    DWORD PTR [esp],eax
  40ff6e:	e8 3d 2a 02 00       	call   4329b0 <strlen>
  40ff73:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  40ff77:	8b b5 70 fa ff ff    	mov    esi,DWORD PTR [ebp-0x590]
  40ff7d:	31 d2                	xor    edx,edx
  40ff7f:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  40ff83:	8d 8d a0 fa ff ff    	lea    ecx,[ebp-0x560]
  40ff89:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  40ff8d:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  40ff91:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  40ff97:	89 34 24             	mov    DWORD PTR [esp],esi
  40ff9a:	e8 b1 2e 02 00       	call   432e50 <WriteFile@20>
  40ff9f:	89 bd d8 fe ff ff    	mov    DWORD PTR [ebp-0x128],edi
  40ffa5:	83 ec 14             	sub    esp,0x14
  40ffa8:	ba 20 4c 65 76       	mov    edx,0x76654c20
  40ffad:	89 1c 24             	mov    DWORD PTR [esp],ebx
  40ffb0:	b8 65 6c 73 00       	mov    eax,0x736c65
  40ffb5:	8d 8d c8 fb ff ff    	lea    ecx,[ebp-0x438]
  40ffbb:	89 95 dc fe ff ff    	mov    DWORD PTR [ebp-0x124],edx
  40ffc1:	bb 48 00 00 00       	mov    ebx,0x48
  40ffc6:	89 85 e0 fe ff ff    	mov    DWORD PTR [ebp-0x120],eax
  40ffcc:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  40ffd0:	e8 1b 2a 02 00       	call   4329f0 <strcat>
  40ffd5:	eb 25                	jmp    40fffc <bixby110control::GenerateReport(char*)+0x78c>
  40ffd7:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  40ffdd:	43                   	inc    ebx
  40ffde:	89 04 24             	mov    DWORD PTR [esp],eax
  40ffe1:	e8 ca 29 02 00       	call   4329b0 <strlen>
  40ffe6:	ba 2c 00 00 00       	mov    edx,0x2c
  40ffeb:	83 fb 4f             	cmp    ebx,0x4f
  40ffee:	66 89 94 28 d8 fe ff 	mov    WORD PTR [eax+ebp*1-0x128],dx
  40fff5:	ff
  40fff6:	0f 8f 92 00 00 00    	jg     41008e <bixby110control::GenerateReport(char*)+0x81e>
  40fffc:	0f b6 8d 87 fa ff ff 	movzx  ecx,BYTE PTR [ebp-0x579]
  410003:	8d b5 d8 fd ff ff    	lea    esi,[ebp-0x228]
  410009:	8b 85 78 fa ff ff    	mov    eax,DWORD PTR [ebp-0x588]
  41000f:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  410013:	8d b5 d8 fd ff ff    	lea    esi,[ebp-0x228]
  410019:	00 d9                	add    cl,bl
  41001b:	89 04 24             	mov    DWORD PTR [esp],eax
  41001e:	0f b6 f9             	movzx  edi,cl
  410021:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  410025:	8d bd d8 fe ff ff    	lea    edi,[ebp-0x128]
  41002b:	e8 80 9c ff ff       	call   409cb0 <bixby110io::getUnit0Data(unsigned char, char*)>
  410030:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  410034:	ba 0a 4a 44 00       	mov    edx,0x444a0a
  410039:	8d 8d d8 fd ff ff    	lea    ecx,[ebp-0x228]
  41003f:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  410043:	89 0c 24             	mov    DWORD PTR [esp],ecx
  410046:	e8 45 29 02 00       	call   432990 <sprintf>
  41004b:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41004f:	89 3c 24             	mov    DWORD PTR [esp],edi
  410052:	e8 99 29 02 00       	call   4329f0 <strcat>
  410057:	83 fb 4f             	cmp    ebx,0x4f
  41005a:	0f 85 77 ff ff ff    	jne    40ffd7 <bixby110control::GenerateReport(char*)+0x767>
  410060:	8d b5 d8 fe ff ff    	lea    esi,[ebp-0x128]
  410066:	43                   	inc    ebx
  410067:	bf 0d 0a 00 00       	mov    edi,0xa0d
  41006c:	89 34 24             	mov    DWORD PTR [esp],esi
  41006f:	e8 3c 29 02 00       	call   4329b0 <strlen>
  410074:	66 89 bc 28 d8 fe ff 	mov    WORD PTR [eax+ebp*1-0x128],di
  41007b:	ff
  41007c:	31 c9                	xor    ecx,ecx
  41007e:	83 fb 4f             	cmp    ebx,0x4f
  410081:	88 8c 28 da fe ff ff 	mov    BYTE PTR [eax+ebp*1-0x126],cl
  410088:	0f 8e 6e ff ff ff    	jle    40fffc <bixby110control::GenerateReport(char*)+0x78c>
  41008e:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  410094:	bf 41 73 68 20       	mov    edi,0x20687341
  410099:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  41009f:	89 04 24             	mov    DWORD PTR [esp],eax
  4100a2:	e8 09 29 02 00       	call   4329b0 <strlen>
  4100a7:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  4100ab:	8b b5 70 fa ff ff    	mov    esi,DWORD PTR [ebp-0x590]
  4100b1:	31 c9                	xor    ecx,ecx
  4100b3:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  4100b7:	8d 95 9c fa ff ff    	lea    edx,[ebp-0x564]
  4100bd:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  4100c1:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  4100c5:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  4100cb:	89 34 24             	mov    DWORD PTR [esp],esi
  4100ce:	e8 7d 2d 02 00       	call   432e50 <WriteFile@20>
  4100d3:	89 bd d8 fe ff ff    	mov    DWORD PTR [ebp-0x128],edi
  4100d9:	83 ec 14             	sub    esp,0x14
  4100dc:	b9 4c 65 76 65       	mov    ecx,0x6576654c
  4100e1:	89 1c 24             	mov    DWORD PTR [esp],ebx
  4100e4:	b8 6c 73 20 00       	mov    eax,0x20736c
  4100e9:	8d 95 c8 fb ff ff    	lea    edx,[ebp-0x438]
  4100ef:	89 8d dc fe ff ff    	mov    DWORD PTR [ebp-0x124],ecx
  4100f5:	bb 50 00 00 00       	mov    ebx,0x50
  4100fa:	89 85 e0 fe ff ff    	mov    DWORD PTR [ebp-0x120],eax
  410100:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  410104:	e8 e7 28 02 00       	call   4329f0 <strcat>
  410109:	eb 25                	jmp    410130 <bixby110control::GenerateReport(char*)+0x8c0>
  41010b:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  410111:	43                   	inc    ebx
  410112:	89 04 24             	mov    DWORD PTR [esp],eax
  410115:	e8 96 28 02 00       	call   4329b0 <strlen>
  41011a:	b9 2c 00 00 00       	mov    ecx,0x2c
  41011f:	83 fb 57             	cmp    ebx,0x57
  410122:	66 89 8c 28 d8 fe ff 	mov    WORD PTR [eax+ebp*1-0x128],cx
  410129:	ff
  41012a:	0f 8f 92 00 00 00    	jg     4101c2 <bixby110control::GenerateReport(char*)+0x952>
  410130:	0f b6 95 87 fa ff ff 	movzx  edx,BYTE PTR [ebp-0x579]
  410137:	8d b5 d8 fd ff ff    	lea    esi,[ebp-0x228]
  41013d:	8b 85 78 fa ff ff    	mov    eax,DWORD PTR [ebp-0x588]
  410143:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  410147:	8d b5 d8 fd ff ff    	lea    esi,[ebp-0x228]
  41014d:	00 da                	add    dl,bl
  41014f:	89 04 24             	mov    DWORD PTR [esp],eax
  410152:	0f b6 fa             	movzx  edi,dl
  410155:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  410159:	8d bd d8 fe ff ff    	lea    edi,[ebp-0x128]
  41015f:	e8 4c 9b ff ff       	call   409cb0 <bixby110io::getUnit0Data(unsigned char, char*)>
  410164:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  410168:	b9 0a 4a 44 00       	mov    ecx,0x444a0a
  41016d:	8d 95 d8 fd ff ff    	lea    edx,[ebp-0x228]
  410173:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  410177:	89 14 24             	mov    DWORD PTR [esp],edx
  41017a:	e8 11 28 02 00       	call   432990 <sprintf>
  41017f:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  410183:	89 3c 24             	mov    DWORD PTR [esp],edi
  410186:	e8 65 28 02 00       	call   4329f0 <strcat>
  41018b:	83 fb 57             	cmp    ebx,0x57
  41018e:	0f 85 77 ff ff ff    	jne    41010b <bixby110control::GenerateReport(char*)+0x89b>
  410194:	8d b5 d8 fe ff ff    	lea    esi,[ebp-0x128]
  41019a:	43                   	inc    ebx
  41019b:	bf 0d 0a 00 00       	mov    edi,0xa0d
  4101a0:	89 34 24             	mov    DWORD PTR [esp],esi
  4101a3:	e8 08 28 02 00       	call   4329b0 <strlen>
  4101a8:	66 89 bc 28 d8 fe ff 	mov    WORD PTR [eax+ebp*1-0x128],di
  4101af:	ff
  4101b0:	31 d2                	xor    edx,edx
  4101b2:	83 fb 57             	cmp    ebx,0x57
  4101b5:	88 94 28 da fe ff ff 	mov    BYTE PTR [eax+ebp*1-0x126],dl
  4101bc:	0f 8e 6e ff ff ff    	jle    410130 <bixby110control::GenerateReport(char*)+0x8c0>
  4101c2:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  4101c8:	bf 58 00 00 00       	mov    edi,0x58
  4101cd:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  4101d3:	89 04 24             	mov    DWORD PTR [esp],eax
  4101d6:	e8 d5 27 02 00       	call   4329b0 <strlen>
  4101db:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  4101df:	8b b5 70 fa ff ff    	mov    esi,DWORD PTR [ebp-0x590]
  4101e5:	31 d2                	xor    edx,edx
  4101e7:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  4101eb:	8d 8d 98 fa ff ff    	lea    ecx,[ebp-0x568]
  4101f1:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  4101f5:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  4101f9:	89 34 24             	mov    DWORD PTR [esp],esi
  4101fc:	e8 4f 2c 02 00       	call   432e50 <WriteFile@20>
  410201:	0f b6 85 87 fa ff ff 	movzx  eax,BYTE PTR [ebp-0x579]
  410208:	83 ec 14             	sub    esp,0x14
  41020b:	89 bd 6c fa ff ff    	mov    DWORD PTR [ebp-0x594],edi
  410211:	8d 0c 80             	lea    ecx,[eax+eax*4]
  410214:	89 85 80 fa ff ff    	mov    DWORD PTR [ebp-0x580],eax
  41021a:	8b 95 80 fa ff ff    	mov    edx,DWORD PTR [ebp-0x580]
  410220:	8d 1c 4a             	lea    ebx,[edx+ecx*2]
  410223:	c1 e3 03             	shl    ebx,0x3
  410226:	89 9d 74 fa ff ff    	mov    DWORD PTR [ebp-0x58c],ebx
  41022c:	8b 9d 6c fa ff ff    	mov    ebx,DWORD PTR [ebp-0x594]
  410232:	31 f6                	xor    esi,esi
  410234:	8b bd 80 fa ff ff    	mov    edi,DWORD PTR [ebp-0x580]
  41023a:	01 df                	add    edi,ebx
  41023c:	8b 9d 74 fa ff ff    	mov    ebx,DWORD PTR [ebp-0x58c]
  410242:	89 bd 7c fa ff ff    	mov    DWORD PTR [ebp-0x584],edi
  410248:	eb 13                	jmp    41025d <bixby110control::GenerateReport(char*)+0x9ed>
  41024a:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  410250:	46                   	inc    esi
  410251:	83 c3 58             	add    ebx,0x58
  410254:	83 fe 51             	cmp    esi,0x51
  410257:	0f 8f 2e 01 00 00    	jg     41038b <bixby110control::GenerateReport(char*)+0xb1b>
  41025d:	0f b6 8b 29 dd 43 00 	movzx  ecx,BYTE PTR [ebx+0x43dd29]
  410264:	8b 95 80 fa ff ff    	mov    edx,DWORD PTR [ebp-0x580]
  41026a:	3b 8d 7c fa ff ff    	cmp    ecx,DWORD PTR [ebp-0x584]
  410270:	8d 3c 16             	lea    edi,[esi+edx*1]
  410273:	75 db                	jne    410250 <bixby110control::GenerateReport(char*)+0x9e0>
  410275:	0f b6 85 87 fa ff ff 	movzx  eax,BYTE PTR [ebp-0x579]
  41027c:	8d 8d d8 fd ff ff    	lea    ecx,[ebp-0x228]
  410282:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  410286:	8b 8d 78 fa ff ff    	mov    ecx,DWORD PTR [ebp-0x588]
  41028c:	02 85 6c fa ff ff    	add    al,BYTE PTR [ebp-0x594]
  410292:	89 0c 24             	mov    DWORD PTR [esp],ecx
  410295:	0f b6 d0             	movzx  edx,al
  410298:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41029c:	e8 0f 9a ff ff       	call   409cb0 <bixby110io::getUnit0Data(unsigned char, char*)>
  4102a1:	89 85 88 fa ff ff    	mov    DWORD PTR [ebp-0x578],eax
  4102a7:	8d 95 d8 fe ff ff    	lea    edx,[ebp-0x128]
  4102ad:	8d 83 e1 dc 43 00    	lea    eax,[ebx+0x43dce1]
  4102b3:	89 14 24             	mov    DWORD PTR [esp],edx
  4102b6:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4102ba:	e8 01 27 02 00       	call   4329c0 <strcpy>
  4102bf:	8d 8d c8 fb ff ff    	lea    ecx,[ebp-0x438]
  4102c5:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  4102cb:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  4102cf:	89 04 24             	mov    DWORD PTR [esp],eax
  4102d2:	e8 19 27 02 00       	call   4329f0 <strcat>
  4102d7:	80 bb e0 dc 43 00 0a 	cmp    BYTE PTR [ebx+0x43dce0],0xa
  4102de:	0f 84 fa 00 00 00    	je     4103de <bixby110control::GenerateReport(char*)+0xb6e>
  4102e4:	8b 95 88 fa ff ff    	mov    edx,DWORD PTR [ebp-0x578]
  4102ea:	b8 0a 4a 44 00       	mov    eax,0x444a0a
  4102ef:	8d 8d d8 fd ff ff    	lea    ecx,[ebp-0x228]
  4102f5:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4102f9:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4102fc:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  410300:	e8 8b 26 02 00       	call   432990 <sprintf>
  410305:	8d 8d d8 fd ff ff    	lea    ecx,[ebp-0x228]
  41030b:	46                   	inc    esi
  41030c:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  410312:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  410316:	8d bd d8 fe ff ff    	lea    edi,[ebp-0x128]
  41031c:	83 c3 58             	add    ebx,0x58
  41031f:	89 04 24             	mov    DWORD PTR [esp],eax
  410322:	e8 c9 26 02 00       	call   4329f0 <strcat>
  410327:	89 3c 24             	mov    DWORD PTR [esp],edi
  41032a:	31 ff                	xor    edi,edi
  41032c:	e8 7f 26 02 00       	call   4329b0 <strlen>
  410331:	31 c9                	xor    ecx,ecx
  410333:	ba 0d 0a 00 00       	mov    edx,0xa0d
  410338:	66 89 94 28 d8 fe ff 	mov    WORD PTR [eax+ebp*1-0x128],dx
  41033f:	ff
  410340:	88 8c 28 da fe ff ff 	mov    BYTE PTR [eax+ebp*1-0x126],cl
  410347:	8d 85 d8 fe ff ff    	lea    eax,[ebp-0x128]
  41034d:	89 04 24             	mov    DWORD PTR [esp],eax
  410350:	e8 5b 26 02 00       	call   4329b0 <strlen>
  410355:	89 7c 24 10          	mov    DWORD PTR [esp+0x10],edi
  410359:	8b bd 70 fa ff ff    	mov    edi,DWORD PTR [ebp-0x590]
  41035f:	8d 95 94 fa ff ff    	lea    edx,[ebp-0x56c]
  410365:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  410369:	8d 8d d8 fe ff ff    	lea    ecx,[ebp-0x128]
  41036f:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  410373:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  410377:	89 3c 24             	mov    DWORD PTR [esp],edi
  41037a:	e8 d1 2a 02 00       	call   432e50 <WriteFile@20>
  41037f:	83 ec 14             	sub    esp,0x14
  410382:	83 fe 51             	cmp    esi,0x51
  410385:	0f 8e d2 fe ff ff    	jle    41025d <bixby110control::GenerateReport(char*)+0x9ed>
  41038b:	ff 85 6c fa ff ff    	inc    DWORD PTR [ebp-0x594]
  410391:	83 bd 6c fa ff ff 6f 	cmp    DWORD PTR [ebp-0x594],0x6f
  410398:	0f 8e 8e fe ff ff    	jle    41022c <bixby110control::GenerateReport(char*)+0x9bc>
  41039e:	ff 85 8c fa ff ff    	inc    DWORD PTR [ebp-0x574]
  4103a4:	83 bd 8c fa ff ff 01 	cmp    DWORD PTR [ebp-0x574],0x1
  4103ab:	0f 8e 42 fa ff ff    	jle    40fdf3 <bixby110control::GenerateReport(char*)+0x583>
  4103b1:	8b b5 70 fa ff ff    	mov    esi,DWORD PTR [ebp-0x590]
  4103b7:	89 34 24             	mov    DWORD PTR [esp],esi
  4103ba:	e8 51 2a 02 00       	call   432e10 <CloseHandle@4>
  4103bf:	83 ec 04             	sub    esp,0x4
  4103c2:	e9 a2 00 00 00       	jmp    410469 <bixby110control::GenerateReport(char*)+0xbf9>
  4103c7:	c6 85 87 fa ff ff 30 	mov    BYTE PTR [ebp-0x579],0x30
  4103ce:	bf 20 42 3a 00       	mov    edi,0x3a4220
  4103d3:	89 bd c8 fb ff ff    	mov    DWORD PTR [ebp-0x438],edi
  4103d9:	e9 85 fa ff ff       	jmp    40fe63 <bixby110control::GenerateReport(char*)+0x5f3>
  4103de:	8b 95 90 fa ff ff    	mov    edx,DWORD PTR [ebp-0x570]
  4103e4:	8b 84 ba 2c 06 00 00 	mov    eax,DWORD PTR [edx+edi*4+0x62c]
  4103eb:	89 04 24             	mov    DWORD PTR [esp],eax
  4103ee:	e8 8d 22 01 00       	call   422680 <manual3checkbox::IsChecked()>
  4103f3:	84 c0                	test   al,al
  4103f5:	74 22                	je     410419 <bixby110control::GenerateReport(char*)+0xba9>
  4103f7:	c6 85 e0 fd ff ff 00 	mov    BYTE PTR [ebp-0x220],0x0
  4103fe:	b9 20 43 68 65       	mov    ecx,0x65684320
  410403:	bf 63 6b 65 64       	mov    edi,0x64656b63
  410408:	89 8d d8 fd ff ff    	mov    DWORD PTR [ebp-0x228],ecx
  41040e:	89 bd dc fd ff ff    	mov    DWORD PTR [ebp-0x224],edi
  410414:	e9 ec fe ff ff       	jmp    410305 <bixby110control::GenerateReport(char*)+0xa95>
  410419:	c6 85 e2 fd ff ff 00 	mov    BYTE PTR [ebp-0x21e],0x0
  410420:	bf 20 55 6e 63       	mov    edi,0x636e5520
  410425:	ba 68 65 63 6b       	mov    edx,0x6b636568
  41042a:	89 bd d8 fd ff ff    	mov    DWORD PTR [ebp-0x228],edi
  410430:	b8 65 64 00 00       	mov    eax,0x6465
  410435:	89 95 dc fd ff ff    	mov    DWORD PTR [ebp-0x224],edx
  41043b:	66 89 85 e0 fd ff ff 	mov    WORD PTR [ebp-0x220],ax
  410442:	e9 be fe ff ff       	jmp    410305 <bixby110control::GenerateReport(char*)+0xa95>
  410447:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41044b:	ba 10 4a 44 00       	mov    edx,0x444a10
  410450:	31 ff                	xor    edi,edi
  410452:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  410456:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  41045a:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  410461:	e8 2a 27 02 00       	call   432b90 <MessageBoxA@16>
  410466:	83 ec 10             	sub    esp,0x10
  410469:	8d 65 f4             	lea    esp,[ebp-0xc]
  41046c:	5b                   	pop    ebx
  41046d:	5e                   	pop    esi
  41046e:	5f                   	pop    edi
  41046f:	5d                   	pop    ebp
  410470:	c3                   	ret
  410471:	90                   	nop
  410472:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]
  410479:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]

# source=Bixby110dlg.cpp
# va=0x00411190 size=0x70
0x00411190 <bixby110control::AppendDataLogLine(char*, unsigned char)>:
  411190:	55                   	push   ebp
  411191:	31 c9                	xor    ecx,ecx
  411193:	89 e5                	mov    ebp,esp
  411195:	53                   	push   ebx
  411196:	83 ec 34             	sub    esp,0x34
  411199:	8b 5d 0c             	mov    ebx,DWORD PTR [ebp+0xc]
  41119c:	0f b6 45 10          	movzx  eax,BYTE PTR [ebp+0x10]
  4111a0:	88 45 e7             	mov    BYTE PTR [ebp-0x19],al
  4111a3:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  4111a9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  4111b0:	0f be c1             	movsx  eax,cl
  4111b3:	0f b6 14 03          	movzx  edx,BYTE PTR [ebx+eax*1]
  4111b7:	84 d2                	test   dl,dl
  4111b9:	74 0e                	je     4111c9 <bixby110control::AppendDataLogLine(char*, unsigned char)+0x39>
  4111bb:	88 54 28 e8          	mov    BYTE PTR [eax+ebp*1-0x18],dl
  4111bf:	fe c1                	inc    cl
  4111c1:	80 f9 0e             	cmp    cl,0xe
  4111c4:	7e ea                	jle    4111b0 <bixby110control::AppendDataLogLine(char*, unsigned char)+0x20>
  4111c6:	0f be c1             	movsx  eax,cl
  4111c9:	c6 44 28 e8 00       	mov    BYTE PTR [eax+ebp*1-0x18],0x0
  4111ce:	8b 55 08             	mov    edx,DWORD PTR [ebp+0x8]
  4111d1:	8d 45 e8             	lea    eax,[ebp-0x18]
  4111d4:	0f b6 5d e7          	movzx  ebx,BYTE PTR [ebp-0x19]
  4111d8:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4111dc:	c1 e3 04             	shl    ebx,0x4
  4111df:	8d 8c 13 51 12 00 00 	lea    ecx,[ebx+edx*1+0x1251]
  4111e6:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4111e9:	e8 d2 17 02 00       	call   4329c0 <strcpy>
  4111ee:	83 c4 34             	add    esp,0x34
  4111f1:	5b                   	pop    ebx
  4111f2:	5d                   	pop    ebp
  4111f3:	c3                   	ret
  4111f4:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  4111fa:	8d bf 00 00 00 00    	lea    edi,[edi+0x0]

# source=Bixby110dlg.cpp
# va=0x00411200 size=0x80
0x00411200 <bixby110control::AppendDataLogLine(char*)>:
  411200:	55                   	push   ebp
  411201:	89 e5                	mov    ebp,esp
  411203:	83 ec 18             	sub    esp,0x18
  411206:	89 75 f8             	mov    DWORD PTR [ebp-0x8],esi
  411209:	8b 75 08             	mov    esi,DWORD PTR [ebp+0x8]
  41120c:	89 5d f4             	mov    DWORD PTR [ebp-0xc],ebx
  41120f:	89 7d fc             	mov    DWORD PTR [ebp-0x4],edi
  411212:	80 be d4 0a 00 00 04 	cmp    BYTE PTR [esi+0xad4],0x4
  411219:	74 0d                	je     411228 <bixby110control::AppendDataLogLine(char*)+0x28>
  41121b:	8b 5d f4             	mov    ebx,DWORD PTR [ebp-0xc]
  41121e:	8b 75 f8             	mov    esi,DWORD PTR [ebp-0x8]
  411221:	8b 7d fc             	mov    edi,DWORD PTR [ebp-0x4]
  411224:	89 ec                	mov    esp,ebp
  411226:	5d                   	pop    ebp
  411227:	c3                   	ret
  411228:	8d be d5 0d 00 00    	lea    edi,[esi+0xdd5]
  41122e:	89 3c 24             	mov    DWORD PTR [esp],edi
  411231:	e8 7a 17 02 00       	call   4329b0 <strlen>
  411236:	8b 55 0c             	mov    edx,DWORD PTR [ebp+0xc]
  411239:	89 c3                	mov    ebx,eax
  41123b:	89 14 24             	mov    DWORD PTR [esp],edx
  41123e:	e8 6d 17 02 00       	call   4329b0 <strlen>
  411243:	8d 04 03             	lea    eax,[ebx+eax*1]
  411246:	3d f9 03 00 00       	cmp    eax,0x3f9
  41124b:	77 ce                	ja     41121b <bixby110control::AppendDataLogLine(char*)+0x1b>
  41124d:	89 3c 24             	mov    DWORD PTR [esp],edi
  411250:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  411253:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  411257:	e8 94 17 02 00       	call   4329f0 <strcat>
  41125c:	89 3c 24             	mov    DWORD PTR [esp],edi
  41125f:	bf 2c 20 00 00       	mov    edi,0x202c
  411264:	e8 47 17 02 00       	call   4329b0 <strlen>
  411269:	66 89 bc 30 d5 0d 00 	mov    WORD PTR [eax+esi*1+0xdd5],di
  411270:	00
  411271:	31 c9                	xor    ecx,ecx
  411273:	88 8c 30 d7 0d 00 00 	mov    BYTE PTR [eax+esi*1+0xdd7],cl
  41127a:	eb 9f                	jmp    41121b <bixby110control::AppendDataLogLine(char*)+0x1b>
  41127c:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]

# source=Bixby110dlg.cpp
# va=0x00411280 size=0xC0
0x00411280 <bixby110control::WriteDataLogTimeDate()>:
  411280:	55                   	push   ebp
  411281:	89 e5                	mov    ebp,esp
  411283:	81 ec 48 01 00 00    	sub    esp,0x148
  411289:	89 5d f4             	mov    DWORD PTR [ebp-0xc],ebx
  41128c:	8b 45 08             	mov    eax,DWORD PTR [ebp+0x8]
  41128f:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  411295:	89 75 f8             	mov    DWORD PTR [ebp-0x8],esi
  411298:	8d b5 e8 fe ff ff    	lea    esi,[ebp-0x118]
  41129e:	89 85 d4 fe ff ff    	mov    DWORD PTR [ebp-0x12c],eax
  4112a4:	89 7d fc             	mov    DWORD PTR [ebp-0x4],edi
  4112a7:	89 1c 24             	mov    DWORD PTR [esp],ebx
  4112aa:	e8 c1 1b 02 00       	call   432e70 <GetLocalTime@4>
  4112af:	83 ec 04             	sub    esp,0x4
  4112b2:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  4112b6:	89 1c 24             	mov    DWORD PTR [esp],ebx
  4112b9:	e8 12 70 ff ff       	call   4082d0 <FormatTime(_SYSTEMTIME*, char*)>
  4112be:	8b 95 d4 fe ff ff    	mov    edx,DWORD PTR [ebp-0x12c]
  4112c4:	80 ba d4 0a 00 00 04 	cmp    BYTE PTR [edx+0xad4],0x4
  4112cb:	74 13                	je     4112e0 <bixby110control::WriteDataLogTimeDate()+0x60>
  4112cd:	8b 5d f4             	mov    ebx,DWORD PTR [ebp-0xc]
  4112d0:	8b 75 f8             	mov    esi,DWORD PTR [ebp-0x8]
  4112d3:	8b 7d fc             	mov    edi,DWORD PTR [ebp-0x4]
  4112d6:	89 ec                	mov    esp,ebp
  4112d8:	5d                   	pop    ebp
  4112d9:	c3                   	ret
  4112da:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  4112e0:	89 d7                	mov    edi,edx
  4112e2:	81 c7 d5 0d 00 00    	add    edi,0xdd5
  4112e8:	89 3c 24             	mov    DWORD PTR [esp],edi
  4112eb:	e8 c0 16 02 00       	call   4329b0 <strlen>
  4112f0:	89 34 24             	mov    DWORD PTR [esp],esi
  4112f3:	89 c3                	mov    ebx,eax
  4112f5:	e8 b6 16 02 00       	call   4329b0 <strlen>
  4112fa:	8d 14 03             	lea    edx,[ebx+eax*1]
  4112fd:	81 fa f9 03 00 00    	cmp    edx,0x3f9
  411303:	77 c8                	ja     4112cd <bixby110control::WriteDataLogTimeDate()+0x4d>
  411305:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  411309:	be 2c 20 00 00       	mov    esi,0x202c
  41130e:	89 3c 24             	mov    DWORD PTR [esp],edi
  411311:	e8 da 16 02 00       	call   4329f0 <strcat>
  411316:	89 3c 24             	mov    DWORD PTR [esp],edi
  411319:	e8 92 16 02 00       	call   4329b0 <strlen>
  41131e:	8b 8d d4 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x12c]
  411324:	31 d2                	xor    edx,edx
  411326:	66 89 b4 08 d5 0d 00 	mov    WORD PTR [eax+ecx*1+0xdd5],si
  41132d:	00
  41132e:	88 94 08 d7 0d 00 00 	mov    BYTE PTR [eax+ecx*1+0xdd7],dl
  411335:	eb 96                	jmp    4112cd <bixby110control::WriteDataLogTimeDate()+0x4d>
  411337:	90                   	nop
  411338:	90                   	nop
  411339:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]

# source=Bixby110dlg.cpp
# va=0x00411340 size=0x70
0x00411340 <bixby110control::DataLogLineAssemblePayload()>:
  411340:	55                   	push   ebp
  411341:	89 e5                	mov    ebp,esp
  411343:	57                   	push   edi
  411344:	56                   	push   esi
  411345:	be 1f 00 00 00       	mov    esi,0x1f
  41134a:	53                   	push   ebx
  41134b:	83 ec 0c             	sub    esp,0xc
  41134e:	8b 45 08             	mov    eax,DWORD PTR [ebp+0x8]
  411351:	89 45 f0             	mov    DWORD PTR [ebp-0x10],eax
  411354:	89 c3                	mov    ebx,eax
  411356:	8d b8 d5 0d 00 00    	lea    edi,[eax+0xdd5]
  41135c:	81 c3 51 12 00 00    	add    ebx,0x1251
  411362:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]
  411369:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  411370:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  411374:	83 c3 10             	add    ebx,0x10
  411377:	89 3c 24             	mov    DWORD PTR [esp],edi
  41137a:	e8 71 16 02 00       	call   4329f0 <strcat>
  41137f:	89 3c 24             	mov    DWORD PTR [esp],edi
  411382:	e8 29 16 02 00       	call   4329b0 <strlen>
  411387:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  41138a:	b9 2c 20 00 00       	mov    ecx,0x202c
  41138f:	66 89 8c 10 d5 0d 00 	mov    WORD PTR [eax+edx*1+0xdd5],cx
  411396:	00
  411397:	31 c9                	xor    ecx,ecx
  411399:	4e                   	dec    esi
  41139a:	88 8c 10 d7 0d 00 00 	mov    BYTE PTR [eax+edx*1+0xdd7],cl
  4113a1:	79 cd                	jns    411370 <bixby110control::DataLogLineAssemblePayload()+0x30>
  4113a3:	83 c4 0c             	add    esp,0xc
  4113a6:	5b                   	pop    ebx
  4113a7:	5e                   	pop    esi
  4113a8:	5f                   	pop    edi
  4113a9:	5d                   	pop    ebp
  4113aa:	c3                   	ret
  4113ab:	90                   	nop
  4113ac:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]

# source=Bixby110dlg.cpp
# va=0x004113B0 size=0x160
0x004113B0 <bixby110control::WriteDataLogLine()>:
  4113b0:	55                   	push   ebp
  4113b1:	89 e5                	mov    ebp,esp
  4113b3:	81 ec 58 01 00 00    	sub    esp,0x158
  4113b9:	89 75 f8             	mov    DWORD PTR [ebp-0x8],esi
  4113bc:	8b 75 08             	mov    esi,DWORD PTR [ebp+0x8]
  4113bf:	89 5d f4             	mov    DWORD PTR [ebp-0xc],ebx
  4113c2:	89 7d fc             	mov    DWORD PTR [ebp-0x4],edi
  4113c5:	0f b6 86 d4 0a 00 00 	movzx  eax,BYTE PTR [esi+0xad4]
  4113cc:	3c 04                	cmp    al,0x4
  4113ce:	74 48                	je     411418 <bixby110control::WriteDataLogLine()+0x68>
  4113d0:	3c 03                	cmp    al,0x3
  4113d2:	0f 84 bc 00 00 00    	je     411494 <bixby110control::WriteDataLogLine()+0xe4>
  4113d8:	c6 86 d5 0d 00 00 00 	mov    BYTE PTR [esi+0xdd5],0x0
  4113df:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  4113e5:	8d bd e8 fe ff ff    	lea    edi,[ebp-0x118]
  4113eb:	89 1c 24             	mov    DWORD PTR [esp],ebx
  4113ee:	e8 7d 1a 02 00       	call   432e70 <GetLocalTime@4>
  4113f3:	83 ec 04             	sub    esp,0x4
  4113f6:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  4113fa:	89 1c 24             	mov    DWORD PTR [esp],ebx
  4113fd:	e8 ce 6e ff ff       	call   4082d0 <FormatTime(_SYSTEMTIME*, char*)>
  411402:	80 be d4 0a 00 00 04 	cmp    BYTE PTR [esi+0xad4],0x4
  411409:	74 26                	je     411431 <bixby110control::WriteDataLogLine()+0x81>
  41140b:	8b 5d f4             	mov    ebx,DWORD PTR [ebp-0xc]
  41140e:	8b 75 f8             	mov    esi,DWORD PTR [ebp-0x8]
  411411:	8b 7d fc             	mov    edi,DWORD PTR [ebp-0x4]
  411414:	89 ec                	mov    esp,ebp
  411416:	5d                   	pop    ebp
  411417:	c3                   	ret
  411418:	0f b6 86 71 14 00 00 	movzx  eax,BYTE PTR [esi+0x1471]
  41141f:	02 86 70 14 00 00    	add    al,BYTE PTR [esi+0x1470]
  411425:	3c 63                	cmp    al,0x63
  411427:	77 77                	ja     4114a0 <bixby110control::WriteDataLogLine()+0xf0>
  411429:	88 86 70 14 00 00    	mov    BYTE PTR [esi+0x1470],al
  41142f:	eb a7                	jmp    4113d8 <bixby110control::WriteDataLogLine()+0x28>
  411431:	8d 8e d5 0d 00 00    	lea    ecx,[esi+0xdd5]
  411437:	89 8d d0 fe ff ff    	mov    DWORD PTR [ebp-0x130],ecx
  41143d:	89 0c 24             	mov    DWORD PTR [esp],ecx
  411440:	e8 6b 15 02 00       	call   4329b0 <strlen>
  411445:	89 3c 24             	mov    DWORD PTR [esp],edi
  411448:	89 c3                	mov    ebx,eax
  41144a:	e8 61 15 02 00       	call   4329b0 <strlen>
  41144f:	8d 04 03             	lea    eax,[ebx+eax*1]
  411452:	3d f9 03 00 00       	cmp    eax,0x3f9
  411457:	77 b2                	ja     41140b <bixby110control::WriteDataLogLine()+0x5b>
  411459:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41145d:	8b 9d d0 fe ff ff    	mov    ebx,DWORD PTR [ebp-0x130]
  411463:	bf 2c 20 00 00       	mov    edi,0x202c
  411468:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41146b:	e8 80 15 02 00       	call   4329f0 <strcat>
  411470:	8b 85 d0 fe ff ff    	mov    eax,DWORD PTR [ebp-0x130]
  411476:	89 04 24             	mov    DWORD PTR [esp],eax
  411479:	e8 32 15 02 00       	call   4329b0 <strlen>
  41147e:	66 89 bc 30 d5 0d 00 	mov    WORD PTR [eax+esi*1+0xdd5],di
  411485:	00
  411486:	31 d2                	xor    edx,edx
  411488:	88 94 30 d7 0d 00 00 	mov    BYTE PTR [eax+esi*1+0xdd7],dl
  41148f:	e9 77 ff ff ff       	jmp    41140b <bixby110control::WriteDataLogLine()+0x5b>
  411494:	c6 86 d4 0a 00 00 04 	mov    BYTE PTR [esi+0xad4],0x4
  41149b:	e9 38 ff ff ff       	jmp    4113d8 <bixby110control::WriteDataLogLine()+0x28>
  4114a0:	8d 9e d5 0d 00 00    	lea    ebx,[esi+0xdd5]
  4114a6:	2c 64                	sub    al,0x64
  4114a8:	bf 0d 0a 00 00       	mov    edi,0xa0d
  4114ad:	88 86 70 14 00 00    	mov    BYTE PTR [esi+0x1470],al
  4114b3:	89 1c 24             	mov    DWORD PTR [esp],ebx
  4114b6:	e8 f5 14 02 00       	call   4329b0 <strlen>
  4114bb:	66 89 bc 30 d5 0d 00 	mov    WORD PTR [eax+esi*1+0xdd5],di
  4114c2:	00
  4114c3:	31 d2                	xor    edx,edx
  4114c5:	88 94 30 d7 0d 00 00 	mov    BYTE PTR [eax+esi*1+0xdd7],dl
  4114cc:	89 1c 24             	mov    DWORD PTR [esp],ebx
  4114cf:	e8 dc 14 02 00       	call   4329b0 <strlen>
  4114d4:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  4114d8:	31 c9                	xor    ecx,ecx
  4114da:	8d 95 d4 fe ff ff    	lea    edx,[ebp-0x12c]
  4114e0:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  4114e4:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  4114e8:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  4114ec:	8b 86 64 14 00 00    	mov    eax,DWORD PTR [esi+0x1464]
  4114f2:	89 04 24             	mov    DWORD PTR [esp],eax
  4114f5:	e8 56 19 02 00       	call   432e50 <WriteFile@20>
  4114fa:	0f b6 86 d4 0a 00 00 	movzx  eax,BYTE PTR [esi+0xad4]
  411501:	83 ec 14             	sub    esp,0x14
  411504:	e9 c7 fe ff ff       	jmp    4113d0 <bixby110control::WriteDataLogLine()+0x20>
  411509:	90                   	nop
  41150a:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]

# source=Bixby110dlg.cpp
# va=0x00411510 size=0x390
0x00411510 <bixby110control::WriteDataLogDescription()>:
  411510:	55                   	push   ebp
  411511:	89 e5                	mov    ebp,esp
  411513:	57                   	push   edi
  411514:	56                   	push   esi
  411515:	53                   	push   ebx
  411516:	81 ec 5c 01 00 00    	sub    esp,0x15c
  41151c:	8b 45 08             	mov    eax,DWORD PTR [ebp+0x8]
  41151f:	89 85 d0 fe ff ff    	mov    DWORD PTR [ebp-0x130],eax
  411525:	80 b8 d4 0a 00 00 04 	cmp    BYTE PTR [eax+0xad4],0x4
  41152c:	0f 84 ee 01 00 00    	je     411720 <bixby110control::WriteDataLogDescription()+0x210>
  411532:	8b 85 d0 fe ff ff    	mov    eax,DWORD PTR [ebp-0x130]
  411538:	31 db                	xor    ebx,ebx
  41153a:	be 41 01 44 00       	mov    esi,0x440141
  41153f:	05 d5 0d 00 00       	add    eax,0xdd5
  411544:	89 85 c4 fe ff ff    	mov    DWORD PTR [ebp-0x13c],eax
  41154a:	eb 11                	jmp    41155d <bixby110control::WriteDataLogDescription()+0x4d>
  41154c:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
  411550:	43                   	inc    ebx
  411551:	83 c6 58             	add    esi,0x58
  411554:	83 fb 1c             	cmp    ebx,0x1c
  411557:	0f 8f 93 00 00 00    	jg     4115f0 <bixby110control::WriteDataLogDescription()+0xe0>
  41155d:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  411563:	8b 8c 9a c0 01 00 00 	mov    ecx,DWORD PTR [edx+ebx*4+0x1c0]
  41156a:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41156d:	e8 0e 11 01 00       	call   422680 <manual3checkbox::IsChecked()>
  411572:	84 c0                	test   al,al
  411574:	74 da                	je     411550 <bixby110control::WriteDataLogDescription()+0x40>
  411576:	8b bd d0 fe ff ff    	mov    edi,DWORD PTR [ebp-0x130]
  41157c:	80 bf d4 0a 00 00 04 	cmp    BYTE PTR [edi+0xad4],0x4
  411583:	75 cb                	jne    411550 <bixby110control::WriteDataLogDescription()+0x40>
  411585:	8b 8d c4 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x13c]
  41158b:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41158e:	e8 1d 14 02 00       	call   4329b0 <strlen>
  411593:	89 34 24             	mov    DWORD PTR [esp],esi
  411596:	89 c7                	mov    edi,eax
  411598:	e8 13 14 02 00       	call   4329b0 <strlen>
  41159d:	8d 04 07             	lea    eax,[edi+eax*1]
  4115a0:	3d f9 03 00 00       	cmp    eax,0x3f9
  4115a5:	77 a9                	ja     411550 <bixby110control::WriteDataLogDescription()+0x40>
  4115a7:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  4115ab:	8b 95 c4 fe ff ff    	mov    edx,DWORD PTR [ebp-0x13c]
  4115b1:	43                   	inc    ebx
  4115b2:	bf 2c 20 00 00       	mov    edi,0x202c
  4115b7:	83 c6 58             	add    esi,0x58
  4115ba:	89 14 24             	mov    DWORD PTR [esp],edx
  4115bd:	e8 2e 14 02 00       	call   4329f0 <strcat>
  4115c2:	8b 85 c4 fe ff ff    	mov    eax,DWORD PTR [ebp-0x13c]
  4115c8:	89 04 24             	mov    DWORD PTR [esp],eax
  4115cb:	e8 e0 13 02 00       	call   4329b0 <strlen>
  4115d0:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  4115d6:	31 c9                	xor    ecx,ecx
  4115d8:	83 fb 1c             	cmp    ebx,0x1c
  4115db:	66 89 bc 10 d5 0d 00 	mov    WORD PTR [eax+edx*1+0xdd5],di
  4115e2:	00
  4115e3:	88 8c 10 d7 0d 00 00 	mov    BYTE PTR [eax+edx*1+0xdd7],cl
  4115ea:	0f 8e 6d ff ff ff    	jle    41155d <bixby110control::WriteDataLogDescription()+0x4d>
  4115f0:	8b 8d d0 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x130]
  4115f6:	be e9 0b 44 00       	mov    esi,0x440be9
  4115fb:	bf 1f 00 00 00       	mov    edi,0x1f
  411600:	0f b6 99 d4 0a 00 00 	movzx  ebx,BYTE PTR [ecx+0xad4]
  411607:	81 c1 d5 0d 00 00    	add    ecx,0xdd5
  41160d:	89 8d cc fe ff ff    	mov    DWORD PTR [ebp-0x134],ecx
  411613:	89 b5 c8 fe ff ff    	mov    DWORD PTR [ebp-0x138],esi
  411619:	80 fb 04             	cmp    bl,0x4
  41161c:	0f 84 84 00 00 00    	je     4116a6 <bixby110control::WriteDataLogDescription()+0x196>
  411622:	83 85 c8 fe ff ff 58 	add    DWORD PTR [ebp-0x138],0x58
  411629:	47                   	inc    edi
  41162a:	83 ff 21             	cmp    edi,0x21
  41162d:	7e ea                	jle    411619 <bixby110control::WriteDataLogDescription()+0x109>
  41162f:	80 fb 04             	cmp    bl,0x4
  411632:	0f 84 ab 01 00 00    	je     4117e3 <bixby110control::WriteDataLogDescription()+0x2d3>
  411638:	8b bd d0 fe ff ff    	mov    edi,DWORD PTR [ebp-0x130]
  41163e:	c6 87 70 14 00 00 64 	mov    BYTE PTR [edi+0x1470],0x64
  411645:	80 fb 03             	cmp    bl,0x3
  411648:	0f 84 bb 01 00 00    	je     411809 <bixby110control::WriteDataLogDescription()+0x2f9>
  41164e:	8b 8d d0 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x130]
  411654:	8d 9d d8 fe ff ff    	lea    ebx,[ebp-0x128]
  41165a:	8d b5 e8 fe ff ff    	lea    esi,[ebp-0x118]
  411660:	c6 81 d5 0d 00 00 00 	mov    BYTE PTR [ecx+0xdd5],0x0
  411667:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41166a:	e8 01 18 02 00       	call   432e70 <GetLocalTime@4>
  41166f:	83 ec 04             	sub    esp,0x4
  411672:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  411676:	89 1c 24             	mov    DWORD PTR [esp],ebx
  411679:	e8 52 6c ff ff       	call   4082d0 <FormatTime(_SYSTEMTIME*, char*)>
  41167e:	8b 85 d0 fe ff ff    	mov    eax,DWORD PTR [ebp-0x130]
  411684:	80 b8 d4 0a 00 00 04 	cmp    BYTE PTR [eax+0xad4],0x4
  41168b:	0f 84 f5 00 00 00    	je     411786 <bixby110control::WriteDataLogDescription()+0x276>
  411691:	8b 8d d0 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x130]
  411697:	c6 81 70 14 00 00 64 	mov    BYTE PTR [ecx+0x1470],0x64
  41169e:	8d 65 f4             	lea    esp,[ebp-0xc]
  4116a1:	5b                   	pop    ebx
  4116a2:	5e                   	pop    esi
  4116a3:	5f                   	pop    edi
  4116a4:	5d                   	pop    ebp
  4116a5:	c3                   	ret
  4116a6:	8b 8d cc fe ff ff    	mov    ecx,DWORD PTR [ebp-0x134]
  4116ac:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4116af:	e8 fc 12 02 00       	call   4329b0 <strlen>
  4116b4:	8b 95 c8 fe ff ff    	mov    edx,DWORD PTR [ebp-0x138]
  4116ba:	89 c6                	mov    esi,eax
  4116bc:	89 14 24             	mov    DWORD PTR [esp],edx
  4116bf:	e8 ec 12 02 00       	call   4329b0 <strlen>
  4116c4:	8d 04 06             	lea    eax,[esi+eax*1]
  4116c7:	3d f9 03 00 00       	cmp    eax,0x3f9
  4116cc:	0f 87 50 ff ff ff    	ja     411622 <bixby110control::WriteDataLogDescription()+0x112>
  4116d2:	8b b5 c8 fe ff ff    	mov    esi,DWORD PTR [ebp-0x138]
  4116d8:	31 db                	xor    ebx,ebx
  4116da:	8b 8d cc fe ff ff    	mov    ecx,DWORD PTR [ebp-0x134]
  4116e0:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  4116e4:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4116e7:	e8 04 13 02 00       	call   4329f0 <strcat>
  4116ec:	8b 85 cc fe ff ff    	mov    eax,DWORD PTR [ebp-0x134]
  4116f2:	89 04 24             	mov    DWORD PTR [esp],eax
  4116f5:	e8 b6 12 02 00       	call   4329b0 <strlen>
  4116fa:	8b b5 d0 fe ff ff    	mov    esi,DWORD PTR [ebp-0x130]
  411700:	ba 2c 20 00 00       	mov    edx,0x202c
  411705:	66 89 94 30 d5 0d 00 	mov    WORD PTR [eax+esi*1+0xdd5],dx
  41170c:	00
  41170d:	88 9c 30 d7 0d 00 00 	mov    BYTE PTR [eax+esi*1+0xdd7],bl
  411714:	0f b6 9e d4 0a 00 00 	movzx  ebx,BYTE PTR [esi+0xad4]
  41171b:	e9 02 ff ff ff       	jmp    411622 <bixby110control::WriteDataLogDescription()+0x112>
  411720:	89 c6                	mov    esi,eax
  411722:	81 c6 d5 0d 00 00    	add    esi,0xdd5
  411728:	89 34 24             	mov    DWORD PTR [esp],esi
  41172b:	e8 80 12 02 00       	call   4329b0 <strlen>
  411730:	c7 04 24 e8 4e 44 00 	mov    DWORD PTR [esp],0x444ee8
  411737:	89 c3                	mov    ebx,eax
  411739:	e8 72 12 02 00       	call   4329b0 <strlen>
  41173e:	8d 04 03             	lea    eax,[ebx+eax*1]
  411741:	3d f9 03 00 00       	cmp    eax,0x3f9
  411746:	0f 87 e6 fd ff ff    	ja     411532 <bixby110control::WriteDataLogDescription()+0x22>
  41174c:	89 34 24             	mov    DWORD PTR [esp],esi
  41174f:	bf e8 4e 44 00       	mov    edi,0x444ee8
  411754:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  411758:	e8 93 12 02 00       	call   4329f0 <strcat>
  41175d:	89 34 24             	mov    DWORD PTR [esp],esi
  411760:	be 2c 20 00 00       	mov    esi,0x202c
  411765:	e8 46 12 02 00       	call   4329b0 <strlen>
  41176a:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  411770:	31 c9                	xor    ecx,ecx
  411772:	66 89 b4 10 d5 0d 00 	mov    WORD PTR [eax+edx*1+0xdd5],si
  411779:	00
  41177a:	88 8c 10 d7 0d 00 00 	mov    BYTE PTR [eax+edx*1+0xdd7],cl
  411781:	e9 ac fd ff ff       	jmp    411532 <bixby110control::WriteDataLogDescription()+0x22>
  411786:	89 c7                	mov    edi,eax
  411788:	81 c7 d5 0d 00 00    	add    edi,0xdd5
  41178e:	89 3c 24             	mov    DWORD PTR [esp],edi
  411791:	e8 1a 12 02 00       	call   4329b0 <strlen>
  411796:	89 34 24             	mov    DWORD PTR [esp],esi
  411799:	89 c3                	mov    ebx,eax
  41179b:	e8 10 12 02 00       	call   4329b0 <strlen>
  4117a0:	8d 04 03             	lea    eax,[ebx+eax*1]
  4117a3:	3d f9 03 00 00       	cmp    eax,0x3f9
  4117a8:	0f 87 e3 fe ff ff    	ja     411691 <bixby110control::WriteDataLogDescription()+0x181>
  4117ae:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  4117b2:	be 2c 20 00 00       	mov    esi,0x202c
  4117b7:	89 3c 24             	mov    DWORD PTR [esp],edi
  4117ba:	e8 31 12 02 00       	call   4329f0 <strcat>
  4117bf:	89 3c 24             	mov    DWORD PTR [esp],edi
  4117c2:	e8 e9 11 02 00       	call   4329b0 <strlen>
  4117c7:	8b bd d0 fe ff ff    	mov    edi,DWORD PTR [ebp-0x130]
  4117cd:	31 d2                	xor    edx,edx
  4117cf:	66 89 b4 38 d5 0d 00 	mov    WORD PTR [eax+edi*1+0xdd5],si
  4117d6:	00
  4117d7:	88 94 38 d7 0d 00 00 	mov    BYTE PTR [eax+edi*1+0xdd7],dl
  4117de:	e9 ae fe ff ff       	jmp    411691 <bixby110control::WriteDataLogDescription()+0x181>
  4117e3:	8b bd d0 fe ff ff    	mov    edi,DWORD PTR [ebp-0x130]
  4117e9:	0f b6 97 71 14 00 00 	movzx  edx,BYTE PTR [edi+0x1471]
  4117f0:	88 d0                	mov    al,dl
  4117f2:	04 64                	add    al,0x64
  4117f4:	3c 63                	cmp    al,0x63
  4117f6:	77 23                	ja     41181b <bixby110control::WriteDataLogDescription()+0x30b>
  4117f8:	8b b5 d0 fe ff ff    	mov    esi,DWORD PTR [ebp-0x130]
  4117fe:	88 86 70 14 00 00    	mov    BYTE PTR [esi+0x1470],al
  411804:	e9 45 fe ff ff       	jmp    41164e <bixby110control::WriteDataLogDescription()+0x13e>
  411809:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  41180f:	c6 82 d4 0a 00 00 04 	mov    BYTE PTR [edx+0xad4],0x4
  411816:	e9 33 fe ff ff       	jmp    41164e <bixby110control::WriteDataLogDescription()+0x13e>
  41181b:	8b 85 d0 fe ff ff    	mov    eax,DWORD PTR [ebp-0x130]
  411821:	31 db                	xor    ebx,ebx
  411823:	31 f6                	xor    esi,esi
  411825:	88 90 70 14 00 00    	mov    BYTE PTR [eax+0x1470],dl
  41182b:	89 c7                	mov    edi,eax
  41182d:	81 c7 d5 0d 00 00    	add    edi,0xdd5
  411833:	89 3c 24             	mov    DWORD PTR [esp],edi
  411836:	e8 75 11 02 00       	call   4329b0 <strlen>
  41183b:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  411841:	b9 0d 0a 00 00       	mov    ecx,0xa0d
  411846:	66 89 8c 10 d5 0d 00 	mov    WORD PTR [eax+edx*1+0xdd5],cx
  41184d:	00
  41184e:	88 9c 10 d7 0d 00 00 	mov    BYTE PTR [eax+edx*1+0xdd7],bl
  411855:	89 3c 24             	mov    DWORD PTR [esp],edi
  411858:	e8 53 11 02 00       	call   4329b0 <strlen>
  41185d:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  411861:	8b 85 d0 fe ff ff    	mov    eax,DWORD PTR [ebp-0x130]
  411867:	8d 8d d4 fe ff ff    	lea    ecx,[ebp-0x12c]
  41186d:	89 74 24 10          	mov    DWORD PTR [esp+0x10],esi
  411871:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  411875:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  411879:	8b 98 64 14 00 00    	mov    ebx,DWORD PTR [eax+0x1464]
  41187f:	89 1c 24             	mov    DWORD PTR [esp],ebx
  411882:	e8 c9 15 02 00       	call   432e50 <WriteFile@20>
  411887:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  41188d:	83 ec 14             	sub    esp,0x14
  411890:	0f b6 9a d4 0a 00 00 	movzx  ebx,BYTE PTR [edx+0xad4]
  411897:	e9 a9 fd ff ff       	jmp    411645 <bixby110control::WriteDataLogDescription()+0x135>
  41189c:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]

# source=Bixby110dlg.cpp
# va=0x00415750 size=0x900
0x00415750 <bixby110control::LoadReport(char*)>:
  415750:	55                   	push   ebp
  415751:	b8 bc 14 00 00       	mov    eax,0x14bc
  415756:	89 e5                	mov    ebp,esp
  415758:	57                   	push   edi
  415759:	56                   	push   esi
  41575a:	53                   	push   ebx
  41575b:	e8 b0 ce 01 00       	call   432610 <__chkstk>
  415760:	8b 5d 0c             	mov    ebx,DWORD PTR [ebp+0xc]
  415763:	31 ff                	xor    edi,edi
  415765:	8d 85 c8 eb ff ff    	lea    eax,[ebp-0x1438]
  41576b:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  41576f:	8b 55 08             	mov    edx,DWORD PTR [ebp+0x8]
  415772:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415776:	89 1c 24             	mov    DWORD PTR [esp],ebx
  415779:	89 95 6c eb ff ff    	mov    DWORD PTR [ebp-0x1494],edx
  41577f:	e8 3c d7 01 00       	call   432ec0 <OpenFile@12>
  415784:	89 85 68 eb ff ff    	mov    DWORD PTR [ebp-0x1498],eax
  41578a:	83 ec 0c             	sub    esp,0xc
  41578d:	83 f8 ff             	cmp    eax,0xffffffff
  415790:	0f 84 65 08 00 00    	je     415ffb <bixby110control::LoadReport(char*)+0x8ab>
  415796:	89 04 24             	mov    DWORD PTR [esp],eax
  415799:	31 c9                	xor    ecx,ecx
  41579b:	8d bd 74 eb ff ff    	lea    edi,[ebp-0x148c]
  4157a1:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  4157a5:	8d b5 58 ec ff ff    	lea    esi,[ebp-0x13a8]
  4157ab:	e8 20 d7 01 00       	call   432ed0 <GetFileSize@8>
  4157b0:	83 ec 08             	sub    esp,0x8
  4157b3:	31 d2                	xor    edx,edx
  4157b5:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  4157b9:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  4157bd:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  4157c1:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  4157c5:	8b 8d 68 eb ff ff    	mov    ecx,DWORD PTR [ebp-0x1498]
  4157cb:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4157ce:	e8 8d d6 01 00       	call   432e60 <ReadFile@20>
  4157d3:	83 ec 14             	sub    esp,0x14
  4157d6:	84 c0                	test   al,al
  4157d8:	0f 84 be 07 00 00    	je     415f9c <bixby110control::LoadReport(char*)+0x84c>
  4157de:	8b bd 74 eb ff ff    	mov    edi,DWORD PTR [ebp-0x148c]
  4157e4:	8d 95 58 ec ff ff    	lea    edx,[ebp-0x13a8]
  4157ea:	b9 88 50 44 00       	mov    ecx,0x445088
  4157ef:	31 db                	xor    ebx,ebx
  4157f1:	88 9c 2f 58 ec ff ff 	mov    BYTE PTR [edi+ebp*1-0x13a8],bl
  4157f8:	8d bd 72 eb ff ff    	lea    edi,[ebp-0x148e]
  4157fe:	c6 85 72 eb ff ff 0d 	mov    BYTE PTR [ebp-0x148e],0xd
  415805:	c6 85 73 eb ff ff 00 	mov    BYTE PTR [ebp-0x148d],0x0
  41580c:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415810:	89 14 24             	mov    DWORD PTR [esp],edx
  415813:	e8 28 27 ff ff       	call   407f40 <strsearchtail(char*, char*)>
  415818:	89 04 24             	mov    DWORD PTR [esp],eax
  41581b:	89 c6                	mov    esi,eax
  41581d:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  415821:	e8 9a 26 ff ff       	call   407ec0 <strsearch(char*, char*)>
  415826:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41582a:	89 c3                	mov    ebx,eax
  41582c:	29 f3                	sub    ebx,esi
  41582e:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  415832:	8b b5 6c eb ff ff    	mov    esi,DWORD PTR [ebp-0x1494]
  415838:	81 c6 6d 1d 00 00    	add    esi,0x1d6d
  41583e:	89 b5 5c eb ff ff    	mov    DWORD PTR [ebp-0x14a4],esi
  415844:	89 34 24             	mov    DWORD PTR [esp],esi
  415847:	be ff c0 40 00       	mov    esi,0x40c0ff
  41584c:	e8 af d1 01 00       	call   432a00 <strncpy>
  415851:	8b 8d 6c eb ff ff    	mov    ecx,DWORD PTR [ebp-0x1494]
  415857:	31 c0                	xor    eax,eax
  415859:	88 84 19 6d 1d 00 00 	mov    BYTE PTR [ecx+ebx*1+0x1d6d],al
  415860:	8b 9d 5c eb ff ff    	mov    ebx,DWORD PTR [ebp-0x14a4]
  415866:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41586a:	8b 91 00 08 00 00    	mov    edx,DWORD PTR [ecx+0x800]
  415870:	89 14 24             	mov    DWORD PTR [esp],edx
  415873:	e8 f8 d8 00 00       	call   423170 <edit::Settext(char const*)>
  415878:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41587c:	8b 85 6c eb ff ff    	mov    eax,DWORD PTR [ebp-0x1494]
  415882:	8b 98 00 08 00 00    	mov    ebx,DWORD PTR [eax+0x800]
  415888:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41588b:	e8 70 d9 00 00       	call   423200 <edit::SetBkColor(unsigned long)>
  415890:	8d 8d 58 ec ff ff    	lea    ecx,[ebp-0x13a8]
  415896:	ba 98 50 44 00       	mov    edx,0x445098
  41589b:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41589f:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4158a2:	e8 99 26 ff ff       	call   407f40 <strsearchtail(char*, char*)>
  4158a7:	89 04 24             	mov    DWORD PTR [esp],eax
  4158aa:	89 c6                	mov    esi,eax
  4158ac:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  4158b0:	e8 0b 26 ff ff       	call   407ec0 <strsearch(char*, char*)>
  4158b5:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  4158b9:	89 c3                	mov    ebx,eax
  4158bb:	29 f3                	sub    ebx,esi
  4158bd:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  4158c1:	8b b5 5c eb ff ff    	mov    esi,DWORD PTR [ebp-0x14a4]
  4158c7:	89 34 24             	mov    DWORD PTR [esp],esi
  4158ca:	be ff c0 40 00       	mov    esi,0x40c0ff
  4158cf:	e8 2c d1 01 00       	call   432a00 <strncpy>
  4158d4:	8b 95 6c eb ff ff    	mov    edx,DWORD PTR [ebp-0x1494]
  4158da:	31 c0                	xor    eax,eax
  4158dc:	88 84 1a 6d 1d 00 00 	mov    BYTE PTR [edx+ebx*1+0x1d6d],al
  4158e3:	8b 9d 5c eb ff ff    	mov    ebx,DWORD PTR [ebp-0x14a4]
  4158e9:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  4158ed:	8b 8a 04 08 00 00    	mov    ecx,DWORD PTR [edx+0x804]
  4158f3:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4158f6:	e8 75 d8 00 00       	call   423170 <edit::Settext(char const*)>
  4158fb:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  4158ff:	8b 85 6c eb ff ff    	mov    eax,DWORD PTR [ebp-0x1494]
  415905:	8b 98 04 08 00 00    	mov    ebx,DWORD PTR [eax+0x804]
  41590b:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41590e:	e8 ed d8 00 00       	call   423200 <edit::SetBkColor(unsigned long)>
  415913:	8d 95 58 ec ff ff    	lea    edx,[ebp-0x13a8]
  415919:	b9 aa 50 44 00       	mov    ecx,0x4450aa
  41591e:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415922:	89 14 24             	mov    DWORD PTR [esp],edx
  415925:	e8 16 26 ff ff       	call   407f40 <strsearchtail(char*, char*)>
  41592a:	89 04 24             	mov    DWORD PTR [esp],eax
  41592d:	89 c6                	mov    esi,eax
  41592f:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  415933:	e8 88 25 ff ff       	call   407ec0 <strsearch(char*, char*)>
  415938:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41593c:	89 c3                	mov    ebx,eax
  41593e:	29 f3                	sub    ebx,esi
  415940:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  415944:	8b b5 5c eb ff ff    	mov    esi,DWORD PTR [ebp-0x14a4]
  41594a:	89 34 24             	mov    DWORD PTR [esp],esi
  41594d:	be ff c0 40 00       	mov    esi,0x40c0ff
  415952:	e8 a9 d0 01 00       	call   432a00 <strncpy>
  415957:	8b 95 6c eb ff ff    	mov    edx,DWORD PTR [ebp-0x1494]
  41595d:	31 c0                	xor    eax,eax
  41595f:	88 84 1a 6d 1d 00 00 	mov    BYTE PTR [edx+ebx*1+0x1d6d],al
  415966:	8b 8d 5c eb ff ff    	mov    ecx,DWORD PTR [ebp-0x14a4]
  41596c:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415970:	8b ba 08 08 00 00    	mov    edi,DWORD PTR [edx+0x808]
  415976:	89 3c 24             	mov    DWORD PTR [esp],edi
  415979:	e8 f2 d7 00 00       	call   423170 <edit::Settext(char const*)>
  41597e:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  415982:	8b 85 6c eb ff ff    	mov    eax,DWORD PTR [ebp-0x1494]
  415988:	8b 98 08 08 00 00    	mov    ebx,DWORD PTR [eax+0x808]
  41598e:	89 1c 24             	mov    DWORD PTR [esp],ebx
  415991:	e8 6a d8 00 00       	call   423200 <edit::SetBkColor(unsigned long)>
  415996:	c6 85 66 eb ff ff 00 	mov    BYTE PTR [ebp-0x149a],0x0
  41599d:	80 bd 66 eb ff ff 00 	cmp    BYTE PTR [ebp-0x149a],0x0
  4159a4:	0f 85 d4 05 00 00    	jne    415f7e <bixby110control::LoadReport(char*)+0x82e>
  4159aa:	c6 85 7c eb ff ff 00 	mov    BYTE PTR [ebp-0x1484],0x0
  4159b1:	b8 20 41 3a 20       	mov    eax,0x203a4120
  4159b6:	89 85 78 eb ff ff    	mov    DWORD PTR [ebp-0x1488],eax
  4159bc:	c6 85 67 eb ff ff 00 	mov    BYTE PTR [ebp-0x1499],0x0
  4159c3:	ba 46 61 6e 20       	mov    edx,0x206e6146
  4159c8:	be 4c 65 76 65       	mov    esi,0x6576654c
  4159cd:	b8 6c 73 20 00       	mov    eax,0x20736c
  4159d2:	89 95 88 eb ff ff    	mov    DWORD PTR [ebp-0x1478],edx
  4159d8:	8d bd 88 eb ff ff    	lea    edi,[ebp-0x1478]
  4159de:	8d 9d 78 eb ff ff    	lea    ebx,[ebp-0x1488]
  4159e4:	89 b5 8c eb ff ff    	mov    DWORD PTR [ebp-0x1474],esi
  4159ea:	89 85 90 eb ff ff    	mov    DWORD PTR [ebp-0x1470],eax
  4159f0:	89 3c 24             	mov    DWORD PTR [esp],edi
  4159f3:	31 ff                	xor    edi,edi
  4159f5:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  4159f9:	e8 f2 cf 01 00       	call   4329f0 <strcat>
  4159fe:	8d 8d 88 eb ff ff    	lea    ecx,[ebp-0x1478]
  415a04:	8d 95 58 ec ff ff    	lea    edx,[ebp-0x13a8]
  415a0a:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415a0e:	89 14 24             	mov    DWORD PTR [esp],edx
  415a11:	e8 2a 25 ff ff       	call   407f40 <strsearchtail(char*, char*)>
  415a16:	89 c6                	mov    esi,eax
  415a18:	90                   	nop
  415a19:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]
  415a20:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  415a24:	b8 03 00 00 00       	mov    eax,0x3
  415a29:	83 c6 05             	add    esi,0x5
  415a2c:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  415a30:	8b 8d 5c eb ff ff    	mov    ecx,DWORD PTR [ebp-0x14a4]
  415a36:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415a39:	e8 c2 cf 01 00       	call   432a00 <strncpy>
  415a3e:	8b 85 6c eb ff ff    	mov    eax,DWORD PTR [ebp-0x1494]
  415a44:	c6 80 70 1d 00 00 00 	mov    BYTE PTR [eax+0x1d70],0x0
  415a4b:	8b 95 5c eb ff ff    	mov    edx,DWORD PTR [ebp-0x14a4]
  415a51:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415a55:	0f b6 9d 67 eb ff ff 	movzx  ebx,BYTE PTR [ebp-0x1499]
  415a5c:	8d 1c 1f             	lea    ebx,[edi+ebx*1]
  415a5f:	8b 8c 98 e4 04 00 00 	mov    ecx,DWORD PTR [eax+ebx*4+0x4e4]
  415a66:	47                   	inc    edi
  415a67:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415a6a:	e8 01 d7 00 00       	call   423170 <edit::Settext(char const*)>
  415a6f:	8b 85 6c eb ff ff    	mov    eax,DWORD PTR [ebp-0x1494]
  415a75:	ba ff c0 40 00       	mov    edx,0x40c0ff
  415a7a:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415a7e:	8b 8c 98 e4 04 00 00 	mov    ecx,DWORD PTR [eax+ebx*4+0x4e4]
  415a85:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415a88:	e8 73 d7 00 00       	call   423200 <edit::SetBkColor(unsigned long)>
  415a8d:	83 ff 07             	cmp    edi,0x7
  415a90:	7e 8e                	jle    415a20 <bixby110control::LoadReport(char*)+0x2d0>
  415a92:	b9 65 6c 73 00       	mov    ecx,0x736c65
  415a97:	8d 95 78 eb ff ff    	lea    edx,[ebp-0x1488]
  415a9d:	bf 46 65 65 64       	mov    edi,0x64656546
  415aa2:	89 bd 88 eb ff ff    	mov    DWORD PTR [ebp-0x1478],edi
  415aa8:	b8 20 4c 65 76       	mov    eax,0x76654c20
  415aad:	8d 9d 88 eb ff ff    	lea    ebx,[ebp-0x1478]
  415ab3:	89 8d 90 eb ff ff    	mov    DWORD PTR [ebp-0x1470],ecx
  415ab9:	8d b5 88 eb ff ff    	lea    esi,[ebp-0x1478]
  415abf:	8d bd 58 ec ff ff    	lea    edi,[ebp-0x13a8]
  415ac5:	89 85 8c eb ff ff    	mov    DWORD PTR [ebp-0x1474],eax
  415acb:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415acf:	89 1c 24             	mov    DWORD PTR [esp],ebx
  415ad2:	e8 19 cf 01 00       	call   4329f0 <strcat>
  415ad7:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  415adb:	89 3c 24             	mov    DWORD PTR [esp],edi
  415ade:	31 ff                	xor    edi,edi
  415ae0:	e8 5b 24 ff ff       	call   407f40 <strsearchtail(char*, char*)>
  415ae5:	89 c6                	mov    esi,eax
  415ae7:	89 f6                	mov    esi,esi
  415ae9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  415af0:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  415af4:	ba 03 00 00 00       	mov    edx,0x3
  415af9:	83 c6 05             	add    esi,0x5
  415afc:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  415b00:	8b 8d 5c eb ff ff    	mov    ecx,DWORD PTR [ebp-0x14a4]
  415b06:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415b09:	e8 f2 ce 01 00       	call   432a00 <strncpy>
  415b0e:	8b 95 6c eb ff ff    	mov    edx,DWORD PTR [ebp-0x1494]
  415b14:	c6 82 70 1d 00 00 00 	mov    BYTE PTR [edx+0x1d70],0x0
  415b1b:	8b 85 5c eb ff ff    	mov    eax,DWORD PTR [ebp-0x14a4]
  415b21:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415b25:	0f b6 9d 67 eb ff ff 	movzx  ebx,BYTE PTR [ebp-0x1499]
  415b2c:	8d 1c 1f             	lea    ebx,[edi+ebx*1]
  415b2f:	8b 8c 9a 04 05 00 00 	mov    ecx,DWORD PTR [edx+ebx*4+0x504]
  415b36:	47                   	inc    edi
  415b37:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415b3a:	e8 31 d6 00 00       	call   423170 <edit::Settext(char const*)>
  415b3f:	8b 95 6c eb ff ff    	mov    edx,DWORD PTR [ebp-0x1494]
  415b45:	b8 ff c0 40 00       	mov    eax,0x40c0ff
  415b4a:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415b4e:	8b 8c 9a 04 05 00 00 	mov    ecx,DWORD PTR [edx+ebx*4+0x504]
  415b55:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415b58:	e8 a3 d6 00 00       	call   423200 <edit::SetBkColor(unsigned long)>
  415b5d:	83 ff 07             	cmp    edi,0x7
  415b60:	7e 8e                	jle    415af0 <bixby110control::LoadReport(char*)+0x3a0>
  415b62:	ba 4c 65 76 65       	mov    edx,0x6576654c
  415b67:	b9 6c 73 20 00       	mov    ecx,0x20736c
  415b6c:	be 41 73 68 20       	mov    esi,0x20687341
  415b71:	89 b5 88 eb ff ff    	mov    DWORD PTR [ebp-0x1478],esi
  415b77:	8d 85 78 eb ff ff    	lea    eax,[ebp-0x1488]
  415b7d:	8d 9d 88 eb ff ff    	lea    ebx,[ebp-0x1478]
  415b83:	89 95 8c eb ff ff    	mov    DWORD PTR [ebp-0x1474],edx
  415b89:	8d bd 88 eb ff ff    	lea    edi,[ebp-0x1478]
  415b8f:	8d b5 58 ec ff ff    	lea    esi,[ebp-0x13a8]
  415b95:	89 8d 90 eb ff ff    	mov    DWORD PTR [ebp-0x1470],ecx
  415b9b:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415b9f:	89 1c 24             	mov    DWORD PTR [esp],ebx
  415ba2:	e8 49 ce 01 00       	call   4329f0 <strcat>
  415ba7:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  415bab:	31 ff                	xor    edi,edi
  415bad:	89 34 24             	mov    DWORD PTR [esp],esi
  415bb0:	e8 8b 23 ff ff       	call   407f40 <strsearchtail(char*, char*)>
  415bb5:	89 c6                	mov    esi,eax
  415bb7:	89 f6                	mov    esi,esi
  415bb9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  415bc0:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  415bc4:	ba 03 00 00 00       	mov    edx,0x3
  415bc9:	83 c6 05             	add    esi,0x5
  415bcc:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  415bd0:	8b 85 5c eb ff ff    	mov    eax,DWORD PTR [ebp-0x14a4]
  415bd6:	89 04 24             	mov    DWORD PTR [esp],eax
  415bd9:	e8 22 ce 01 00       	call   432a00 <strncpy>
  415bde:	8b 95 6c eb ff ff    	mov    edx,DWORD PTR [ebp-0x1494]
  415be4:	c6 82 70 1d 00 00 00 	mov    BYTE PTR [edx+0x1d70],0x0
  415beb:	8b 9d 5c eb ff ff    	mov    ebx,DWORD PTR [ebp-0x14a4]
  415bf1:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  415bf5:	0f b6 8d 67 eb ff ff 	movzx  ecx,BYTE PTR [ebp-0x1499]
  415bfc:	8d 1c 0f             	lea    ebx,[edi+ecx*1]
  415bff:	8b 84 9a 24 05 00 00 	mov    eax,DWORD PTR [edx+ebx*4+0x524]
  415c06:	47                   	inc    edi
  415c07:	89 04 24             	mov    DWORD PTR [esp],eax
  415c0a:	e8 61 d5 00 00       	call   423170 <edit::Settext(char const*)>
  415c0f:	8b 8d 6c eb ff ff    	mov    ecx,DWORD PTR [ebp-0x1494]
  415c15:	ba ff c0 40 00       	mov    edx,0x40c0ff
  415c1a:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415c1e:	8b 84 99 24 05 00 00 	mov    eax,DWORD PTR [ecx+ebx*4+0x524]
  415c25:	89 04 24             	mov    DWORD PTR [esp],eax
  415c28:	e8 d3 d5 00 00       	call   423200 <edit::SetBkColor(unsigned long)>
  415c2d:	83 ff 07             	cmp    edi,0x7
  415c30:	7e 8e                	jle    415bc0 <bixby110control::LoadReport(char*)+0x470>
  415c32:	c6 85 9c eb ff ff 00 	mov    BYTE PTR [ebp-0x1464],0x0
  415c39:	b9 53 74 61 72       	mov    ecx,0x72617453
  415c3e:	ba 73 74 6d 65       	mov    edx,0x656d7473
  415c43:	89 8d 88 eb ff ff    	mov    DWORD PTR [ebp-0x1478],ecx
  415c49:	be 74 75 70 20       	mov    esi,0x20707574
  415c4e:	8d 8d 88 eb ff ff    	lea    ecx,[ebp-0x1478]
  415c54:	89 b5 8c eb ff ff    	mov    DWORD PTR [ebp-0x1474],esi
  415c5a:	bf 41 64 6a 75       	mov    edi,0x756a6441
  415c5f:	b8 6e 74 73 20       	mov    eax,0x2073746e
  415c64:	89 bd 90 eb ff ff    	mov    DWORD PTR [ebp-0x1470],edi
  415c6a:	8d 9d 78 eb ff ff    	lea    ebx,[ebp-0x1488]
  415c70:	8d b5 88 eb ff ff    	lea    esi,[ebp-0x1478]
  415c76:	89 95 94 eb ff ff    	mov    DWORD PTR [ebp-0x146c],edx
  415c7c:	8d bd 58 ec ff ff    	lea    edi,[ebp-0x13a8]
  415c82:	89 85 98 eb ff ff    	mov    DWORD PTR [ebp-0x1468],eax
  415c88:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415c8b:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  415c8f:	e8 5c cd 01 00       	call   4329f0 <strcat>
  415c94:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  415c98:	89 3c 24             	mov    DWORD PTR [esp],edi
  415c9b:	31 ff                	xor    edi,edi
  415c9d:	e8 9e 22 ff ff       	call   407f40 <strsearchtail(char*, char*)>
  415ca2:	89 c6                	mov    esi,eax
  415ca4:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  415ca8:	ba 03 00 00 00       	mov    edx,0x3
  415cad:	83 c6 05             	add    esi,0x5
  415cb0:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  415cb4:	8b 85 5c eb ff ff    	mov    eax,DWORD PTR [ebp-0x14a4]
  415cba:	89 04 24             	mov    DWORD PTR [esp],eax
  415cbd:	e8 3e cd 01 00       	call   432a00 <strncpy>
  415cc2:	8b 95 6c eb ff ff    	mov    edx,DWORD PTR [ebp-0x1494]
  415cc8:	c6 82 70 1d 00 00 00 	mov    BYTE PTR [edx+0x1d70],0x0
  415ccf:	8b 8d 5c eb ff ff    	mov    ecx,DWORD PTR [ebp-0x14a4]
  415cd5:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415cd9:	0f b6 9d 67 eb ff ff 	movzx  ebx,BYTE PTR [ebp-0x1499]
  415ce0:	8d 1c 1f             	lea    ebx,[edi+ebx*1]
  415ce3:	8b 84 9a 44 05 00 00 	mov    eax,DWORD PTR [edx+ebx*4+0x544]
  415cea:	47                   	inc    edi
  415ceb:	89 04 24             	mov    DWORD PTR [esp],eax
  415cee:	e8 7d d4 00 00       	call   423170 <edit::Settext(char const*)>
  415cf3:	8b 95 6c eb ff ff    	mov    edx,DWORD PTR [ebp-0x1494]
  415cf9:	b9 ff c0 40 00       	mov    ecx,0x40c0ff
  415cfe:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415d02:	8b 84 9a 44 05 00 00 	mov    eax,DWORD PTR [edx+ebx*4+0x544]
  415d09:	89 04 24             	mov    DWORD PTR [esp],eax
  415d0c:	e8 ef d4 00 00       	call   423200 <edit::SetBkColor(unsigned long)>
  415d11:	83 ff 01             	cmp    edi,0x1
  415d14:	7e 8e                	jle    415ca4 <bixby110control::LoadReport(char*)+0x554>
  415d16:	c6 85 9c eb ff ff 00 	mov    BYTE PTR [ebp-0x1464],0x0
  415d1d:	bb 41 73 68 20       	mov    ebx,0x20687341
  415d22:	ba 75 73 74 6d       	mov    edx,0x6d747375
  415d27:	89 9d 88 eb ff ff    	mov    DWORD PTR [ebp-0x1478],ebx
  415d2d:	8d 8d 78 eb ff ff    	lea    ecx,[ebp-0x1488]
  415d33:	be 44 75 6d 70       	mov    esi,0x706d7544
  415d38:	89 b5 8c eb ff ff    	mov    DWORD PTR [ebp-0x1474],esi
  415d3e:	bf 20 41 64 6a       	mov    edi,0x6a644120
  415d43:	b8 65 6e 74 73       	mov    eax,0x73746e65
  415d48:	89 bd 90 eb ff ff    	mov    DWORD PTR [ebp-0x1470],edi
  415d4e:	8d 9d 88 eb ff ff    	lea    ebx,[ebp-0x1478]
  415d54:	8d b5 88 eb ff ff    	lea    esi,[ebp-0x1478]
  415d5a:	89 95 94 eb ff ff    	mov    DWORD PTR [ebp-0x146c],edx
  415d60:	8d bd 58 ec ff ff    	lea    edi,[ebp-0x13a8]
  415d66:	89 85 98 eb ff ff    	mov    DWORD PTR [ebp-0x1468],eax
  415d6c:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415d70:	89 1c 24             	mov    DWORD PTR [esp],ebx
  415d73:	e8 78 cc 01 00       	call   4329f0 <strcat>
  415d78:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  415d7c:	89 3c 24             	mov    DWORD PTR [esp],edi
  415d7f:	31 ff                	xor    edi,edi
  415d81:	e8 ba 21 ff ff       	call   407f40 <strsearchtail(char*, char*)>
  415d86:	89 c6                	mov    esi,eax
  415d88:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  415d8c:	ba 03 00 00 00       	mov    edx,0x3
  415d91:	83 c6 05             	add    esi,0x5
  415d94:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  415d98:	8b 8d 5c eb ff ff    	mov    ecx,DWORD PTR [ebp-0x14a4]
  415d9e:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415da1:	e8 5a cc 01 00       	call   432a00 <strncpy>
  415da6:	8b 95 6c eb ff ff    	mov    edx,DWORD PTR [ebp-0x1494]
  415dac:	c6 82 70 1d 00 00 00 	mov    BYTE PTR [edx+0x1d70],0x0
  415db3:	8b 9d 5c eb ff ff    	mov    ebx,DWORD PTR [ebp-0x14a4]
  415db9:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  415dbd:	0f b6 85 67 eb ff ff 	movzx  eax,BYTE PTR [ebp-0x1499]
  415dc4:	8d 1c 07             	lea    ebx,[edi+eax*1]
  415dc7:	8b 8c 9a 4c 05 00 00 	mov    ecx,DWORD PTR [edx+ebx*4+0x54c]
  415dce:	89 85 60 eb ff ff    	mov    DWORD PTR [ebp-0x14a0],eax
  415dd4:	47                   	inc    edi
  415dd5:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415dd8:	e8 93 d3 00 00       	call   423170 <edit::Settext(char const*)>
  415ddd:	8b 85 6c eb ff ff    	mov    eax,DWORD PTR [ebp-0x1494]
  415de3:	ba ff c0 40 00       	mov    edx,0x40c0ff
  415de8:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415dec:	8b 8c 98 4c 05 00 00 	mov    ecx,DWORD PTR [eax+ebx*4+0x54c]
  415df3:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415df6:	e8 05 d4 00 00       	call   423200 <edit::SetBkColor(unsigned long)>
  415dfb:	83 ff 01             	cmp    edi,0x1
  415dfe:	7e 88                	jle    415d88 <bixby110control::LoadReport(char*)+0x638>
  415e00:	c6 85 9c eb ff ff 00 	mov    BYTE PTR [ebp-0x1464],0x0
  415e07:	be 4f 74 68 65       	mov    esi,0x6568744f
  415e0c:	b9 73 20 20 20       	mov    ecx,0x20202073
  415e11:	89 b5 88 eb ff ff    	mov    DWORD PTR [ebp-0x1478],esi
  415e17:	ba 72 20 41 64       	mov    edx,0x64412072
  415e1c:	bb 6a 75 73 74       	mov    ebx,0x7473756a
  415e21:	89 8d 98 eb ff ff    	mov    DWORD PTR [ebp-0x1468],ecx
  415e27:	bf 6d 65 6e 74       	mov    edi,0x746e656d
  415e2c:	8d 85 78 eb ff ff    	lea    eax,[ebp-0x1488]
  415e32:	89 95 8c eb ff ff    	mov    DWORD PTR [ebp-0x1474],edx
  415e38:	8d b5 88 eb ff ff    	lea    esi,[ebp-0x1478]
  415e3e:	89 9d 90 eb ff ff    	mov    DWORD PTR [ebp-0x1470],ebx
  415e44:	8d 9d 58 ec ff ff    	lea    ebx,[ebp-0x13a8]
  415e4a:	89 bd 94 eb ff ff    	mov    DWORD PTR [ebp-0x146c],edi
  415e50:	bf 03 00 00 00       	mov    edi,0x3
  415e55:	89 34 24             	mov    DWORD PTR [esp],esi
  415e58:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415e5c:	e8 8f cb 01 00       	call   4329f0 <strcat>
  415e61:	89 1c 24             	mov    DWORD PTR [esp],ebx
  415e64:	8d 95 88 eb ff ff    	lea    edx,[ebp-0x1478]
  415e6a:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415e6e:	e8 cd 20 ff ff       	call   407f40 <strsearchtail(char*, char*)>
  415e73:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415e77:	89 c3                	mov    ebx,eax
  415e79:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  415e7d:	8b 8d 5c eb ff ff    	mov    ecx,DWORD PTR [ebp-0x14a4]
  415e83:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415e86:	e8 75 cb 01 00       	call   432a00 <strncpy>
  415e8b:	8b 95 6c eb ff ff    	mov    edx,DWORD PTR [ebp-0x1494]
  415e91:	c6 82 70 1d 00 00 00 	mov    BYTE PTR [edx+0x1d70],0x0
  415e98:	8b 85 5c eb ff ff    	mov    eax,DWORD PTR [ebp-0x14a4]
  415e9e:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415ea2:	8b b5 60 eb ff ff    	mov    esi,DWORD PTR [ebp-0x14a0]
  415ea8:	8b bc b2 54 05 00 00 	mov    edi,DWORD PTR [edx+esi*4+0x554]
  415eaf:	89 3c 24             	mov    DWORD PTR [esp],edi
  415eb2:	e8 b9 d2 00 00       	call   423170 <edit::Settext(char const*)>
  415eb7:	b9 ff c0 40 00       	mov    ecx,0x40c0ff
  415ebc:	8b b5 6c eb ff ff    	mov    esi,DWORD PTR [ebp-0x1494]
  415ec2:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415ec6:	8b 85 60 eb ff ff    	mov    eax,DWORD PTR [ebp-0x14a0]
  415ecc:	8b bc 86 54 05 00 00 	mov    edi,DWORD PTR [esi+eax*4+0x554]
  415ed3:	8d 73 05             	lea    esi,[ebx+0x5]
  415ed6:	89 3c 24             	mov    DWORD PTR [esp],edi
  415ed9:	bf 01 00 00 00       	mov    edi,0x1
  415ede:	e8 1d d3 00 00       	call   423200 <edit::SetBkColor(unsigned long)>
  415ee3:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  415ee9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  415ef0:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  415ef4:	ba 03 00 00 00       	mov    edx,0x3
  415ef9:	83 c6 05             	add    esi,0x5
  415efc:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  415f00:	8b 85 5c eb ff ff    	mov    eax,DWORD PTR [ebp-0x14a4]
  415f06:	89 04 24             	mov    DWORD PTR [esp],eax
  415f09:	e8 f2 ca 01 00       	call   432a00 <strncpy>
  415f0e:	8b 95 6c eb ff ff    	mov    edx,DWORD PTR [ebp-0x1494]
  415f14:	c6 82 70 1d 00 00 00 	mov    BYTE PTR [edx+0x1d70],0x0
  415f1b:	8b 9d 5c eb ff ff    	mov    ebx,DWORD PTR [ebp-0x14a4]
  415f21:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  415f25:	0f b6 8d 67 eb ff ff 	movzx  ecx,BYTE PTR [ebp-0x1499]
  415f2c:	8d 1c 0f             	lea    ebx,[edi+ecx*1]
  415f2f:	8b 84 9a 54 05 00 00 	mov    eax,DWORD PTR [edx+ebx*4+0x554]
  415f36:	47                   	inc    edi
  415f37:	89 04 24             	mov    DWORD PTR [esp],eax
  415f3a:	e8 31 d2 00 00       	call   423170 <edit::Settext(char const*)>
  415f3f:	8b 8d 6c eb ff ff    	mov    ecx,DWORD PTR [ebp-0x1494]
  415f45:	ba ff c0 40 00       	mov    edx,0x40c0ff
  415f4a:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415f4e:	8b 84 99 54 05 00 00 	mov    eax,DWORD PTR [ecx+ebx*4+0x554]
  415f55:	89 04 24             	mov    DWORD PTR [esp],eax
  415f58:	e8 a3 d2 00 00       	call   423200 <edit::SetBkColor(unsigned long)>
  415f5d:	83 ff 06             	cmp    edi,0x6
  415f60:	7e 8e                	jle    415ef0 <bixby110control::LoadReport(char*)+0x7a0>
  415f62:	fe 85 66 eb ff ff    	inc    BYTE PTR [ebp-0x149a]
  415f68:	80 bd 66 eb ff ff 01 	cmp    BYTE PTR [ebp-0x149a],0x1
  415f6f:	7f 71                	jg     415fe2 <bixby110control::LoadReport(char*)+0x892>
  415f71:	80 bd 66 eb ff ff 00 	cmp    BYTE PTR [ebp-0x149a],0x0
  415f78:	0f 84 2c fa ff ff    	je     4159aa <bixby110control::LoadReport(char*)+0x25a>
  415f7e:	c6 85 7c eb ff ff 00 	mov    BYTE PTR [ebp-0x1484],0x0
  415f85:	be 20 42 3a 20       	mov    esi,0x203a4220
  415f8a:	89 b5 78 eb ff ff    	mov    DWORD PTR [ebp-0x1488],esi
  415f90:	c6 85 67 eb ff ff 29 	mov    BYTE PTR [ebp-0x1499],0x29
  415f97:	e9 27 fa ff ff       	jmp    4159c3 <bixby110control::LoadReport(char*)+0x273>
  415f9c:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  415fa0:	8b bd 6c eb ff ff    	mov    edi,DWORD PTR [ebp-0x1494]
  415fa6:	bb b4 50 44 00       	mov    ebx,0x4450b4
  415fab:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  415faf:	be d6 50 44 00       	mov    esi,0x4450d6
  415fb4:	81 c7 6d 1d 00 00    	add    edi,0x1d6d
  415fba:	89 3c 24             	mov    DWORD PTR [esp],edi
  415fbd:	e8 ce c9 01 00       	call   432990 <sprintf>
  415fc2:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  415fc6:	b9 30 00 00 00       	mov    ecx,0x30
  415fcb:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  415fcf:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  415fd3:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  415fda:	e8 b1 cb 01 00       	call   432b90 <MessageBoxA@16>
  415fdf:	83 ec 10             	sub    esp,0x10
  415fe2:	8b 85 68 eb ff ff    	mov    eax,DWORD PTR [ebp-0x1498]
  415fe8:	89 04 24             	mov    DWORD PTR [esp],eax
  415feb:	e8 20 ce 01 00       	call   432e10 <CloseHandle@4>
  415ff0:	83 ec 04             	sub    esp,0x4
  415ff3:	8d 65 f4             	lea    esp,[ebp-0xc]
  415ff6:	5b                   	pop    ebx
  415ff7:	5e                   	pop    esi
  415ff8:	5f                   	pop    edi
  415ff9:	5d                   	pop    ebp
  415ffa:	c3                   	ret
  415ffb:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  415fff:	8b bd 6c eb ff ff    	mov    edi,DWORD PTR [ebp-0x1494]
  416005:	b9 e0 50 44 00       	mov    ecx,0x4450e0
  41600a:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41600e:	be 30 00 00 00       	mov    esi,0x30
  416013:	81 c7 6d 1d 00 00    	add    edi,0x1d6d
  416019:	89 3c 24             	mov    DWORD PTR [esp],edi
  41601c:	e8 6f c9 01 00       	call   432990 <sprintf>
  416021:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  416025:	ba d6 50 44 00       	mov    edx,0x4450d6
  41602a:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41602e:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  416032:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  416039:	e8 52 cb 01 00       	call   432b90 <MessageBoxA@16>
  41603e:	83 ec 10             	sub    esp,0x10
  416041:	8d 65 f4             	lea    esp,[ebp-0xc]
  416044:	5b                   	pop    ebx
  416045:	5e                   	pop    esi
  416046:	5f                   	pop    edi
  416047:	5d                   	pop    ebp
  416048:	c3                   	ret
  416049:	90                   	nop
  41604a:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
