# Flue, fuel, and utility monitor UI core
# BixCheck 5.5.01; generated by tools/analyze_bixcheck.py
# Exact GNU objdump Intel-syntax excerpts; addresses are build-specific.

# source=Bixby110dlg.cpp
# va=0x00416DF0 size=0x3E0
0x00416DF0 <bixby110control::Bixby110DialogSetupFlueMonitor(int, int, int, int)>:
  416df0:	55                   	push   ebp
  416df1:	89 e5                	mov    ebp,esp
  416df3:	57                   	push   edi
  416df4:	56                   	push   esi
  416df5:	53                   	push   ebx
  416df6:	83 ec 4c             	sub    esp,0x4c
  416df9:	8b 5d 10             	mov    ebx,DWORD PTR [ebp+0x10]
  416dfc:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  416dff:	8b 75 08             	mov    esi,DWORD PTR [ebp+0x8]
  416e02:	89 5d e4             	mov    DWORD PTR [ebp-0x1c],ebx
  416e05:	89 4d e8             	mov    DWORD PTR [ebp-0x18],ecx
  416e08:	8b 46 18             	mov    eax,DWORD PTR [esi+0x18]
  416e0b:	0f b6 96 6c 1d 00 00 	movzx  edx,BYTE PTR [esi+0x1d6c]
  416e12:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  416e16:	8b be b0 1f 00 00    	mov    edi,DWORD PTR [esi+0x1fb0]
  416e1c:	42                   	inc    edx
  416e1d:	89 55 f0             	mov    DWORD PTR [ebp-0x10],edx
  416e20:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  416e23:	89 7c 24 18          	mov    DWORD PTR [esp+0x18],edi
  416e27:	8b 7d e8             	mov    edi,DWORD PTR [ebp-0x18]
  416e2a:	ba 64 00 00 00       	mov    edx,0x64
  416e2f:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  416e33:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  416e37:	b9 c1 d0 43 00       	mov    ecx,0x43d0c1
  416e3c:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  416e40:	31 ff                	xor    edi,edi
  416e42:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  416e46:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  416e4a:	8b 96 1c 0a 00 00    	mov    edx,DWORD PTR [esi+0xa1c]
  416e50:	89 14 24             	mov    DWORD PTR [esp],edx
  416e53:	e8 f8 c6 00 00       	call   423550 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  416e58:	c7 45 ec 00 00 00 00 	mov    DWORD PTR [ebp-0x14],0x0
  416e5f:	8b 45 e8             	mov    eax,DWORD PTR [ebp-0x18]
  416e62:	83 c0 23             	add    eax,0x23
  416e65:	89 45 e0             	mov    DWORD PTR [ebp-0x20],eax
  416e68:	90                   	nop
  416e69:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]
  416e70:	0f b6 8e 6c 1d 00 00 	movzx  ecx,BYTE PTR [esi+0x1d6c]
  416e77:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  416e7a:	01 cb                	add    ebx,ecx
  416e7c:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  416e80:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  416e83:	8b 86 b0 1f 00 00    	mov    eax,DWORD PTR [esi+0x1fb0]
  416e89:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  416e8d:	ba 64 00 00 00       	mov    edx,0x64
  416e92:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  416e96:	8b 55 ec             	mov    edx,DWORD PTR [ebp-0x14]
  416e99:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  416e9d:	8b 45 e0             	mov    eax,DWORD PTR [ebp-0x20]
  416ea0:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  416ea4:	8d 8f c1 c5 43 00    	lea    ecx,[edi+0x43c5c1]
  416eaa:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  416eae:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  416eb2:	8b 84 96 9c 09 00 00 	mov    eax,DWORD PTR [esi+edx*4+0x99c]
  416eb9:	89 04 24             	mov    DWORD PTR [esp],eax
  416ebc:	e8 8f c6 00 00       	call   423550 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  416ec1:	31 c9                	xor    ecx,ecx
  416ec3:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  416ec7:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  416eca:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  416ecd:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  416ed1:	8b 86 b0 1f 00 00    	mov    eax,DWORD PTR [esi+0x1fb0]
  416ed7:	ba 1e 00 00 00       	mov    edx,0x1e
  416edc:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  416ee0:	0f b6 97 09 c6 43 00 	movzx  edx,BYTE PTR [edi+0x43c609]
  416ee7:	83 c7 58             	add    edi,0x58
  416eea:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  416eee:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  416ef1:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  416ef5:	b9 fd 50 44 00       	mov    ecx,0x4450fd
  416efa:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  416efe:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  416f02:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  416f06:	8b 84 96 2c 0a 00 00 	mov    eax,DWORD PTR [esi+edx*4+0xa2c]
  416f0d:	89 04 24             	mov    DWORD PTR [esp],eax
  416f10:	e8 5b c1 00 00       	call   423070 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  416f15:	ff 45 ec             	inc    DWORD PTR [ebp-0x14]
  416f18:	83 7d ec 07          	cmp    DWORD PTR [ebp-0x14],0x7
  416f1c:	0f 8e 4e ff ff ff    	jle    416e70 <bixby110control::Bixby110DialogSetupFlueMonitor(int, int, int, int)+0x80>
  416f22:	8b 4e 18             	mov    ecx,DWORD PTR [esi+0x18]
  416f25:	bb 64 00 00 00       	mov    ebx,0x64
  416f2a:	8b 7d 0c             	mov    edi,DWORD PTR [ebp+0xc]
  416f2d:	8b 45 f0             	mov    eax,DWORD PTR [ebp-0x10]
  416f30:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  416f34:	81 c7 96 00 00 00    	add    edi,0x96
  416f3a:	8b 96 b0 1f 00 00    	mov    edx,DWORD PTR [esi+0x1fb0]
  416f40:	89 7d dc             	mov    DWORD PTR [ebp-0x24],edi
  416f43:	8b 4d dc             	mov    ecx,DWORD PTR [ebp-0x24]
  416f46:	89 5c 24 10          	mov    DWORD PTR [esp+0x10],ebx
  416f4a:	8b 7d e4             	mov    edi,DWORD PTR [ebp-0x1c]
  416f4d:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  416f51:	ba 19 d1 43 00       	mov    edx,0x43d119
  416f56:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  416f5a:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  416f5e:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  416f62:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  416f66:	8b 86 20 0a 00 00    	mov    eax,DWORD PTR [esi+0xa20]
  416f6c:	89 04 24             	mov    DWORD PTR [esp],eax
  416f6f:	e8 dc c5 00 00       	call   423550 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  416f74:	c7 45 d4 08 00 00 00 	mov    DWORD PTR [ebp-0x2c],0x8
  416f7b:	8b 5d 0c             	mov    ebx,DWORD PTR [ebp+0xc]
  416f7e:	81 c3 b9 00 00 00    	add    ebx,0xb9
  416f84:	89 5d d8             	mov    DWORD PTR [ebp-0x28],ebx
  416f87:	bb c0 02 00 00       	mov    ebx,0x2c0
  416f8c:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
  416f90:	0f b6 8e 6c 1d 00 00 	movzx  ecx,BYTE PTR [esi+0x1d6c]
  416f97:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  416f9a:	01 cf                	add    edi,ecx
  416f9c:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  416fa0:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  416fa3:	8b 86 b0 1f 00 00    	mov    eax,DWORD PTR [esi+0x1fb0]
  416fa9:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  416fad:	ba 64 00 00 00       	mov    edx,0x64
  416fb2:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  416fb6:	8b 55 d4             	mov    edx,DWORD PTR [ebp-0x2c]
  416fb9:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  416fbd:	8b 45 d8             	mov    eax,DWORD PTR [ebp-0x28]
  416fc0:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  416fc4:	8d 8b c1 c5 43 00    	lea    ecx,[ebx+0x43c5c1]
  416fca:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  416fce:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  416fd2:	8b 84 96 9c 09 00 00 	mov    eax,DWORD PTR [esi+edx*4+0x99c]
  416fd9:	89 04 24             	mov    DWORD PTR [esp],eax
  416fdc:	e8 6f c5 00 00       	call   423550 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  416fe1:	31 c9                	xor    ecx,ecx
  416fe3:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  416fe7:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  416fea:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  416fed:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  416ff1:	8b 86 b0 1f 00 00    	mov    eax,DWORD PTR [esi+0x1fb0]
  416ff7:	ba 1e 00 00 00       	mov    edx,0x1e
  416ffc:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  417000:	0f b6 93 09 c6 43 00 	movzx  edx,BYTE PTR [ebx+0x43c609]
  417007:	83 c3 58             	add    ebx,0x58
  41700a:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  41700e:	8b 45 dc             	mov    eax,DWORD PTR [ebp-0x24]
  417011:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  417015:	b9 fd 50 44 00       	mov    ecx,0x4450fd
  41701a:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  41701e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  417022:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  417026:	8b 84 96 2c 0a 00 00 	mov    eax,DWORD PTR [esi+edx*4+0xa2c]
  41702d:	89 04 24             	mov    DWORD PTR [esp],eax
  417030:	e8 3b c0 00 00       	call   423070 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  417035:	ff 45 d4             	inc    DWORD PTR [ebp-0x2c]
  417038:	83 7d d4 0f          	cmp    DWORD PTR [ebp-0x2c],0xf
  41703c:	0f 8e 4e ff ff ff    	jle    416f90 <bixby110control::Bixby110DialogSetupFlueMonitor(int, int, int, int)+0x1a0>
  417042:	0f b6 9e 6c 1d 00 00 	movzx  ebx,BYTE PTR [esi+0x1d6c]
  417049:	8b 4e 18             	mov    ecx,DWORD PTR [esi+0x18]
  41704c:	8b 45 f0             	mov    eax,DWORD PTR [ebp-0x10]
  41704f:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  417053:	8b 4d e8             	mov    ecx,DWORD PTR [ebp-0x18]
  417056:	8b 96 b0 1f 00 00    	mov    edx,DWORD PTR [esi+0x1fb0]
  41705c:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  417060:	8d 1c 5f             	lea    ebx,[edi+ebx*2]
  417063:	bf 64 00 00 00       	mov    edi,0x64
  417068:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  41706c:	ba 71 d1 43 00       	mov    edx,0x43d171
  417071:	89 7c 24 10          	mov    DWORD PTR [esp+0x10],edi
  417075:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417079:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41707d:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  417081:	8b 86 24 0a 00 00    	mov    eax,DWORD PTR [esi+0xa24]
  417087:	89 04 24             	mov    DWORD PTR [esp],eax
  41708a:	e8 c1 c4 00 00       	call   423550 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  41708f:	0f b6 be 6c 1d 00 00 	movzx  edi,BYTE PTR [esi+0x1d6c]
  417096:	01 fb                	add    ebx,edi
  417098:	bf 10 00 00 00       	mov    edi,0x10
  41709d:	89 5d d0             	mov    DWORD PTR [ebp-0x30],ebx
  4170a0:	8b 5d e8             	mov    ebx,DWORD PTR [ebp-0x18]
  4170a3:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  4170a9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  4170b0:	31 d2                	xor    edx,edx
  4170b2:	89 54 24 20          	mov    DWORD PTR [esp+0x20],edx
  4170b6:	8b 46 18             	mov    eax,DWORD PTR [esi+0x18]
  4170b9:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  4170bc:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  4170c0:	8b 8e b0 1f 00 00    	mov    ecx,DWORD PTR [esi+0x1fb0]
  4170c6:	b8 1e 00 00 00       	mov    eax,0x1e
  4170cb:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  4170cf:	ba fd 50 44 00       	mov    edx,0x4450fd
  4170d4:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  4170d8:	8b 4d d0             	mov    ecx,DWORD PTR [ebp-0x30]
  4170db:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  4170df:	83 c3 23             	add    ebx,0x23
  4170e2:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  4170e6:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  4170ea:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  4170ee:	8b 84 be 2c 0a 00 00 	mov    eax,DWORD PTR [esi+edi*4+0xa2c]
  4170f5:	47                   	inc    edi
  4170f6:	89 04 24             	mov    DWORD PTR [esp],eax
  4170f9:	e8 72 bf 00 00       	call   423070 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  4170fe:	83 ff 17             	cmp    edi,0x17
  417101:	7e ad                	jle    4170b0 <bixby110control::Bixby110DialogSetupFlueMonitor(int, int, int, int)+0x2c0>
  417103:	0f b6 9e 6c 1d 00 00 	movzx  ebx,BYTE PTR [esi+0x1d6c]
  41710a:	8b 46 18             	mov    eax,DWORD PTR [esi+0x18]
  41710d:	8b 55 d0             	mov    edx,DWORD PTR [ebp-0x30]
  417110:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  417114:	8b 8e b0 1f 00 00    	mov    ecx,DWORD PTR [esi+0x1fb0]
  41711a:	8d 3c 5a             	lea    edi,[edx+ebx*2]
  41711d:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  417121:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  417124:	b8 64 00 00 00       	mov    eax,0x64
  417129:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  41712d:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  417131:	8b 4d e8             	mov    ecx,DWORD PTR [ebp-0x18]
  417134:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  417138:	ba c9 d1 43 00       	mov    edx,0x43d1c9
  41713d:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  417141:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  417145:	8b 86 28 0a 00 00    	mov    eax,DWORD PTR [esi+0xa28]
  41714b:	89 04 24             	mov    DWORD PTR [esp],eax
  41714e:	e8 fd c3 00 00       	call   423550 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  417153:	0f b6 8e 6c 1d 00 00 	movzx  ecx,BYTE PTR [esi+0x1d6c]
  41715a:	8b 5d e8             	mov    ebx,DWORD PTR [ebp-0x18]
  41715d:	01 cf                	add    edi,ecx
  41715f:	89 7d cc             	mov    DWORD PTR [ebp-0x34],edi
  417162:	bf 18 00 00 00       	mov    edi,0x18
  417167:	89 f6                	mov    esi,esi
  417169:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  417170:	31 c0                	xor    eax,eax
  417172:	89 44 24 20          	mov    DWORD PTR [esp+0x20],eax
  417176:	8b 4e 18             	mov    ecx,DWORD PTR [esi+0x18]
  417179:	8b 45 f0             	mov    eax,DWORD PTR [ebp-0x10]
  41717c:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  417180:	8b 96 b0 1f 00 00    	mov    edx,DWORD PTR [esi+0x1fb0]
  417186:	b9 1e 00 00 00       	mov    ecx,0x1e
  41718b:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  41718f:	b8 fd 50 44 00       	mov    eax,0x4450fd
  417194:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  417198:	8b 55 cc             	mov    edx,DWORD PTR [ebp-0x34]
  41719b:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  41719f:	83 c3 23             	add    ebx,0x23
  4171a2:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  4171a6:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  4171aa:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4171ae:	8b 8c be 2c 0a 00 00 	mov    ecx,DWORD PTR [esi+edi*4+0xa2c]
  4171b5:	47                   	inc    edi
  4171b6:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4171b9:	e8 b2 be 00 00       	call   423070 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  4171be:	83 ff 1f             	cmp    edi,0x1f
  4171c1:	7e ad                	jle    417170 <bixby110control::Bixby110DialogSetupFlueMonitor(int, int, int, int)+0x380>
  4171c3:	83 c4 4c             	add    esp,0x4c
  4171c6:	5b                   	pop    ebx
  4171c7:	5e                   	pop    esi
  4171c8:	5f                   	pop    edi
  4171c9:	5d                   	pop    ebp
  4171ca:	c3                   	ret
  4171cb:	90                   	nop
  4171cc:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]

# source=Bixby110dlg.cpp
# va=0x004171D0 size=0x5E0
0x004171D0 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)>:
  4171d0:	55                   	push   ebp
  4171d1:	b8 64 00 00 00       	mov    eax,0x64
  4171d6:	89 e5                	mov    ebp,esp
  4171d8:	57                   	push   edi
  4171d9:	56                   	push   esi
  4171da:	53                   	push   ebx
  4171db:	83 ec 6c             	sub    esp,0x6c
  4171de:	8b 4d 08             	mov    ecx,DWORD PTR [ebp+0x8]
  4171e1:	8b 75 0c             	mov    esi,DWORD PTR [ebp+0xc]
  4171e4:	8b 5d 18             	mov    ebx,DWORD PTR [ebp+0x18]
  4171e7:	89 4d e4             	mov    DWORD PTR [ebp-0x1c],ecx
  4171ea:	0f b6 91 6c 1d 00 00 	movzx  edx,BYTE PTR [ecx+0x1d6c]
  4171f1:	8b 4d 14             	mov    ecx,DWORD PTR [ebp+0x14]
  4171f4:	42                   	inc    edx
  4171f5:	89 55 e0             	mov    DWORD PTR [ebp-0x20],edx
  4171f8:	8b 55 e4             	mov    edx,DWORD PTR [ebp-0x1c]
  4171fb:	8b 7a 18             	mov    edi,DWORD PTR [edx+0x18]
  4171fe:	89 74 24 18          	mov    DWORD PTR [esp+0x18],esi
  417202:	8b 75 e0             	mov    esi,DWORD PTR [ebp-0x20]
  417205:	89 7c 24 1c          	mov    DWORD PTR [esp+0x1c],edi
  417209:	bf 41 fc 43 00       	mov    edi,0x43fc41
  41720e:	89 74 24 14          	mov    DWORD PTR [esp+0x14],esi
  417212:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417216:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41721a:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41721e:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  417222:	8b 82 74 07 00 00    	mov    eax,DWORD PTR [edx+0x774]
  417228:	89 04 24             	mov    DWORD PTR [esp],eax
  41722b:	e8 20 c3 00 00       	call   423550 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  417230:	8b 55 e4             	mov    edx,DWORD PTR [ebp-0x1c]
  417233:	b8 64 00 00 00       	mov    eax,0x64
  417238:	8b 7d 0c             	mov    edi,DWORD PTR [ebp+0xc]
  41723b:	8b 4a 18             	mov    ecx,DWORD PTR [edx+0x18]
  41723e:	89 7c 24 18          	mov    DWORD PTR [esp+0x18],edi
  417242:	bf 49 fd 43 00       	mov    edi,0x43fd49
  417247:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  41724b:	8b 4d 14             	mov    ecx,DWORD PTR [ebp+0x14]
  41724e:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417252:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  417256:	83 c1 46             	add    ecx,0x46
  417259:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41725d:	89 74 24 14          	mov    DWORD PTR [esp+0x14],esi
  417261:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  417265:	8b b2 78 07 00 00    	mov    esi,DWORD PTR [edx+0x778]
  41726b:	89 4d d8             	mov    DWORD PTR [ebp-0x28],ecx
  41726e:	89 34 24             	mov    DWORD PTR [esp],esi
  417271:	be 64 00 00 00       	mov    esi,0x64
  417276:	e8 d5 c2 00 00       	call   423550 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  41727b:	8b 55 e4             	mov    edx,DWORD PTR [ebp-0x1c]
  41727e:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  417281:	8b 7d e0             	mov    edi,DWORD PTR [ebp-0x20]
  417284:	8b 42 18             	mov    eax,DWORD PTR [edx+0x18]
  417287:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  41728b:	b9 51 fe 43 00       	mov    ecx,0x43fe51
  417290:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  417294:	8b 45 14             	mov    eax,DWORD PTR [ebp+0x14]
  417297:	89 74 24 10          	mov    DWORD PTR [esp+0x10],esi
  41729b:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  41729f:	05 8c 00 00 00       	add    eax,0x8c
  4172a4:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  4172a8:	89 7c 24 14          	mov    DWORD PTR [esp+0x14],edi
  4172ac:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  4172b0:	8b ba 7c 07 00 00    	mov    edi,DWORD PTR [edx+0x77c]
  4172b6:	89 45 dc             	mov    DWORD PTR [ebp-0x24],eax
  4172b9:	89 3c 24             	mov    DWORD PTR [esp],edi
  4172bc:	e8 8f c2 00 00       	call   423550 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  4172c1:	8b 75 e4             	mov    esi,DWORD PTR [ebp-0x1c]
  4172c4:	8b 7d 14             	mov    edi,DWORD PTR [ebp+0x14]
  4172c7:	8b 55 10             	mov    edx,DWORD PTR [ebp+0x10]
  4172ca:	0f b6 86 6c 1d 00 00 	movzx  eax,BYTE PTR [esi+0x1d6c]
  4172d1:	83 c7 14             	add    edi,0x14
  4172d4:	8b 75 14             	mov    esi,DWORD PTR [ebp+0x14]
  4172d7:	89 7d cc             	mov    DWORD PTR [ebp-0x34],edi
  4172da:	8b 7d 10             	mov    edi,DWORD PTR [ebp+0x10]
  4172dd:	83 c2 08             	add    edx,0x8
  4172e0:	89 55 c0             	mov    DWORD PTR [ebp-0x40],edx
  4172e3:	0f b6 c8             	movzx  ecx,al
  4172e6:	81 c6 a0 00 00 00    	add    esi,0xa0
  4172ec:	89 75 d4             	mov    DWORD PTR [ebp-0x2c],esi
  4172ef:	01 cb                	add    ebx,ecx
  4172f1:	8b 4d e4             	mov    ecx,DWORD PTR [ebp-0x1c]
  4172f4:	c1 e7 02             	shl    edi,0x2
  4172f7:	8b 45 14             	mov    eax,DWORD PTR [ebp+0x14]
  4172fa:	8b 55 10             	mov    edx,DWORD PTR [ebp+0x10]
  4172fd:	8d b4 0f 24 05 00 00 	lea    esi,[edi+ecx*1+0x524]
  417304:	8b 4d 10             	mov    ecx,DWORD PTR [ebp+0x10]
  417307:	83 c0 5a             	add    eax,0x5a
  41730a:	29 4d c0             	sub    DWORD PTR [ebp-0x40],ecx
  41730d:	01 d7                	add    edi,edx
  41730f:	89 45 d0             	mov    DWORD PTR [ebp-0x30],eax
  417312:	8d 04 79             	lea    eax,[ecx+edi*2]
  417315:	8d 3c c5 00 00 00 00 	lea    edi,[eax*8+0x0]
  41731c:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
  417320:	8b 55 e4             	mov    edx,DWORD PTR [ebp-0x1c]
  417323:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  417326:	8b 42 18             	mov    eax,DWORD PTR [edx+0x18]
  417329:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  41732d:	8d 97 e1 dc 43 00    	lea    edx,[edi+0x43dce1]
  417333:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  417337:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  41733b:	8b 45 14             	mov    eax,DWORD PTR [ebp+0x14]
  41733e:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  417342:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  417346:	8b 8e 78 fe ff ff    	mov    ecx,DWORD PTR [esi-0x188]
  41734c:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41734f:	e8 2c b8 00 00       	call   422b80 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  417354:	31 c0                	xor    eax,eax
  417356:	8b 55 e4             	mov    edx,DWORD PTR [ebp-0x1c]
  417359:	89 44 24 20          	mov    DWORD PTR [esp+0x20],eax
  41735d:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  417360:	8b 4a 18             	mov    ecx,DWORD PTR [edx+0x18]
  417363:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417367:	8b 55 e0             	mov    edx,DWORD PTR [ebp-0x20]
  41736a:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  41736e:	8b 45 cc             	mov    eax,DWORD PTR [ebp-0x34]
  417371:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  417375:	b9 28 00 00 00       	mov    ecx,0x28
  41737a:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  41737e:	ba fd 50 44 00       	mov    edx,0x4450fd
  417383:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  417387:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  41738b:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41738f:	8b 4e c0             	mov    ecx,DWORD PTR [esi-0x40]
  417392:	89 0c 24             	mov    DWORD PTR [esp],ecx
  417395:	e8 d6 bc 00 00       	call   423070 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  41739a:	b8 fe 50 44 00       	mov    eax,0x4450fe
  41739f:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4173a3:	8b 56 c0             	mov    edx,DWORD PTR [esi-0x40]
  4173a6:	89 14 24             	mov    DWORD PTR [esp],edx
  4173a9:	e8 c2 bd 00 00       	call   423170 <edit::Settext(char const*)>
  4173ae:	8b 4d e4             	mov    ecx,DWORD PTR [ebp-0x1c]
  4173b1:	8b 55 0c             	mov    edx,DWORD PTR [ebp+0xc]
  4173b4:	8b 41 18             	mov    eax,DWORD PTR [ecx+0x18]
  4173b7:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  4173bb:	8b 4d d8             	mov    ecx,DWORD PTR [ebp-0x28]
  4173be:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  4173c2:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  4173c6:	8d 87 a1 df 43 00    	lea    eax,[edi+0x43dfa1]
  4173cc:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  4173d0:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4173d4:	8b 96 98 fe ff ff    	mov    edx,DWORD PTR [esi-0x168]
  4173da:	89 14 24             	mov    DWORD PTR [esp],edx
  4173dd:	e8 9e b7 00 00       	call   422b80 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  4173e2:	31 c9                	xor    ecx,ecx
  4173e4:	8b 45 e4             	mov    eax,DWORD PTR [ebp-0x1c]
  4173e7:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  4173eb:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  4173ee:	8b 50 18             	mov    edx,DWORD PTR [eax+0x18]
  4173f1:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  4173f5:	8b 45 e0             	mov    eax,DWORD PTR [ebp-0x20]
  4173f8:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  4173fc:	8b 4d d0             	mov    ecx,DWORD PTR [ebp-0x30]
  4173ff:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  417403:	ba 28 00 00 00       	mov    edx,0x28
  417408:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  41740c:	b8 fd 50 44 00       	mov    eax,0x4450fd
  417411:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  417415:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  417419:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41741d:	8b 56 e0             	mov    edx,DWORD PTR [esi-0x20]
  417420:	89 14 24             	mov    DWORD PTR [esp],edx
  417423:	e8 48 bc 00 00       	call   423070 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  417428:	b9 fe 50 44 00       	mov    ecx,0x4450fe
  41742d:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  417431:	8b 46 e0             	mov    eax,DWORD PTR [esi-0x20]
  417434:	89 04 24             	mov    DWORD PTR [esp],eax
  417437:	e8 34 bd 00 00       	call   423170 <edit::Settext(char const*)>
  41743c:	8b 55 e4             	mov    edx,DWORD PTR [ebp-0x1c]
  41743f:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  417442:	8b 4a 18             	mov    ecx,DWORD PTR [edx+0x18]
  417445:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417449:	8d 97 61 e2 43 00    	lea    edx,[edi+0x43e261]
  41744f:	83 c7 58             	add    edi,0x58
  417452:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  417456:	8b 4d dc             	mov    ecx,DWORD PTR [ebp-0x24]
  417459:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41745d:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  417461:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  417465:	8b 86 b8 fe ff ff    	mov    eax,DWORD PTR [esi-0x148]
  41746b:	89 04 24             	mov    DWORD PTR [esp],eax
  41746e:	e8 0d b7 00 00       	call   422b80 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  417473:	31 c9                	xor    ecx,ecx
  417475:	8b 55 e4             	mov    edx,DWORD PTR [ebp-0x1c]
  417478:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  41747c:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  41747f:	8b 42 18             	mov    eax,DWORD PTR [edx+0x18]
  417482:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417486:	8b 55 e0             	mov    edx,DWORD PTR [ebp-0x20]
  417489:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  41748d:	8b 4d d4             	mov    ecx,DWORD PTR [ebp-0x2c]
  417490:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  417494:	b8 28 00 00 00       	mov    eax,0x28
  417499:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  41749d:	ba fd 50 44 00       	mov    edx,0x4450fd
  4174a2:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  4174a6:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  4174aa:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  4174ae:	8b 06                	mov    eax,DWORD PTR [esi]
  4174b0:	89 04 24             	mov    DWORD PTR [esp],eax
  4174b3:	e8 b8 bb 00 00       	call   423070 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  4174b8:	b9 fe 50 44 00       	mov    ecx,0x4450fe
  4174bd:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  4174c1:	8b 16                	mov    edx,DWORD PTR [esi]
  4174c3:	83 c6 04             	add    esi,0x4
  4174c6:	89 14 24             	mov    DWORD PTR [esp],edx
  4174c9:	e8 a2 bc 00 00       	call   423170 <edit::Settext(char const*)>
  4174ce:	8b 45 e4             	mov    eax,DWORD PTR [ebp-0x1c]
  4174d1:	0f b6 90 6c 1d 00 00 	movzx  edx,BYTE PTR [eax+0x1d6c]
  4174d8:	0f b6 c2             	movzx  eax,dl
  4174db:	01 c3                	add    ebx,eax
  4174dd:	ff 4d c0             	dec    DWORD PTR [ebp-0x40]
  4174e0:	0f 85 3a fe ff ff    	jne    417320 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x150>
  4174e6:	01 c3                	add    ebx,eax
  4174e8:	8b 4d 10             	mov    ecx,DWORD PTR [ebp+0x10]
  4174eb:	89 5d bc             	mov    DWORD PTR [ebp-0x44],ebx
  4174ee:	8b 5d 10             	mov    ebx,DWORD PTR [ebp+0x10]
  4174f1:	83 c1 18             	add    ecx,0x18
  4174f4:	83 c3 29             	add    ebx,0x29
  4174f7:	39 cb                	cmp    ebx,ecx
  4174f9:	0f 8e 4f 02 00 00    	jle    41774e <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x57e>
  4174ff:	8b 75 e4             	mov    esi,DWORD PTR [ebp-0x1c]
  417502:	8d 04 8d 00 00 00 00 	lea    eax,[ecx*4+0x0]
  417509:	29 cb                	sub    ebx,ecx
  41750b:	89 5d b8             	mov    DWORD PTR [ebp-0x48],ebx
  41750e:	8d bc 30 2c 06 00 00 	lea    edi,[eax+esi*1+0x62c]
  417515:	01 c8                	add    eax,ecx
  417517:	8d 04 41             	lea    eax,[ecx+eax*2]
  41751a:	c1 e0 03             	shl    eax,0x3
  41751d:	8d b0 e1 dc 43 00    	lea    esi,[eax+0x43dce1]
  417523:	89 75 c8             	mov    DWORD PTR [ebp-0x38],esi
  417526:	89 45 c4             	mov    DWORD PTR [ebp-0x3c],eax
  417529:	e9 cc 00 00 00       	jmp    4175fa <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x42a>
  41752e:	89 f6                	mov    esi,esi
  417530:	48                   	dec    eax
  417531:	83 f8 01             	cmp    eax,0x1
  417534:	0f 87 a6 00 00 00    	ja     4175e0 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x410>
  41753a:	8b 75 e4             	mov    esi,DWORD PTR [ebp-0x1c]
  41753d:	8b 55 bc             	mov    edx,DWORD PTR [ebp-0x44]
  417540:	8b 4d 14             	mov    ecx,DWORD PTR [ebp+0x14]
  417543:	8b 5e 18             	mov    ebx,DWORD PTR [esi+0x18]
  417546:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  417549:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  41754d:	89 5c 24 14          	mov    DWORD PTR [esp+0x14],ebx
  417551:	8b 5d c8             	mov    ebx,DWORD PTR [ebp-0x38]
  417554:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  417558:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  41755c:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  417560:	8b b7 70 fd ff ff    	mov    esi,DWORD PTR [edi-0x290]
  417566:	89 34 24             	mov    DWORD PTR [esp],esi
  417569:	e8 12 b6 00 00       	call   422b80 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  41756e:	8b 55 e4             	mov    edx,DWORD PTR [ebp-0x1c]
  417571:	31 c0                	xor    eax,eax
  417573:	8b 5d 0c             	mov    ebx,DWORD PTR [ebp+0xc]
  417576:	89 44 24 20          	mov    DWORD PTR [esp+0x20],eax
  41757a:	8b 75 e0             	mov    esi,DWORD PTR [ebp-0x20]
  41757d:	8b 4a 18             	mov    ecx,DWORD PTR [edx+0x18]
  417580:	89 5c 24 18          	mov    DWORD PTR [esp+0x18],ebx
  417584:	8b 55 bc             	mov    edx,DWORD PTR [ebp-0x44]
  417587:	b8 28 00 00 00       	mov    eax,0x28
  41758c:	89 74 24 14          	mov    DWORD PTR [esp+0x14],esi
  417590:	bb fd 50 44 00       	mov    ebx,0x4450fd
  417595:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  417599:	8b 4d 14             	mov    ecx,DWORD PTR [ebp+0x14]
  41759c:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  4175a0:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  4175a4:	83 c1 78             	add    ecx,0x78
  4175a7:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  4175ab:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  4175af:	8b b7 b8 fe ff ff    	mov    esi,DWORD PTR [edi-0x148]
  4175b5:	89 34 24             	mov    DWORD PTR [esp],esi
  4175b8:	e8 b3 ba 00 00       	call   423070 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  4175bd:	b8 fe 50 44 00       	mov    eax,0x4450fe
  4175c2:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4175c6:	8b 97 b8 fe ff ff    	mov    edx,DWORD PTR [edi-0x148]
  4175cc:	89 14 24             	mov    DWORD PTR [esp],edx
  4175cf:	e8 9c bb 00 00       	call   423170 <edit::Settext(char const*)>
  4175d4:	8b 4d e4             	mov    ecx,DWORD PTR [ebp-0x1c]
  4175d7:	0f b6 91 6c 1d 00 00 	movzx  edx,BYTE PTR [ecx+0x1d6c]
  4175de:	89 f6                	mov    esi,esi
  4175e0:	83 45 c4 58          	add    DWORD PTR [ebp-0x3c],0x58
  4175e4:	0f b6 f2             	movzx  esi,dl
  4175e7:	83 c7 04             	add    edi,0x4
  4175ea:	01 75 bc             	add    DWORD PTR [ebp-0x44],esi
  4175ed:	83 45 c8 58          	add    DWORD PTR [ebp-0x38],0x58
  4175f1:	ff 4d b8             	dec    DWORD PTR [ebp-0x48]
  4175f4:	0f 84 54 01 00 00    	je     41774e <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x57e>
  4175fa:	8b 5d c4             	mov    ebx,DWORD PTR [ebp-0x3c]
  4175fd:	0f b6 83 e0 dc 43 00 	movzx  eax,BYTE PTR [ebx+0x43dce0]
  417604:	83 f8 09             	cmp    eax,0x9
  417607:	0f 84 49 01 00 00    	je     417756 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x586>
  41760d:	0f 8e 1d ff ff ff    	jle    417530 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x360>
  417613:	83 f8 0a             	cmp    eax,0xa
  417616:	75 c8                	jne    4175e0 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x410>
  417618:	8b 55 e4             	mov    edx,DWORD PTR [ebp-0x1c]
  41761b:	8b 02                	mov    eax,DWORD PTR [edx]
  41761d:	89 04 24             	mov    DWORD PTR [esp],eax
  417620:	e8 8b b5 01 00       	call   432bb0 <GetDC@4>
  417625:	8b 5d e4             	mov    ebx,DWORD PTR [ebp-0x1c]
  417628:	83 ec 04             	sub    esp,0x4
  41762b:	89 c6                	mov    esi,eax
  41762d:	81 c3 6d 1d 00 00    	add    ebx,0x1d6d
  417633:	89 1c 24             	mov    DWORD PTR [esp],ebx
  417636:	e8 75 b3 01 00       	call   4329b0 <strlen>
  41763b:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41763f:	8d 4d e8             	lea    ecx,[ebp-0x18]
  417642:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  417646:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41764a:	89 34 24             	mov    DWORD PTR [esp],esi
  41764d:	e8 ae b4 01 00       	call   432b00 <GetTextExtentPoint32A@16>
  417652:	83 ec 10             	sub    esp,0x10
  417655:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  417659:	8b 75 e4             	mov    esi,DWORD PTR [ebp-0x1c]
  41765c:	8b 16                	mov    edx,DWORD PTR [esi]
  41765e:	89 14 24             	mov    DWORD PTR [esp],edx
  417661:	e8 5a b5 01 00       	call   432bc0 <ReleaseDC@8>
  417666:	8b 5e 18             	mov    ebx,DWORD PTR [esi+0x18]
  417669:	83 ec 08             	sub    esp,0x8
  41766c:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  41766f:	8b 4d bc             	mov    ecx,DWORD PTR [ebp-0x44]
  417672:	8b 55 14             	mov    edx,DWORD PTR [ebp+0x14]
  417675:	89 5c 24 14          	mov    DWORD PTR [esp+0x14],ebx
  417679:	8b 5d c4             	mov    ebx,DWORD PTR [ebp-0x3c]
  41767c:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  417680:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  417684:	81 c3 01 dd 43 00    	add    ebx,0x43dd01
  41768a:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41768e:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  417692:	8b 87 70 fd ff ff    	mov    eax,DWORD PTR [edi-0x290]
  417698:	89 04 24             	mov    DWORD PTR [esp],eax
  41769b:	e8 e0 b4 00 00       	call   422b80 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  4176a0:	31 c9                	xor    ecx,ecx
  4176a2:	8b 5d e0             	mov    ebx,DWORD PTR [ebp-0x20]
  4176a5:	b8 14 00 00 00       	mov    eax,0x14
  4176aa:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  4176ae:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  4176b1:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  4176b5:	8b 75 0c             	mov    esi,DWORD PTR [ebp+0xc]
  4176b8:	89 5c 24 14          	mov    DWORD PTR [esp+0x14],ebx
  4176bc:	8b 4d bc             	mov    ecx,DWORD PTR [ebp-0x44]
  4176bf:	bb fd 50 44 00       	mov    ebx,0x4450fd
  4176c4:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  4176c8:	8b 55 14             	mov    edx,DWORD PTR [ebp+0x14]
  4176cb:	89 74 24 18          	mov    DWORD PTR [esp+0x18],esi
  4176cf:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  4176d3:	83 c2 28             	add    edx,0x28
  4176d6:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  4176da:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  4176de:	8b 87 b8 fe ff ff    	mov    eax,DWORD PTR [edi-0x148]
  4176e4:	89 04 24             	mov    DWORD PTR [esp],eax
  4176e7:	e8 84 b9 00 00       	call   423070 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  4176ec:	8b 4d e4             	mov    ecx,DWORD PTR [ebp-0x1c]
  4176ef:	8b 5d bc             	mov    ebx,DWORD PTR [ebp-0x44]
  4176f2:	8b 45 d8             	mov    eax,DWORD PTR [ebp-0x28]
  4176f5:	8b 51 18             	mov    edx,DWORD PTR [ecx+0x18]
  4176f8:	43                   	inc    ebx
  4176f9:	89 74 24 10          	mov    DWORD PTR [esp+0x10],esi
  4176fd:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  417701:	8b 55 c4             	mov    edx,DWORD PTR [ebp-0x3c]
  417704:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417708:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41770c:	81 c2 e1 dc 43 00    	add    edx,0x43dce1
  417712:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  417716:	8b 0f                	mov    ecx,DWORD PTR [edi]
  417718:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41771b:	e8 a0 ae 00 00       	call   4225c0 <manual3checkbox::CreateManual3checkbox(char const*, int, int, HWND__*, HINSTANCE__*)>
  417720:	8b 37                	mov    esi,DWORD PTR [edi]
  417722:	83 c7 04             	add    edi,0x4
  417725:	89 34 24             	mov    DWORD PTR [esp],esi
  417728:	e8 d3 b0 00 00       	call   422800 <manual3checkbox::SetIndeterminate()>
  41772d:	8b 5d e4             	mov    ebx,DWORD PTR [ebp-0x1c]
  417730:	0f b6 93 6c 1d 00 00 	movzx  edx,BYTE PTR [ebx+0x1d6c]
  417737:	83 45 c4 58          	add    DWORD PTR [ebp-0x3c],0x58
  41773b:	83 45 c8 58          	add    DWORD PTR [ebp-0x38],0x58
  41773f:	0f b6 f2             	movzx  esi,dl
  417742:	01 75 bc             	add    DWORD PTR [ebp-0x44],esi
  417745:	ff 4d b8             	dec    DWORD PTR [ebp-0x48]
  417748:	0f 85 ac fe ff ff    	jne    4175fa <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x42a>
  41774e:	8d 65 f4             	lea    esp,[ebp-0xc]
  417751:	5b                   	pop    ebx
  417752:	5e                   	pop    esi
  417753:	5f                   	pop    edi
  417754:	5d                   	pop    ebp
  417755:	c3                   	ret
  417756:	8b 5d e4             	mov    ebx,DWORD PTR [ebp-0x1c]
  417759:	8b 4d bc             	mov    ecx,DWORD PTR [ebp-0x44]
  41775c:	8b 55 0c             	mov    edx,DWORD PTR [ebp+0xc]
  41775f:	8b 43 18             	mov    eax,DWORD PTR [ebx+0x18]
  417762:	8b 75 14             	mov    esi,DWORD PTR [ebp+0x14]
  417765:	41                   	inc    ecx
  417766:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  41776a:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  41776e:	8b 45 c4             	mov    eax,DWORD PTR [ebp-0x3c]
  417771:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  417775:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  417779:	05 e1 dc 43 00       	add    eax,0x43dce1
  41777e:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  417782:	8b 17                	mov    edx,DWORD PTR [edi]
  417784:	89 14 24             	mov    DWORD PTR [esp],edx
  417787:	e8 34 ae 00 00       	call   4225c0 <manual3checkbox::CreateManual3checkbox(char const*, int, int, HWND__*, HINSTANCE__*)>
  41778c:	8b 0f                	mov    ecx,DWORD PTR [edi]
  41778e:	89 0c 24             	mov    DWORD PTR [esp],ecx
  417791:	e8 6a b0 00 00       	call   422800 <manual3checkbox::SetIndeterminate()>
  417796:	0f b6 93 6c 1d 00 00 	movzx  edx,BYTE PTR [ebx+0x1d6c]
  41779d:	e9 3e fe ff ff       	jmp    4175e0 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x410>
  4177a2:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]
  4177a9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]

# source=Bixby110dlg.cpp
# va=0x004177B0 size=0x5C0
0x004177B0 <bixby110control::Bixby110DialogSetupUtilityWindows()>:
  4177b0:	55                   	push   ebp
  4177b1:	b9 20 4d 6f 6e       	mov    ecx,0x6e6f4d20
  4177b6:	89 e5                	mov    ebp,esp
  4177b8:	57                   	push   edi
  4177b9:	ba 69 74 6f 72       	mov    edx,0x726f7469
  4177be:	56                   	push   esi
  4177bf:	53                   	push   ebx
  4177c0:	83 ec 3c             	sub    esp,0x3c
  4177c3:	bb 46 6c 75 65       	mov    ebx,0x65756c46
  4177c8:	8b 75 08             	mov    esi,DWORD PTR [ebp+0x8]
  4177cb:	8b 86 b0 1f 00 00    	mov    eax,DWORD PTR [esi+0x1fb0]
  4177d1:	c7 46 04 41 00 00 00 	mov    DWORD PTR [esi+0x4],0x41
  4177d8:	c7 46 08 87 00 00 00 	mov    DWORD PTR [esi+0x8],0x87
  4177df:	85 c0                	test   eax,eax
  4177e1:	c7 46 0c 2c 01 00 00 	mov    DWORD PTR [esi+0xc],0x12c
  4177e8:	c7 46 10 22 01 00 00 	mov    DWORD PTR [esi+0x10],0x122
  4177ef:	89 9e 6d 1d 00 00    	mov    DWORD PTR [esi+0x1d6d],ebx
  4177f5:	89 8e 71 1d 00 00    	mov    DWORD PTR [esi+0x1d71],ecx
  4177fb:	89 96 75 1d 00 00    	mov    DWORD PTR [esi+0x1d75],edx
  417801:	c6 86 79 1d 00 00 00 	mov    BYTE PTR [esi+0x1d79],0x0
  417808:	0f 85 82 00 00 00    	jne    417890 <bixby110control::Bixby110DialogSetupUtilityWindows()+0xe0>
  41780e:	31 db                	xor    ebx,ebx
  417810:	31 d2                	xor    edx,edx
  417812:	89 5c 24 2c          	mov    DWORD PTR [esp+0x2c],ebx
  417816:	8b 4e 18             	mov    ecx,DWORD PTR [esi+0x18]
  417819:	89 54 24 24          	mov    DWORD PTR [esp+0x24],edx
  41781d:	89 4c 24 28          	mov    DWORD PTR [esp+0x28],ecx
  417821:	8b 7e 14             	mov    edi,DWORD PTR [esi+0x14]
  417824:	89 7c 24 20          	mov    DWORD PTR [esp+0x20],edi
  417828:	8b 46 10             	mov    eax,DWORD PTR [esi+0x10]
  41782b:	bf 00 00 ca 00       	mov    edi,0xca0000
  417830:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  417834:	8b 5e 0c             	mov    ebx,DWORD PTR [esi+0xc]
  417837:	b8 32 51 44 00       	mov    eax,0x445132
  41783c:	89 5c 24 18          	mov    DWORD PTR [esp+0x18],ebx
  417840:	8b 4e 08             	mov    ecx,DWORD PTR [esi+0x8]
  417843:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  417847:	8b 56 04             	mov    edx,DWORD PTR [esi+0x4]
  41784a:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  41784e:	8d be 6d 1d 00 00    	lea    edi,[esi+0x1d6d]
  417854:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  417858:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  41785c:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  417860:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  417867:	e8 d4 b3 01 00       	call   432c40 <CreateWindowExA@48>
  41786c:	89 86 b0 1f 00 00    	mov    DWORD PTR [esi+0x1fb0],eax
  417872:	83 ec 30             	sub    esp,0x30
  417875:	85 c0                	test   eax,eax
  417877:	0f 85 73 04 00 00    	jne    417cf0 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x540>
  41787d:	31 d2                	xor    edx,edx
  41787f:	b8 3e 51 44 00       	mov    eax,0x44513e
  417884:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  417888:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41788c:	eb 17                	jmp    4178a5 <bixby110control::Bixby110DialogSetupUtilityWindows()+0xf5>
  41788e:	89 f6                	mov    esi,esi
  417890:	bf 5a 51 44 00       	mov    edi,0x44515a
  417895:	31 c0                	xor    eax,eax
  417897:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  41789b:	8d be 6d 1d 00 00    	lea    edi,[esi+0x1d6d]
  4178a1:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  4178a5:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  4178a9:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  4178b0:	e8 db b2 01 00       	call   432b90 <MessageBoxA@16>
  4178b5:	83 ec 10             	sub    esp,0x10
  4178b8:	c7 46 04 6e 00 00 00 	mov    DWORD PTR [esi+0x4],0x6e
  4178bf:	8b 96 b4 1f 00 00    	mov    edx,DWORD PTR [esi+0x1fb4]
  4178c5:	b8 46 75 65 6c       	mov    eax,0x6c657546
  4178ca:	c7 46 08 aa 00 00 00 	mov    DWORD PTR [esi+0x8],0xaa
  4178d1:	bb 20 41 20 44       	mov    ebx,0x44204120
  4178d6:	b9 61 74 61 00       	mov    ecx,0x617461
  4178db:	c7 46 0c e1 00 00 00 	mov    DWORD PTR [esi+0xc],0xe1
  4178e2:	85 d2                	test   edx,edx
  4178e4:	c7 46 10 db 01 00 00 	mov    DWORD PTR [esi+0x10],0x1db
  4178eb:	89 86 6d 1d 00 00    	mov    DWORD PTR [esi+0x1d6d],eax
  4178f1:	89 9e 71 1d 00 00    	mov    DWORD PTR [esi+0x1d71],ebx
  4178f7:	89 8e 75 1d 00 00    	mov    DWORD PTR [esi+0x1d75],ecx
  4178fd:	0f 85 7d 00 00 00    	jne    417980 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x1d0>
  417903:	31 c9                	xor    ecx,ecx
  417905:	31 c0                	xor    eax,eax
  417907:	89 4c 24 2c          	mov    DWORD PTR [esp+0x2c],ecx
  41790b:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  41790e:	89 44 24 24          	mov    DWORD PTR [esp+0x24],eax
  417912:	89 54 24 28          	mov    DWORD PTR [esp+0x28],edx
  417916:	8b 5e 14             	mov    ebx,DWORD PTR [esi+0x14]
  417919:	89 5c 24 20          	mov    DWORD PTR [esp+0x20],ebx
  41791d:	8b 4e 10             	mov    ecx,DWORD PTR [esi+0x10]
  417920:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  417924:	8b 56 0c             	mov    edx,DWORD PTR [esi+0xc]
  417927:	b9 00 00 ca 00       	mov    ecx,0xca0000
  41792c:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  417930:	8b 46 08             	mov    eax,DWORD PTR [esi+0x8]
  417933:	ba 32 51 44 00       	mov    edx,0x445132
  417938:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  41793c:	8b 5e 04             	mov    ebx,DWORD PTR [esi+0x4]
  41793f:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  417943:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  417947:	89 5c 24 10          	mov    DWORD PTR [esp+0x10],ebx
  41794b:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41794f:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  417956:	e8 e5 b2 01 00       	call   432c40 <CreateWindowExA@48>
  41795b:	89 86 b4 1f 00 00    	mov    DWORD PTR [esi+0x1fb4],eax
  417961:	83 ec 30             	sub    esp,0x30
  417964:	85 c0                	test   eax,eax
  417966:	0f 85 04 03 00 00    	jne    417c70 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x4c0>
  41796c:	31 c0                	xor    eax,eax
  41796e:	bb 3e 51 44 00       	mov    ebx,0x44513e
  417973:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  417977:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  41797b:	eb 12                	jmp    41798f <bixby110control::Bixby110DialogSetupUtilityWindows()+0x1df>
  41797d:	8d 76 00             	lea    esi,[esi+0x0]
  417980:	31 c0                	xor    eax,eax
  417982:	b9 5a 51 44 00       	mov    ecx,0x44515a
  417987:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  41798b:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41798f:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  417993:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  41799a:	e8 f1 b1 01 00       	call   432b90 <MessageBoxA@16>
  41799f:	83 ec 10             	sub    esp,0x10
  4179a2:	c7 46 04 91 00 00 00 	mov    DWORD PTR [esi+0x4],0x91
  4179a9:	8b 96 b8 1f 00 00    	mov    edx,DWORD PTR [esi+0x1fb8]
  4179af:	b8 46 75 65 6c       	mov    eax,0x6c657546
  4179b4:	c7 46 08 cd 00 00 00 	mov    DWORD PTR [esi+0x8],0xcd
  4179bb:	b9 20 42 20 44       	mov    ecx,0x44204220
  4179c0:	bb 61 74 61 00       	mov    ebx,0x617461
  4179c5:	c7 46 0c e1 00 00 00 	mov    DWORD PTR [esi+0xc],0xe1
  4179cc:	85 d2                	test   edx,edx
  4179ce:	c7 46 10 db 01 00 00 	mov    DWORD PTR [esi+0x10],0x1db
  4179d5:	89 86 6d 1d 00 00    	mov    DWORD PTR [esi+0x1d6d],eax
  4179db:	89 8e 71 1d 00 00    	mov    DWORD PTR [esi+0x1d71],ecx
  4179e1:	89 9e 75 1d 00 00    	mov    DWORD PTR [esi+0x1d75],ebx
  4179e7:	75 7a                	jne    417a63 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x2b3>
  4179e9:	31 db                	xor    ebx,ebx
  4179eb:	31 c0                	xor    eax,eax
  4179ed:	89 5c 24 2c          	mov    DWORD PTR [esp+0x2c],ebx
  4179f1:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  4179f4:	89 44 24 24          	mov    DWORD PTR [esp+0x24],eax
  4179f8:	89 54 24 28          	mov    DWORD PTR [esp+0x28],edx
  4179fc:	8b 4e 14             	mov    ecx,DWORD PTR [esi+0x14]
  4179ff:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  417a03:	8b 5e 10             	mov    ebx,DWORD PTR [esi+0x10]
  417a06:	89 5c 24 1c          	mov    DWORD PTR [esp+0x1c],ebx
  417a0a:	8b 56 0c             	mov    edx,DWORD PTR [esi+0xc]
  417a0d:	bb 00 00 ca 00       	mov    ebx,0xca0000
  417a12:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  417a16:	8b 46 08             	mov    eax,DWORD PTR [esi+0x8]
  417a19:	ba 32 51 44 00       	mov    edx,0x445132
  417a1e:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  417a22:	8b 4e 04             	mov    ecx,DWORD PTR [esi+0x4]
  417a25:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417a29:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  417a2d:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  417a31:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  417a35:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  417a3c:	e8 ff b1 01 00       	call   432c40 <CreateWindowExA@48>
  417a41:	89 86 b8 1f 00 00    	mov    DWORD PTR [esi+0x1fb8],eax
  417a47:	83 ec 30             	sub    esp,0x30
  417a4a:	85 c0                	test   eax,eax
  417a4c:	0f 85 9f 01 00 00    	jne    417bf1 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x441>
  417a52:	31 c0                	xor    eax,eax
  417a54:	b9 3e 51 44 00       	mov    ecx,0x44513e
  417a59:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  417a5d:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  417a61:	eb 0f                	jmp    417a72 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x2c2>
  417a63:	31 c0                	xor    eax,eax
  417a65:	b9 5a 51 44 00       	mov    ecx,0x44515a
  417a6a:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  417a6e:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  417a72:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  417a76:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  417a7d:	e8 0e b1 01 00       	call   432b90 <MessageBoxA@16>
  417a82:	83 ec 10             	sub    esp,0x10
  417a85:	c7 46 04 b4 00 00 00 	mov    DWORD PTR [esi+0x4],0xb4
  417a8c:	8b 96 bc 1f 00 00    	mov    edx,DWORD PTR [esi+0x1fbc]
  417a92:	b8 54 65 6c 65       	mov    eax,0x656c6554
  417a97:	c7 46 08 f0 00 00 00 	mov    DWORD PTR [esi+0x8],0xf0
  417a9e:	b9 6d 65 74 72       	mov    ecx,0x7274656d
  417aa3:	bb 79 00 00 00       	mov    ebx,0x79
  417aa8:	c7 46 0c e6 00 00 00 	mov    DWORD PTR [esi+0xc],0xe6
  417aaf:	85 d2                	test   edx,edx
  417ab1:	c7 46 10 fc 01 00 00 	mov    DWORD PTR [esi+0x10],0x1fc
  417ab8:	89 86 6d 1d 00 00    	mov    DWORD PTR [esi+0x1d6d],eax
  417abe:	89 8e 71 1d 00 00    	mov    DWORD PTR [esi+0x1d71],ecx
  417ac4:	66 89 9e 75 1d 00 00 	mov    WORD PTR [esi+0x1d75],bx
  417acb:	75 76                	jne    417b43 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x393>
  417acd:	31 db                	xor    ebx,ebx
  417acf:	31 c0                	xor    eax,eax
  417ad1:	89 5c 24 2c          	mov    DWORD PTR [esp+0x2c],ebx
  417ad5:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  417ad8:	89 44 24 24          	mov    DWORD PTR [esp+0x24],eax
  417adc:	89 54 24 28          	mov    DWORD PTR [esp+0x28],edx
  417ae0:	8b 4e 14             	mov    ecx,DWORD PTR [esi+0x14]
  417ae3:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  417ae7:	8b 5e 10             	mov    ebx,DWORD PTR [esi+0x10]
  417aea:	89 5c 24 1c          	mov    DWORD PTR [esp+0x1c],ebx
  417aee:	8b 56 0c             	mov    edx,DWORD PTR [esi+0xc]
  417af1:	bb 00 00 ca 00       	mov    ebx,0xca0000
  417af6:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  417afa:	8b 46 08             	mov    eax,DWORD PTR [esi+0x8]
  417afd:	ba 32 51 44 00       	mov    edx,0x445132
  417b02:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  417b06:	8b 4e 04             	mov    ecx,DWORD PTR [esi+0x4]
  417b09:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417b0d:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  417b11:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  417b15:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  417b19:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  417b20:	e8 1b b1 01 00       	call   432c40 <CreateWindowExA@48>
  417b25:	89 86 bc 1f 00 00    	mov    DWORD PTR [esi+0x1fbc],eax
  417b2b:	83 ec 30             	sub    esp,0x30
  417b2e:	85 c0                	test   eax,eax
  417b30:	75 3e                	jne    417b70 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x3c0>
  417b32:	31 c9                	xor    ecx,ecx
  417b34:	be 3e 51 44 00       	mov    esi,0x44513e
  417b39:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  417b3d:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  417b41:	eb 0f                	jmp    417b52 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x3a2>
  417b43:	31 db                	xor    ebx,ebx
  417b45:	be 5a 51 44 00       	mov    esi,0x44515a
  417b4a:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417b4e:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  417b52:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  417b56:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  417b5d:	e8 2e b0 01 00       	call   432b90 <MessageBoxA@16>
  417b62:	83 ec 10             	sub    esp,0x10
  417b65:	8d 65 f4             	lea    esp,[ebp-0xc]
  417b68:	5b                   	pop    ebx
  417b69:	5e                   	pop    esi
  417b6a:	5f                   	pop    edi
  417b6b:	5d                   	pop    ebp
  417b6c:	c3                   	ret
  417b6d:	8d 76 00             	lea    esi,[esi+0x0]
  417b70:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  417b77:	31 ff                	xor    edi,edi
  417b79:	e8 92 af 01 00       	call   432b10 <GetStockObject@4>
  417b7e:	83 ec 04             	sub    esp,0x4
  417b81:	b9 30 00 00 00       	mov    ecx,0x30
  417b86:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  417b8a:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  417b8e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  417b92:	8b 96 bc 1f 00 00    	mov    edx,DWORD PTR [esi+0x1fbc]
  417b98:	89 14 24             	mov    DWORD PTR [esp],edx
  417b9b:	e8 b0 b0 01 00       	call   432c50 <SendMessageA@16>
  417ba0:	8b 86 bc 1f 00 00    	mov    eax,DWORD PTR [esi+0x1fbc]
  417ba6:	83 ec 10             	sub    esp,0x10
  417ba9:	89 04 24             	mov    DWORD PTR [esp],eax
  417bac:	e8 ff af 01 00       	call   432bb0 <GetDC@4>
  417bb1:	83 ec 04             	sub    esp,0x4
  417bb4:	89 c3                	mov    ebx,eax
  417bb6:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  417bbd:	e8 4e af 01 00       	call   432b10 <GetStockObject@4>
  417bc2:	83 ec 04             	sub    esp,0x4
  417bc5:	89 1c 24             	mov    DWORD PTR [esp],ebx
  417bc8:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  417bcc:	e8 4f af 01 00       	call   432b20 <SelectObject@8>
  417bd1:	83 ec 08             	sub    esp,0x8
  417bd4:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  417bd8:	8b be bc 1f 00 00    	mov    edi,DWORD PTR [esi+0x1fbc]
  417bde:	89 3c 24             	mov    DWORD PTR [esp],edi
  417be1:	e8 da af 01 00       	call   432bc0 <ReleaseDC@8>
  417be6:	83 ec 08             	sub    esp,0x8
  417be9:	8d 65 f4             	lea    esp,[ebp-0xc]
  417bec:	5b                   	pop    ebx
  417bed:	5e                   	pop    esi
  417bee:	5f                   	pop    edi
  417bef:	5d                   	pop    ebp
  417bf0:	c3                   	ret
  417bf1:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  417bf8:	31 db                	xor    ebx,ebx
  417bfa:	e8 11 af 01 00       	call   432b10 <GetStockObject@4>
  417bff:	83 ec 04             	sub    esp,0x4
  417c02:	ba 30 00 00 00       	mov    edx,0x30
  417c07:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  417c0b:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417c0f:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  417c13:	8b 86 b8 1f 00 00    	mov    eax,DWORD PTR [esi+0x1fb8]
  417c19:	89 04 24             	mov    DWORD PTR [esp],eax
  417c1c:	e8 2f b0 01 00       	call   432c50 <SendMessageA@16>
  417c21:	8b 8e b8 1f 00 00    	mov    ecx,DWORD PTR [esi+0x1fb8]
  417c27:	83 ec 10             	sub    esp,0x10
  417c2a:	89 0c 24             	mov    DWORD PTR [esp],ecx
  417c2d:	e8 7e af 01 00       	call   432bb0 <GetDC@4>
  417c32:	83 ec 04             	sub    esp,0x4
  417c35:	89 c3                	mov    ebx,eax
  417c37:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  417c3e:	e8 cd ae 01 00       	call   432b10 <GetStockObject@4>
  417c43:	83 ec 04             	sub    esp,0x4
  417c46:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  417c4a:	89 1c 24             	mov    DWORD PTR [esp],ebx
  417c4d:	e8 ce ae 01 00       	call   432b20 <SelectObject@8>
  417c52:	83 ec 08             	sub    esp,0x8
  417c55:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  417c59:	8b 96 b8 1f 00 00    	mov    edx,DWORD PTR [esi+0x1fb8]
  417c5f:	89 14 24             	mov    DWORD PTR [esp],edx
  417c62:	e8 59 af 01 00       	call   432bc0 <ReleaseDC@8>
  417c67:	83 ec 08             	sub    esp,0x8
  417c6a:	e9 16 fe ff ff       	jmp    417a85 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x2d5>
  417c6f:	90                   	nop
  417c70:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  417c77:	31 db                	xor    ebx,ebx
  417c79:	e8 92 ae 01 00       	call   432b10 <GetStockObject@4>
  417c7e:	83 ec 04             	sub    esp,0x4
  417c81:	ba 30 00 00 00       	mov    edx,0x30
  417c86:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  417c8a:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417c8e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  417c92:	8b 86 b4 1f 00 00    	mov    eax,DWORD PTR [esi+0x1fb4]
  417c98:	89 04 24             	mov    DWORD PTR [esp],eax
  417c9b:	e8 b0 af 01 00       	call   432c50 <SendMessageA@16>
  417ca0:	8b 8e b4 1f 00 00    	mov    ecx,DWORD PTR [esi+0x1fb4]
  417ca6:	83 ec 10             	sub    esp,0x10
  417ca9:	89 0c 24             	mov    DWORD PTR [esp],ecx
  417cac:	e8 ff ae 01 00       	call   432bb0 <GetDC@4>
  417cb1:	83 ec 04             	sub    esp,0x4
  417cb4:	89 c3                	mov    ebx,eax
  417cb6:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  417cbd:	e8 4e ae 01 00       	call   432b10 <GetStockObject@4>
  417cc2:	83 ec 04             	sub    esp,0x4
  417cc5:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  417cc9:	89 1c 24             	mov    DWORD PTR [esp],ebx
  417ccc:	e8 4f ae 01 00       	call   432b20 <SelectObject@8>
  417cd1:	83 ec 08             	sub    esp,0x8
  417cd4:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  417cd8:	8b 96 b4 1f 00 00    	mov    edx,DWORD PTR [esi+0x1fb4]
  417cde:	89 14 24             	mov    DWORD PTR [esp],edx
  417ce1:	e8 da ae 01 00       	call   432bc0 <ReleaseDC@8>
  417ce6:	83 ec 08             	sub    esp,0x8
  417ce9:	e9 b4 fc ff ff       	jmp    4179a2 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x1f2>
  417cee:	89 f6                	mov    esi,esi
  417cf0:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  417cf7:	31 db                	xor    ebx,ebx
  417cf9:	e8 12 ae 01 00       	call   432b10 <GetStockObject@4>
  417cfe:	83 ec 04             	sub    esp,0x4
  417d01:	b9 30 00 00 00       	mov    ecx,0x30
  417d06:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  417d0a:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  417d0e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  417d12:	8b 96 b0 1f 00 00    	mov    edx,DWORD PTR [esi+0x1fb0]
  417d18:	89 14 24             	mov    DWORD PTR [esp],edx
  417d1b:	e8 30 af 01 00       	call   432c50 <SendMessageA@16>
  417d20:	8b 86 b0 1f 00 00    	mov    eax,DWORD PTR [esi+0x1fb0]
  417d26:	83 ec 10             	sub    esp,0x10
  417d29:	89 04 24             	mov    DWORD PTR [esp],eax
  417d2c:	e8 7f ae 01 00       	call   432bb0 <GetDC@4>
  417d31:	83 ec 04             	sub    esp,0x4
  417d34:	89 c3                	mov    ebx,eax
  417d36:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  417d3d:	e8 ce ad 01 00       	call   432b10 <GetStockObject@4>
  417d42:	83 ec 04             	sub    esp,0x4
  417d45:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  417d49:	89 1c 24             	mov    DWORD PTR [esp],ebx
  417d4c:	e8 cf ad 01 00       	call   432b20 <SelectObject@8>
  417d51:	83 ec 08             	sub    esp,0x8
  417d54:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  417d58:	8b 8e b0 1f 00 00    	mov    ecx,DWORD PTR [esi+0x1fb0]
  417d5e:	89 0c 24             	mov    DWORD PTR [esp],ecx
  417d61:	e8 5a ae 01 00       	call   432bc0 <ReleaseDC@8>
  417d66:	83 ec 08             	sub    esp,0x8
  417d69:	e9 4a fb ff ff       	jmp    4178b8 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x108>
  417d6e:	89 f6                	mov    esi,esi

# source=Bixby110dlg.cpp
# va=0x004181E0 size=0xF0
0x004181E0 <bixby110control::Bixby110DialogSetupUtilityWindowButtons(int, int, int, int)>:
  4181e0:	55                   	push   ebp
  4181e1:	b9 21 d2 43 00       	mov    ecx,0x43d221
  4181e6:	89 e5                	mov    ebp,esp
  4181e8:	57                   	push   edi
  4181e9:	56                   	push   esi
  4181ea:	53                   	push   ebx
  4181eb:	83 ec 1c             	sub    esp,0x1c
  4181ee:	8b 5d 08             	mov    ebx,DWORD PTR [ebp+0x8]
  4181f1:	8b 7d 0c             	mov    edi,DWORD PTR [ebp+0xc]
  4181f4:	8b 75 10             	mov    esi,DWORD PTR [ebp+0x10]
  4181f7:	8b 43 18             	mov    eax,DWORD PTR [ebx+0x18]
  4181fa:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  4181fe:	8b 13                	mov    edx,DWORD PTR [ebx]
  418200:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  418204:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  418208:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  41820c:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  418210:	8b 83 08 09 00 00    	mov    eax,DWORD PTR [ebx+0x908]
  418216:	89 04 24             	mov    DWORD PTR [esp],eax
  418219:	e8 62 a9 00 00       	call   422b80 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  41821e:	0f b6 93 6c 1d 00 00 	movzx  edx,BYTE PTR [ebx+0x1d6c]
  418225:	8b 4b 18             	mov    ecx,DWORD PTR [ebx+0x18]
  418228:	01 d6                	add    esi,edx
  41822a:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  41822e:	ba 79 d2 43 00       	mov    edx,0x43d279
  418233:	8b 03                	mov    eax,DWORD PTR [ebx]
  418235:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  418239:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  41823d:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  418241:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  418245:	8b 8b 0c 09 00 00    	mov    ecx,DWORD PTR [ebx+0x90c]
  41824b:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41824e:	e8 2d a9 00 00       	call   422b80 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  418253:	0f b6 83 6c 1d 00 00 	movzx  eax,BYTE PTR [ebx+0x1d6c]
  41825a:	8b 53 18             	mov    edx,DWORD PTR [ebx+0x18]
  41825d:	01 c6                	add    esi,eax
  41825f:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  418263:	b8 d1 d2 43 00       	mov    eax,0x43d2d1
  418268:	8b 0b                	mov    ecx,DWORD PTR [ebx]
  41826a:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  41826e:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  418272:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  418276:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41827a:	8b 93 10 09 00 00    	mov    edx,DWORD PTR [ebx+0x910]
  418280:	89 14 24             	mov    DWORD PTR [esp],edx
  418283:	e8 f8 a8 00 00       	call   422b80 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  418288:	0f b6 8b 6c 1d 00 00 	movzx  ecx,BYTE PTR [ebx+0x1d6c]
  41828f:	8b 43 18             	mov    eax,DWORD PTR [ebx+0x18]
  418292:	01 ce                	add    esi,ecx
  418294:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  418298:	b9 29 d3 43 00       	mov    ecx,0x43d329
  41829d:	8b 13                	mov    edx,DWORD PTR [ebx]
  41829f:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  4182a3:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  4182a7:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  4182ab:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  4182af:	8b 83 14 09 00 00    	mov    eax,DWORD PTR [ebx+0x914]
  4182b5:	89 04 24             	mov    DWORD PTR [esp],eax
  4182b8:	e8 c3 a8 00 00       	call   422b80 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  4182bd:	83 c4 1c             	add    esp,0x1c
  4182c0:	5b                   	pop    ebx
  4182c1:	5e                   	pop    esi
  4182c2:	5f                   	pop    edi
  4182c3:	5d                   	pop    ebp
  4182c4:	c3                   	ret
  4182c5:	90                   	nop
  4182c6:	8d 76 00             	lea    esi,[esi+0x0]
  4182c9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
