# Firmware downloader core (unsafe binary protocol)
# BixCheck 5.0.21; generated by tools/analyze_bixcheck.py
# Exact GNU objdump Intel-syntax excerpts; addresses are build-specific.

# source=Bixby110Downloader.cpp
# va=0x0041BD20 size=0x220
0x0041BD20 <bixby110downloader::GetStoveVersion()>:
  41bd20:	55                   	push   ebp
  41bd21:	ba 08 00 00 00       	mov    edx,0x8
  41bd26:	89 e5                	mov    ebp,esp
  41bd28:	57                   	push   edi
  41bd29:	bf 64 00 00 00       	mov    edi,0x64
  41bd2e:	56                   	push   esi
  41bd2f:	be 43 00 00 00       	mov    esi,0x43
  41bd34:	53                   	push   ebx
  41bd35:	83 ec 1c             	sub    esp,0x1c
  41bd38:	8b 5d 08             	mov    ebx,DWORD PTR [ebp+0x8]
  41bd3b:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41bd3f:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  41bd43:	8d b3 fc 05 00 00    	lea    esi,[ebx+0x5fc]
  41bd49:	89 34 24             	mov    DWORD PTR [esp],esi
  41bd4c:	e8 7f d1 fe ff       	call   408ed0 <bixby110io::readreg(unsigned char, unsigned char)>
  41bd51:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41bd55:	8b 03                	mov    eax,DWORD PTR [ebx]
  41bd57:	bf 64 00 00 00       	mov    edi,0x64
  41bd5c:	89 04 24             	mov    DWORD PTR [esp],eax
  41bd5f:	e8 dc c0 fe ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  41bd64:	89 34 24             	mov    DWORD PTR [esp],esi
  41bd67:	e8 34 d2 fe ff       	call   408fa0 <bixby110io::CollectResponse()>
  41bd6c:	89 34 24             	mov    DWORD PTR [esp],esi
  41bd6f:	b9 0b 00 00 00       	mov    ecx,0xb
  41bd74:	ba 43 00 00 00       	mov    edx,0x43
  41bd79:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41bd7d:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41bd81:	e8 4a d1 fe ff       	call   408ed0 <bixby110io::readreg(unsigned char, unsigned char)>
  41bd86:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41bd8a:	8b 03                	mov    eax,DWORD PTR [ebx]
  41bd8c:	bf 64 00 00 00       	mov    edi,0x64
  41bd91:	89 04 24             	mov    DWORD PTR [esp],eax
  41bd94:	e8 a7 c0 fe ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  41bd99:	89 34 24             	mov    DWORD PTR [esp],esi
  41bd9c:	e8 ff d1 fe ff       	call   408fa0 <bixby110io::CollectResponse()>
  41bda1:	89 34 24             	mov    DWORD PTR [esp],esi
  41bda4:	b9 0c 00 00 00       	mov    ecx,0xc
  41bda9:	ba 43 00 00 00       	mov    edx,0x43
  41bdae:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41bdb2:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41bdb6:	e8 15 d1 fe ff       	call   408ed0 <bixby110io::readreg(unsigned char, unsigned char)>
  41bdbb:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41bdbf:	8b 03                	mov    eax,DWORD PTR [ebx]
  41bdc1:	bf 64 00 00 00       	mov    edi,0x64
  41bdc6:	89 04 24             	mov    DWORD PTR [esp],eax
  41bdc9:	e8 72 c0 fe ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  41bdce:	89 34 24             	mov    DWORD PTR [esp],esi
  41bdd1:	e8 ca d1 fe ff       	call   408fa0 <bixby110io::CollectResponse()>
  41bdd6:	89 34 24             	mov    DWORD PTR [esp],esi
  41bdd9:	b9 0d 00 00 00       	mov    ecx,0xd
  41bdde:	ba 43 00 00 00       	mov    edx,0x43
  41bde3:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41bde7:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41bdeb:	e8 e0 d0 fe ff       	call   408ed0 <bixby110io::readreg(unsigned char, unsigned char)>
  41bdf0:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41bdf4:	8b 03                	mov    eax,DWORD PTR [ebx]
  41bdf6:	bf 64 00 00 00       	mov    edi,0x64
  41bdfb:	89 04 24             	mov    DWORD PTR [esp],eax
  41bdfe:	e8 3d c0 fe ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  41be03:	89 34 24             	mov    DWORD PTR [esp],esi
  41be06:	e8 95 d1 fe ff       	call   408fa0 <bixby110io::CollectResponse()>
  41be0b:	89 34 24             	mov    DWORD PTR [esp],esi
  41be0e:	ba 43 00 00 00       	mov    edx,0x43
  41be13:	b9 0e 00 00 00       	mov    ecx,0xe
  41be18:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41be1c:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41be20:	e8 ab d0 fe ff       	call   408ed0 <bixby110io::readreg(unsigned char, unsigned char)>
  41be25:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41be29:	8b 03                	mov    eax,DWORD PTR [ebx]
  41be2b:	bf 37 53 45 00       	mov    edi,0x455337
  41be30:	89 04 24             	mov    DWORD PTR [esp],eax
  41be33:	e8 08 c0 fe ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  41be38:	89 34 24             	mov    DWORD PTR [esp],esi
  41be3b:	e8 60 d1 fe ff       	call   408fa0 <bixby110io::CollectResponse()>
  41be40:	89 34 24             	mov    DWORD PTR [esp],esi
  41be43:	b9 08 00 00 00       	mov    ecx,0x8
  41be48:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41be4c:	e8 ef d0 fe ff       	call   408f40 <bixby110io::getCMDbuf(unsigned char)>
  41be51:	88 83 30 0e 00 00    	mov    BYTE PTR [ebx+0xe30],al
  41be57:	0f be d0             	movsx  edx,al
  41be5a:	c6 83 31 0e 00 00 00 	mov    BYTE PTR [ebx+0xe31],0x0
  41be61:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41be65:	8d bb ce 8e 00 00    	lea    edi,[ebx+0x8ece]
  41be6b:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  41be6f:	89 3c 24             	mov    DWORD PTR [esp],edi
  41be72:	e8 09 35 01 00       	call   42f380 <sprintf>
  41be77:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41be7b:	8b 83 d4 03 00 00    	mov    eax,DWORD PTR [ebx+0x3d4]
  41be81:	89 04 24             	mov    DWORD PTR [esp],eax
  41be84:	e8 97 40 00 00       	call   41ff20 <edit::Settext(char const*)>
  41be89:	89 34 24             	mov    DWORD PTR [esp],esi
  41be8c:	b9 0b 00 00 00       	mov    ecx,0xb
  41be91:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41be95:	e8 a6 d0 fe ff       	call   408f40 <bixby110io::getCMDbuf(unsigned char)>
  41be9a:	88 83 38 0e 00 00    	mov    BYTE PTR [ebx+0xe38],al
  41bea0:	ba 0c 00 00 00       	mov    edx,0xc
  41bea5:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41bea9:	89 34 24             	mov    DWORD PTR [esp],esi
  41beac:	e8 8f d0 fe ff       	call   408f40 <bixby110io::getCMDbuf(unsigned char)>
  41beb1:	88 83 39 0e 00 00    	mov    BYTE PTR [ebx+0xe39],al
  41beb7:	b8 0d 00 00 00       	mov    eax,0xd
  41bebc:	89 34 24             	mov    DWORD PTR [esp],esi
  41bebf:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41bec3:	e8 78 d0 fe ff       	call   408f40 <bixby110io::getCMDbuf(unsigned char)>
  41bec8:	88 83 3a 0e 00 00    	mov    BYTE PTR [ebx+0xe3a],al
  41bece:	b9 0e 00 00 00       	mov    ecx,0xe
  41bed3:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41bed7:	89 34 24             	mov    DWORD PTR [esp],esi
  41beda:	e8 61 d0 fe ff       	call   408f40 <bixby110io::getCMDbuf(unsigned char)>
  41bedf:	88 83 3b 0e 00 00    	mov    BYTE PTR [ebx+0xe3b],al
  41bee5:	0f be d0             	movsx  edx,al
  41bee8:	c6 83 3c 0e 00 00 00 	mov    BYTE PTR [ebx+0xe3c],0x0
  41beef:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  41bef3:	ba 3b 53 45 00       	mov    edx,0x45533b
  41bef8:	0f be 83 3a 0e 00 00 	movsx  eax,BYTE PTR [ebx+0xe3a]
  41beff:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  41bf03:	0f be b3 39 0e 00 00 	movsx  esi,BYTE PTR [ebx+0xe39]
  41bf0a:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  41bf0e:	0f be 8b 38 0e 00 00 	movsx  ecx,BYTE PTR [ebx+0xe38]
  41bf15:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41bf19:	89 3c 24             	mov    DWORD PTR [esp],edi
  41bf1c:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41bf20:	e8 5b 34 01 00       	call   42f380 <sprintf>
  41bf25:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41bf29:	8b 83 dc 03 00 00    	mov    eax,DWORD PTR [ebx+0x3dc]
  41bf2f:	89 04 24             	mov    DWORD PTR [esp],eax
  41bf32:	e8 e9 3f 00 00       	call   41ff20 <edit::Settext(char const*)>
  41bf37:	83 c4 1c             	add    esp,0x1c
  41bf3a:	5b                   	pop    ebx
  41bf3b:	5e                   	pop    esi
  41bf3c:	5f                   	pop    edi
  41bf3d:	5d                   	pop    ebp
  41bf3e:	c3                   	ret
  41bf3f:	90                   	nop

# source=Bixby110Downloader.cpp
# va=0x0041BF40 size=0x40
0x0041BF40 <bixby110downloader::AttemptStoveReset()>:
  41bf40:	55                   	push   ebp
  41bf41:	b8 c4 00 00 00       	mov    eax,0xc4
  41bf46:	89 e5                	mov    ebp,esp
  41bf48:	83 ec 18             	sub    esp,0x18
  41bf4b:	b9 0f 00 00 00       	mov    ecx,0xf
  41bf50:	ba 43 00 00 00       	mov    edx,0x43
  41bf55:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  41bf59:	8b 45 08             	mov    eax,DWORD PTR [ebp+0x8]
  41bf5c:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41bf60:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41bf64:	05 fc 05 00 00       	add    eax,0x5fc
  41bf69:	89 04 24             	mov    DWORD PTR [esp],eax
  41bf6c:	e8 1f cf fe ff       	call   408e90 <bixby110io::writereg(unsigned char, unsigned char, unsigned char)>
  41bf71:	c9                   	leave
  41bf72:	c3                   	ret
  41bf73:	90                   	nop
  41bf74:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  41bf7a:	8d bf 00 00 00 00    	lea    edi,[edi+0x0]

# source=Bixby110Downloader.cpp
# va=0x0041BF80 size=0xA0
0x0041BF80 <bixby110downloader::SendDone()>:
  41bf80:	55                   	push   ebp
  41bf81:	ba ed ff ff ff       	mov    edx,0xffffffed
  41bf86:	89 e5                	mov    ebp,esp
  41bf88:	57                   	push   edi
  41bf89:	8d 7d f3             	lea    edi,[ebp-0xd]
  41bf8c:	56                   	push   esi
  41bf8d:	53                   	push   ebx
  41bf8e:	83 ec 1c             	sub    esp,0x1c
  41bf91:	b3 32                	mov    bl,0x32
  41bf93:	8b 45 08             	mov    eax,DWORD PTR [ebp+0x8]
  41bf96:	8d b0 fc 05 00 00    	lea    esi,[eax+0x5fc]
  41bf9c:	c6 80 4d 8e 00 00 ed 	mov    BYTE PTR [eax+0x8e4d],0xed
  41bfa3:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41bfa7:	89 34 24             	mov    DWORD PTR [esp],esi
  41bfaa:	e8 91 d8 fe ff       	call   409840 <bixby110io::write_char(char)>
  41bfaf:	eb 07                	jmp    41bfb8 <bixby110downloader::SendDone()+0x38>
  41bfb1:	fe cb                	dec    bl
  41bfb3:	80 fb ff             	cmp    bl,0xff
  41bfb6:	74 27                	je     41bfdf <bixby110downloader::SendDone()+0x5f>
  41bfb8:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41bfbc:	89 34 24             	mov    DWORD PTR [esp],esi
  41bfbf:	e8 ec d8 fe ff       	call   4098b0 <bixby110io::status_read_char(unsigned char*)>
  41bfc4:	84 c0                	test   al,al
  41bfc6:	75 e9                	jne    41bfb1 <bixby110downloader::SendDone()+0x31>
  41bfc8:	b8 01 00 00 00       	mov    eax,0x1
  41bfcd:	84 c0                	test   al,al
  41bfcf:	74 12                	je     41bfe3 <bixby110downloader::SendDone()+0x63>
  41bfd1:	80 7d f3 e4          	cmp    BYTE PTR [ebp-0xd],0xe4
  41bfd5:	75 0c                	jne    41bfe3 <bixby110downloader::SendDone()+0x63>
  41bfd7:	8d 65 f4             	lea    esp,[ebp-0xc]
  41bfda:	5b                   	pop    ebx
  41bfdb:	5e                   	pop    esi
  41bfdc:	5f                   	pop    edi
  41bfdd:	5d                   	pop    ebp
  41bfde:	c3                   	ret
  41bfdf:	31 c0                	xor    eax,eax
  41bfe1:	eb ea                	jmp    41bfcd <bixby110downloader::SendDone()+0x4d>
  41bfe3:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  41bfea:	b9 50 53 45 00       	mov    ecx,0x455350
  41bfef:	be 30 00 00 00       	mov    esi,0x30
  41bff4:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  41bff8:	bb 7f 53 45 00       	mov    ebx,0x45537f
  41bffd:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  41c001:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41c005:	e8 66 35 01 00       	call   42f570 <MessageBoxA@16>
  41c00a:	83 ec 10             	sub    esp,0x10
  41c00d:	c7 04 24 01 00 00 00 	mov    DWORD PTR [esp],0x1
  41c014:	e8 07 34 01 00       	call   42f420 <exit>
  41c019:	90                   	nop
  41c01a:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]

# source=Bixby110Downloader.cpp
# va=0x0041C4C0 size=0x670
0x0041C4C0 <bixby110downloader::LoadHex(char*)>:
  41c4c0:	55                   	push   ebp
  41c4c1:	89 e5                	mov    ebp,esp
  41c4c3:	57                   	push   edi
  41c4c4:	56                   	push   esi
  41c4c5:	53                   	push   ebx
  41c4c6:	83 ec 2c             	sub    esp,0x2c
  41c4c9:	8b 4d 08             	mov    ecx,DWORD PTR [ebp+0x8]
  41c4cc:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  41c4cf:	89 4d d8             	mov    DWORD PTR [ebp-0x28],ecx
  41c4d2:	8b 55 d8             	mov    edx,DWORD PTR [ebp-0x28]
  41c4d5:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41c4d9:	89 14 24             	mov    DWORD PTR [esp],edx
  41c4dc:	e8 ff fb ff ff       	call   41c0e0 <bixby110downloader::LoadHex_Open(char*)>
  41c4e1:	31 d2                	xor    edx,edx
  41c4e3:	84 c0                	test   al,al
  41c4e5:	0f 84 6f 03 00 00    	je     41c85a <bixby110downloader::LoadHex(char*)+0x39a>
  41c4eb:	8b 7d d8             	mov    edi,DWORD PTR [ebp-0x28]
  41c4ee:	31 c0                	xor    eax,eax
  41c4f0:	89 87 48 8e 00 00    	mov    DWORD PTR [edi+0x8e48],eax
  41c4f6:	81 c7 e1 03 00 00    	add    edi,0x3e1
  41c4fc:	89 7d e0             	mov    DWORD PTR [ebp-0x20],edi
  41c4ff:	90                   	nop
  41c500:	8b 55 d8             	mov    edx,DWORD PTR [ebp-0x28]
  41c503:	89 14 24             	mov    DWORD PTR [esp],edx
  41c506:	e8 c5 fd ff ff       	call   41c2d0 <bixby110downloader::LoadHex_Read()>
  41c50b:	85 c0                	test   eax,eax
  41c50d:	0f 84 de 04 00 00    	je     41c9f1 <bixby110downloader::LoadHex(char*)+0x531>
  41c513:	8b 7d d8             	mov    edi,DWORD PTR [ebp-0x28]
  41c516:	80 bf e0 03 00 00 3a 	cmp    BYTE PTR [edi+0x3e0],0x3a
  41c51d:	0f 85 03 05 00 00    	jne    41ca26 <bixby110downloader::LoadHex(char*)+0x566>
  41c523:	0f b6 97 e1 03 00 00 	movzx  edx,BYTE PTR [edi+0x3e1]
  41c52a:	88 d3                	mov    bl,dl
  41c52c:	80 eb 61             	sub    bl,0x61
  41c52f:	80 fb 05             	cmp    bl,0x5
  41c532:	0f 87 ec 03 00 00    	ja     41c924 <bixby110downloader::LoadHex(char*)+0x464>
  41c538:	80 ea 57             	sub    dl,0x57
  41c53b:	8b 75 e0             	mov    esi,DWORD PTR [ebp-0x20]
  41c53e:	0f be fa             	movsx  edi,dl
  41c541:	89 f9                	mov    ecx,edi
  41c543:	c1 e1 04             	shl    ecx,0x4
  41c546:	0f b6 56 01          	movzx  edx,BYTE PTR [esi+0x1]
  41c54a:	88 d0                	mov    al,dl
  41c54c:	2c 61                	sub    al,0x61
  41c54e:	3c 05                	cmp    al,0x5
  41c550:	0f 87 bc 03 00 00    	ja     41c912 <bixby110downloader::LoadHex(char*)+0x452>
  41c556:	80 ea 57             	sub    dl,0x57
  41c559:	8b 5d e0             	mov    ebx,DWORD PTR [ebp-0x20]
  41c55c:	0f be f2             	movsx  esi,dl
  41c55f:	8b 55 d8             	mov    edx,DWORD PTR [ebp-0x28]
  41c562:	8b 45 e0             	mov    eax,DWORD PTR [ebp-0x20]
  41c565:	01 f1                	add    ecx,esi
  41c567:	83 c3 02             	add    ebx,0x2
  41c56a:	89 4d e8             	mov    DWORD PTR [ebp-0x18],ecx
  41c56d:	89 9a e0 04 00 00    	mov    DWORD PTR [edx+0x4e0],ebx
  41c573:	0f b6 50 02          	movzx  edx,BYTE PTR [eax+0x2]
  41c577:	88 d1                	mov    cl,dl
  41c579:	80 e9 61             	sub    cl,0x61
  41c57c:	80 f9 05             	cmp    cl,0x5
  41c57f:	0f 87 7b 03 00 00    	ja     41c900 <bixby110downloader::LoadHex(char*)+0x440>
  41c585:	80 ea 57             	sub    dl,0x57
  41c588:	0f be fa             	movsx  edi,dl
  41c58b:	89 f9                	mov    ecx,edi
  41c58d:	c1 e1 04             	shl    ecx,0x4
  41c590:	0f b6 53 01          	movzx  edx,BYTE PTR [ebx+0x1]
  41c594:	88 d0                	mov    al,dl
  41c596:	2c 61                	sub    al,0x61
  41c598:	3c 05                	cmp    al,0x5
  41c59a:	0f 87 50 03 00 00    	ja     41c8f0 <bixby110downloader::LoadHex(char*)+0x430>
  41c5a0:	80 ea 57             	sub    dl,0x57
  41c5a3:	0f be f2             	movsx  esi,dl
  41c5a6:	8d 53 02             	lea    edx,[ebx+0x2]
  41c5a9:	01 f1                	add    ecx,esi
  41c5ab:	89 55 e4             	mov    DWORD PTR [ebp-0x1c],edx
  41c5ae:	c1 e1 08             	shl    ecx,0x8
  41c5b1:	0f b6 53 02          	movzx  edx,BYTE PTR [ebx+0x2]
  41c5b5:	88 d0                	mov    al,dl
  41c5b7:	2c 61                	sub    al,0x61
  41c5b9:	3c 05                	cmp    al,0x5
  41c5bb:	0f 87 1f 03 00 00    	ja     41c8e0 <bixby110downloader::LoadHex(char*)+0x420>
  41c5c1:	80 ea 57             	sub    dl,0x57
  41c5c4:	8b 7d e4             	mov    edi,DWORD PTR [ebp-0x1c]
  41c5c7:	0f be c2             	movsx  eax,dl
  41c5ca:	89 c6                	mov    esi,eax
  41c5cc:	c1 e6 04             	shl    esi,0x4
  41c5cf:	0f b6 57 01          	movzx  edx,BYTE PTR [edi+0x1]
  41c5d3:	88 d0                	mov    al,dl
  41c5d5:	2c 61                	sub    al,0x61
  41c5d7:	3c 05                	cmp    al,0x5
  41c5d9:	0f 87 e7 02 00 00    	ja     41c8c6 <bixby110downloader::LoadHex(char*)+0x406>
  41c5df:	80 ea 57             	sub    dl,0x57
  41c5e2:	0f be c2             	movsx  eax,dl
  41c5e5:	8d 3c 06             	lea    edi,[esi+eax*1]
  41c5e8:	8b 55 d8             	mov    edx,DWORD PTR [ebp-0x28]
  41c5eb:	01 f9                	add    ecx,edi
  41c5ed:	d1 e9                	shr    ecx,1
  41c5ef:	89 4d f0             	mov    DWORD PTR [ebp-0x10],ecx
  41c5f2:	8d 4b 04             	lea    ecx,[ebx+0x4]
  41c5f5:	89 8a e0 04 00 00    	mov    DWORD PTR [edx+0x4e0],ecx
  41c5fb:	0f b6 53 04          	movzx  edx,BYTE PTR [ebx+0x4]
  41c5ff:	88 d3                	mov    bl,dl
  41c601:	80 eb 61             	sub    bl,0x61
  41c604:	80 fb 05             	cmp    bl,0x5
  41c607:	0f 87 a3 02 00 00    	ja     41c8b0 <bixby110downloader::LoadHex(char*)+0x3f0>
  41c60d:	80 ea 57             	sub    dl,0x57
  41c610:	0f be f2             	movsx  esi,dl
  41c613:	89 f3                	mov    ebx,esi
  41c615:	c1 e3 04             	shl    ebx,0x4
  41c618:	0f b6 51 01          	movzx  edx,BYTE PTR [ecx+0x1]
  41c61c:	88 d0                	mov    al,dl
  41c61e:	2c 61                	sub    al,0x61
  41c620:	3c 05                	cmp    al,0x5
  41c622:	0f 87 70 02 00 00    	ja     41c898 <bixby110downloader::LoadHex(char*)+0x3d8>
  41c628:	80 ea 57             	sub    dl,0x57
  41c62b:	0f be fa             	movsx  edi,dl
  41c62e:	83 c1 02             	add    ecx,0x2
  41c631:	8d 04 3b             	lea    eax,[ebx+edi*1]
  41c634:	8b 7d d8             	mov    edi,DWORD PTR [ebp-0x28]
  41c637:	83 f8 01             	cmp    eax,0x1
  41c63a:	89 8f e0 04 00 00    	mov    DWORD PTR [edi+0x4e0],ecx
  41c640:	0f 84 09 04 00 00    	je     41ca4f <bixby110downloader::LoadHex(char*)+0x58f>
  41c646:	0f 87 3e 04 00 00    	ja     41ca8a <bixby110downloader::LoadHex(char*)+0x5ca>
  41c64c:	c7 45 ec 00 00 00 00 	mov    DWORD PTR [ebp-0x14],0x0
  41c653:	8b 75 e8             	mov    esi,DWORD PTR [ebp-0x18]
  41c656:	d1 ee                	shr    esi,1
  41c658:	83 fe 00             	cmp    esi,0x0
  41c65b:	0f 86 9f fe ff ff    	jbe    41c500 <bixby110downloader::LoadHex(char*)+0x40>
  41c661:	8b 7d d8             	mov    edi,DWORD PTR [ebp-0x28]
  41c664:	8b 5d f0             	mov    ebx,DWORD PTR [ebp-0x10]
  41c667:	8b b7 48 8e 00 00    	mov    esi,DWORD PTR [edi+0x8e48]
  41c66d:	66 89 9c b7 48 0e 00 	mov    WORD PTR [edi+esi*4+0xe48],bx
  41c674:	00
  41c675:	0f b6 11             	movzx  edx,BYTE PTR [ecx]
  41c678:	88 d0                	mov    al,dl
  41c67a:	2c 61                	sub    al,0x61
  41c67c:	3c 05                	cmp    al,0x5
  41c67e:	0f 87 07 01 00 00    	ja     41c78b <bixby110downloader::LoadHex(char*)+0x2cb>
  41c684:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  41c68a:	8d bf 00 00 00 00    	lea    edi,[edi+0x0]
  41c690:	80 ea 57             	sub    dl,0x57
  41c693:	0f be fa             	movsx  edi,dl
  41c696:	89 fb                	mov    ebx,edi
  41c698:	c1 e3 04             	shl    ebx,0x4
  41c69b:	0f b6 51 01          	movzx  edx,BYTE PTR [ecx+0x1]
  41c69f:	88 d1                	mov    cl,dl
  41c6a1:	80 e9 61             	sub    cl,0x61
  41c6a4:	80 f9 05             	cmp    cl,0x5
  41c6a7:	0f 87 13 01 00 00    	ja     41c7c0 <bixby110downloader::LoadHex(char*)+0x300>
  41c6ad:	80 ea 57             	sub    dl,0x57
  41c6b0:	0f be c2             	movsx  eax,dl
  41c6b3:	8b 55 d8             	mov    edx,DWORD PTR [ebp-0x28]
  41c6b6:	8d 0c 03             	lea    ecx,[ebx+eax*1]
  41c6b9:	88 8c b2 4b 0e 00 00 	mov    BYTE PTR [edx+esi*4+0xe4b],cl
  41c6c0:	8b ba e0 04 00 00    	mov    edi,DWORD PTR [edx+0x4e0]
  41c6c6:	8b b2 48 8e 00 00    	mov    esi,DWORD PTR [edx+0x8e48]
  41c6cc:	8d 4f 02             	lea    ecx,[edi+0x2]
  41c6cf:	89 8a e0 04 00 00    	mov    DWORD PTR [edx+0x4e0],ecx
  41c6d5:	0f b6 57 02          	movzx  edx,BYTE PTR [edi+0x2]
  41c6d9:	88 d3                	mov    bl,dl
  41c6db:	80 eb 61             	sub    bl,0x61
  41c6de:	80 fb 05             	cmp    bl,0x5
  41c6e1:	0f 87 7d 01 00 00    	ja     41c864 <bixby110downloader::LoadHex(char*)+0x3a4>
  41c6e7:	80 ea 57             	sub    dl,0x57
  41c6ea:	0f be fa             	movsx  edi,dl
  41c6ed:	89 fb                	mov    ebx,edi
  41c6ef:	c1 e3 04             	shl    ebx,0x4
  41c6f2:	0f b6 51 01          	movzx  edx,BYTE PTR [ecx+0x1]
  41c6f6:	88 d1                	mov    cl,dl
  41c6f8:	80 e9 61             	sub    cl,0x61
  41c6fb:	80 f9 05             	cmp    cl,0x5
  41c6fe:	0f 87 d0 00 00 00    	ja     41c7d4 <bixby110downloader::LoadHex(char*)+0x314>
  41c704:	80 ea 57             	sub    dl,0x57
  41c707:	0f be ca             	movsx  ecx,dl
  41c70a:	8d 14 0b             	lea    edx,[ebx+ecx*1]
  41c70d:	8b 4d d8             	mov    ecx,DWORD PTR [ebp-0x28]
  41c710:	88 94 b1 4a 0e 00 00 	mov    BYTE PTR [ecx+esi*4+0xe4a],dl
  41c717:	8b 91 48 8e 00 00    	mov    edx,DWORD PTR [ecx+0x8e48]
  41c71d:	80 bc 91 4a 0e 00 00 	cmp    BYTE PTR [ecx+edx*4+0xe4a],0x3f
  41c724:	3f
  41c725:	0f 87 dc 00 00 00    	ja     41c807 <bixby110downloader::LoadHex(char*)+0x347>
  41c72b:	ff 45 f0             	inc    DWORD PTR [ebp-0x10]
  41c72e:	8d 72 01             	lea    esi,[edx+0x1]
  41c731:	8b b9 e0 04 00 00    	mov    edi,DWORD PTR [ecx+0x4e0]
  41c737:	8b 5d d8             	mov    ebx,DWORD PTR [ebp-0x28]
  41c73a:	83 c7 02             	add    edi,0x2
  41c73d:	81 fe ff 1f 00 00    	cmp    esi,0x1fff
  41c743:	89 bb e0 04 00 00    	mov    DWORD PTR [ebx+0x4e0],edi
  41c749:	89 f9                	mov    ecx,edi
  41c74b:	89 b3 48 8e 00 00    	mov    DWORD PTR [ebx+0x8e48],esi
  41c751:	0f 87 1f 02 00 00    	ja     41c976 <bixby110downloader::LoadHex(char*)+0x4b6>
  41c757:	ff 45 ec             	inc    DWORD PTR [ebp-0x14]
  41c75a:	8b 45 e8             	mov    eax,DWORD PTR [ebp-0x18]
  41c75d:	d1 e8                	shr    eax,1
  41c75f:	3b 45 ec             	cmp    eax,DWORD PTR [ebp-0x14]
  41c762:	0f 86 98 fd ff ff    	jbe    41c500 <bixby110downloader::LoadHex(char*)+0x40>
  41c768:	8b 7d d8             	mov    edi,DWORD PTR [ebp-0x28]
  41c76b:	8b 5d f0             	mov    ebx,DWORD PTR [ebp-0x10]
  41c76e:	8b b7 48 8e 00 00    	mov    esi,DWORD PTR [edi+0x8e48]
  41c774:	66 89 9c b7 48 0e 00 	mov    WORD PTR [edi+esi*4+0xe48],bx
  41c77b:	00
  41c77c:	0f b6 11             	movzx  edx,BYTE PTR [ecx]
  41c77f:	88 d0                	mov    al,dl
  41c781:	2c 61                	sub    al,0x61
  41c783:	3c 05                	cmp    al,0x5
  41c785:	0f 86 05 ff ff ff    	jbe    41c690 <bixby110downloader::LoadHex(char*)+0x1d0>
  41c78b:	88 d0                	mov    al,dl
  41c78d:	2c 41                	sub    al,0x41
  41c78f:	3c 05                	cmp    al,0x5
  41c791:	0f 87 df 00 00 00    	ja     41c876 <bixby110downloader::LoadHex(char*)+0x3b6>
  41c797:	80 ea 37             	sub    dl,0x37
  41c79a:	0f be fa             	movsx  edi,dl
  41c79d:	89 fb                	mov    ebx,edi
  41c79f:	0f b6 51 01          	movzx  edx,BYTE PTR [ecx+0x1]
  41c7a3:	c1 e3 04             	shl    ebx,0x4
  41c7a6:	88 d1                	mov    cl,dl
  41c7a8:	80 e9 61             	sub    cl,0x61
  41c7ab:	80 f9 05             	cmp    cl,0x5
  41c7ae:	0f 86 f9 fe ff ff    	jbe    41c6ad <bixby110downloader::LoadHex(char*)+0x1ed>
  41c7b4:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  41c7ba:	8d bf 00 00 00 00    	lea    edi,[edi+0x0]
  41c7c0:	88 d0                	mov    al,dl
  41c7c2:	2c 41                	sub    al,0x41
  41c7c4:	3c 05                	cmp    al,0x5
  41c7c6:	0f 87 c4 00 00 00    	ja     41c890 <bixby110downloader::LoadHex(char*)+0x3d0>
  41c7cc:	80 ea 37             	sub    dl,0x37
  41c7cf:	e9 dc fe ff ff       	jmp    41c6b0 <bixby110downloader::LoadHex(char*)+0x1f0>
  41c7d4:	88 d0                	mov    al,dl
  41c7d6:	2c 41                	sub    al,0x41
  41c7d8:	3c 05                	cmp    al,0x5
  41c7da:	0f 87 a0 00 00 00    	ja     41c880 <bixby110downloader::LoadHex(char*)+0x3c0>
  41c7e0:	80 ea 37             	sub    dl,0x37
  41c7e3:	0f be ca             	movsx  ecx,dl
  41c7e6:	8d 14 0b             	lea    edx,[ebx+ecx*1]
  41c7e9:	8b 4d d8             	mov    ecx,DWORD PTR [ebp-0x28]
  41c7ec:	88 94 b1 4a 0e 00 00 	mov    BYTE PTR [ecx+esi*4+0xe4a],dl
  41c7f3:	8b 91 48 8e 00 00    	mov    edx,DWORD PTR [ecx+0x8e48]
  41c7f9:	80 bc 91 4a 0e 00 00 	cmp    BYTE PTR [ecx+edx*4+0xe4a],0x3f
  41c800:	3f
  41c801:	0f 86 24 ff ff ff    	jbe    41c72b <bixby110downloader::LoadHex(char*)+0x26b>
  41c807:	8b 5d d8             	mov    ebx,DWORD PTR [ebp-0x28]
  41c80a:	b9 42 61 64 20       	mov    ecx,0x20646142
  41c80f:	b8 48 45 58 20       	mov    eax,0x20584548
  41c814:	ba 66 69 6c 65       	mov    edx,0x656c6966
  41c819:	be 20 66 6f 72       	mov    esi,0x726f6620
  41c81e:	bf 6d 61 74 00       	mov    edi,0x74616d
  41c823:	89 8b ce 8e 00 00    	mov    DWORD PTR [ebx+0x8ece],ecx
  41c829:	89 d9                	mov    ecx,ebx
  41c82b:	81 c1 ce 8e 00 00    	add    ecx,0x8ece
  41c831:	89 83 d2 8e 00 00    	mov    DWORD PTR [ebx+0x8ed2],eax
  41c837:	89 93 d6 8e 00 00    	mov    DWORD PTR [ebx+0x8ed6],edx
  41c83d:	89 b3 da 8e 00 00    	mov    DWORD PTR [ebx+0x8eda],esi
  41c843:	89 bb de 8e 00 00    	mov    DWORD PTR [ebx+0x8ede],edi
  41c849:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41c84d:	8b 43 7c             	mov    eax,DWORD PTR [ebx+0x7c]
  41c850:	89 04 24             	mov    DWORD PTR [esp],eax
  41c853:	e8 c8 36 00 00       	call   41ff20 <edit::Settext(char const*)>
  41c858:	31 d2                	xor    edx,edx
  41c85a:	8d 65 f4             	lea    esp,[ebp-0xc]
  41c85d:	89 d0                	mov    eax,edx
  41c85f:	5b                   	pop    ebx
  41c860:	5e                   	pop    esi
  41c861:	5f                   	pop    edi
  41c862:	5d                   	pop    ebp
  41c863:	c3                   	ret
  41c864:	88 d3                	mov    bl,dl
  41c866:	80 eb 41             	sub    bl,0x41
  41c869:	80 fb 05             	cmp    bl,0x5
  41c86c:	77 1a                	ja     41c888 <bixby110downloader::LoadHex(char*)+0x3c8>
  41c86e:	80 ea 37             	sub    dl,0x37
  41c871:	e9 74 fe ff ff       	jmp    41c6ea <bixby110downloader::LoadHex(char*)+0x22a>
  41c876:	80 ea 30             	sub    dl,0x30
  41c879:	e9 15 fe ff ff       	jmp    41c693 <bixby110downloader::LoadHex(char*)+0x1d3>
  41c87e:	89 f6                	mov    esi,esi
  41c880:	80 ea 30             	sub    dl,0x30
  41c883:	e9 7f fe ff ff       	jmp    41c707 <bixby110downloader::LoadHex(char*)+0x247>
  41c888:	80 ea 30             	sub    dl,0x30
  41c88b:	e9 5a fe ff ff       	jmp    41c6ea <bixby110downloader::LoadHex(char*)+0x22a>
  41c890:	80 ea 30             	sub    dl,0x30
  41c893:	e9 18 fe ff ff       	jmp    41c6b0 <bixby110downloader::LoadHex(char*)+0x1f0>
  41c898:	88 d0                	mov    al,dl
  41c89a:	2c 41                	sub    al,0x41
  41c89c:	3c 05                	cmp    al,0x5
  41c89e:	0f 87 ca 00 00 00    	ja     41c96e <bixby110downloader::LoadHex(char*)+0x4ae>
  41c8a4:	80 ea 37             	sub    dl,0x37
  41c8a7:	e9 7f fd ff ff       	jmp    41c62b <bixby110downloader::LoadHex(char*)+0x16b>
  41c8ac:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
  41c8b0:	88 d3                	mov    bl,dl
  41c8b2:	80 eb 41             	sub    bl,0x41
  41c8b5:	80 fb 05             	cmp    bl,0x5
  41c8b8:	0f 87 a8 00 00 00    	ja     41c966 <bixby110downloader::LoadHex(char*)+0x4a6>
  41c8be:	80 ea 37             	sub    dl,0x37
  41c8c1:	e9 4a fd ff ff       	jmp    41c610 <bixby110downloader::LoadHex(char*)+0x150>
  41c8c6:	88 d0                	mov    al,dl
  41c8c8:	2c 41                	sub    al,0x41
  41c8ca:	3c 05                	cmp    al,0x5
  41c8cc:	0f 87 8c 00 00 00    	ja     41c95e <bixby110downloader::LoadHex(char*)+0x49e>
  41c8d2:	80 ea 37             	sub    dl,0x37
  41c8d5:	e9 08 fd ff ff       	jmp    41c5e2 <bixby110downloader::LoadHex(char*)+0x122>
  41c8da:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  41c8e0:	88 d0                	mov    al,dl
  41c8e2:	2c 41                	sub    al,0x41
  41c8e4:	3c 05                	cmp    al,0x5
  41c8e6:	77 6e                	ja     41c956 <bixby110downloader::LoadHex(char*)+0x496>
  41c8e8:	80 ea 37             	sub    dl,0x37
  41c8eb:	e9 d4 fc ff ff       	jmp    41c5c4 <bixby110downloader::LoadHex(char*)+0x104>
  41c8f0:	88 d0                	mov    al,dl
  41c8f2:	2c 41                	sub    al,0x41
  41c8f4:	3c 05                	cmp    al,0x5
  41c8f6:	77 56                	ja     41c94e <bixby110downloader::LoadHex(char*)+0x48e>
  41c8f8:	80 ea 37             	sub    dl,0x37
  41c8fb:	e9 a3 fc ff ff       	jmp    41c5a3 <bixby110downloader::LoadHex(char*)+0xe3>
  41c900:	88 d1                	mov    cl,dl
  41c902:	80 e9 41             	sub    cl,0x41
  41c905:	80 f9 05             	cmp    cl,0x5
  41c908:	77 3c                	ja     41c946 <bixby110downloader::LoadHex(char*)+0x486>
  41c90a:	80 ea 37             	sub    dl,0x37
  41c90d:	e9 76 fc ff ff       	jmp    41c588 <bixby110downloader::LoadHex(char*)+0xc8>
  41c912:	88 d3                	mov    bl,dl
  41c914:	80 eb 41             	sub    bl,0x41
  41c917:	80 fb 05             	cmp    bl,0x5
  41c91a:	77 22                	ja     41c93e <bixby110downloader::LoadHex(char*)+0x47e>
  41c91c:	80 ea 37             	sub    dl,0x37
  41c91f:	e9 35 fc ff ff       	jmp    41c559 <bixby110downloader::LoadHex(char*)+0x99>
  41c924:	88 d1                	mov    cl,dl
  41c926:	80 e9 41             	sub    cl,0x41
  41c929:	80 f9 05             	cmp    cl,0x5
  41c92c:	77 08                	ja     41c936 <bixby110downloader::LoadHex(char*)+0x476>
  41c92e:	80 ea 37             	sub    dl,0x37
  41c931:	e9 05 fc ff ff       	jmp    41c53b <bixby110downloader::LoadHex(char*)+0x7b>
  41c936:	80 ea 30             	sub    dl,0x30
  41c939:	e9 fd fb ff ff       	jmp    41c53b <bixby110downloader::LoadHex(char*)+0x7b>
  41c93e:	80 ea 30             	sub    dl,0x30
  41c941:	e9 13 fc ff ff       	jmp    41c559 <bixby110downloader::LoadHex(char*)+0x99>
  41c946:	80 ea 30             	sub    dl,0x30
  41c949:	e9 3a fc ff ff       	jmp    41c588 <bixby110downloader::LoadHex(char*)+0xc8>
  41c94e:	80 ea 30             	sub    dl,0x30
  41c951:	e9 4d fc ff ff       	jmp    41c5a3 <bixby110downloader::LoadHex(char*)+0xe3>
  41c956:	80 ea 30             	sub    dl,0x30
  41c959:	e9 66 fc ff ff       	jmp    41c5c4 <bixby110downloader::LoadHex(char*)+0x104>
  41c95e:	80 ea 30             	sub    dl,0x30
  41c961:	e9 7c fc ff ff       	jmp    41c5e2 <bixby110downloader::LoadHex(char*)+0x122>
  41c966:	80 ea 30             	sub    dl,0x30
  41c969:	e9 a2 fc ff ff       	jmp    41c610 <bixby110downloader::LoadHex(char*)+0x150>
  41c96e:	80 ea 30             	sub    dl,0x30
  41c971:	e9 b5 fc ff ff       	jmp    41c62b <bixby110downloader::LoadHex(char*)+0x16b>
  41c976:	8b 7d d8             	mov    edi,DWORD PTR [ebp-0x28]
  41c979:	be 00 20 00 00       	mov    esi,0x2000
  41c97e:	bb e4 53 45 00       	mov    ebx,0x4553e4
  41c983:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  41c987:	be fc 53 45 00       	mov    esi,0x4553fc
  41c98c:	8b 8f 48 8e 00 00    	mov    ecx,DWORD PTR [edi+0x8e48]
  41c992:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41c996:	89 fb                	mov    ebx,edi
  41c998:	81 c3 ce 8e 00 00    	add    ebx,0x8ece
  41c99e:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41c9a2:	89 df                	mov    edi,ebx
  41c9a4:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41c9a7:	e8 d4 29 01 00       	call   42f380 <sprintf>
  41c9ac:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41c9b0:	31 c0                	xor    eax,eax
  41c9b2:	ba 26 54 45 00       	mov    edx,0x455426
  41c9b7:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  41c9bb:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  41c9bf:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  41c9c6:	e8 a5 2b 01 00       	call   42f570 <MessageBoxA@16>
  41c9cb:	fc                   	cld
  41c9cc:	b9 0a 00 00 00       	mov    ecx,0xa
  41c9d1:	83 ec 10             	sub    esp,0x10
  41c9d4:	f3 a5                	rep movs DWORD PTR es:[edi],DWORD PTR ds:[esi]
  41c9d6:	89 fe                	mov    esi,edi
  41c9d8:	0f b7 3d 24 54 45 00 	movzx  edi,WORD PTR ds:0x455424
  41c9df:	66 89 3e             	mov    WORD PTR [esi],di
  41c9e2:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41c9e6:	8b 55 d8             	mov    edx,DWORD PTR [ebp-0x28]
  41c9e9:	8b 42 7c             	mov    eax,DWORD PTR [edx+0x7c]
  41c9ec:	e9 5f fe ff ff       	jmp    41c850 <bixby110downloader::LoadHex(char*)+0x390>
  41c9f1:	8b 55 d8             	mov    edx,DWORD PTR [ebp-0x28]
  41c9f4:	0f b6 82 cc 03 00 00 	movzx  eax,BYTE PTR [edx+0x3cc]
  41c9fb:	84 c0                	test   al,al
  41c9fd:	0f 84 f5 00 00 00    	je     41caf8 <bixby110downloader::LoadHex(char*)+0x638>
  41ca03:	fe c8                	dec    al
  41ca05:	0f 85 4d fe ff ff    	jne    41c858 <bixby110downloader::LoadHex(char*)+0x398>
  41ca0b:	8b 5d d8             	mov    ebx,DWORD PTR [ebp-0x28]
  41ca0e:	8b 83 e8 04 00 00    	mov    eax,DWORD PTR [ebx+0x4e8]
  41ca14:	89 04 24             	mov    DWORD PTR [esp],eax
  41ca17:	e8 d4 2d 01 00       	call   42f7f0 <CloseHandle@4>
  41ca1c:	83 ec 04             	sub    esp,0x4
  41ca1f:	31 d2                	xor    edx,edx
  41ca21:	e9 34 fe ff ff       	jmp    41c85a <bixby110downloader::LoadHex(char*)+0x39a>
  41ca26:	fc                   	cld
  41ca27:	8b 55 d8             	mov    edx,DWORD PTR [ebp-0x28]
  41ca2a:	be 30 54 45 00       	mov    esi,0x455430
  41ca2f:	8b 45 e0             	mov    eax,DWORD PTR [ebp-0x20]
  41ca32:	b9 0c 00 00 00       	mov    ecx,0xc
  41ca37:	89 d3                	mov    ebx,edx
  41ca39:	89 82 e0 04 00 00    	mov    DWORD PTR [edx+0x4e0],eax
  41ca3f:	81 c3 ce 8e 00 00    	add    ebx,0x8ece
  41ca45:	89 df                	mov    edi,ebx
  41ca47:	f3 a5                	rep movs DWORD PTR es:[edi],DWORD PTR ds:[esi]
  41ca49:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41ca4d:	eb 97                	jmp    41c9e6 <bixby110downloader::LoadHex(char*)+0x526>
  41ca4f:	0f b6 87 cc 03 00 00 	movzx  eax,BYTE PTR [edi+0x3cc]
  41ca56:	84 c0                	test   al,al
  41ca58:	0f 84 80 00 00 00    	je     41cade <bixby110downloader::LoadHex(char*)+0x61e>
  41ca5e:	fe c8                	dec    al
  41ca60:	74 0a                	je     41ca6c <bixby110downloader::LoadHex(char*)+0x5ac>
  41ca62:	ba 01 00 00 00       	mov    edx,0x1
  41ca67:	e9 ee fd ff ff       	jmp    41c85a <bixby110downloader::LoadHex(char*)+0x39a>
  41ca6c:	8b 55 d8             	mov    edx,DWORD PTR [ebp-0x28]
  41ca6f:	8b 9a e8 04 00 00    	mov    ebx,DWORD PTR [edx+0x4e8]
  41ca75:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41ca78:	e8 73 2d 01 00       	call   42f7f0 <CloseHandle@4>
  41ca7d:	83 ec 04             	sub    esp,0x4
  41ca80:	ba 01 00 00 00       	mov    edx,0x1
  41ca85:	e9 d0 fd ff ff       	jmp    41c85a <bixby110downloader::LoadHex(char*)+0x39a>
  41ca8a:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41ca8e:	8b 7d d8             	mov    edi,DWORD PTR [ebp-0x28]
  41ca91:	b9 60 54 45 00       	mov    ecx,0x455460
  41ca96:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41ca9a:	81 c7 ce 8e 00 00    	add    edi,0x8ece
  41caa0:	89 3c 24             	mov    DWORD PTR [esp],edi
  41caa3:	e8 d8 28 01 00       	call   42f380 <sprintf>
  41caa8:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  41caac:	8b 45 d8             	mov    eax,DWORD PTR [ebp-0x28]
  41caaf:	8b 70 7c             	mov    esi,DWORD PTR [eax+0x7c]
  41cab2:	89 34 24             	mov    DWORD PTR [esp],esi
  41cab5:	e8 66 34 00 00       	call   41ff20 <edit::Settext(char const*)>
  41caba:	8b 7d d8             	mov    edi,DWORD PTR [ebp-0x28]
  41cabd:	0f b6 87 cc 03 00 00 	movzx  eax,BYTE PTR [edi+0x3cc]
  41cac4:	84 c0                	test   al,al
  41cac6:	74 4d                	je     41cb15 <bixby110downloader::LoadHex(char*)+0x655>
  41cac8:	fe c8                	dec    al
  41caca:	0f 85 88 fd ff ff    	jne    41c858 <bixby110downloader::LoadHex(char*)+0x398>
  41cad0:	8b 55 d8             	mov    edx,DWORD PTR [ebp-0x28]
  41cad3:	8b 82 e8 04 00 00    	mov    eax,DWORD PTR [edx+0x4e8]
  41cad9:	e9 36 ff ff ff       	jmp    41ca14 <bixby110downloader::LoadHex(char*)+0x554>
  41cade:	8b 8f e4 04 00 00    	mov    ecx,DWORD PTR [edi+0x4e4]
  41cae4:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41cae7:	e8 14 29 01 00       	call   42f400 <fclose>
  41caec:	0f b6 87 cc 03 00 00 	movzx  eax,BYTE PTR [edi+0x3cc]
  41caf3:	e9 66 ff ff ff       	jmp    41ca5e <bixby110downloader::LoadHex(char*)+0x59e>
  41caf8:	8b b2 e4 04 00 00    	mov    esi,DWORD PTR [edx+0x4e4]
  41cafe:	89 34 24             	mov    DWORD PTR [esp],esi
  41cb01:	e8 fa 28 01 00       	call   42f400 <fclose>
  41cb06:	8b 4d d8             	mov    ecx,DWORD PTR [ebp-0x28]
  41cb09:	0f b6 81 cc 03 00 00 	movzx  eax,BYTE PTR [ecx+0x3cc]
  41cb10:	e9 ee fe ff ff       	jmp    41ca03 <bixby110downloader::LoadHex(char*)+0x543>
  41cb15:	8b 9f e4 04 00 00    	mov    ebx,DWORD PTR [edi+0x4e4]
  41cb1b:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41cb1e:	e8 dd 28 01 00       	call   42f400 <fclose>
  41cb23:	0f b6 87 cc 03 00 00 	movzx  eax,BYTE PTR [edi+0x3cc]
  41cb2a:	eb 9c                	jmp    41cac8 <bixby110downloader::LoadHex(char*)+0x608>
  41cb2c:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]

# source=Bixby110Downloader.cpp
# va=0x0041CB30 size=0x500
0x0041CB30 <bixby110downloader::DownLoad()>:
  41cb30:	55                   	push   ebp
  41cb31:	89 e5                	mov    ebp,esp
  41cb33:	57                   	push   edi
  41cb34:	56                   	push   esi
  41cb35:	53                   	push   ebx
  41cb36:	83 ec 6c             	sub    esp,0x6c
  41cb39:	8b 7d 08             	mov    edi,DWORD PTR [ebp+0x8]
  41cb3c:	8b 97 88 00 00 00    	mov    edx,DWORD PTR [edi+0x88]
  41cb42:	8d b7 fc 05 00 00    	lea    esi,[edi+0x5fc]
  41cb48:	89 14 24             	mov    DWORD PTR [esp],edx
  41cb4b:	e8 00 29 00 00       	call   41f450 <manual3checkbox::IsChecked()>
  41cb50:	84 c0                	test   al,al
  41cb52:	0f 95 c0             	setne  al
  41cb55:	31 db                	xor    ebx,ebx
  41cb57:	88 87 8c 00 00 00    	mov    BYTE PTR [edi+0x8c],al
  41cb5d:	c6 45 c7 01          	mov    BYTE PTR [ebp-0x39],0x1
  41cb61:	89 34 24             	mov    DWORD PTR [esp],esi
  41cb64:	8d 55 c7             	lea    edx,[ebp-0x39]
  41cb67:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41cb6b:	e8 40 cd fe ff       	call   4098b0 <bixby110io::status_read_char(unsigned char*)>
  41cb70:	84 c0                	test   al,al
  41cb72:	0f 94 c1             	sete   cl
  41cb75:	0f b6 c1             	movzx  eax,cl
  41cb78:	3c 01                	cmp    al,0x1
  41cb7a:	14 00                	adc    al,0x0
  41cb7c:	43                   	inc    ebx
  41cb7d:	83 fb 63             	cmp    ebx,0x63
  41cb80:	0f 97 c2             	seta   dl
  41cb83:	3c 09                	cmp    al,0x9
  41cb85:	0f 97 c1             	seta   cl
  41cb88:	08 ca                	or     dl,cl
  41cb8a:	75 06                	jne    41cb92 <bixby110downloader::DownLoad()+0x62>
  41cb8c:	80 7d c7 00          	cmp    BYTE PTR [ebp-0x39],0x0
  41cb90:	75 cf                	jne    41cb61 <bixby110downloader::DownLoad()+0x31>
  41cb92:	c7 45 b8 00 00 00 00 	mov    DWORD PTR [ebp-0x48],0x0
  41cb99:	8b 9f 48 8e 00 00    	mov    ebx,DWORD PTR [edi+0x8e48]
  41cb9f:	c6 45 aa 00          	mov    BYTE PTR [ebp-0x56],0x0
  41cba3:	83 fb 00             	cmp    ebx,0x0
  41cba6:	0f 86 51 04 00 00    	jbe    41cffd <bixby110downloader::DownLoad()+0x4cd>
  41cbac:	c7 45 9c 00 00 00 00 	mov    DWORD PTR [ebp-0x64],0x0
  41cbb3:	8d 87 fc 05 00 00    	lea    eax,[edi+0x5fc]
  41cbb9:	8d b7 ce 8e 00 00    	lea    esi,[edi+0x8ece]
  41cbbf:	89 45 98             	mov    DWORD PTR [ebp-0x68],eax
  41cbc2:	89 75 a0             	mov    DWORD PTR [ebp-0x60],esi
  41cbc5:	3b 5d b8             	cmp    ebx,DWORD PTR [ebp-0x48]
  41cbc8:	8d 4d c8             	lea    ecx,[ebp-0x38]
  41cbcb:	c7 45 b0 00 00 00 00 	mov    DWORD PTR [ebp-0x50],0x0
  41cbd2:	8b 55 b8             	mov    edx,DWORD PTR [ebp-0x48]
  41cbd5:	c6 45 bf 00          	mov    BYTE PTR [ebp-0x41],0x0
  41cbd9:	0f b7 b4 97 48 0e 00 	movzx  esi,WORD PTR [edi+edx*4+0xe48]
  41cbe0:	00
  41cbe1:	89 f2                	mov    edx,esi
  41cbe3:	89 75 b4             	mov    DWORD PTR [ebp-0x4c],esi
  41cbe6:	76 54                	jbe    41cc3c <bixby110downloader::DownLoad()+0x10c>
  41cbe8:	8b 75 b8             	mov    esi,DWORD PTR [ebp-0x48]
  41cbeb:	42                   	inc    edx
  41cbec:	0f b6 84 b7 4a 0e 00 	movzx  eax,BYTE PTR [edi+esi*4+0xe4a]
  41cbf3:	00
  41cbf4:	88 01                	mov    BYTE PTR [ecx],al
  41cbf6:	0f b6 84 b7 4b 0e 00 	movzx  eax,BYTE PTR [edi+esi*4+0xe4b]
  41cbfd:	00
  41cbfe:	88 41 01             	mov    BYTE PTR [ecx+0x1],al
  41cc01:	83 c1 02             	add    ecx,0x2
  41cc04:	0f b6 84 b7 4a 0e 00 	movzx  eax,BYTE PTR [edi+esi*4+0xe4a]
  41cc0b:	00
  41cc0c:	00 45 bf             	add    BYTE PTR [ebp-0x41],al
  41cc0f:	0f b6 84 b7 4b 0e 00 	movzx  eax,BYTE PTR [edi+esi*4+0xe4b]
  41cc16:	00
  41cc17:	46                   	inc    esi
  41cc18:	83 45 b0 02          	add    DWORD PTR [ebp-0x50],0x2
  41cc1c:	00 45 bf             	add    BYTE PTR [ebp-0x41],al
  41cc1f:	0f b7 84 b7 48 0e 00 	movzx  eax,WORD PTR [edi+esi*4+0xe48]
  41cc26:	00
  41cc27:	83 45 9c 64          	add    DWORD PTR [ebp-0x64],0x64
  41cc2b:	89 75 b8             	mov    DWORD PTR [ebp-0x48],esi
  41cc2e:	39 d0                	cmp    eax,edx
  41cc30:	75 0a                	jne    41cc3c <bixby110downloader::DownLoad()+0x10c>
  41cc32:	83 7d b0 1f          	cmp    DWORD PTR [ebp-0x50],0x1f
  41cc36:	77 04                	ja     41cc3c <bixby110downloader::DownLoad()+0x10c>
  41cc38:	39 f3                	cmp    ebx,esi
  41cc3a:	77 ac                	ja     41cbe8 <bixby110downloader::DownLoad()+0xb8>
  41cc3c:	c7 45 ac 00 00 00 00 	mov    DWORD PTR [ebp-0x54],0x0
  41cc43:	80 bf 8c 00 00 00 00 	cmp    BYTE PTR [edi+0x8c],0x0
  41cc4a:	0f 84 b5 03 00 00    	je     41d005 <bixby110downloader::DownLoad()+0x4d5>
  41cc50:	bb 0a 00 00 00       	mov    ebx,0xa
  41cc55:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41cc59:	c7 04 24 f4 01 00 00 	mov    DWORD PTR [esp],0x1f4
  41cc60:	e8 fb 2b 01 00       	call   42f860 <Beep@8>
  41cc65:	0f be 75 bf          	movsx  esi,BYTE PTR [ebp-0x41]
  41cc69:	83 ec 08             	sub    esp,0x8
  41cc6c:	c6 45 ab 14          	mov    BYTE PTR [ebp-0x55],0x14
  41cc70:	89 75 a4             	mov    DWORD PTR [ebp-0x5c],esi
  41cc73:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  41cc79:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  41cc80:	c6 45 c7 00          	mov    BYTE PTR [ebp-0x39],0x0
  41cc84:	8b 4d a0             	mov    ecx,DWORD PTR [ebp-0x60]
  41cc87:	bb 89 54 45 00       	mov    ebx,0x455489
  41cc8c:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41cc90:	8b 45 b4             	mov    eax,DWORD PTR [ebp-0x4c]
  41cc93:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41cc96:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41cc9a:	e8 e1 26 01 00       	call   42f380 <sprintf>
  41cc9f:	8b 5d a0             	mov    ebx,DWORD PTR [ebp-0x60]
  41cca2:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41cca6:	8b 77 70             	mov    esi,DWORD PTR [edi+0x70]
  41cca9:	89 34 24             	mov    DWORD PTR [esp],esi
  41ccac:	be e3 ff ff ff       	mov    esi,0xffffffe3
  41ccb1:	e8 6a 32 00 00       	call   41ff20 <edit::Settext(char const*)>
  41ccb6:	0f b6 55 bf          	movzx  edx,BYTE PTR [ebp-0x41]
  41ccba:	b8 8e 54 45 00       	mov    eax,0x45548e
  41ccbf:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41ccc2:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41ccc6:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  41ccca:	e8 b1 26 01 00       	call   42f380 <sprintf>
  41cccf:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41ccd3:	8b 4f 78             	mov    ecx,DWORD PTR [edi+0x78]
  41ccd6:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41ccd9:	e8 42 32 00 00       	call   41ff20 <edit::Settext(char const*)>
  41ccde:	c6 87 4d 8e 00 00 e3 	mov    BYTE PTR [edi+0x8e4d],0xe3
  41cce5:	8b 55 98             	mov    edx,DWORD PTR [ebp-0x68]
  41cce8:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41ccec:	89 14 24             	mov    DWORD PTR [esp],edx
  41ccef:	e8 4c cb fe ff       	call   409840 <bixby110io::write_char(char)>
  41ccf4:	8b 45 b4             	mov    eax,DWORD PTR [ebp-0x4c]
  41ccf7:	c1 e8 08             	shr    eax,0x8
  41ccfa:	0f be c8             	movsx  ecx,al
  41ccfd:	88 87 4d 8e 00 00    	mov    BYTE PTR [edi+0x8e4d],al
  41cd03:	8b 75 98             	mov    esi,DWORD PTR [ebp-0x68]
  41cd06:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41cd0a:	89 34 24             	mov    DWORD PTR [esp],esi
  41cd0d:	e8 2e cb fe ff       	call   409840 <bixby110io::write_char(char)>
  41cd12:	0f b6 45 b4          	movzx  eax,BYTE PTR [ebp-0x4c]
  41cd16:	0f be d8             	movsx  ebx,al
  41cd19:	88 87 4d 8e 00 00    	mov    BYTE PTR [edi+0x8e4d],al
  41cd1f:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41cd23:	8b 5d 98             	mov    ebx,DWORD PTR [ebp-0x68]
  41cd26:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41cd29:	e8 12 cb fe ff       	call   409840 <bixby110io::write_char(char)>
  41cd2e:	0f b6 45 b0          	movzx  eax,BYTE PTR [ebp-0x50]
  41cd32:	0f be f0             	movsx  esi,al
  41cd35:	88 87 4d 8e 00 00    	mov    BYTE PTR [edi+0x8e4d],al
  41cd3b:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41cd3e:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41cd42:	e8 f9 ca fe ff       	call   409840 <bixby110io::write_char(char)>
  41cd47:	0f b6 55 bf          	movzx  edx,BYTE PTR [ebp-0x41]
  41cd4b:	88 97 4d 8e 00 00    	mov    BYTE PTR [edi+0x8e4d],dl
  41cd51:	8b 4d a4             	mov    ecx,DWORD PTR [ebp-0x5c]
  41cd54:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41cd57:	31 db                	xor    ebx,ebx
  41cd59:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41cd5d:	e8 de ca fe ff       	call   409840 <bixby110io::write_char(char)>
  41cd62:	0f b6 87 c9 03 00 00 	movzx  eax,BYTE PTR [edi+0x3c9]
  41cd69:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41cd6d:	8b 17                	mov    edx,DWORD PTR [edi]
  41cd6f:	89 14 24             	mov    DWORD PTR [esp],edx
  41cd72:	e8 c9 b0 fe ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  41cd77:	c6 87 ce 8e 00 00 00 	mov    BYTE PTR [edi+0x8ece],0x0
  41cd7e:	3b 5d b0             	cmp    ebx,DWORD PTR [ebp-0x50]
  41cd81:	0f 83 89 00 00 00    	jae    41ce10 <bixby110downloader::DownLoad()+0x2e0>
  41cd87:	8d b7 ce 8f 00 00    	lea    esi,[edi+0x8fce]
  41cd8d:	eb 07                	jmp    41cd96 <bixby110downloader::DownLoad()+0x266>
  41cd8f:	90                   	nop
  41cd90:	43                   	inc    ebx
  41cd91:	3b 5d b0             	cmp    ebx,DWORD PTR [ebp-0x50]
  41cd94:	73 7a                	jae    41ce10 <bixby110downloader::DownLoad()+0x2e0>
  41cd96:	0f b6 44 2b c8       	movzx  eax,BYTE PTR [ebx+ebp*1-0x38]
  41cd9b:	b9 8e 54 45 00       	mov    ecx,0x45548e
  41cda0:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41cda4:	89 34 24             	mov    DWORD PTR [esp],esi
  41cda7:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41cdab:	e8 d0 25 01 00       	call   42f380 <sprintf>
  41cdb0:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41cdb4:	8b 55 a0             	mov    edx,DWORD PTR [ebp-0x60]
  41cdb7:	89 14 24             	mov    DWORD PTR [esp],edx
  41cdba:	e8 21 26 01 00       	call   42f3e0 <strcat>
  41cdbf:	0f be 44 2b c8       	movsx  eax,BYTE PTR [ebx+ebp*1-0x38]
  41cdc4:	88 87 4d 8e 00 00    	mov    BYTE PTR [edi+0x8e4d],al
  41cdca:	8b 4d 98             	mov    ecx,DWORD PTR [ebp-0x68]
  41cdcd:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41cdd1:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41cdd4:	e8 67 ca fe ff       	call   409840 <bixby110io::write_char(char)>
  41cdd9:	0f b6 97 cb 03 00 00 	movzx  edx,BYTE PTR [edi+0x3cb]
  41cde0:	00 55 aa             	add    BYTE PTR [ebp-0x56],dl
  41cde3:	80 7d aa 63          	cmp    BYTE PTR [ebp-0x56],0x63
  41cde7:	76 a7                	jbe    41cd90 <bixby110downloader::DownLoad()+0x260>
  41cde9:	80 6d aa 64          	sub    BYTE PTR [ebp-0x56],0x64
  41cded:	b9 01 00 00 00       	mov    ecx,0x1
  41cdf2:	43                   	inc    ebx
  41cdf3:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41cdf7:	8b 17                	mov    edx,DWORD PTR [edi]
  41cdf9:	89 14 24             	mov    DWORD PTR [esp],edx
  41cdfc:	e8 3f b0 fe ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  41ce01:	3b 5d b0             	cmp    ebx,DWORD PTR [ebp-0x50]
  41ce04:	72 90                	jb     41cd96 <bixby110downloader::DownLoad()+0x266>
  41ce06:	8d 76 00             	lea    esi,[esi+0x0]
  41ce09:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  41ce10:	8b 5d a0             	mov    ebx,DWORD PTR [ebp-0x60]
  41ce13:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41ce17:	8b 77 74             	mov    esi,DWORD PTR [edi+0x74]
  41ce1a:	89 34 24             	mov    DWORD PTR [esp],esi
  41ce1d:	e8 fe 30 00 00       	call   41ff20 <edit::Settext(char const*)>
  41ce22:	0f b6 5d ab          	movzx  ebx,BYTE PTR [ebp-0x55]
  41ce26:	eb 16                	jmp    41ce3e <bixby110downloader::DownLoad()+0x30e>
  41ce28:	8b 45 98             	mov    eax,DWORD PTR [ebp-0x68]
  41ce2b:	8d 55 c7             	lea    edx,[ebp-0x39]
  41ce2e:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41ce32:	89 04 24             	mov    DWORD PTR [esp],eax
  41ce35:	e8 76 ca fe ff       	call   4098b0 <bixby110io::status_read_char(unsigned char*)>
  41ce3a:	84 c0                	test   al,al
  41ce3c:	74 07                	je     41ce45 <bixby110downloader::DownLoad()+0x315>
  41ce3e:	fe cb                	dec    bl
  41ce40:	80 fb ff             	cmp    bl,0xff
  41ce43:	75 e3                	jne    41ce28 <bixby110downloader::DownLoad()+0x2f8>
  41ce45:	83 7d ac 1d          	cmp    DWORD PTR [ebp-0x54],0x1d
  41ce49:	0f 8f ae 01 00 00    	jg     41cffd <bixby110downloader::DownLoad()+0x4cd>
  41ce4f:	8b 4f 68             	mov    ecx,DWORD PTR [edi+0x68]
  41ce52:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41ce55:	e8 26 2c 00 00       	call   41fa80 <pushbutton::WasPushed()>
  41ce5a:	85 c0                	test   eax,eax
  41ce5c:	74 07                	je     41ce65 <bixby110downloader::DownLoad()+0x335>
  41ce5e:	c7 45 ac 1e 00 00 00 	mov    DWORD PTR [ebp-0x54],0x1e
  41ce65:	80 7d c7 e7          	cmp    BYTE PTR [ebp-0x39],0xe7
  41ce69:	0f 84 80 00 00 00    	je     41ceef <bixby110downloader::DownLoad()+0x3bf>
  41ce6f:	ff 45 ac             	inc    DWORD PTR [ebp-0x54]
  41ce72:	0f b6 87 cb 03 00 00 	movzx  eax,BYTE PTR [edi+0x3cb]
  41ce79:	fe c0                	inc    al
  41ce7b:	3c 64                	cmp    al,0x64
  41ce7d:	0f 86 19 01 00 00    	jbe    41cf9c <bixby110downloader::DownLoad()+0x46c>
  41ce83:	c6 87 cb 03 00 00 64 	mov    BYTE PTR [edi+0x3cb],0x64
  41ce8a:	0f b6 97 cb 03 00 00 	movzx  edx,BYTE PTR [edi+0x3cb]
  41ce91:	b8 93 54 45 00       	mov    eax,0x455493
  41ce96:	8d 5d c0             	lea    ebx,[ebp-0x40]
  41ce99:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41ce9d:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41cea0:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  41cea4:	e8 d7 24 01 00       	call   42f380 <sprintf>
  41cea9:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41cead:	8b b7 c0 03 00 00    	mov    esi,DWORD PTR [edi+0x3c0]
  41ceb3:	89 34 24             	mov    DWORD PTR [esp],esi
  41ceb6:	e8 65 30 00 00       	call   41ff20 <edit::Settext(char const*)>
  41cebb:	80 bf 8c 00 00 00 00 	cmp    BYTE PTR [edi+0x8c],0x0
  41cec2:	0f 85 df 00 00 00    	jne    41cfa7 <bixby110downloader::DownLoad()+0x477>
  41cec8:	80 7d ab ea          	cmp    BYTE PTR [ebp-0x55],0xea
  41cecc:	77 04                	ja     41ced2 <bixby110downloader::DownLoad()+0x3a2>
  41cece:	80 45 ab 14          	add    BYTE PTR [ebp-0x55],0x14
  41ced2:	be 0a 00 00 00       	mov    esi,0xa
  41ced7:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41cedb:	c7 04 24 e8 03 00 00 	mov    DWORD PTR [esp],0x3e8
  41cee2:	e8 79 29 01 00       	call   42f860 <Beep@8>
  41cee7:	83 ec 08             	sub    esp,0x8
  41ceea:	e9 91 fd ff ff       	jmp    41cc80 <bixby110downloader::DownLoad()+0x150>
  41ceef:	b3 27                	mov    bl,0x27
  41cef1:	eb 07                	jmp    41cefa <bixby110downloader::DownLoad()+0x3ca>
  41cef3:	fe cb                	dec    bl
  41cef5:	80 fb ff             	cmp    bl,0xff
  41cef8:	74 16                	je     41cf10 <bixby110downloader::DownLoad()+0x3e0>
  41cefa:	8b 45 98             	mov    eax,DWORD PTR [ebp-0x68]
  41cefd:	8d 55 c7             	lea    edx,[ebp-0x39]
  41cf00:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41cf04:	89 04 24             	mov    DWORD PTR [esp],eax
  41cf07:	e8 a4 c9 fe ff       	call   4098b0 <bixby110io::status_read_char(unsigned char*)>
  41cf0c:	84 c0                	test   al,al
  41cf0e:	75 e3                	jne    41cef3 <bixby110downloader::DownLoad()+0x3c3>
  41cf10:	83 7d ac 1d          	cmp    DWORD PTR [ebp-0x54],0x1d
  41cf14:	0f 8f e3 00 00 00    	jg     41cffd <bixby110downloader::DownLoad()+0x4cd>
  41cf1a:	80 7d c7 e4          	cmp    BYTE PTR [ebp-0x39],0xe4
  41cf1e:	0f 84 95 00 00 00    	je     41cfb9 <bixby110downloader::DownLoad()+0x489>
  41cf24:	ff 45 ac             	inc    DWORD PTR [ebp-0x54]
  41cf27:	0f b6 87 cb 03 00 00 	movzx  eax,BYTE PTR [edi+0x3cb]
  41cf2e:	fe c0                	inc    al
  41cf30:	3c 64                	cmp    al,0x64
  41cf32:	0f 86 db 00 00 00    	jbe    41d013 <bixby110downloader::DownLoad()+0x4e3>
  41cf38:	c6 87 cb 03 00 00 64 	mov    BYTE PTR [edi+0x3cb],0x64
  41cf3f:	0f b6 87 cb 03 00 00 	movzx  eax,BYTE PTR [edi+0x3cb]
  41cf46:	b9 93 54 45 00       	mov    ecx,0x455493
  41cf4b:	8d 75 c0             	lea    esi,[ebp-0x40]
  41cf4e:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41cf52:	89 34 24             	mov    DWORD PTR [esp],esi
  41cf55:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41cf59:	e8 22 24 01 00       	call   42f380 <sprintf>
  41cf5e:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41cf62:	8b 9f c0 03 00 00    	mov    ebx,DWORD PTR [edi+0x3c0]
  41cf68:	89 1c 24             	mov    DWORD PTR [esp],ebx
  41cf6b:	e8 b0 2f 00 00       	call   41ff20 <edit::Settext(char const*)>
  41cf70:	80 bf 8c 00 00 00 00 	cmp    BYTE PTR [edi+0x8c],0x0
  41cf77:	0f 85 a1 00 00 00    	jne    41d01e <bixby110downloader::DownLoad()+0x4ee>
  41cf7d:	80 7d ab ea          	cmp    BYTE PTR [ebp-0x55],0xea
  41cf81:	77 04                	ja     41cf87 <bixby110downloader::DownLoad()+0x457>
  41cf83:	80 45 ab 14          	add    BYTE PTR [ebp-0x55],0x14
  41cf87:	bb 0a 00 00 00       	mov    ebx,0xa
  41cf8c:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41cf90:	c7 04 24 dc 05 00 00 	mov    DWORD PTR [esp],0x5dc
  41cf97:	e9 46 ff ff ff       	jmp    41cee2 <bixby110downloader::DownLoad()+0x3b2>
  41cf9c:	88 87 cb 03 00 00    	mov    BYTE PTR [edi+0x3cb],al
  41cfa2:	e9 e3 fe ff ff       	jmp    41ce8a <bixby110downloader::DownLoad()+0x35a>
  41cfa7:	c6 45 ab 3c          	mov    BYTE PTR [ebp-0x55],0x3c
  41cfab:	b9 01 00 00 00       	mov    ecx,0x1
  41cfb0:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41cfb4:	e9 22 ff ff ff       	jmp    41cedb <bixby110downloader::DownLoad()+0x3ab>
  41cfb9:	8b 45 9c             	mov    eax,DWORD PTR [ebp-0x64]
  41cfbc:	31 d2                	xor    edx,edx
  41cfbe:	f7 b7 48 8e 00 00    	div    DWORD PTR [edi+0x8e48]
  41cfc4:	ba 93 54 45 00       	mov    edx,0x455493
  41cfc9:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41cfcd:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41cfd1:	8b 45 a0             	mov    eax,DWORD PTR [ebp-0x60]
  41cfd4:	89 04 24             	mov    DWORD PTR [esp],eax
  41cfd7:	e8 a4 23 01 00       	call   42f380 <sprintf>
  41cfdc:	8b 4d a0             	mov    ecx,DWORD PTR [ebp-0x60]
  41cfdf:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41cfe3:	8b 77 6c             	mov    esi,DWORD PTR [edi+0x6c]
  41cfe6:	89 34 24             	mov    DWORD PTR [esp],esi
  41cfe9:	e8 32 2f 00 00       	call   41ff20 <edit::Settext(char const*)>
  41cfee:	8b 9f 48 8e 00 00    	mov    ebx,DWORD PTR [edi+0x8e48]
  41cff4:	3b 5d b8             	cmp    ebx,DWORD PTR [ebp-0x48]
  41cff7:	0f 87 c8 fb ff ff    	ja     41cbc5 <bixby110downloader::DownLoad()+0x95>
  41cffd:	8d 65 f4             	lea    esp,[ebp-0xc]
  41d000:	5b                   	pop    ebx
  41d001:	5e                   	pop    esi
  41d002:	5f                   	pop    edi
  41d003:	5d                   	pop    ebp
  41d004:	c3                   	ret
  41d005:	b9 01 00 00 00       	mov    ecx,0x1
  41d00a:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41d00e:	e9 46 fc ff ff       	jmp    41cc59 <bixby110downloader::DownLoad()+0x129>
  41d013:	88 87 cb 03 00 00    	mov    BYTE PTR [edi+0x3cb],al
  41d019:	e9 21 ff ff ff       	jmp    41cf3f <bixby110downloader::DownLoad()+0x40f>
  41d01e:	c6 45 ab 3c          	mov    BYTE PTR [ebp-0x55],0x3c
  41d022:	ba 01 00 00 00       	mov    edx,0x1
  41d027:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41d02b:	e9 60 ff ff ff       	jmp    41cf90 <bixby110downloader::DownLoad()+0x460>

# source=Bixby110Downloader.cpp
# va=0x0041D030 size=0x130
0x0041D030 <bixby110downloader::Identify()>:
  41d030:	55                   	push   ebp
  41d031:	89 e5                	mov    ebp,esp
  41d033:	57                   	push   edi
  41d034:	8d 7d c8             	lea    edi,[ebp-0x38]
  41d037:	56                   	push   esi
  41d038:	53                   	push   ebx
  41d039:	83 ec 5c             	sub    esp,0x5c
  41d03c:	8b 5d 08             	mov    ebx,DWORD PTR [ebp+0x8]
  41d03f:	c6 45 c6 00          	mov    BYTE PTR [ebp-0x3a],0x0
  41d043:	8d b3 fc 05 00 00    	lea    esi,[ebx+0x5fc]
  41d049:	e9 95 00 00 00       	jmp    41d0e3 <bixby110downloader::Identify()+0xb3>
  41d04e:	89 f6                	mov    esi,esi
  41d050:	0f b6 83 c8 03 00 00 	movzx  eax,BYTE PTR [ebx+0x3c8]
  41d057:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41d05b:	8b 0b                	mov    ecx,DWORD PTR [ebx]
  41d05d:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41d060:	e8 db ad fe ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  41d065:	89 34 24             	mov    DWORD PTR [esp],esi
  41d068:	8d 55 c7             	lea    edx,[ebp-0x39]
  41d06b:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41d06f:	e8 3c c8 fe ff       	call   4098b0 <bixby110io::status_read_char(unsigned char*)>
  41d074:	84 c0                	test   al,al
  41d076:	0f 94 c0             	sete   al
  41d079:	0f b6 c8             	movzx  ecx,al
  41d07c:	88 4d c6             	mov    BYTE PTR [ebp-0x3a],cl
  41d07f:	31 d2                	xor    edx,edx
  41d081:	31 c0                	xor    eax,eax
  41d083:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  41d087:	31 c9                	xor    ecx,ecx
  41d089:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  41d08d:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41d091:	8b 13                	mov    edx,DWORD PTR [ebx]
  41d093:	89 3c 24             	mov    DWORD PTR [esp],edi
  41d096:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41d09a:	e8 f1 25 01 00       	call   42f690 <PeekMessageA@20>
  41d09f:	83 ec 14             	sub    esp,0x14
  41d0a2:	85 c0                	test   eax,eax
  41d0a4:	0f 85 a7 00 00 00    	jne    41d151 <bixby110downloader::Identify()+0x121>
  41d0aa:	0f b6 8b c8 03 00 00 	movzx  ecx,BYTE PTR [ebx+0x3c8]
  41d0b1:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41d0b5:	8b 13                	mov    edx,DWORD PTR [ebx]
  41d0b7:	89 14 24             	mov    DWORD PTR [esp],edx
  41d0ba:	e8 81 ad fe ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  41d0bf:	80 7d c7 eb          	cmp    BYTE PTR [ebp-0x39],0xeb
  41d0c3:	74 45                	je     41d10a <bixby110downloader::Identify()+0xda>
  41d0c5:	c7 04 24 e8 03 00 00 	mov    DWORD PTR [esp],0x3e8
  41d0cc:	ba 01 00 00 00       	mov    edx,0x1
  41d0d1:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41d0d5:	e8 86 27 01 00       	call   42f860 <Beep@8>
  41d0da:	b0 01                	mov    al,0x1
  41d0dc:	83 ec 08             	sub    esp,0x8
  41d0df:	84 c0                	test   al,al
  41d0e1:	74 4d                	je     41d130 <bixby110downloader::Identify()+0x100>
  41d0e3:	80 7d c6 00          	cmp    BYTE PTR [ebp-0x3a],0x0
  41d0e7:	0f 85 63 ff ff ff    	jne    41d050 <bixby110downloader::Identify()+0x20>
  41d0ed:	c6 83 4d 8e 00 00 ea 	mov    BYTE PTR [ebx+0x8e4d],0xea
  41d0f4:	b8 ea ff ff ff       	mov    eax,0xffffffea
  41d0f9:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41d0fd:	89 34 24             	mov    DWORD PTR [esp],esi
  41d100:	e8 3b c7 fe ff       	call   409840 <bixby110io::write_char(char)>
  41d105:	e9 46 ff ff ff       	jmp    41d050 <bixby110downloader::Identify()+0x20>
  41d10a:	c7 04 24 d0 07 00 00 	mov    DWORD PTR [esp],0x7d0
  41d111:	be 0a 00 00 00       	mov    esi,0xa
  41d116:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41d11a:	e8 41 27 01 00       	call   42f860 <Beep@8>
  41d11f:	83 ec 08             	sub    esp,0x8
  41d122:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]
  41d129:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  41d130:	0f b6 8b c8 03 00 00 	movzx  ecx,BYTE PTR [ebx+0x3c8]
  41d137:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41d13b:	8b 3b                	mov    edi,DWORD PTR [ebx]
  41d13d:	89 3c 24             	mov    DWORD PTR [esp],edi
  41d140:	e8 fb ac fe ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  41d145:	0f b6 45 c7          	movzx  eax,BYTE PTR [ebp-0x39]
  41d149:	8d 65 f4             	lea    esp,[ebp-0xc]
  41d14c:	5b                   	pop    ebx
  41d14d:	5e                   	pop    esi
  41d14e:	5f                   	pop    edi
  41d14f:	5d                   	pop    ebp
  41d150:	c3                   	ret
  41d151:	8d 65 f4             	lea    esp,[ebp-0xc]
  41d154:	31 c0                	xor    eax,eax
  41d156:	5b                   	pop    ebx
  41d157:	5e                   	pop    esi
  41d158:	5f                   	pop    edi
  41d159:	5d                   	pop    ebp
  41d15a:	c3                   	ret
  41d15b:	90                   	nop
  41d15c:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
