# Flue, fuel, and utility monitor UI core
# BixCheck 5.0.21; generated by tools/analyze_bixcheck.py
# Exact GNU objdump Intel-syntax excerpts; addresses are build-specific.

# source=Bixby110dlg.cpp
# va=0x00414E10 size=0x3E0
0x00414E10 <bixby110control::Bixby110DialogSetupFlueMonitor(int, int, int, int)>:
  414e10:	55                   	push   ebp
  414e11:	89 e5                	mov    ebp,esp
  414e13:	57                   	push   edi
  414e14:	56                   	push   esi
  414e15:	53                   	push   ebx
  414e16:	83 ec 4c             	sub    esp,0x4c
  414e19:	8b 5d 10             	mov    ebx,DWORD PTR [ebp+0x10]
  414e1c:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  414e1f:	8b 75 08             	mov    esi,DWORD PTR [ebp+0x8]
  414e22:	89 5d e4             	mov    DWORD PTR [ebp-0x1c],ebx
  414e25:	89 4d e8             	mov    DWORD PTR [ebp-0x18],ecx
  414e28:	8b 46 18             	mov    eax,DWORD PTR [esi+0x18]
  414e2b:	0f b6 96 30 19 00 00 	movzx  edx,BYTE PTR [esi+0x1930]
  414e32:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  414e36:	8b be 70 1c 00 00    	mov    edi,DWORD PTR [esi+0x1c70]
  414e3c:	42                   	inc    edx
  414e3d:	89 55 f0             	mov    DWORD PTR [ebp-0x10],edx
  414e40:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  414e43:	89 7c 24 18          	mov    DWORD PTR [esp+0x18],edi
  414e47:	8b 7d e8             	mov    edi,DWORD PTR [ebp-0x18]
  414e4a:	ba 64 00 00 00       	mov    edx,0x64
  414e4f:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  414e53:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  414e57:	b9 c1 a0 43 00       	mov    ecx,0x43a0c1
  414e5c:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  414e60:	31 ff                	xor    edi,edi
  414e62:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  414e66:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  414e6a:	8b 96 34 08 00 00    	mov    edx,DWORD PTR [esi+0x834]
  414e70:	89 14 24             	mov    DWORD PTR [esp],edx
  414e73:	e8 88 b4 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  414e78:	c7 45 ec 00 00 00 00 	mov    DWORD PTR [ebp-0x14],0x0
  414e7f:	8b 45 e8             	mov    eax,DWORD PTR [ebp-0x18]
  414e82:	83 c0 23             	add    eax,0x23
  414e85:	89 45 e0             	mov    DWORD PTR [ebp-0x20],eax
  414e88:	90                   	nop
  414e89:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]
  414e90:	0f b6 8e 30 19 00 00 	movzx  ecx,BYTE PTR [esi+0x1930]
  414e97:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  414e9a:	01 cb                	add    ebx,ecx
  414e9c:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  414ea0:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  414ea3:	8b 86 70 1c 00 00    	mov    eax,DWORD PTR [esi+0x1c70]
  414ea9:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  414ead:	ba 64 00 00 00       	mov    edx,0x64
  414eb2:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  414eb6:	8b 55 ec             	mov    edx,DWORD PTR [ebp-0x14]
  414eb9:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  414ebd:	8b 45 e0             	mov    eax,DWORD PTR [ebp-0x20]
  414ec0:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  414ec4:	8d 8f c1 95 43 00    	lea    ecx,[edi+0x4395c1]
  414eca:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  414ece:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  414ed2:	8b 84 96 b4 07 00 00 	mov    eax,DWORD PTR [esi+edx*4+0x7b4]
  414ed9:	89 04 24             	mov    DWORD PTR [esp],eax
  414edc:	e8 1f b4 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  414ee1:	31 c9                	xor    ecx,ecx
  414ee3:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  414ee7:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  414eea:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  414eed:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  414ef1:	8b 86 70 1c 00 00    	mov    eax,DWORD PTR [esi+0x1c70]
  414ef7:	ba 1e 00 00 00       	mov    edx,0x1e
  414efc:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  414f00:	0f b6 97 09 96 43 00 	movzx  edx,BYTE PTR [edi+0x439609]
  414f07:	83 c7 58             	add    edi,0x58
  414f0a:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  414f0e:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  414f11:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  414f15:	b9 49 05 44 00       	mov    ecx,0x440549
  414f1a:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  414f1e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  414f22:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  414f26:	8b 84 96 44 08 00 00 	mov    eax,DWORD PTR [esi+edx*4+0x844]
  414f2d:	89 04 24             	mov    DWORD PTR [esp],eax
  414f30:	e8 eb ae 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  414f35:	ff 45 ec             	inc    DWORD PTR [ebp-0x14]
  414f38:	83 7d ec 07          	cmp    DWORD PTR [ebp-0x14],0x7
  414f3c:	0f 8e 4e ff ff ff    	jle    414e90 <bixby110control::Bixby110DialogSetupFlueMonitor(int, int, int, int)+0x80>
  414f42:	8b 4e 18             	mov    ecx,DWORD PTR [esi+0x18]
  414f45:	bb 64 00 00 00       	mov    ebx,0x64
  414f4a:	8b 7d 0c             	mov    edi,DWORD PTR [ebp+0xc]
  414f4d:	8b 45 f0             	mov    eax,DWORD PTR [ebp-0x10]
  414f50:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  414f54:	81 c7 96 00 00 00    	add    edi,0x96
  414f5a:	8b 96 70 1c 00 00    	mov    edx,DWORD PTR [esi+0x1c70]
  414f60:	89 7d dc             	mov    DWORD PTR [ebp-0x24],edi
  414f63:	8b 4d dc             	mov    ecx,DWORD PTR [ebp-0x24]
  414f66:	89 5c 24 10          	mov    DWORD PTR [esp+0x10],ebx
  414f6a:	8b 7d e4             	mov    edi,DWORD PTR [ebp-0x1c]
  414f6d:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  414f71:	ba 19 a1 43 00       	mov    edx,0x43a119
  414f76:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  414f7a:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  414f7e:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  414f82:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  414f86:	8b 86 38 08 00 00    	mov    eax,DWORD PTR [esi+0x838]
  414f8c:	89 04 24             	mov    DWORD PTR [esp],eax
  414f8f:	e8 6c b3 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  414f94:	c7 45 d4 08 00 00 00 	mov    DWORD PTR [ebp-0x2c],0x8
  414f9b:	8b 5d 0c             	mov    ebx,DWORD PTR [ebp+0xc]
  414f9e:	81 c3 b9 00 00 00    	add    ebx,0xb9
  414fa4:	89 5d d8             	mov    DWORD PTR [ebp-0x28],ebx
  414fa7:	bb c0 02 00 00       	mov    ebx,0x2c0
  414fac:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
  414fb0:	0f b6 8e 30 19 00 00 	movzx  ecx,BYTE PTR [esi+0x1930]
  414fb7:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  414fba:	01 cf                	add    edi,ecx
  414fbc:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  414fc0:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  414fc3:	8b 86 70 1c 00 00    	mov    eax,DWORD PTR [esi+0x1c70]
  414fc9:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  414fcd:	ba 64 00 00 00       	mov    edx,0x64
  414fd2:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  414fd6:	8b 55 d4             	mov    edx,DWORD PTR [ebp-0x2c]
  414fd9:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  414fdd:	8b 45 d8             	mov    eax,DWORD PTR [ebp-0x28]
  414fe0:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  414fe4:	8d 8b c1 95 43 00    	lea    ecx,[ebx+0x4395c1]
  414fea:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  414fee:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  414ff2:	8b 84 96 b4 07 00 00 	mov    eax,DWORD PTR [esi+edx*4+0x7b4]
  414ff9:	89 04 24             	mov    DWORD PTR [esp],eax
  414ffc:	e8 ff b2 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  415001:	31 c9                	xor    ecx,ecx
  415003:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  415007:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  41500a:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  41500d:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  415011:	8b 86 70 1c 00 00    	mov    eax,DWORD PTR [esi+0x1c70]
  415017:	ba 1e 00 00 00       	mov    edx,0x1e
  41501c:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  415020:	0f b6 93 09 96 43 00 	movzx  edx,BYTE PTR [ebx+0x439609]
  415027:	83 c3 58             	add    ebx,0x58
  41502a:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  41502e:	8b 45 dc             	mov    eax,DWORD PTR [ebp-0x24]
  415031:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  415035:	b9 49 05 44 00       	mov    ecx,0x440549
  41503a:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  41503e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  415042:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415046:	8b 84 96 44 08 00 00 	mov    eax,DWORD PTR [esi+edx*4+0x844]
  41504d:	89 04 24             	mov    DWORD PTR [esp],eax
  415050:	e8 cb ad 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  415055:	ff 45 d4             	inc    DWORD PTR [ebp-0x2c]
  415058:	83 7d d4 0f          	cmp    DWORD PTR [ebp-0x2c],0xf
  41505c:	0f 8e 4e ff ff ff    	jle    414fb0 <bixby110control::Bixby110DialogSetupFlueMonitor(int, int, int, int)+0x1a0>
  415062:	0f b6 9e 30 19 00 00 	movzx  ebx,BYTE PTR [esi+0x1930]
  415069:	8b 4e 18             	mov    ecx,DWORD PTR [esi+0x18]
  41506c:	8b 45 f0             	mov    eax,DWORD PTR [ebp-0x10]
  41506f:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  415073:	8b 4d e8             	mov    ecx,DWORD PTR [ebp-0x18]
  415076:	8b 96 70 1c 00 00    	mov    edx,DWORD PTR [esi+0x1c70]
  41507c:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  415080:	8d 1c 5f             	lea    ebx,[edi+ebx*2]
  415083:	bf 64 00 00 00       	mov    edi,0x64
  415088:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  41508c:	ba 71 a1 43 00       	mov    edx,0x43a171
  415091:	89 7c 24 10          	mov    DWORD PTR [esp+0x10],edi
  415095:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  415099:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41509d:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  4150a1:	8b 86 3c 08 00 00    	mov    eax,DWORD PTR [esi+0x83c]
  4150a7:	89 04 24             	mov    DWORD PTR [esp],eax
  4150aa:	e8 51 b2 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  4150af:	0f b6 be 30 19 00 00 	movzx  edi,BYTE PTR [esi+0x1930]
  4150b6:	01 fb                	add    ebx,edi
  4150b8:	bf 10 00 00 00       	mov    edi,0x10
  4150bd:	89 5d d0             	mov    DWORD PTR [ebp-0x30],ebx
  4150c0:	8b 5d e8             	mov    ebx,DWORD PTR [ebp-0x18]
  4150c3:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  4150c9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  4150d0:	31 d2                	xor    edx,edx
  4150d2:	89 54 24 20          	mov    DWORD PTR [esp+0x20],edx
  4150d6:	8b 46 18             	mov    eax,DWORD PTR [esi+0x18]
  4150d9:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  4150dc:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  4150e0:	8b 8e 70 1c 00 00    	mov    ecx,DWORD PTR [esi+0x1c70]
  4150e6:	b8 1e 00 00 00       	mov    eax,0x1e
  4150eb:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  4150ef:	ba 49 05 44 00       	mov    edx,0x440549
  4150f4:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  4150f8:	8b 4d d0             	mov    ecx,DWORD PTR [ebp-0x30]
  4150fb:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  4150ff:	83 c3 23             	add    ebx,0x23
  415102:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  415106:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  41510a:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41510e:	8b 84 be 44 08 00 00 	mov    eax,DWORD PTR [esi+edi*4+0x844]
  415115:	47                   	inc    edi
  415116:	89 04 24             	mov    DWORD PTR [esp],eax
  415119:	e8 02 ad 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  41511e:	83 ff 17             	cmp    edi,0x17
  415121:	7e ad                	jle    4150d0 <bixby110control::Bixby110DialogSetupFlueMonitor(int, int, int, int)+0x2c0>
  415123:	0f b6 9e 30 19 00 00 	movzx  ebx,BYTE PTR [esi+0x1930]
  41512a:	8b 46 18             	mov    eax,DWORD PTR [esi+0x18]
  41512d:	8b 55 d0             	mov    edx,DWORD PTR [ebp-0x30]
  415130:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  415134:	8b 8e 70 1c 00 00    	mov    ecx,DWORD PTR [esi+0x1c70]
  41513a:	8d 3c 5a             	lea    edi,[edx+ebx*2]
  41513d:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  415141:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  415144:	b8 64 00 00 00       	mov    eax,0x64
  415149:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  41514d:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  415151:	8b 4d e8             	mov    ecx,DWORD PTR [ebp-0x18]
  415154:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  415158:	ba c9 a1 43 00       	mov    edx,0x43a1c9
  41515d:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  415161:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415165:	8b 86 40 08 00 00    	mov    eax,DWORD PTR [esi+0x840]
  41516b:	89 04 24             	mov    DWORD PTR [esp],eax
  41516e:	e8 8d b1 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  415173:	0f b6 8e 30 19 00 00 	movzx  ecx,BYTE PTR [esi+0x1930]
  41517a:	8b 5d e8             	mov    ebx,DWORD PTR [ebp-0x18]
  41517d:	01 cf                	add    edi,ecx
  41517f:	89 7d cc             	mov    DWORD PTR [ebp-0x34],edi
  415182:	bf 18 00 00 00       	mov    edi,0x18
  415187:	89 f6                	mov    esi,esi
  415189:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  415190:	31 c0                	xor    eax,eax
  415192:	89 44 24 20          	mov    DWORD PTR [esp+0x20],eax
  415196:	8b 4e 18             	mov    ecx,DWORD PTR [esi+0x18]
  415199:	8b 45 f0             	mov    eax,DWORD PTR [ebp-0x10]
  41519c:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  4151a0:	8b 96 70 1c 00 00    	mov    edx,DWORD PTR [esi+0x1c70]
  4151a6:	b9 1e 00 00 00       	mov    ecx,0x1e
  4151ab:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  4151af:	b8 49 05 44 00       	mov    eax,0x440549
  4151b4:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  4151b8:	8b 55 cc             	mov    edx,DWORD PTR [ebp-0x34]
  4151bb:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  4151bf:	83 c3 23             	add    ebx,0x23
  4151c2:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  4151c6:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  4151ca:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4151ce:	8b 8c be 44 08 00 00 	mov    ecx,DWORD PTR [esi+edi*4+0x844]
  4151d5:	47                   	inc    edi
  4151d6:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4151d9:	e8 42 ac 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  4151de:	83 ff 1f             	cmp    edi,0x1f
  4151e1:	7e ad                	jle    415190 <bixby110control::Bixby110DialogSetupFlueMonitor(int, int, int, int)+0x380>
  4151e3:	83 c4 4c             	add    esp,0x4c
  4151e6:	5b                   	pop    ebx
  4151e7:	5e                   	pop    esi
  4151e8:	5f                   	pop    edi
  4151e9:	5d                   	pop    ebp
  4151ea:	c3                   	ret
  4151eb:	90                   	nop
  4151ec:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]

# source=Bixby110dlg.cpp
# va=0x004151F0 size=0x3C0
0x004151F0 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)>:
  4151f0:	55                   	push   ebp
  4151f1:	89 e5                	mov    ebp,esp
  4151f3:	57                   	push   edi
  4151f4:	56                   	push   esi
  4151f5:	53                   	push   ebx
  4151f6:	83 ec 4c             	sub    esp,0x4c
  4151f9:	8b 75 08             	mov    esi,DWORD PTR [ebp+0x8]
  4151fc:	8b 55 0c             	mov    edx,DWORD PTR [ebp+0xc]
  4151ff:	8b 5d 18             	mov    ebx,DWORD PTR [ebp+0x18]
  415202:	89 75 f0             	mov    DWORD PTR [ebp-0x10],esi
  415205:	8b 7d f0             	mov    edi,DWORD PTR [ebp-0x10]
  415208:	0f b6 86 30 19 00 00 	movzx  eax,BYTE PTR [esi+0x1930]
  41520f:	8b 4f 18             	mov    ecx,DWORD PTR [edi+0x18]
  415212:	8b 7d 14             	mov    edi,DWORD PTR [ebp+0x14]
  415215:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  415219:	40                   	inc    eax
  41521a:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  41521d:	89 45 ec             	mov    DWORD PTR [ebp-0x14],eax
  415220:	8b 75 ec             	mov    esi,DWORD PTR [ebp-0x14]
  415223:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  415227:	b8 64 00 00 00       	mov    eax,0x64
  41522c:	b9 81 c8 43 00       	mov    ecx,0x43c881
  415231:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  415235:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  415239:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41523d:	89 74 24 14          	mov    DWORD PTR [esp+0x14],esi
  415241:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  415245:	8b b2 8c 05 00 00    	mov    esi,DWORD PTR [edx+0x58c]
  41524b:	89 34 24             	mov    DWORD PTR [esp],esi
  41524e:	e8 ad b0 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  415253:	8b 45 f0             	mov    eax,DWORD PTR [ebp-0x10]
  415256:	ba 64 00 00 00       	mov    edx,0x64
  41525b:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  41525e:	8b 75 ec             	mov    esi,DWORD PTR [ebp-0x14]
  415261:	8b 78 18             	mov    edi,DWORD PTR [eax+0x18]
  415264:	8b 45 14             	mov    eax,DWORD PTR [ebp+0x14]
  415267:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  41526b:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  41526e:	83 c0 46             	add    eax,0x46
  415271:	89 7c 24 1c          	mov    DWORD PTR [esp+0x1c],edi
  415275:	bf 89 c9 43 00       	mov    edi,0x43c989
  41527a:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  41527e:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  415282:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  415286:	89 74 24 14          	mov    DWORD PTR [esp+0x14],esi
  41528a:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41528e:	8b b1 90 05 00 00    	mov    esi,DWORD PTR [ecx+0x590]
  415294:	89 45 e4             	mov    DWORD PTR [ebp-0x1c],eax
  415297:	89 34 24             	mov    DWORD PTR [esp],esi
  41529a:	be 64 00 00 00       	mov    esi,0x64
  41529f:	e8 5c b0 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  4152a4:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  4152a7:	8b 7d 0c             	mov    edi,DWORD PTR [ebp+0xc]
  4152aa:	8b 4d ec             	mov    ecx,DWORD PTR [ebp-0x14]
  4152ad:	8b 42 18             	mov    eax,DWORD PTR [edx+0x18]
  4152b0:	8b 55 14             	mov    edx,DWORD PTR [ebp+0x14]
  4152b3:	89 7c 24 18          	mov    DWORD PTR [esp+0x18],edi
  4152b7:	8b 7d f0             	mov    edi,DWORD PTR [ebp-0x10]
  4152ba:	81 c2 8c 00 00 00    	add    edx,0x8c
  4152c0:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  4152c4:	b8 91 ca 43 00       	mov    eax,0x43ca91
  4152c9:	89 74 24 10          	mov    DWORD PTR [esp+0x10],esi
  4152cd:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  4152d1:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  4152d5:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  4152d9:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4152dd:	8b 8f 94 05 00 00    	mov    ecx,DWORD PTR [edi+0x594]
  4152e3:	89 55 d0             	mov    DWORD PTR [ebp-0x30],edx
  4152e6:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4152e9:	e8 12 b0 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  4152ee:	8b 75 f0             	mov    esi,DWORD PTR [ebp-0x10]
  4152f1:	8b 4d 14             	mov    ecx,DWORD PTR [ebp+0x14]
  4152f4:	8b 7d 10             	mov    edi,DWORD PTR [ebp+0x10]
  4152f7:	0f b6 96 30 19 00 00 	movzx  edx,BYTE PTR [esi+0x1930]
  4152fe:	83 c1 14             	add    ecx,0x14
  415301:	83 c7 08             	add    edi,0x8
  415304:	89 4d e8             	mov    DWORD PTR [ebp-0x18],ecx
  415307:	0f b6 c2             	movzx  eax,dl
  41530a:	8b 4d 10             	mov    ecx,DWORD PTR [ebp+0x10]
  41530d:	89 7d cc             	mov    DWORD PTR [ebp-0x34],edi
  415310:	8d 34 03             	lea    esi,[ebx+eax*1]
  415313:	8b 5d 14             	mov    ebx,DWORD PTR [ebp+0x14]
  415316:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  415319:	c1 e1 02             	shl    ecx,0x2
  41531c:	8b 7d 10             	mov    edi,DWORD PTR [ebp+0x10]
  41531f:	81 c3 a0 00 00 00    	add    ebx,0xa0
  415325:	8b 45 14             	mov    eax,DWORD PTR [ebp+0x14]
  415328:	89 5d e0             	mov    DWORD PTR [ebp-0x20],ebx
  41532b:	8d 9c 11 b4 04 00 00 	lea    ebx,[ecx+edx*1+0x4b4]
  415332:	8b 55 10             	mov    edx,DWORD PTR [ebp+0x10]
  415335:	29 55 cc             	sub    DWORD PTR [ebp-0x34],edx
  415338:	83 c0 5a             	add    eax,0x5a
  41533b:	01 f9                	add    ecx,edi
  41533d:	89 45 d4             	mov    DWORD PTR [ebp-0x2c],eax
  415340:	8d 04 4a             	lea    eax,[edx+ecx*2]
  415343:	8d 3c c5 00 00 00 00 	lea    edi,[eax*8+0x0]
  41534a:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  415350:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  415353:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  415356:	8b 4a 18             	mov    ecx,DWORD PTR [edx+0x18]
  415359:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  41535d:	8b 55 14             	mov    edx,DWORD PTR [ebp+0x14]
  415360:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  415364:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  415368:	8d 8f e1 ac 43 00    	lea    ecx,[edi+0x43ace1]
  41536e:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  415372:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415376:	8b 83 a8 fe ff ff    	mov    eax,DWORD PTR [ebx-0x158]
  41537c:	89 04 24             	mov    DWORD PTR [esp],eax
  41537f:	e8 ac a5 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  415384:	31 d2                	xor    edx,edx
  415386:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  415389:	89 54 24 20          	mov    DWORD PTR [esp+0x20],edx
  41538d:	8b 55 0c             	mov    edx,DWORD PTR [ebp+0xc]
  415390:	8b 41 18             	mov    eax,DWORD PTR [ecx+0x18]
  415393:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  415397:	8b 4d ec             	mov    ecx,DWORD PTR [ebp-0x14]
  41539a:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  41539e:	8b 55 e8             	mov    edx,DWORD PTR [ebp-0x18]
  4153a1:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  4153a5:	b8 28 00 00 00       	mov    eax,0x28
  4153aa:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  4153ae:	b9 49 05 44 00       	mov    ecx,0x440549
  4153b3:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  4153b7:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  4153bb:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  4153bf:	8b 43 c0             	mov    eax,DWORD PTR [ebx-0x40]
  4153c2:	89 04 24             	mov    DWORD PTR [esp],eax
  4153c5:	e8 56 aa 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  4153ca:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  4153cd:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  4153d0:	8b 4a 18             	mov    ecx,DWORD PTR [edx+0x18]
  4153d3:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  4153d7:	8b 55 e4             	mov    edx,DWORD PTR [ebp-0x1c]
  4153da:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  4153de:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  4153e2:	8d 8f a1 af 43 00    	lea    ecx,[edi+0x43afa1]
  4153e8:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  4153ec:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  4153f0:	8b 83 c8 fe ff ff    	mov    eax,DWORD PTR [ebx-0x138]
  4153f6:	89 04 24             	mov    DWORD PTR [esp],eax
  4153f9:	e8 32 a5 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  4153fe:	31 d2                	xor    edx,edx
  415400:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  415403:	89 54 24 20          	mov    DWORD PTR [esp+0x20],edx
  415407:	8b 55 0c             	mov    edx,DWORD PTR [ebp+0xc]
  41540a:	8b 41 18             	mov    eax,DWORD PTR [ecx+0x18]
  41540d:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  415411:	8b 4d ec             	mov    ecx,DWORD PTR [ebp-0x14]
  415414:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  415418:	8b 55 d4             	mov    edx,DWORD PTR [ebp-0x2c]
  41541b:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  41541f:	b8 28 00 00 00       	mov    eax,0x28
  415424:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  415428:	b9 49 05 44 00       	mov    ecx,0x440549
  41542d:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  415431:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415435:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  415439:	8b 43 e0             	mov    eax,DWORD PTR [ebx-0x20]
  41543c:	89 04 24             	mov    DWORD PTR [esp],eax
  41543f:	e8 dc a9 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  415444:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  415447:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  41544a:	8b 4a 18             	mov    ecx,DWORD PTR [edx+0x18]
  41544d:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  415451:	8d 97 61 b2 43 00    	lea    edx,[edi+0x43b261]
  415457:	83 c7 58             	add    edi,0x58
  41545a:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  41545e:	8b 4d d0             	mov    ecx,DWORD PTR [ebp-0x30]
  415461:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415465:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  415469:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41546d:	8b 83 e8 fe ff ff    	mov    eax,DWORD PTR [ebx-0x118]
  415473:	89 04 24             	mov    DWORD PTR [esp],eax
  415476:	e8 b5 a4 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  41547b:	31 c9                	xor    ecx,ecx
  41547d:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  415480:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  415484:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  415487:	8b 42 18             	mov    eax,DWORD PTR [edx+0x18]
  41548a:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  41548e:	8b 55 ec             	mov    edx,DWORD PTR [ebp-0x14]
  415491:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  415495:	8b 4d e0             	mov    ecx,DWORD PTR [ebp-0x20]
  415498:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  41549c:	b8 28 00 00 00       	mov    eax,0x28
  4154a1:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  4154a5:	ba 49 05 44 00       	mov    edx,0x440549
  4154aa:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  4154ae:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  4154b2:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  4154b6:	8b 03                	mov    eax,DWORD PTR [ebx]
  4154b8:	83 c3 04             	add    ebx,0x4
  4154bb:	89 04 24             	mov    DWORD PTR [esp],eax
  4154be:	e8 5d a9 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  4154c3:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  4154c6:	0f b6 91 30 19 00 00 	movzx  edx,BYTE PTR [ecx+0x1930]
  4154cd:	0f b6 c2             	movzx  eax,dl
  4154d0:	01 c6                	add    esi,eax
  4154d2:	ff 4d cc             	dec    DWORD PTR [ebp-0x34]
  4154d5:	0f 85 75 fe ff ff    	jne    415350 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x160>
  4154db:	8b 5d 10             	mov    ebx,DWORD PTR [ebp+0x10]
  4154de:	01 c6                	add    esi,eax
  4154e0:	8b 7d 10             	mov    edi,DWORD PTR [ebp+0x10]
  4154e3:	83 c3 18             	add    ebx,0x18
  4154e6:	83 c7 23             	add    edi,0x23
  4154e9:	39 df                	cmp    edi,ebx
  4154eb:	89 7d d8             	mov    DWORD PTR [ebp-0x28],edi
  4154ee:	0f 8e b4 00 00 00    	jle    4155a8 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x3b8>
  4154f4:	8b 55 14             	mov    edx,DWORD PTR [ebp+0x14]
  4154f7:	8d 0c 9b             	lea    ecx,[ebx+ebx*4]
  4154fa:	8d 04 4b             	lea    eax,[ebx+ecx*2]
  4154fd:	8d 3c c5 e1 ac 43 00 	lea    edi,[eax*8+0x43ace1]
  415504:	83 c2 78             	add    edx,0x78
  415507:	89 55 dc             	mov    DWORD PTR [ebp-0x24],edx
  41550a:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  415510:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  415513:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  415516:	8b 42 18             	mov    eax,DWORD PTR [edx+0x18]
  415519:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  41551d:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  415520:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  415524:	83 c7 58             	add    edi,0x58
  415527:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  41552b:	8b 45 14             	mov    eax,DWORD PTR [ebp+0x14]
  41552e:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  415532:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  415536:	8b 8c 9a 5c 03 00 00 	mov    ecx,DWORD PTR [edx+ebx*4+0x35c]
  41553d:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415540:	e8 eb a3 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  415545:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  415548:	31 c0                	xor    eax,eax
  41554a:	89 44 24 20          	mov    DWORD PTR [esp+0x20],eax
  41554e:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  415551:	8b 4a 18             	mov    ecx,DWORD PTR [edx+0x18]
  415554:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  415558:	ba 28 00 00 00       	mov    edx,0x28
  41555d:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  415561:	8b 45 dc             	mov    eax,DWORD PTR [ebp-0x24]
  415564:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  415568:	8b 4d ec             	mov    ecx,DWORD PTR [ebp-0x14]
  41556b:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  41556f:	8b 55 f0             	mov    edx,DWORD PTR [ebp-0x10]
  415572:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  415576:	b9 49 05 44 00       	mov    ecx,0x440549
  41557b:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41557f:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  415583:	8b 84 9a 74 04 00 00 	mov    eax,DWORD PTR [edx+ebx*4+0x474]
  41558a:	43                   	inc    ebx
  41558b:	89 04 24             	mov    DWORD PTR [esp],eax
  41558e:	e8 8d a8 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  415593:	8b 4d f0             	mov    ecx,DWORD PTR [ebp-0x10]
  415596:	0f b6 81 30 19 00 00 	movzx  eax,BYTE PTR [ecx+0x1930]
  41559d:	01 c6                	add    esi,eax
  41559f:	39 5d d8             	cmp    DWORD PTR [ebp-0x28],ebx
  4155a2:	0f 8f 68 ff ff ff    	jg     415510 <bixby110control::Bixby110DialogSetupFuelMonitor(HWND__*, int, int, int, int, int)+0x320>
  4155a8:	83 c4 4c             	add    esp,0x4c
  4155ab:	5b                   	pop    ebx
  4155ac:	5e                   	pop    esi
  4155ad:	5f                   	pop    edi
  4155ae:	5d                   	pop    ebp
  4155af:	c3                   	ret

# source=Bixby110dlg.cpp
# va=0x004155B0 size=0x5C0
0x004155B0 <bixby110control::Bixby110DialogSetupUtilityWindows()>:
  4155b0:	55                   	push   ebp
  4155b1:	b9 20 4d 6f 6e       	mov    ecx,0x6e6f4d20
  4155b6:	89 e5                	mov    ebp,esp
  4155b8:	57                   	push   edi
  4155b9:	ba 69 74 6f 72       	mov    edx,0x726f7469
  4155be:	56                   	push   esi
  4155bf:	53                   	push   ebx
  4155c0:	83 ec 3c             	sub    esp,0x3c
  4155c3:	bb 46 6c 75 65       	mov    ebx,0x65756c46
  4155c8:	8b 75 08             	mov    esi,DWORD PTR [ebp+0x8]
  4155cb:	8b 86 70 1c 00 00    	mov    eax,DWORD PTR [esi+0x1c70]
  4155d1:	c7 46 04 41 00 00 00 	mov    DWORD PTR [esi+0x4],0x41
  4155d8:	c7 46 08 87 00 00 00 	mov    DWORD PTR [esi+0x8],0x87
  4155df:	85 c0                	test   eax,eax
  4155e1:	c7 46 0c 2c 01 00 00 	mov    DWORD PTR [esi+0xc],0x12c
  4155e8:	c7 46 10 22 01 00 00 	mov    DWORD PTR [esi+0x10],0x122
  4155ef:	89 9e 31 19 00 00    	mov    DWORD PTR [esi+0x1931],ebx
  4155f5:	89 8e 35 19 00 00    	mov    DWORD PTR [esi+0x1935],ecx
  4155fb:	89 96 39 19 00 00    	mov    DWORD PTR [esi+0x1939],edx
  415601:	c6 86 3d 19 00 00 00 	mov    BYTE PTR [esi+0x193d],0x0
  415608:	0f 85 82 00 00 00    	jne    415690 <bixby110control::Bixby110DialogSetupUtilityWindows()+0xe0>
  41560e:	31 db                	xor    ebx,ebx
  415610:	31 d2                	xor    edx,edx
  415612:	89 5c 24 2c          	mov    DWORD PTR [esp+0x2c],ebx
  415616:	8b 4e 18             	mov    ecx,DWORD PTR [esi+0x18]
  415619:	89 54 24 24          	mov    DWORD PTR [esp+0x24],edx
  41561d:	89 4c 24 28          	mov    DWORD PTR [esp+0x28],ecx
  415621:	8b 7e 14             	mov    edi,DWORD PTR [esi+0x14]
  415624:	89 7c 24 20          	mov    DWORD PTR [esp+0x20],edi
  415628:	8b 46 10             	mov    eax,DWORD PTR [esi+0x10]
  41562b:	bf 00 00 ca 00       	mov    edi,0xca0000
  415630:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  415634:	8b 5e 0c             	mov    ebx,DWORD PTR [esi+0xc]
  415637:	b8 7c 05 44 00       	mov    eax,0x44057c
  41563c:	89 5c 24 18          	mov    DWORD PTR [esp+0x18],ebx
  415640:	8b 4e 08             	mov    ecx,DWORD PTR [esi+0x8]
  415643:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  415647:	8b 56 04             	mov    edx,DWORD PTR [esi+0x4]
  41564a:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  41564e:	8d be 31 19 00 00    	lea    edi,[esi+0x1931]
  415654:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  415658:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  41565c:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415660:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  415667:	e8 b4 9f 01 00       	call   42f620 <CreateWindowExA@48>
  41566c:	89 86 70 1c 00 00    	mov    DWORD PTR [esi+0x1c70],eax
  415672:	83 ec 30             	sub    esp,0x30
  415675:	85 c0                	test   eax,eax
  415677:	0f 85 73 04 00 00    	jne    415af0 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x540>
  41567d:	31 d2                	xor    edx,edx
  41567f:	b8 88 05 44 00       	mov    eax,0x440588
  415684:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  415688:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41568c:	eb 17                	jmp    4156a5 <bixby110control::Bixby110DialogSetupUtilityWindows()+0xf5>
  41568e:	89 f6                	mov    esi,esi
  415690:	bf a4 05 44 00       	mov    edi,0x4405a4
  415695:	31 c0                	xor    eax,eax
  415697:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  41569b:	8d be 31 19 00 00    	lea    edi,[esi+0x1931]
  4156a1:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  4156a5:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  4156a9:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  4156b0:	e8 bb 9e 01 00       	call   42f570 <MessageBoxA@16>
  4156b5:	83 ec 10             	sub    esp,0x10
  4156b8:	c7 46 04 6e 00 00 00 	mov    DWORD PTR [esi+0x4],0x6e
  4156bf:	8b 96 74 1c 00 00    	mov    edx,DWORD PTR [esi+0x1c74]
  4156c5:	b8 46 75 65 6c       	mov    eax,0x6c657546
  4156ca:	c7 46 08 aa 00 00 00 	mov    DWORD PTR [esi+0x8],0xaa
  4156d1:	bb 20 41 20 44       	mov    ebx,0x44204120
  4156d6:	b9 61 74 61 00       	mov    ecx,0x617461
  4156db:	c7 46 0c e1 00 00 00 	mov    DWORD PTR [esi+0xc],0xe1
  4156e2:	85 d2                	test   edx,edx
  4156e4:	c7 46 10 7c 01 00 00 	mov    DWORD PTR [esi+0x10],0x17c
  4156eb:	89 86 31 19 00 00    	mov    DWORD PTR [esi+0x1931],eax
  4156f1:	89 9e 35 19 00 00    	mov    DWORD PTR [esi+0x1935],ebx
  4156f7:	89 8e 39 19 00 00    	mov    DWORD PTR [esi+0x1939],ecx
  4156fd:	0f 85 7d 00 00 00    	jne    415780 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x1d0>
  415703:	31 c9                	xor    ecx,ecx
  415705:	31 c0                	xor    eax,eax
  415707:	89 4c 24 2c          	mov    DWORD PTR [esp+0x2c],ecx
  41570b:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  41570e:	89 44 24 24          	mov    DWORD PTR [esp+0x24],eax
  415712:	89 54 24 28          	mov    DWORD PTR [esp+0x28],edx
  415716:	8b 5e 14             	mov    ebx,DWORD PTR [esi+0x14]
  415719:	89 5c 24 20          	mov    DWORD PTR [esp+0x20],ebx
  41571d:	8b 4e 10             	mov    ecx,DWORD PTR [esi+0x10]
  415720:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  415724:	8b 56 0c             	mov    edx,DWORD PTR [esi+0xc]
  415727:	b9 00 00 ca 00       	mov    ecx,0xca0000
  41572c:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  415730:	8b 46 08             	mov    eax,DWORD PTR [esi+0x8]
  415733:	ba 7c 05 44 00       	mov    edx,0x44057c
  415738:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  41573c:	8b 5e 04             	mov    ebx,DWORD PTR [esi+0x4]
  41573f:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  415743:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  415747:	89 5c 24 10          	mov    DWORD PTR [esp+0x10],ebx
  41574b:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41574f:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  415756:	e8 c5 9e 01 00       	call   42f620 <CreateWindowExA@48>
  41575b:	89 86 74 1c 00 00    	mov    DWORD PTR [esi+0x1c74],eax
  415761:	83 ec 30             	sub    esp,0x30
  415764:	85 c0                	test   eax,eax
  415766:	0f 85 04 03 00 00    	jne    415a70 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x4c0>
  41576c:	31 c0                	xor    eax,eax
  41576e:	bb 88 05 44 00       	mov    ebx,0x440588
  415773:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  415777:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  41577b:	eb 12                	jmp    41578f <bixby110control::Bixby110DialogSetupUtilityWindows()+0x1df>
  41577d:	8d 76 00             	lea    esi,[esi+0x0]
  415780:	31 c0                	xor    eax,eax
  415782:	b9 a4 05 44 00       	mov    ecx,0x4405a4
  415787:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  41578b:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41578f:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  415793:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  41579a:	e8 d1 9d 01 00       	call   42f570 <MessageBoxA@16>
  41579f:	83 ec 10             	sub    esp,0x10
  4157a2:	c7 46 04 91 00 00 00 	mov    DWORD PTR [esi+0x4],0x91
  4157a9:	8b 96 78 1c 00 00    	mov    edx,DWORD PTR [esi+0x1c78]
  4157af:	b8 46 75 65 6c       	mov    eax,0x6c657546
  4157b4:	c7 46 08 cd 00 00 00 	mov    DWORD PTR [esi+0x8],0xcd
  4157bb:	b9 20 42 20 44       	mov    ecx,0x44204220
  4157c0:	bb 61 74 61 00       	mov    ebx,0x617461
  4157c5:	c7 46 0c e1 00 00 00 	mov    DWORD PTR [esi+0xc],0xe1
  4157cc:	85 d2                	test   edx,edx
  4157ce:	c7 46 10 7c 01 00 00 	mov    DWORD PTR [esi+0x10],0x17c
  4157d5:	89 86 31 19 00 00    	mov    DWORD PTR [esi+0x1931],eax
  4157db:	89 8e 35 19 00 00    	mov    DWORD PTR [esi+0x1935],ecx
  4157e1:	89 9e 39 19 00 00    	mov    DWORD PTR [esi+0x1939],ebx
  4157e7:	75 7a                	jne    415863 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x2b3>
  4157e9:	31 db                	xor    ebx,ebx
  4157eb:	31 c0                	xor    eax,eax
  4157ed:	89 5c 24 2c          	mov    DWORD PTR [esp+0x2c],ebx
  4157f1:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  4157f4:	89 44 24 24          	mov    DWORD PTR [esp+0x24],eax
  4157f8:	89 54 24 28          	mov    DWORD PTR [esp+0x28],edx
  4157fc:	8b 4e 14             	mov    ecx,DWORD PTR [esi+0x14]
  4157ff:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  415803:	8b 5e 10             	mov    ebx,DWORD PTR [esi+0x10]
  415806:	89 5c 24 1c          	mov    DWORD PTR [esp+0x1c],ebx
  41580a:	8b 56 0c             	mov    edx,DWORD PTR [esi+0xc]
  41580d:	bb 00 00 ca 00       	mov    ebx,0xca0000
  415812:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  415816:	8b 46 08             	mov    eax,DWORD PTR [esi+0x8]
  415819:	ba 7c 05 44 00       	mov    edx,0x44057c
  41581e:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  415822:	8b 4e 04             	mov    ecx,DWORD PTR [esi+0x4]
  415825:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  415829:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  41582d:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  415831:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415835:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  41583c:	e8 df 9d 01 00       	call   42f620 <CreateWindowExA@48>
  415841:	89 86 78 1c 00 00    	mov    DWORD PTR [esi+0x1c78],eax
  415847:	83 ec 30             	sub    esp,0x30
  41584a:	85 c0                	test   eax,eax
  41584c:	0f 85 9f 01 00 00    	jne    4159f1 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x441>
  415852:	31 c0                	xor    eax,eax
  415854:	b9 88 05 44 00       	mov    ecx,0x440588
  415859:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  41585d:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  415861:	eb 0f                	jmp    415872 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x2c2>
  415863:	31 c0                	xor    eax,eax
  415865:	b9 a4 05 44 00       	mov    ecx,0x4405a4
  41586a:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  41586e:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  415872:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  415876:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  41587d:	e8 ee 9c 01 00       	call   42f570 <MessageBoxA@16>
  415882:	83 ec 10             	sub    esp,0x10
  415885:	c7 46 04 b4 00 00 00 	mov    DWORD PTR [esi+0x4],0xb4
  41588c:	8b 96 7c 1c 00 00    	mov    edx,DWORD PTR [esi+0x1c7c]
  415892:	b8 54 65 6c 65       	mov    eax,0x656c6554
  415897:	c7 46 08 f0 00 00 00 	mov    DWORD PTR [esi+0x8],0xf0
  41589e:	b9 6d 65 74 72       	mov    ecx,0x7274656d
  4158a3:	bb 79 00 00 00       	mov    ebx,0x79
  4158a8:	c7 46 0c e6 00 00 00 	mov    DWORD PTR [esi+0xc],0xe6
  4158af:	85 d2                	test   edx,edx
  4158b1:	c7 46 10 eb 01 00 00 	mov    DWORD PTR [esi+0x10],0x1eb
  4158b8:	89 86 31 19 00 00    	mov    DWORD PTR [esi+0x1931],eax
  4158be:	89 8e 35 19 00 00    	mov    DWORD PTR [esi+0x1935],ecx
  4158c4:	66 89 9e 39 19 00 00 	mov    WORD PTR [esi+0x1939],bx
  4158cb:	75 76                	jne    415943 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x393>
  4158cd:	31 db                	xor    ebx,ebx
  4158cf:	31 c0                	xor    eax,eax
  4158d1:	89 5c 24 2c          	mov    DWORD PTR [esp+0x2c],ebx
  4158d5:	8b 56 18             	mov    edx,DWORD PTR [esi+0x18]
  4158d8:	89 44 24 24          	mov    DWORD PTR [esp+0x24],eax
  4158dc:	89 54 24 28          	mov    DWORD PTR [esp+0x28],edx
  4158e0:	8b 4e 14             	mov    ecx,DWORD PTR [esi+0x14]
  4158e3:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  4158e7:	8b 5e 10             	mov    ebx,DWORD PTR [esi+0x10]
  4158ea:	89 5c 24 1c          	mov    DWORD PTR [esp+0x1c],ebx
  4158ee:	8b 56 0c             	mov    edx,DWORD PTR [esi+0xc]
  4158f1:	bb 00 00 ca 00       	mov    ebx,0xca0000
  4158f6:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  4158fa:	8b 46 08             	mov    eax,DWORD PTR [esi+0x8]
  4158fd:	ba 7c 05 44 00       	mov    edx,0x44057c
  415902:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  415906:	8b 4e 04             	mov    ecx,DWORD PTR [esi+0x4]
  415909:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  41590d:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  415911:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  415915:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415919:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  415920:	e8 fb 9c 01 00       	call   42f620 <CreateWindowExA@48>
  415925:	89 86 7c 1c 00 00    	mov    DWORD PTR [esi+0x1c7c],eax
  41592b:	83 ec 30             	sub    esp,0x30
  41592e:	85 c0                	test   eax,eax
  415930:	75 3e                	jne    415970 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x3c0>
  415932:	31 c9                	xor    ecx,ecx
  415934:	be 88 05 44 00       	mov    esi,0x440588
  415939:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  41593d:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  415941:	eb 0f                	jmp    415952 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x3a2>
  415943:	31 db                	xor    ebx,ebx
  415945:	be a4 05 44 00       	mov    esi,0x4405a4
  41594a:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  41594e:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  415952:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  415956:	c7 04 24 00 00 00 00 	mov    DWORD PTR [esp],0x0
  41595d:	e8 0e 9c 01 00       	call   42f570 <MessageBoxA@16>
  415962:	83 ec 10             	sub    esp,0x10
  415965:	8d 65 f4             	lea    esp,[ebp-0xc]
  415968:	5b                   	pop    ebx
  415969:	5e                   	pop    esi
  41596a:	5f                   	pop    edi
  41596b:	5d                   	pop    ebp
  41596c:	c3                   	ret
  41596d:	8d 76 00             	lea    esi,[esi+0x0]
  415970:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  415977:	31 ff                	xor    edi,edi
  415979:	e8 72 9b 01 00       	call   42f4f0 <GetStockObject@4>
  41597e:	83 ec 04             	sub    esp,0x4
  415981:	b9 30 00 00 00       	mov    ecx,0x30
  415986:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41598a:	89 7c 24 0c          	mov    DWORD PTR [esp+0xc],edi
  41598e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  415992:	8b 96 7c 1c 00 00    	mov    edx,DWORD PTR [esi+0x1c7c]
  415998:	89 14 24             	mov    DWORD PTR [esp],edx
  41599b:	e8 90 9c 01 00       	call   42f630 <SendMessageA@16>
  4159a0:	8b 86 7c 1c 00 00    	mov    eax,DWORD PTR [esi+0x1c7c]
  4159a6:	83 ec 10             	sub    esp,0x10
  4159a9:	89 04 24             	mov    DWORD PTR [esp],eax
  4159ac:	e8 df 9b 01 00       	call   42f590 <GetDC@4>
  4159b1:	83 ec 04             	sub    esp,0x4
  4159b4:	89 c3                	mov    ebx,eax
  4159b6:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  4159bd:	e8 2e 9b 01 00       	call   42f4f0 <GetStockObject@4>
  4159c2:	83 ec 04             	sub    esp,0x4
  4159c5:	89 1c 24             	mov    DWORD PTR [esp],ebx
  4159c8:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4159cc:	e8 2f 9b 01 00       	call   42f500 <SelectObject@8>
  4159d1:	83 ec 08             	sub    esp,0x8
  4159d4:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  4159d8:	8b be 7c 1c 00 00    	mov    edi,DWORD PTR [esi+0x1c7c]
  4159de:	89 3c 24             	mov    DWORD PTR [esp],edi
  4159e1:	e8 ba 9b 01 00       	call   42f5a0 <ReleaseDC@8>
  4159e6:	83 ec 08             	sub    esp,0x8
  4159e9:	8d 65 f4             	lea    esp,[ebp-0xc]
  4159ec:	5b                   	pop    ebx
  4159ed:	5e                   	pop    esi
  4159ee:	5f                   	pop    edi
  4159ef:	5d                   	pop    ebp
  4159f0:	c3                   	ret
  4159f1:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  4159f8:	31 db                	xor    ebx,ebx
  4159fa:	e8 f1 9a 01 00       	call   42f4f0 <GetStockObject@4>
  4159ff:	83 ec 04             	sub    esp,0x4
  415a02:	ba 30 00 00 00       	mov    edx,0x30
  415a07:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415a0b:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  415a0f:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  415a13:	8b 86 78 1c 00 00    	mov    eax,DWORD PTR [esi+0x1c78]
  415a19:	89 04 24             	mov    DWORD PTR [esp],eax
  415a1c:	e8 0f 9c 01 00       	call   42f630 <SendMessageA@16>
  415a21:	8b 8e 78 1c 00 00    	mov    ecx,DWORD PTR [esi+0x1c78]
  415a27:	83 ec 10             	sub    esp,0x10
  415a2a:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415a2d:	e8 5e 9b 01 00       	call   42f590 <GetDC@4>
  415a32:	83 ec 04             	sub    esp,0x4
  415a35:	89 c3                	mov    ebx,eax
  415a37:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  415a3e:	e8 ad 9a 01 00       	call   42f4f0 <GetStockObject@4>
  415a43:	83 ec 04             	sub    esp,0x4
  415a46:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415a4a:	89 1c 24             	mov    DWORD PTR [esp],ebx
  415a4d:	e8 ae 9a 01 00       	call   42f500 <SelectObject@8>
  415a52:	83 ec 08             	sub    esp,0x8
  415a55:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  415a59:	8b 96 78 1c 00 00    	mov    edx,DWORD PTR [esi+0x1c78]
  415a5f:	89 14 24             	mov    DWORD PTR [esp],edx
  415a62:	e8 39 9b 01 00       	call   42f5a0 <ReleaseDC@8>
  415a67:	83 ec 08             	sub    esp,0x8
  415a6a:	e9 16 fe ff ff       	jmp    415885 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x2d5>
  415a6f:	90                   	nop
  415a70:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  415a77:	31 db                	xor    ebx,ebx
  415a79:	e8 72 9a 01 00       	call   42f4f0 <GetStockObject@4>
  415a7e:	83 ec 04             	sub    esp,0x4
  415a81:	ba 30 00 00 00       	mov    edx,0x30
  415a86:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  415a8a:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  415a8e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  415a92:	8b 86 74 1c 00 00    	mov    eax,DWORD PTR [esi+0x1c74]
  415a98:	89 04 24             	mov    DWORD PTR [esp],eax
  415a9b:	e8 90 9b 01 00       	call   42f630 <SendMessageA@16>
  415aa0:	8b 8e 74 1c 00 00    	mov    ecx,DWORD PTR [esi+0x1c74]
  415aa6:	83 ec 10             	sub    esp,0x10
  415aa9:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415aac:	e8 df 9a 01 00       	call   42f590 <GetDC@4>
  415ab1:	83 ec 04             	sub    esp,0x4
  415ab4:	89 c3                	mov    ebx,eax
  415ab6:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  415abd:	e8 2e 9a 01 00       	call   42f4f0 <GetStockObject@4>
  415ac2:	83 ec 04             	sub    esp,0x4
  415ac5:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415ac9:	89 1c 24             	mov    DWORD PTR [esp],ebx
  415acc:	e8 2f 9a 01 00       	call   42f500 <SelectObject@8>
  415ad1:	83 ec 08             	sub    esp,0x8
  415ad4:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  415ad8:	8b 96 74 1c 00 00    	mov    edx,DWORD PTR [esi+0x1c74]
  415ade:	89 14 24             	mov    DWORD PTR [esp],edx
  415ae1:	e8 ba 9a 01 00       	call   42f5a0 <ReleaseDC@8>
  415ae6:	83 ec 08             	sub    esp,0x8
  415ae9:	e9 b4 fc ff ff       	jmp    4157a2 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x1f2>
  415aee:	89 f6                	mov    esi,esi
  415af0:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  415af7:	31 db                	xor    ebx,ebx
  415af9:	e8 f2 99 01 00       	call   42f4f0 <GetStockObject@4>
  415afe:	83 ec 04             	sub    esp,0x4
  415b01:	b9 30 00 00 00       	mov    ecx,0x30
  415b06:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  415b0a:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  415b0e:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  415b12:	8b 96 70 1c 00 00    	mov    edx,DWORD PTR [esi+0x1c70]
  415b18:	89 14 24             	mov    DWORD PTR [esp],edx
  415b1b:	e8 10 9b 01 00       	call   42f630 <SendMessageA@16>
  415b20:	8b 86 70 1c 00 00    	mov    eax,DWORD PTR [esi+0x1c70]
  415b26:	83 ec 10             	sub    esp,0x10
  415b29:	89 04 24             	mov    DWORD PTR [esp],eax
  415b2c:	e8 5f 9a 01 00       	call   42f590 <GetDC@4>
  415b31:	83 ec 04             	sub    esp,0x4
  415b34:	89 c3                	mov    ebx,eax
  415b36:	c7 04 24 11 00 00 00 	mov    DWORD PTR [esp],0x11
  415b3d:	e8 ae 99 01 00       	call   42f4f0 <GetStockObject@4>
  415b42:	83 ec 04             	sub    esp,0x4
  415b45:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  415b49:	89 1c 24             	mov    DWORD PTR [esp],ebx
  415b4c:	e8 af 99 01 00       	call   42f500 <SelectObject@8>
  415b51:	83 ec 08             	sub    esp,0x8
  415b54:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  415b58:	8b 8e 70 1c 00 00    	mov    ecx,DWORD PTR [esi+0x1c70]
  415b5e:	89 0c 24             	mov    DWORD PTR [esp],ecx
  415b61:	e8 3a 9a 01 00       	call   42f5a0 <ReleaseDC@8>
  415b66:	83 ec 08             	sub    esp,0x8
  415b69:	e9 4a fb ff ff       	jmp    4156b8 <bixby110control::Bixby110DialogSetupUtilityWindows()+0x108>
  415b6e:	89 f6                	mov    esi,esi

# source=Bixby110dlg.cpp
# va=0x00415FE0 size=0xF0
0x00415FE0 <bixby110control::Bixby110DialogSetupUtilityWindowButtons(int, int, int, int)>:
  415fe0:	55                   	push   ebp
  415fe1:	b9 21 a2 43 00       	mov    ecx,0x43a221
  415fe6:	89 e5                	mov    ebp,esp
  415fe8:	57                   	push   edi
  415fe9:	56                   	push   esi
  415fea:	53                   	push   ebx
  415feb:	83 ec 1c             	sub    esp,0x1c
  415fee:	8b 5d 08             	mov    ebx,DWORD PTR [ebp+0x8]
  415ff1:	8b 7d 0c             	mov    edi,DWORD PTR [ebp+0xc]
  415ff4:	8b 75 10             	mov    esi,DWORD PTR [ebp+0x10]
  415ff7:	8b 43 18             	mov    eax,DWORD PTR [ebx+0x18]
  415ffa:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  415ffe:	8b 13                	mov    edx,DWORD PTR [ebx]
  416000:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  416004:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  416008:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  41600c:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  416010:	8b 83 20 07 00 00    	mov    eax,DWORD PTR [ebx+0x720]
  416016:	89 04 24             	mov    DWORD PTR [esp],eax
  416019:	e8 12 99 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  41601e:	0f b6 93 30 19 00 00 	movzx  edx,BYTE PTR [ebx+0x1930]
  416025:	8b 4b 18             	mov    ecx,DWORD PTR [ebx+0x18]
  416028:	01 d6                	add    esi,edx
  41602a:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  41602e:	ba 79 a2 43 00       	mov    edx,0x43a279
  416033:	8b 03                	mov    eax,DWORD PTR [ebx]
  416035:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  416039:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  41603d:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  416041:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  416045:	8b 8b 24 07 00 00    	mov    ecx,DWORD PTR [ebx+0x724]
  41604b:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41604e:	e8 dd 98 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  416053:	0f b6 83 30 19 00 00 	movzx  eax,BYTE PTR [ebx+0x1930]
  41605a:	8b 53 18             	mov    edx,DWORD PTR [ebx+0x18]
  41605d:	01 c6                	add    esi,eax
  41605f:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  416063:	b8 d1 a2 43 00       	mov    eax,0x43a2d1
  416068:	8b 0b                	mov    ecx,DWORD PTR [ebx]
  41606a:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  41606e:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  416072:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  416076:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41607a:	8b 93 28 07 00 00    	mov    edx,DWORD PTR [ebx+0x728]
  416080:	89 14 24             	mov    DWORD PTR [esp],edx
  416083:	e8 a8 98 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  416088:	0f b6 8b 30 19 00 00 	movzx  ecx,BYTE PTR [ebx+0x1930]
  41608f:	8b 43 18             	mov    eax,DWORD PTR [ebx+0x18]
  416092:	01 ce                	add    esi,ecx
  416094:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  416098:	b9 29 a3 43 00       	mov    ecx,0x43a329
  41609d:	8b 13                	mov    edx,DWORD PTR [ebx]
  41609f:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  4160a3:	89 7c 24 08          	mov    DWORD PTR [esp+0x8],edi
  4160a7:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  4160ab:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  4160af:	8b 83 2c 07 00 00    	mov    eax,DWORD PTR [ebx+0x72c]
  4160b5:	89 04 24             	mov    DWORD PTR [esp],eax
  4160b8:	e8 73 98 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  4160bd:	83 c4 1c             	add    esp,0x1c
  4160c0:	5b                   	pop    ebx
  4160c1:	5e                   	pop    esi
  4160c2:	5f                   	pop    edi
  4160c3:	5d                   	pop    ebp
  4160c4:	c3                   	ret
  4160c5:	90                   	nop
  4160c6:	8d 76 00             	lea    esi,[esi+0x0]
  4160c9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
