# Configuration writes, initialization, QuickCal, and debug UI core
# BixCheck 5.0.21; generated by tools/analyze_bixcheck.py
# Exact GNU objdump Intel-syntax excerpts; addresses are build-specific.

# source=Bixby110dlg.cpp
# va=0x00412F20 size=0x7C0
0x00412F20 <bixby110control::Bixby110TuneAdjustments(unsigned char)>:
  412f20:	55                   	push   ebp
  412f21:	89 e5                	mov    ebp,esp
  412f23:	57                   	push   edi
  412f24:	56                   	push   esi
  412f25:	53                   	push   ebx
  412f26:	81 ec 8c 00 00 00    	sub    esp,0x8c
  412f2c:	8b 45 08             	mov    eax,DWORD PTR [ebp+0x8]
  412f2f:	0f b6 55 0c          	movzx  edx,BYTE PTR [ebp+0xc]
  412f33:	c6 45 bb 05          	mov    BYTE PTR [ebp-0x45],0x5
  412f37:	89 45 d4             	mov    DWORD PTR [ebp-0x2c],eax
  412f3a:	c6 45 ba 23          	mov    BYTE PTR [ebp-0x46],0x23
  412f3e:	88 55 d3             	mov    BYTE PTR [ebp-0x2d],dl
  412f41:	fe ca                	dec    dl
  412f43:	74 08                	je     412f4d <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x2d>
  412f45:	c6 45 bb 00          	mov    BYTE PTR [ebp-0x45],0x0
  412f49:	c6 45 ba 00          	mov    BYTE PTR [ebp-0x46],0x0
  412f4d:	c7 45 bc 00 00 00 00 	mov    DWORD PTR [ebp-0x44],0x0
  412f54:	31 db                	xor    ebx,ebx
  412f56:	8b 4d d4             	mov    ecx,DWORD PTR [ebp-0x2c]
  412f59:	8b b4 99 84 06 00 00 	mov    esi,DWORD PTR [ecx+ebx*4+0x684]
  412f60:	89 34 24             	mov    DWORD PTR [esp],esi
  412f63:	e8 38 c8 00 00       	call   41f7a0 <manualradiobutton::IsChecked()>
  412f68:	84 c0                	test   al,al
  412f6a:	74 03                	je     412f6f <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x4f>
  412f6c:	89 5d bc             	mov    DWORD PTR [ebp-0x44],ebx
  412f6f:	43                   	inc    ebx
  412f70:	83 fb 01             	cmp    ebx,0x1
  412f73:	7e e1                	jle    412f56 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x36>
  412f75:	c7 45 cc 00 00 00 00 	mov    DWORD PTR [ebp-0x34],0x0
  412f7c:	31 db                	xor    ebx,ebx
  412f7e:	8b 55 d4             	mov    edx,DWORD PTR [ebp-0x2c]
  412f81:	8b bc 9a 8c 06 00 00 	mov    edi,DWORD PTR [edx+ebx*4+0x68c]
  412f88:	89 3c 24             	mov    DWORD PTR [esp],edi
  412f8b:	e8 10 c8 00 00       	call   41f7a0 <manualradiobutton::IsChecked()>
  412f90:	84 c0                	test   al,al
  412f92:	74 03                	je     412f97 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x77>
  412f94:	89 5d cc             	mov    DWORD PTR [ebp-0x34],ebx
  412f97:	43                   	inc    ebx
  412f98:	83 fb 02             	cmp    ebx,0x2
  412f9b:	7e e1                	jle    412f7e <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x5e>
  412f9d:	0f b6 45 bb          	movzx  eax,BYTE PTR [ebp-0x45]
  412fa1:	80 7d d3 01          	cmp    BYTE PTR [ebp-0x2d],0x1
  412fa5:	89 45 c8             	mov    DWORD PTR [ebp-0x38],eax
  412fa8:	0f 84 43 04 00 00    	je     4133f1 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x4d1>
  412fae:	0f b6 5d bb          	movzx  ebx,BYTE PTR [ebp-0x45]
  412fb2:	8d 43 05             	lea    eax,[ebx+0x5]
  412fb5:	89 c6                	mov    esi,eax
  412fb7:	89 f6                	mov    esi,esi
  412fb9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  412fc0:	8b 7d d4             	mov    edi,DWORD PTR [ebp-0x2c]
  412fc3:	8b 8c 9f 98 06 00 00 	mov    ecx,DWORD PTR [edi+ebx*4+0x698]
  412fca:	89 0c 24             	mov    DWORD PTR [esp],ecx
  412fcd:	e8 ce c7 00 00       	call   41f7a0 <manualradiobutton::IsChecked()>
  412fd2:	84 c0                	test   al,al
  412fd4:	74 03                	je     412fd9 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0xb9>
  412fd6:	89 5d c8             	mov    DWORD PTR [ebp-0x38],ebx
  412fd9:	43                   	inc    ebx
  412fda:	39 de                	cmp    esi,ebx
  412fdc:	7f e2                	jg     412fc0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0xa0>
  412fde:	c7 45 c4 00 00 00 00 	mov    DWORD PTR [ebp-0x3c],0x0
  412fe5:	31 db                	xor    ebx,ebx
  412fe7:	8b 55 d4             	mov    edx,DWORD PTR [ebp-0x2c]
  412fea:	8b b4 9a c0 06 00 00 	mov    esi,DWORD PTR [edx+ebx*4+0x6c0]
  412ff1:	89 34 24             	mov    DWORD PTR [esp],esi
  412ff4:	e8 a7 c7 00 00       	call   41f7a0 <manualradiobutton::IsChecked()>
  412ff9:	84 c0                	test   al,al
  412ffb:	74 03                	je     413000 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0xe0>
  412ffd:	89 5d c4             	mov    DWORD PTR [ebp-0x3c],ebx
  413000:	43                   	inc    ebx
  413001:	83 fb 01             	cmp    ebx,0x1
  413004:	7e e1                	jle    412fe7 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0xc7>
  413006:	c7 45 c0 00 00 00 00 	mov    DWORD PTR [ebp-0x40],0x0
  41300d:	8b 5d d4             	mov    ebx,DWORD PTR [ebp-0x2c]
  413010:	8b 83 c8 06 00 00    	mov    eax,DWORD PTR [ebx+0x6c8]
  413016:	31 db                	xor    ebx,ebx
  413018:	89 04 24             	mov    DWORD PTR [esp],eax
  41301b:	e8 f0 c7 00 00       	call   41f810 <manualradiobutton::SetChecked()>
  413020:	8b 7d d4             	mov    edi,DWORD PTR [ebp-0x2c]
  413023:	8b 8c 9f c8 06 00 00 	mov    ecx,DWORD PTR [edi+ebx*4+0x6c8]
  41302a:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41302d:	e8 6e c7 00 00       	call   41f7a0 <manualradiobutton::IsChecked()>
  413032:	84 c0                	test   al,al
  413034:	74 03                	je     413039 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x119>
  413036:	89 5d c0             	mov    DWORD PTR [ebp-0x40],ebx
  413039:	43                   	inc    ebx
  41303a:	83 fb 01             	cmp    ebx,0x1
  41303d:	7e e1                	jle    413020 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x100>
  41303f:	8b 5d bc             	mov    ebx,DWORD PTR [ebp-0x44]
  413042:	8b 45 d4             	mov    eax,DWORD PTR [ebp-0x2c]
  413045:	8b b4 98 84 06 00 00 	mov    esi,DWORD PTR [eax+ebx*4+0x684]
  41304c:	89 34 24             	mov    DWORD PTR [esp],esi
  41304f:	e8 bc c7 00 00       	call   41f810 <manualradiobutton::SetChecked()>
  413054:	8b 75 d4             	mov    esi,DWORD PTR [ebp-0x2c]
  413057:	8b 55 cc             	mov    edx,DWORD PTR [ebp-0x34]
  41305a:	8b 8c 96 8c 06 00 00 	mov    ecx,DWORD PTR [esi+edx*4+0x68c]
  413061:	89 0c 24             	mov    DWORD PTR [esp],ecx
  413064:	e8 a7 c7 00 00       	call   41f810 <manualradiobutton::SetChecked()>
  413069:	8b 7d c8             	mov    edi,DWORD PTR [ebp-0x38]
  41306c:	8b 9c be 98 06 00 00 	mov    ebx,DWORD PTR [esi+edi*4+0x698]
  413073:	89 1c 24             	mov    DWORD PTR [esp],ebx
  413076:	e8 95 c7 00 00       	call   41f810 <manualradiobutton::SetChecked()>
  41307b:	8b 45 c4             	mov    eax,DWORD PTR [ebp-0x3c]
  41307e:	8b 94 86 c0 06 00 00 	mov    edx,DWORD PTR [esi+eax*4+0x6c0]
  413085:	89 14 24             	mov    DWORD PTR [esp],edx
  413088:	e8 83 c7 00 00       	call   41f810 <manualradiobutton::SetChecked()>
  41308d:	8b 4d c0             	mov    ecx,DWORD PTR [ebp-0x40]
  413090:	8b bc 8e c8 06 00 00 	mov    edi,DWORD PTR [esi+ecx*4+0x6c8]
  413097:	31 f6                	xor    esi,esi
  413099:	89 3c 24             	mov    DWORD PTR [esp],edi
  41309c:	e8 6f c7 00 00       	call   41f810 <manualradiobutton::SetChecked()>
  4130a1:	0f b6 55 bb          	movzx  edx,BYTE PTR [ebp-0x45]
  4130a5:	8b 5d cc             	mov    ebx,DWORD PTR [ebp-0x34]
  4130a8:	8b 4d c8             	mov    ecx,DWORD PTR [ebp-0x38]
  4130ab:	8d 04 5b             	lea    eax,[ebx+ebx*2]
  4130ae:	c1 e0 03             	shl    eax,0x3
  4130b1:	29 d1                	sub    ecx,edx
  4130b3:	89 45 b4             	mov    DWORD PTR [ebp-0x4c],eax
  4130b6:	8b 45 c4             	mov    eax,DWORD PTR [ebp-0x3c]
  4130b9:	8d 1c 49             	lea    ebx,[ecx+ecx*2]
  4130bc:	c1 e3 03             	shl    ebx,0x3
  4130bf:	8d 14 40             	lea    edx,[eax+eax*2]
  4130c2:	8d 3c d5 00 00 00 00 	lea    edi,[edx*8+0x0]
  4130c9:	89 5d b0             	mov    DWORD PTR [ebp-0x50],ebx
  4130cc:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
  4130d0:	8b 4d b4             	mov    ecx,DWORD PTR [ebp-0x4c]
  4130d3:	8b 45 b0             	mov    eax,DWORD PTR [ebp-0x50]
  4130d6:	0f b6 94 31 60 95 43 	movzx  edx,BYTE PTR [ecx+esi*1+0x439560]
  4130dd:	00
  4130de:	0f b6 9c 30 e0 94 43 	movzx  ebx,BYTE PTR [eax+esi*1+0x4394e0]
  4130e5:	00
  4130e6:	0f b6 8c 37 a0 94 43 	movzx  ecx,BYTE PTR [edi+esi*1+0x4394a0]
  4130ed:	00
  4130ee:	6b d2 64             	imul   edx,edx,0x64
  4130f1:	0f af d3             	imul   edx,ebx
  4130f4:	8b 5d c0             	mov    ebx,DWORD PTR [ebp-0x40]
  4130f7:	0f af d1             	imul   edx,ecx
  4130fa:	b9 1f 85 eb 51       	mov    ecx,0x51eb851f
  4130ff:	89 d0                	mov    eax,edx
  413101:	f7 e1                	mul    ecx
  413103:	8d 04 5b             	lea    eax,[ebx+ebx*2]
  413106:	0f b6 9c c6 60 94 43 	movzx  ebx,BYTE PTR [esi+eax*8+0x439460]
  41310d:	00
  41310e:	c1 ea 05             	shr    edx,0x5
  413111:	0f af d3             	imul   edx,ebx
  413114:	89 d0                	mov    eax,edx
  413116:	f7 e1                	mul    ecx
  413118:	c1 ea 05             	shr    edx,0x5
  41311b:	89 d0                	mov    eax,edx
  41311d:	f7 e1                	mul    ecx
  41311f:	c1 ea 05             	shr    edx,0x5
  413122:	89 d0                	mov    eax,edx
  413124:	f7 e1                	mul    ecx
  413126:	c1 ea 05             	shr    edx,0x5
  413129:	81 fa ff 00 00 00    	cmp    edx,0xff
  41312f:	76 05                	jbe    413136 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x216>
  413131:	ba ff 00 00 00       	mov    edx,0xff
  413136:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  41313a:	8d 45 d8             	lea    eax,[ebp-0x28]
  41313d:	ba 5e 03 44 00       	mov    edx,0x44035e
  413142:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  413146:	89 04 24             	mov    DWORD PTR [esp],eax
  413149:	e8 32 c2 01 00       	call   42f380 <sprintf>
  41314e:	0f b6 5d ba          	movzx  ebx,BYTE PTR [ebp-0x46]
  413152:	8d 4d d8             	lea    ecx,[ebp-0x28]
  413155:	8b 55 d4             	mov    edx,DWORD PTR [ebp-0x2c]
  413158:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41315c:	8d 1c 1e             	lea    ebx,[esi+ebx*1]
  41315f:	8b 84 9a 74 04 00 00 	mov    eax,DWORD PTR [edx+ebx*4+0x474]
  413166:	46                   	inc    esi
  413167:	89 04 24             	mov    DWORD PTR [esp],eax
  41316a:	e8 b1 cd 00 00       	call   41ff20 <edit::Settext(char const*)>
  41316f:	8b 55 d4             	mov    edx,DWORD PTR [ebp-0x2c]
  413172:	b9 ff c0 40 00       	mov    ecx,0x40c0ff
  413177:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41317b:	8b 84 9a 74 04 00 00 	mov    eax,DWORD PTR [edx+ebx*4+0x474]
  413182:	89 04 24             	mov    DWORD PTR [esp],eax
  413185:	e8 26 ce 00 00       	call   41ffb0 <edit::SetBkColor(unsigned long)>
  41318a:	83 fe 07             	cmp    esi,0x7
  41318d:	0f 8e 3d ff ff ff    	jle    4130d0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x1b0>
  413193:	0f b6 7d bb          	movzx  edi,BYTE PTR [ebp-0x45]
  413197:	31 f6                	xor    esi,esi
  413199:	8b 4d c8             	mov    ecx,DWORD PTR [ebp-0x38]
  41319c:	8b 5d cc             	mov    ebx,DWORD PTR [ebp-0x34]
  41319f:	89 7d a8             	mov    DWORD PTR [ebp-0x58],edi
  4131a2:	8b 45 a8             	mov    eax,DWORD PTR [ebp-0x58]
  4131a5:	8d 14 5b             	lea    edx,[ebx+ebx*2]
  4131a8:	c1 e2 03             	shl    edx,0x3
  4131ab:	bf 1f 85 eb 51       	mov    edi,0x51eb851f
  4131b0:	89 55 ac             	mov    DWORD PTR [ebp-0x54],edx
  4131b3:	29 c1                	sub    ecx,eax
  4131b5:	8d 1c 49             	lea    ebx,[ecx+ecx*2]
  4131b8:	c1 e3 03             	shl    ebx,0x3
  4131bb:	89 5d a4             	mov    DWORD PTR [ebp-0x5c],ebx
  4131be:	89 f6                	mov    esi,esi
  4131c0:	8b 5d ac             	mov    ebx,DWORD PTR [ebp-0x54]
  4131c3:	8b 55 a4             	mov    edx,DWORD PTR [ebp-0x5c]
  4131c6:	0f b6 84 1e 68 95 43 	movzx  eax,BYTE PTR [esi+ebx*1+0x439568]
  4131cd:	00
  4131ce:	0f b6 8c 16 e8 94 43 	movzx  ecx,BYTE PTR [esi+edx*1+0x4394e8]
  4131d5:	00
  4131d6:	6b d8 64             	imul   ebx,eax,0x64
  4131d9:	8b 45 c4             	mov    eax,DWORD PTR [ebp-0x3c]
  4131dc:	8d 14 40             	lea    edx,[eax+eax*2]
  4131df:	0f af d9             	imul   ebx,ecx
  4131e2:	0f b6 8c d6 a8 94 43 	movzx  ecx,BYTE PTR [esi+edx*8+0x4394a8]
  4131e9:	00
  4131ea:	0f af d9             	imul   ebx,ecx
  4131ed:	89 d8                	mov    eax,ebx
  4131ef:	f7 e7                	mul    edi
  4131f1:	8b 45 c0             	mov    eax,DWORD PTR [ebp-0x40]
  4131f4:	89 d3                	mov    ebx,edx
  4131f6:	8d 14 40             	lea    edx,[eax+eax*2]
  4131f9:	c1 eb 05             	shr    ebx,0x5
  4131fc:	0f b6 8c d6 68 94 43 	movzx  ecx,BYTE PTR [esi+edx*8+0x439468]
  413203:	00
  413204:	0f af d9             	imul   ebx,ecx
  413207:	89 d8                	mov    eax,ebx
  413209:	f7 e7                	mul    edi
  41320b:	89 d3                	mov    ebx,edx
  41320d:	c1 eb 05             	shr    ebx,0x5
  413210:	89 d8                	mov    eax,ebx
  413212:	8b 5d c8             	mov    ebx,DWORD PTR [ebp-0x38]
  413215:	f7 e7                	mul    edi
  413217:	89 d1                	mov    ecx,edx
  413219:	c1 e9 05             	shr    ecx,0x5
  41321c:	89 c8                	mov    eax,ecx
  41321e:	f7 e7                	mul    edi
  413220:	89 d1                	mov    ecx,edx
  413222:	c1 e9 05             	shr    ecx,0x5
  413225:	39 5d a8             	cmp    DWORD PTR [ebp-0x58],ebx
  413228:	0f 94 c2             	sete   dl
  41322b:	83 7d bc 01          	cmp    DWORD PTR [ebp-0x44],0x1
  41322f:	0f 94 c0             	sete   al
  413232:	84 d0                	test   al,dl
  413234:	74 0d                	je     413243 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x323>
  413236:	8d 04 89             	lea    eax,[ecx+ecx*4]
  413239:	c1 e0 04             	shl    eax,0x4
  41323c:	f7 e7                	mul    edi
  41323e:	89 d1                	mov    ecx,edx
  413240:	c1 e9 05             	shr    ecx,0x5
  413243:	81 f9 ff 00 00 00    	cmp    ecx,0xff
  413249:	76 05                	jbe    413250 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x330>
  41324b:	b9 ff 00 00 00       	mov    ecx,0xff
  413250:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  413254:	ba 5e 03 44 00       	mov    edx,0x44035e
  413259:	8d 4d d8             	lea    ecx,[ebp-0x28]
  41325c:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  413260:	89 0c 24             	mov    DWORD PTR [esp],ecx
  413263:	e8 18 c1 01 00       	call   42f380 <sprintf>
  413268:	0f b6 5d ba          	movzx  ebx,BYTE PTR [ebp-0x46]
  41326c:	8d 45 d8             	lea    eax,[ebp-0x28]
  41326f:	8b 55 d4             	mov    edx,DWORD PTR [ebp-0x2c]
  413272:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  413276:	8d 1c 1e             	lea    ebx,[esi+ebx*1]
  413279:	8b 8c 9a 94 04 00 00 	mov    ecx,DWORD PTR [edx+ebx*4+0x494]
  413280:	46                   	inc    esi
  413281:	89 0c 24             	mov    DWORD PTR [esp],ecx
  413284:	e8 97 cc 00 00       	call   41ff20 <edit::Settext(char const*)>
  413289:	8b 4d d4             	mov    ecx,DWORD PTR [ebp-0x2c]
  41328c:	b8 ff c0 40 00       	mov    eax,0x40c0ff
  413291:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  413295:	8b 94 99 94 04 00 00 	mov    edx,DWORD PTR [ecx+ebx*4+0x494]
  41329c:	89 14 24             	mov    DWORD PTR [esp],edx
  41329f:	e8 0c cd 00 00       	call   41ffb0 <edit::SetBkColor(unsigned long)>
  4132a4:	83 fe 07             	cmp    esi,0x7
  4132a7:	0f 8e 13 ff ff ff    	jle    4131c0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x2a0>
  4132ad:	0f b6 45 bb          	movzx  eax,BYTE PTR [ebp-0x45]
  4132b1:	31 ff                	xor    edi,edi
  4132b3:	8b 5d c8             	mov    ebx,DWORD PTR [ebp-0x38]
  4132b6:	8b 55 cc             	mov    edx,DWORD PTR [ebp-0x34]
  4132b9:	29 c3                	sub    ebx,eax
  4132bb:	8d 0c 52             	lea    ecx,[edx+edx*2]
  4132be:	89 45 9c             	mov    DWORD PTR [ebp-0x64],eax
  4132c1:	8d 34 5b             	lea    esi,[ebx+ebx*2]
  4132c4:	c1 e1 03             	shl    ecx,0x3
  4132c7:	89 4d a0             	mov    DWORD PTR [ebp-0x60],ecx
  4132ca:	c1 e6 03             	shl    esi,0x3
  4132cd:	89 75 98             	mov    DWORD PTR [ebp-0x68],esi
  4132d0:	8b 75 a0             	mov    esi,DWORD PTR [ebp-0x60]
  4132d3:	8b 4d 98             	mov    ecx,DWORD PTR [ebp-0x68]
  4132d6:	8b 55 c4             	mov    edx,DWORD PTR [ebp-0x3c]
  4132d9:	0f b6 9c 37 70 95 43 	movzx  ebx,BYTE PTR [edi+esi*1+0x439570]
  4132e0:	00
  4132e1:	0f b6 84 0f f0 94 43 	movzx  eax,BYTE PTR [edi+ecx*1+0x4394f0]
  4132e8:	00
  4132e9:	6b f3 64             	imul   esi,ebx,0x64
  4132ec:	8d 1c 52             	lea    ebx,[edx+edx*2]
  4132ef:	0f b6 8c df b0 94 43 	movzx  ecx,BYTE PTR [edi+ebx*8+0x4394b0]
  4132f6:	00
  4132f7:	0f af f0             	imul   esi,eax
  4132fa:	0f af f1             	imul   esi,ecx
  4132fd:	b9 1f 85 eb 51       	mov    ecx,0x51eb851f
  413302:	89 f0                	mov    eax,esi
  413304:	f7 e1                	mul    ecx
  413306:	8b 45 c0             	mov    eax,DWORD PTR [ebp-0x40]
  413309:	89 d6                	mov    esi,edx
  41330b:	8d 14 40             	lea    edx,[eax+eax*2]
  41330e:	c1 ee 05             	shr    esi,0x5
  413311:	0f b6 9c d7 70 94 43 	movzx  ebx,BYTE PTR [edi+edx*8+0x439470]
  413318:	00
  413319:	0f af f3             	imul   esi,ebx
  41331c:	89 f0                	mov    eax,esi
  41331e:	f7 e1                	mul    ecx
  413320:	89 d3                	mov    ebx,edx
  413322:	c1 eb 05             	shr    ebx,0x5
  413325:	89 d8                	mov    eax,ebx
  413327:	f7 e1                	mul    ecx
  413329:	89 d6                	mov    esi,edx
  41332b:	c1 ee 05             	shr    esi,0x5
  41332e:	89 f0                	mov    eax,esi
  413330:	f7 e1                	mul    ecx
  413332:	8b 45 bc             	mov    eax,DWORD PTR [ebp-0x44]
  413335:	89 d6                	mov    esi,edx
  413337:	8b 55 c8             	mov    edx,DWORD PTR [ebp-0x38]
  41333a:	c1 ee 05             	shr    esi,0x5
  41333d:	39 55 9c             	cmp    DWORD PTR [ebp-0x64],edx
  413340:	0f 94 c1             	sete   cl
  413343:	85 c0                	test   eax,eax
  413345:	0f 94 c3             	sete   bl
  413348:	84 cb                	test   bl,cl
  41334a:	74 15                	je     413361 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x441>
  41334c:	8d 1c b6             	lea    ebx,[esi+esi*4]
  41334f:	b9 d3 4d 62 10       	mov    ecx,0x10624dd3
  413354:	8d 04 9b             	lea    eax,[ebx+ebx*4]
  413357:	c1 e0 02             	shl    eax,0x2
  41335a:	f7 e1                	mul    ecx
  41335c:	89 d6                	mov    esi,edx
  41335e:	c1 ee 03             	shr    esi,0x3
  413361:	81 fe ff 00 00 00    	cmp    esi,0xff
  413367:	76 05                	jbe    41336e <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x44e>
  413369:	be ff 00 00 00       	mov    esi,0xff
  41336e:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  413372:	ba 5e 03 44 00       	mov    edx,0x44035e
  413377:	8d 4d d8             	lea    ecx,[ebp-0x28]
  41337a:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  41337e:	89 0c 24             	mov    DWORD PTR [esp],ecx
  413381:	e8 fa bf 01 00       	call   42f380 <sprintf>
  413386:	0f b6 5d ba          	movzx  ebx,BYTE PTR [ebp-0x46]
  41338a:	8d 45 d8             	lea    eax,[ebp-0x28]
  41338d:	8b 55 d4             	mov    edx,DWORD PTR [ebp-0x2c]
  413390:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  413394:	8d 1c 1f             	lea    ebx,[edi+ebx*1]
  413397:	8b 8c 9a b4 04 00 00 	mov    ecx,DWORD PTR [edx+ebx*4+0x4b4]
  41339e:	47                   	inc    edi
  41339f:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4133a2:	e8 79 cb 00 00       	call   41ff20 <edit::Settext(char const*)>
  4133a7:	8b 4d d4             	mov    ecx,DWORD PTR [ebp-0x2c]
  4133aa:	b8 ff c0 40 00       	mov    eax,0x40c0ff
  4133af:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4133b3:	8b 94 99 b4 04 00 00 	mov    edx,DWORD PTR [ecx+ebx*4+0x4b4]
  4133ba:	89 14 24             	mov    DWORD PTR [esp],edx
  4133bd:	e8 ee cb 00 00       	call   41ffb0 <edit::SetBkColor(unsigned long)>
  4133c2:	83 ff 07             	cmp    edi,0x7
  4133c5:	0f 8e 05 ff ff ff    	jle    4132d0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x3b0>
  4133cb:	bf 18 00 00 00       	mov    edi,0x18
  4133d0:	8d 04 bf             	lea    eax,[edi+edi*4]
  4133d3:	8d 1c 47             	lea    ebx,[edi+eax*2]
  4133d6:	0f b6 04 dd 29 ad 43 	movzx  eax,BYTE PTR [ebx*8+0x43ad29]
  4133dd:	00
  4133de:	83 e8 58             	sub    eax,0x58
  4133e1:	83 f8 09             	cmp    eax,0x9
  4133e4:	0f 87 b6 00 00 00    	ja     4134a0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x580>
  4133ea:	ff 24 85 ac 04 44 00 	jmp    DWORD PTR [eax*4+0x4404ac]
  4133f1:	83 c0 04             	add    eax,0x4
  4133f4:	89 45 c8             	mov    DWORD PTR [ebp-0x38],eax
  4133f7:	e9 b2 fb ff ff       	jmp    412fae <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x8e>
  4133fc:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
  413400:	31 db                	xor    ebx,ebx
  413402:	0f b6 45 bb          	movzx  eax,BYTE PTR [ebp-0x45]
  413406:	8b 75 cc             	mov    esi,DWORD PTR [ebp-0x34]
  413409:	8d 14 76             	lea    edx,[esi+esi*2]
  41340c:	89 45 94             	mov    DWORD PTR [ebp-0x6c],eax
  41340f:	01 da                	add    edx,ebx
  413411:	0f b6 0c d5 60 95 43 	movzx  ecx,BYTE PTR [edx*8+0x439560]
  413418:	00
  413419:	8b 55 94             	mov    edx,DWORD PTR [ebp-0x6c]
  41341c:	6b f1 64             	imul   esi,ecx,0x64
  41341f:	8b 4d c8             	mov    ecx,DWORD PTR [ebp-0x38]
  413422:	29 d1                	sub    ecx,edx
  413424:	8d 04 49             	lea    eax,[ecx+ecx*2]
  413427:	01 d8                	add    eax,ebx
  413429:	8b 55 c4             	mov    edx,DWORD PTR [ebp-0x3c]
  41342c:	0f b6 0c c5 e0 94 43 	movzx  ecx,BYTE PTR [eax*8+0x4394e0]
  413433:	00
  413434:	8d 04 52             	lea    eax,[edx+edx*2]
  413437:	01 d8                	add    eax,ebx
  413439:	0f af f1             	imul   esi,ecx
  41343c:	0f b6 0c c5 a7 94 43 	movzx  ecx,BYTE PTR [eax*8+0x4394a7]
  413443:	00
  413444:	0f af f1             	imul   esi,ecx
  413447:	b9 1f 85 eb 51       	mov    ecx,0x51eb851f
  41344c:	89 f0                	mov    eax,esi
  41344e:	8b 75 c0             	mov    esi,DWORD PTR [ebp-0x40]
  413451:	f7 e1                	mul    ecx
  413453:	8d 04 76             	lea    eax,[esi+esi*2]
  413456:	01 d8                	add    eax,ebx
  413458:	0f b6 04 c5 67 94 43 	movzx  eax,BYTE PTR [eax*8+0x439467]
  41345f:	00
  413460:	c1 ea 05             	shr    edx,0x5
  413463:	0f af c2             	imul   eax,edx
  413466:	f7 e1                	mul    ecx
  413468:	89 d6                	mov    esi,edx
  41346a:	c1 ee 05             	shr    esi,0x5
  41346d:	89 f0                	mov    eax,esi
  41346f:	f7 e1                	mul    ecx
  413471:	89 d6                	mov    esi,edx
  413473:	c1 ee 05             	shr    esi,0x5
  413476:	89 f0                	mov    eax,esi
  413478:	f7 e1                	mul    ecx
  41347a:	89 d6                	mov    esi,edx
  41347c:	c1 ee 05             	shr    esi,0x5
  41347f:	4b                   	dec    ebx
  413480:	0f 84 1c 02 00 00    	je     4136a2 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x782>
  413486:	81 fe ff 00 00 00    	cmp    esi,0xff
  41348c:	76 12                	jbe    4134a0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x580>
  41348e:	be ff 00 00 00       	mov    esi,0xff
  413493:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  413499:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  4134a0:	8d 14 bf             	lea    edx,[edi+edi*4]
  4134a3:	8d 0c 57             	lea    ecx,[edi+edx*2]
  4134a6:	0f b6 14 cd 29 ad 43 	movzx  edx,BYTE PTR [ecx*8+0x43ad29]
  4134ad:	00
  4134ae:	80 fa 5b             	cmp    dl,0x5b
  4134b1:	0f 84 b0 00 00 00    	je     413567 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x647>
  4134b7:	80 fa 64             	cmp    dl,0x64
  4134ba:	0f 84 d0 00 00 00    	je     413590 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x670>
  4134c0:	80 fa 68             	cmp    dl,0x68
  4134c3:	0f 84 f7 00 00 00    	je     4135c0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x6a0>
  4134c9:	80 fa 69             	cmp    dl,0x69
  4134cc:	0f 84 5e 01 00 00    	je     413630 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x710>
  4134d2:	80 fa 63             	cmp    dl,0x63
  4134d5:	0f 84 75 01 00 00    	je     413650 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x730>
  4134db:	80 fa 5a             	cmp    dl,0x5a
  4134de:	0f 84 5c 01 00 00    	je     413640 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x720>
  4134e4:	80 fa 62             	cmp    dl,0x62
  4134e7:	0f 84 53 01 00 00    	je     413640 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x720>
  4134ed:	8d 76 00             	lea    esi,[esi+0x0]
  4134f0:	0f b6 45 bb          	movzx  eax,BYTE PTR [ebp-0x45]
  4134f4:	8b 4d c8             	mov    ecx,DWORD PTR [ebp-0x38]
  4134f7:	29 c1                	sub    ecx,eax
  4134f9:	83 f9 04             	cmp    ecx,0x4
  4134fc:	0f 84 de 00 00 00    	je     4135e0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x6c0>
  413502:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  413506:	8d 5d d8             	lea    ebx,[ebp-0x28]
  413509:	b8 5e 03 44 00       	mov    eax,0x44035e
  41350e:	89 1c 24             	mov    DWORD PTR [esp],ebx
  413511:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  413515:	e8 66 be 01 00       	call   42f380 <sprintf>
  41351a:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41351e:	0f b6 5d ba          	movzx  ebx,BYTE PTR [ebp-0x46]
  413522:	8b 4d d4             	mov    ecx,DWORD PTR [ebp-0x2c]
  413525:	8d 1c 1f             	lea    ebx,[edi+ebx*1]
  413528:	8b 84 99 74 04 00 00 	mov    eax,DWORD PTR [ecx+ebx*4+0x474]
  41352f:	47                   	inc    edi
  413530:	89 04 24             	mov    DWORD PTR [esp],eax
  413533:	e8 e8 c9 00 00       	call   41ff20 <edit::Settext(char const*)>
  413538:	8b 4d d4             	mov    ecx,DWORD PTR [ebp-0x2c]
  41353b:	ba ff c0 40 00       	mov    edx,0x40c0ff
  413540:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  413544:	8b 84 99 74 04 00 00 	mov    eax,DWORD PTR [ecx+ebx*4+0x474]
  41354b:	89 04 24             	mov    DWORD PTR [esp],eax
  41354e:	e8 5d ca 00 00       	call   41ffb0 <edit::SetBkColor(unsigned long)>
  413553:	83 ff 22             	cmp    edi,0x22
  413556:	0f 8e 74 fe ff ff    	jle    4133d0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x4b0>
  41355c:	81 c4 8c 00 00 00    	add    esp,0x8c
  413562:	5b                   	pop    ebx
  413563:	5e                   	pop    esi
  413564:	5f                   	pop    edi
  413565:	5d                   	pop    ebp
  413566:	c3                   	ret
  413567:	0f b6 45 bb          	movzx  eax,BYTE PTR [ebp-0x45]
  41356b:	8b 4d c8             	mov    ecx,DWORD PTR [ebp-0x38]
  41356e:	29 c1                	sub    ecx,eax
  413570:	83 f9 03             	cmp    ecx,0x3
  413573:	0f 95 c3             	setne  bl
  413576:	0f b6 c3             	movzx  eax,bl
  413579:	48                   	dec    eax
  41357a:	83 e0 e7             	and    eax,0xffffffe7
  41357d:	80 fa 64             	cmp    dl,0x64
  413580:	8d 70 64             	lea    esi,[eax+0x64]
  413583:	0f 85 37 ff ff ff    	jne    4134c0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x5a0>
  413589:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]
  413590:	0f b6 45 bb          	movzx  eax,BYTE PTR [ebp-0x45]
  413594:	8b 5d c8             	mov    ebx,DWORD PTR [ebp-0x38]
  413597:	29 c3                	sub    ebx,eax
  413599:	89 de                	mov    esi,ebx
  41359b:	4e                   	dec    esi
  41359c:	0f 95 c1             	setne  cl
  41359f:	0f b6 d9             	movzx  ebx,cl
  4135a2:	4b                   	dec    ebx
  4135a3:	83 e3 ce             	and    ebx,0xffffffce
  4135a6:	80 fa 68             	cmp    dl,0x68
  4135a9:	8d 73 64             	lea    esi,[ebx+0x64]
  4135ac:	0f 85 17 ff ff ff    	jne    4134c9 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x5a9>
  4135b2:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]
  4135b9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  4135c0:	0f b6 45 bb          	movzx  eax,BYTE PTR [ebp-0x45]
  4135c4:	be 32 00 00 00       	mov    esi,0x32
  4135c9:	8b 4d c8             	mov    ecx,DWORD PTR [ebp-0x38]
  4135cc:	29 c1                	sub    ecx,eax
  4135ce:	83 f9 04             	cmp    ecx,0x4
  4135d1:	0f 85 2b ff ff ff    	jne    413502 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x5e2>
  4135d7:	89 f6                	mov    esi,esi
  4135d9:	8d bc 27 00 00 00 00 	lea    edi,[edi+eiz*1+0x0]
  4135e0:	80 fa 58             	cmp    dl,0x58
  4135e3:	0f 84 85 00 00 00    	je     41366e <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x74e>
  4135e9:	8d 0c bf             	lea    ecx,[edi+edi*4]
  4135ec:	8d 1c 4f             	lea    ebx,[edi+ecx*2]
  4135ef:	0f b6 04 dd 29 ad 43 	movzx  eax,BYTE PTR [ebx*8+0x43ad29]
  4135f6:	00
  4135f7:	3c 59                	cmp    al,0x59
  4135f9:	74 6c                	je     413667 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x747>
  4135fb:	3c 5a                	cmp    al,0x5a
  4135fd:	74 61                	je     413660 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x740>
  4135ff:	3c 5b                	cmp    al,0x5b
  413601:	74 5d                	je     413660 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x740>
  413603:	3c 60                	cmp    al,0x60
  413605:	0f 84 78 00 00 00    	je     413683 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x763>
  41360b:	90                   	nop
  41360c:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
  413610:	8d 1c bf             	lea    ebx,[edi+edi*4]
  413613:	8d 14 5f             	lea    edx,[edi+ebx*2]
  413616:	80 3c d5 29 ad 43 00 	cmp    BYTE PTR [edx*8+0x43ad29],0x61
  41361d:	61
  41361e:	0f 85 de fe ff ff    	jne    413502 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x5e2>
  413624:	be 55 00 00 00       	mov    esi,0x55
  413629:	e9 d4 fe ff ff       	jmp    413502 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x5e2>
  41362e:	89 f6                	mov    esi,esi
  413630:	be aa 00 00 00       	mov    esi,0xaa
  413635:	e9 b6 fe ff ff       	jmp    4134f0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x5d0>
  41363a:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  413640:	be 64 00 00 00       	mov    esi,0x64
  413645:	e9 a6 fe ff ff       	jmp    4134f0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x5d0>
  41364a:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  413650:	be 04 00 00 00       	mov    esi,0x4
  413655:	e9 96 fe ff ff       	jmp    4134f0 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x5d0>
  41365a:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  413660:	be 4b 00 00 00       	mov    esi,0x4b
  413665:	eb a9                	jmp    413610 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x6f0>
  413667:	be 96 00 00 00       	mov    esi,0x96
  41366c:	eb a2                	jmp    413610 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x6f0>
  41366e:	31 d2                	xor    edx,edx
  413670:	83 7d c4 01          	cmp    DWORD PTR [ebp-0x3c],0x1
  413674:	0f 94 c2             	sete   dl
  413677:	4a                   	dec    edx
  413678:	83 e2 de             	and    edx,0xffffffde
  41367b:	8d 72 72             	lea    esi,[edx+0x72]
  41367e:	e9 66 ff ff ff       	jmp    4135e9 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x6c9>
  413683:	31 c0                	xor    eax,eax
  413685:	83 7d c4 01          	cmp    DWORD PTR [ebp-0x3c],0x1
  413689:	0f 94 c0             	sete   al
  41368c:	48                   	dec    eax
  41368d:	83 e0 de             	and    eax,0xffffffde
  413690:	8d 70 72             	lea    esi,[eax+0x72]
  413693:	e9 78 ff ff ff       	jmp    413610 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x6f0>
  413698:	bb 01 00 00 00       	mov    ebx,0x1
  41369d:	e9 60 fd ff ff       	jmp    413402 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x4e2>
  4136a2:	8b 4d c8             	mov    ecx,DWORD PTR [ebp-0x38]
  4136a5:	39 4d 94             	cmp    DWORD PTR [ebp-0x6c],ecx
  4136a8:	0f 94 c0             	sete   al
  4136ab:	83 7d bc 01          	cmp    DWORD PTR [ebp-0x44],0x1
  4136af:	0f 94 c3             	sete   bl
  4136b2:	84 c3                	test   bl,al
  4136b4:	0f 84 cc fd ff ff    	je     413486 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x566>
  4136ba:	8d 1c b6             	lea    ebx,[esi+esi*4]
  4136bd:	8d 04 9b             	lea    eax,[ebx+ebx*4]
  4136c0:	be d3 4d 62 10       	mov    esi,0x10624dd3
  4136c5:	c1 e0 02             	shl    eax,0x2
  4136c8:	f7 e6                	mul    esi
  4136ca:	89 d6                	mov    esi,edx
  4136cc:	c1 ee 03             	shr    esi,0x3
  4136cf:	e9 b2 fd ff ff       	jmp    413486 <bixby110control::Bixby110TuneAdjustments(unsigned char)+0x566>
  4136d4:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  4136da:	8d bf 00 00 00 00    	lea    edi,[edi+0x0]

# source=Bixby110dlg.cpp
# va=0x004136E0 size=0x120
0x004136E0 <bixby110control::Bixby110Initialize(unsigned char, unsigned char)>:
  4136e0:	55                   	push   ebp
  4136e1:	ba 02 00 00 00       	mov    edx,0x2
  4136e6:	89 e5                	mov    ebp,esp
  4136e8:	56                   	push   esi
  4136e9:	b8 41 00 00 00       	mov    eax,0x41
  4136ee:	53                   	push   ebx
  4136ef:	83 ec 20             	sub    esp,0x20
  4136f2:	8b 75 08             	mov    esi,DWORD PTR [ebp+0x8]
  4136f5:	80 7d 10 01          	cmp    BYTE PTR [ebp+0x10],0x1
  4136f9:	0f b6 4d 0c          	movzx  ecx,BYTE PTR [ebp+0xc]
  4136fd:	8d 9e fc 10 00 00    	lea    ebx,[esi+0x10fc]
  413703:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  413707:	0f 95 45 f7          	setne  BYTE PTR [ebp-0x9]
  41370b:	fe 4d f7             	dec    BYTE PTR [ebp-0x9]
  41370e:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  413712:	89 1c 24             	mov    DWORD PTR [esp],ebx
  413715:	80 65 f7 23          	and    BYTE PTR [ebp-0x9],0x23
  413719:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41371d:	e8 6e 57 ff ff       	call   408e90 <bixby110io::writereg(unsigned char, unsigned char, unsigned char)>
  413722:	b9 64 00 00 00       	mov    ecx,0x64
  413727:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  41372b:	8b 16                	mov    edx,DWORD PTR [esi]
  41372d:	89 14 24             	mov    DWORD PTR [esp],edx
  413730:	e8 0b 47 ff ff       	call   407e40 <TimeDelay(HWND__*, unsigned int)>
  413735:	0f b6 45 f7          	movzx  eax,BYTE PTR [ebp-0x9]
  413739:	c6 45 f6 07          	mov    BYTE PTR [ebp-0xa],0x7
  41373d:	8d 9c 86 5c 03 00 00 	lea    ebx,[esi+eax*4+0x35c]
  413744:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  41374a:	8d bf 00 00 00 00    	lea    edi,[edi+0x0]
  413750:	8b 03                	mov    eax,DWORD PTR [ebx]
  413752:	83 c3 04             	add    ebx,0x4
  413755:	89 04 24             	mov    DWORD PTR [esp],eax
  413758:	e8 43 c3 00 00       	call   41faa0 <pushbutton::SetSimulatedPush()>
  41375d:	fe 4d f6             	dec    BYTE PTR [ebp-0xa]
  413760:	79 ee                	jns    413750 <bixby110control::Bixby110Initialize(unsigned char, unsigned char)+0x70>
  413762:	0f b6 55 f7          	movzx  edx,BYTE PTR [ebp-0x9]
  413766:	c6 45 f5 07          	mov    BYTE PTR [ebp-0xb],0x7
  41376a:	8d 9c 96 7c 03 00 00 	lea    ebx,[esi+edx*4+0x37c]
  413771:	eb 0d                	jmp    413780 <bixby110control::Bixby110Initialize(unsigned char, unsigned char)+0xa0>
  413773:	90                   	nop
  413774:	90                   	nop
  413775:	90                   	nop
  413776:	90                   	nop
  413777:	90                   	nop
  413778:	90                   	nop
  413779:	90                   	nop
  41377a:	90                   	nop
  41377b:	90                   	nop
  41377c:	90                   	nop
  41377d:	90                   	nop
  41377e:	90                   	nop
  41377f:	90                   	nop
  413780:	8b 0b                	mov    ecx,DWORD PTR [ebx]
  413782:	83 c3 04             	add    ebx,0x4
  413785:	89 0c 24             	mov    DWORD PTR [esp],ecx
  413788:	e8 13 c3 00 00       	call   41faa0 <pushbutton::SetSimulatedPush()>
  41378d:	fe 4d f5             	dec    BYTE PTR [ebp-0xb]
  413790:	79 ee                	jns    413780 <bixby110control::Bixby110Initialize(unsigned char, unsigned char)+0xa0>
  413792:	0f b6 45 f7          	movzx  eax,BYTE PTR [ebp-0x9]
  413796:	c6 45 f4 07          	mov    BYTE PTR [ebp-0xc],0x7
  41379a:	8d 9c 86 9c 03 00 00 	lea    ebx,[esi+eax*4+0x39c]
  4137a1:	eb 0d                	jmp    4137b0 <bixby110control::Bixby110Initialize(unsigned char, unsigned char)+0xd0>
  4137a3:	90                   	nop
  4137a4:	90                   	nop
  4137a5:	90                   	nop
  4137a6:	90                   	nop
  4137a7:	90                   	nop
  4137a8:	90                   	nop
  4137a9:	90                   	nop
  4137aa:	90                   	nop
  4137ab:	90                   	nop
  4137ac:	90                   	nop
  4137ad:	90                   	nop
  4137ae:	90                   	nop
  4137af:	90                   	nop
  4137b0:	8b 13                	mov    edx,DWORD PTR [ebx]
  4137b2:	83 c3 04             	add    ebx,0x4
  4137b5:	89 14 24             	mov    DWORD PTR [esp],edx
  4137b8:	e8 e3 c2 00 00       	call   41faa0 <pushbutton::SetSimulatedPush()>
  4137bd:	fe 4d f4             	dec    BYTE PTR [ebp-0xc]
  4137c0:	79 ee                	jns    4137b0 <bixby110control::Bixby110Initialize(unsigned char, unsigned char)+0xd0>
  4137c2:	0f b6 4d f7          	movzx  ecx,BYTE PTR [ebp-0x9]
  4137c6:	c6 45 f3 0a          	mov    BYTE PTR [ebp-0xd],0xa
  4137ca:	8d 9c 8e bc 03 00 00 	lea    ebx,[esi+ecx*4+0x3bc]
  4137d1:	eb 0d                	jmp    4137e0 <bixby110control::Bixby110Initialize(unsigned char, unsigned char)+0x100>
  4137d3:	90                   	nop
  4137d4:	90                   	nop
  4137d5:	90                   	nop
  4137d6:	90                   	nop
  4137d7:	90                   	nop
  4137d8:	90                   	nop
  4137d9:	90                   	nop
  4137da:	90                   	nop
  4137db:	90                   	nop
  4137dc:	90                   	nop
  4137dd:	90                   	nop
  4137de:	90                   	nop
  4137df:	90                   	nop
  4137e0:	8b 33                	mov    esi,DWORD PTR [ebx]
  4137e2:	83 c3 04             	add    ebx,0x4
  4137e5:	89 34 24             	mov    DWORD PTR [esp],esi
  4137e8:	e8 b3 c2 00 00       	call   41faa0 <pushbutton::SetSimulatedPush()>
  4137ed:	fe 4d f3             	dec    BYTE PTR [ebp-0xd]
  4137f0:	79 ee                	jns    4137e0 <bixby110control::Bixby110Initialize(unsigned char, unsigned char)+0x100>
  4137f2:	83 c4 20             	add    esp,0x20
  4137f5:	5b                   	pop    ebx
  4137f6:	5e                   	pop    esi
  4137f7:	5d                   	pop    ebp
  4137f8:	c3                   	ret
  4137f9:	90                   	nop
  4137fa:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]

# source=Bixby110dlg.cpp
# va=0x00414310 size=0x310
0x00414310 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)>:
  414310:	55                   	push   ebp
  414311:	b9 6d 65 74 72       	mov    ecx,0x7274656d
  414316:	89 e5                	mov    ebp,esp
  414318:	57                   	push   edi
  414319:	ba 79 00 00 00       	mov    edx,0x79
  41431e:	56                   	push   esi
  41431f:	53                   	push   ebx
  414320:	81 ec 5c 01 00 00    	sub    esp,0x15c
  414326:	bb 54 65 6c 65       	mov    ebx,0x656c6554
  41432b:	89 9d e8 fe ff ff    	mov    DWORD PTR [ebp-0x118],ebx
  414331:	8b 7d 08             	mov    edi,DWORD PTR [ebp+0x8]
  414334:	8d 9d e8 fe ff ff    	lea    ebx,[ebp-0x118]
  41433a:	89 8d ec fe ff ff    	mov    DWORD PTR [ebp-0x114],ecx
  414340:	8b 75 10             	mov    esi,DWORD PTR [ebp+0x10]
  414343:	66 89 95 f0 fe ff ff 	mov    WORD PTR [ebp-0x110],dx
  41434a:	8b 07                	mov    eax,DWORD PTR [edi]
  41434c:	89 04 24             	mov    DWORD PTR [esp],eax
  41434f:	e8 3c b2 01 00       	call   42f590 <GetDC@4>
  414354:	89 85 d8 fe ff ff    	mov    DWORD PTR [ebp-0x128],eax
  41435a:	83 ec 04             	sub    esp,0x4
  41435d:	89 d9                	mov    ecx,ebx
  41435f:	90                   	nop
  414360:	8b 01                	mov    eax,DWORD PTR [ecx]
  414362:	83 c1 04             	add    ecx,0x4
  414365:	8d 90 ff fe fe fe    	lea    edx,[eax-0x1010101]
  41436b:	f7 d0                	not    eax
  41436d:	21 c2                	and    edx,eax
  41436f:	89 d0                	mov    eax,edx
  414371:	25 80 80 80 80       	and    eax,0x80808080
  414376:	74 e8                	je     414360 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)+0x50>
  414378:	81 e2 80 80 00 00    	and    edx,0x8080
  41437e:	75 06                	jne    414386 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)+0x76>
  414380:	c1 e8 10             	shr    eax,0x10
  414383:	83 c1 02             	add    ecx,0x2
  414386:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41438a:	00 c0                	add    al,al
  41438c:	8d 85 e0 fe ff ff    	lea    eax,[ebp-0x120]
  414392:	83 d9 03             	sbb    ecx,0x3
  414395:	29 d9                	sub    ecx,ebx
  414397:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  41439b:	8b 8d d8 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x128]
  4143a1:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  4143a5:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4143a8:	e8 33 b1 01 00       	call   42f4e0 <GetTextExtentPoint32A@16>
  4143ad:	8b 95 d8 fe ff ff    	mov    edx,DWORD PTR [ebp-0x128]
  4143b3:	83 ec 10             	sub    esp,0x10
  4143b6:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  4143ba:	8b 07                	mov    eax,DWORD PTR [edi]
  4143bc:	89 04 24             	mov    DWORD PTR [esp],eax
  4143bf:	e8 dc b1 01 00       	call   42f5a0 <ReleaseDC@8>
  4143c4:	0f b6 9f 30 19 00 00 	movzx  ebx,BYTE PTR [edi+0x1930]
  4143cb:	31 d2                	xor    edx,edx
  4143cd:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  4143d0:	89 95 d0 fe ff ff    	mov    DWORD PTR [ebp-0x130],edx
  4143d6:	83 ec 08             	sub    esp,0x8
  4143d9:	43                   	inc    ebx
  4143da:	89 9d dc fe ff ff    	mov    DWORD PTR [ebp-0x124],ebx
  4143e0:	81 c1 82 00 00 00    	add    ecx,0x82
  4143e6:	31 db                	xor    ebx,ebx
  4143e8:	89 8d d4 fe ff ff    	mov    DWORD PTR [ebp-0x12c],ecx
  4143ee:	eb 41                	jmp    414431 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)+0x121>
  4143f0:	3c 02                	cmp    al,0x2
  4143f2:	0f 84 f8 00 00 00    	je     4144f0 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)+0x1e0>
  4143f8:	3c 03                	cmp    al,0x3
  4143fa:	0f 84 90 01 00 00    	je     414590 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)+0x280>
  414400:	b8 49 05 44 00       	mov    eax,0x440549
  414405:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  414409:	8b 8c 9f 04 06 00 00 	mov    ecx,DWORD PTR [edi+ebx*4+0x604]
  414410:	43                   	inc    ebx
  414411:	89 0c 24             	mov    DWORD PTR [esp],ecx
  414414:	e8 07 bb 00 00       	call   41ff20 <edit::Settext(char const*)>
  414419:	83 85 d0 fe ff ff 58 	add    DWORD PTR [ebp-0x130],0x58
  414420:	8b 95 e4 fe ff ff    	mov    edx,DWORD PTR [ebp-0x11c]
  414426:	01 d6                	add    esi,edx
  414428:	83 fb 07             	cmp    ebx,0x7
  41442b:	0f 8f e6 01 00 00    	jg     414617 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)+0x307>
  414431:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  414437:	0f b6 82 b6 c5 43 00 	movzx  eax,BYTE PTR [edx+0x43c5b6]
  41443e:	3c 01                	cmp    al,0x1
  414440:	75 ae                	jne    4143f0 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)+0xe0>
  414442:	8b 47 18             	mov    eax,DWORD PTR [edi+0x18]
  414445:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  414449:	8b 0f                	mov    ecx,DWORD PTR [edi]
  41444b:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  41444f:	b9 6e 00 00 00       	mov    ecx,0x6e
  414454:	0f b6 87 30 19 00 00 	movzx  eax,BYTE PTR [edi+0x1930]
  41445b:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  41445f:	89 d1                	mov    ecx,edx
  414461:	81 c1 61 c5 43 00    	add    ecx,0x43c561
  414467:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  41446b:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  41446e:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  414472:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  414476:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  41447a:	8b 94 9f c4 05 00 00 	mov    edx,DWORD PTR [edi+ebx*4+0x5c4]
  414481:	89 14 24             	mov    DWORD PTR [esp],edx
  414484:	e8 77 be 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  414489:	31 c0                	xor    eax,eax
  41448b:	89 44 24 20          	mov    DWORD PTR [esp+0x20],eax
  41448f:	8b 4f 18             	mov    ecx,DWORD PTR [edi+0x18]
  414492:	8b 85 dc fe ff ff    	mov    eax,DWORD PTR [ebp-0x124]
  414498:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  41449c:	8b 17                	mov    edx,DWORD PTR [edi]
  41449e:	b9 96 00 00 00       	mov    ecx,0x96
  4144a3:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  4144a7:	b8 49 05 44 00       	mov    eax,0x440549
  4144ac:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  4144b0:	8b 95 d4 fe ff ff    	mov    edx,DWORD PTR [ebp-0x12c]
  4144b6:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  4144ba:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  4144be:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  4144c2:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4144c6:	8b 8c 9f 04 06 00 00 	mov    ecx,DWORD PTR [edi+ebx*4+0x604]
  4144cd:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4144d0:	e8 4b b9 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  4144d5:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  4144db:	0f b6 82 b6 c5 43 00 	movzx  eax,BYTE PTR [edx+0x43c5b6]
  4144e2:	3c 02                	cmp    al,0x2
  4144e4:	0f 85 0e ff ff ff    	jne    4143f8 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)+0xe8>
  4144ea:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
  4144f0:	8b 4f 18             	mov    ecx,DWORD PTR [edi+0x18]
  4144f3:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  4144f6:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  4144fa:	8b 8d d0 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x130]
  414500:	8b 17                	mov    edx,DWORD PTR [edi]
  414502:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  414506:	81 c1 61 c5 43 00    	add    ecx,0x43c561
  41450c:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  414510:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  414514:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  414518:	8b 94 9f e4 05 00 00 	mov    edx,DWORD PTR [edi+ebx*4+0x5e4]
  41451f:	89 14 24             	mov    DWORD PTR [esp],edx
  414522:	e8 09 b4 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  414527:	b8 80 00 00 00       	mov    eax,0x80
  41452c:	89 44 24 20          	mov    DWORD PTR [esp+0x20],eax
  414530:	8b 4f 18             	mov    ecx,DWORD PTR [edi+0x18]
  414533:	8b 85 dc fe ff ff    	mov    eax,DWORD PTR [ebp-0x124]
  414539:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  41453d:	8b 17                	mov    edx,DWORD PTR [edi]
  41453f:	b9 96 00 00 00       	mov    ecx,0x96
  414544:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  414548:	b8 49 05 44 00       	mov    eax,0x440549
  41454d:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  414551:	8b 95 d4 fe ff ff    	mov    edx,DWORD PTR [ebp-0x12c]
  414557:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  41455b:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  41455f:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  414563:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  414567:	8b 8c 9f 04 06 00 00 	mov    ecx,DWORD PTR [edi+ebx*4+0x604]
  41456e:	89 0c 24             	mov    DWORD PTR [esp],ecx
  414571:	e8 aa b8 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  414576:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  41457c:	0f b6 82 b6 c5 43 00 	movzx  eax,BYTE PTR [edx+0x43c5b6]
  414583:	3c 03                	cmp    al,0x3
  414585:	0f 85 75 fe ff ff    	jne    414400 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)+0xf0>
  41458b:	90                   	nop
  41458c:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
  414590:	8b 47 18             	mov    eax,DWORD PTR [edi+0x18]
  414593:	8b 55 0c             	mov    edx,DWORD PTR [ebp+0xc]
  414596:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  41459a:	8b 85 d0 fe ff ff    	mov    eax,DWORD PTR [ebp-0x130]
  4145a0:	8b 0f                	mov    ecx,DWORD PTR [edi]
  4145a2:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  4145a6:	05 61 c5 43 00       	add    eax,0x43c561
  4145ab:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  4145af:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  4145b3:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  4145b7:	8b 8c 9f e4 05 00 00 	mov    ecx,DWORD PTR [edi+ebx*4+0x5e4]
  4145be:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4145c1:	e8 6a b3 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  4145c6:	31 d2                	xor    edx,edx
  4145c8:	89 54 24 20          	mov    DWORD PTR [esp+0x20],edx
  4145cc:	8b 47 18             	mov    eax,DWORD PTR [edi+0x18]
  4145cf:	8b 95 dc fe ff ff    	mov    edx,DWORD PTR [ebp-0x124]
  4145d5:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  4145d9:	8b 0f                	mov    ecx,DWORD PTR [edi]
  4145db:	b8 96 00 00 00       	mov    eax,0x96
  4145e0:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  4145e4:	ba 49 05 44 00       	mov    edx,0x440549
  4145e9:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  4145ed:	8b 8d d4 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x12c]
  4145f3:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  4145f7:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  4145fb:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  4145ff:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  414603:	8b 84 9f 04 06 00 00 	mov    eax,DWORD PTR [edi+ebx*4+0x604]
  41460a:	89 04 24             	mov    DWORD PTR [esp],eax
  41460d:	e8 0e b8 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  414612:	e9 e9 fd ff ff       	jmp    414400 <bixby110control::Bixby110DialogSetupIndividualization(int, int, int, int)+0xf0>
  414617:	8d 65 f4             	lea    esp,[ebp-0xc]
  41461a:	5b                   	pop    ebx
  41461b:	5e                   	pop    esi
  41461c:	5f                   	pop    edi
  41461d:	5d                   	pop    ebp
  41461e:	c3                   	ret
  41461f:	90                   	nop

# source=Bixby110dlg.cpp
# va=0x00414620 size=0x4B0
0x00414620 <bixby110control::Bixby110DialogSetupQuickCal(int, int, int, int)>:
  414620:	55                   	push   ebp
  414621:	b9 6d 65 74 72       	mov    ecx,0x7274656d
  414626:	89 e5                	mov    ebp,esp
  414628:	57                   	push   edi
  414629:	ba 79 00 00 00       	mov    edx,0x79
  41462e:	56                   	push   esi
  41462f:	53                   	push   ebx
  414630:	81 ec 5c 01 00 00    	sub    esp,0x15c
  414636:	bb 54 65 6c 65       	mov    ebx,0x656c6554
  41463b:	89 9d e8 fe ff ff    	mov    DWORD PTR [ebp-0x118],ebx
  414641:	8b 7d 08             	mov    edi,DWORD PTR [ebp+0x8]
  414644:	8d 9d e8 fe ff ff    	lea    ebx,[ebp-0x118]
  41464a:	89 8d ec fe ff ff    	mov    DWORD PTR [ebp-0x114],ecx
  414650:	66 89 95 f0 fe ff ff 	mov    WORD PTR [ebp-0x110],dx
  414657:	8b 07                	mov    eax,DWORD PTR [edi]
  414659:	89 04 24             	mov    DWORD PTR [esp],eax
  41465c:	e8 2f af 01 00       	call   42f590 <GetDC@4>
  414661:	83 ec 04             	sub    esp,0x4
  414664:	89 c6                	mov    esi,eax
  414666:	89 d9                	mov    ecx,ebx
  414668:	90                   	nop
  414669:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]
  414670:	8b 01                	mov    eax,DWORD PTR [ecx]
  414672:	83 c1 04             	add    ecx,0x4
  414675:	8d 90 ff fe fe fe    	lea    edx,[eax-0x1010101]
  41467b:	f7 d0                	not    eax
  41467d:	21 c2                	and    edx,eax
  41467f:	89 d0                	mov    eax,edx
  414681:	25 80 80 80 80       	and    eax,0x80808080
  414686:	74 e8                	je     414670 <bixby110control::Bixby110DialogSetupQuickCal(int, int, int, int)+0x50>
  414688:	81 e2 80 80 00 00    	and    edx,0x8080
  41468e:	75 06                	jne    414696 <bixby110control::Bixby110DialogSetupQuickCal(int, int, int, int)+0x76>
  414690:	c1 e8 10             	shr    eax,0x10
  414693:	83 c1 02             	add    ecx,0x2
  414696:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  41469a:	00 c0                	add    al,al
  41469c:	8d 95 e0 fe ff ff    	lea    edx,[ebp-0x120]
  4146a2:	83 d9 03             	sbb    ecx,0x3
  4146a5:	29 d9                	sub    ecx,ebx
  4146a7:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  4146ab:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  4146af:	89 34 24             	mov    DWORD PTR [esp],esi
  4146b2:	e8 29 ae 01 00       	call   42f4e0 <GetTextExtentPoint32A@16>
  4146b7:	83 ec 10             	sub    esp,0x10
  4146ba:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  4146be:	8b 0f                	mov    ecx,DWORD PTR [edi]
  4146c0:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4146c3:	e8 d8 ae 01 00       	call   42f5a0 <ReleaseDC@8>
  4146c8:	8b 47 18             	mov    eax,DWORD PTR [edi+0x18]
  4146cb:	83 ec 08             	sub    esp,0x8
  4146ce:	8b b5 e4 fe ff ff    	mov    esi,DWORD PTR [ebp-0x11c]
  4146d4:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  4146d8:	8b 1f                	mov    ebx,DWORD PTR [edi]
  4146da:	46                   	inc    esi
  4146db:	89 b5 dc fe ff ff    	mov    DWORD PTR [ebp-0x124],esi
  4146e1:	8b 45 10             	mov    eax,DWORD PTR [ebp+0x10]
  4146e4:	8b 95 dc fe ff ff    	mov    edx,DWORD PTR [ebp-0x124]
  4146ea:	89 5c 24 18          	mov    DWORD PTR [esp+0x18],ebx
  4146ee:	8b 5d 0c             	mov    ebx,DWORD PTR [ebp+0xc]
  4146f1:	be 82 00 00 00       	mov    esi,0x82
  4146f6:	89 74 24 10          	mov    DWORD PTR [esp+0x10],esi
  4146fa:	8d 4c 12 01          	lea    ecx,[edx+edx*1+0x1]
  4146fe:	83 eb 05             	sub    ebx,0x5
  414701:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  414705:	b9 49 05 44 00       	mov    ecx,0x440549
  41470a:	89 5c 24 08          	mov    DWORD PTR [esp+0x8],ebx
  41470e:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  414712:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  414716:	8b 97 d0 06 00 00    	mov    edx,DWORD PTR [edi+0x6d0]
  41471c:	89 9d d8 fe ff ff    	mov    DWORD PTR [ebp-0x128],ebx
  414722:	31 db                	xor    ebx,ebx
  414724:	89 14 24             	mov    DWORD PTR [esp],edx
  414727:	e8 e4 bc 00 00       	call   420410 <staticborder::CreateStaticborder(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  41472c:	8b 75 0c             	mov    esi,DWORD PTR [ebp+0xc]
  41472f:	83 c6 09             	add    esi,0x9
  414732:	89 b5 d4 fe ff ff    	mov    DWORD PTR [ebp-0x12c],esi
  414738:	be 01 ab 43 00       	mov    esi,0x43ab01
  41473d:	8b 57 18             	mov    edx,DWORD PTR [edi+0x18]
  414740:	8b 45 10             	mov    eax,DWORD PTR [ebp+0x10]
  414743:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  414747:	8b 0f                	mov    ecx,DWORD PTR [edi]
  414749:	40                   	inc    eax
  41474a:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  41474e:	8b 95 d4 fe ff ff    	mov    edx,DWORD PTR [ebp-0x12c]
  414754:	83 c6 58             	add    esi,0x58
  414757:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  41475b:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  41475f:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  414763:	8b 8c 9f 84 06 00 00 	mov    ecx,DWORD PTR [edi+ebx*4+0x684]
  41476a:	43                   	inc    ebx
  41476b:	89 0c 24             	mov    DWORD PTR [esp],ecx
  41476e:	e8 2d af 00 00       	call   41f6a0 <manualradiobutton::CreateManualRadiobutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  414773:	8b 85 dc fe ff ff    	mov    eax,DWORD PTR [ebp-0x124]
  414779:	01 45 10             	add    DWORD PTR [ebp+0x10],eax
  41477c:	83 fb 01             	cmp    ebx,0x1
  41477f:	7e bc                	jle    41473d <bixby110control::Bixby110DialogSetupQuickCal(int, int, int, int)+0x11d>
  414781:	8b 4f 18             	mov    ecx,DWORD PTR [edi+0x18]
  414784:	ba 82 00 00 00       	mov    edx,0x82
  414789:	8b b5 dc fe ff ff    	mov    esi,DWORD PTR [ebp-0x124]
  41478f:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  414793:	8b 07                	mov    eax,DWORD PTR [edi]
  414795:	8d 5c 76 01          	lea    ebx,[esi+esi*2+0x1]
  414799:	89 5c 24 14          	mov    DWORD PTR [esp+0x14],ebx
  41479d:	8b 4d 10             	mov    ecx,DWORD PTR [ebp+0x10]
  4147a0:	be 49 05 44 00       	mov    esi,0x440549
  4147a5:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  4147a9:	31 f6                	xor    esi,esi
  4147ab:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  4147af:	8b 85 d8 fe ff ff    	mov    eax,DWORD PTR [ebp-0x128]
  4147b5:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  4147b9:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  4147bd:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  4147c1:	8b 9f d4 06 00 00    	mov    ebx,DWORD PTR [edi+0x6d4]
  4147c7:	89 1c 24             	mov    DWORD PTR [esp],ebx
  4147ca:	bb e1 a9 43 00       	mov    ebx,0x43a9e1
  4147cf:	e8 3c bc 00 00       	call   420410 <staticborder::CreateStaticborder(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  4147d4:	8b 47 18             	mov    eax,DWORD PTR [edi+0x18]
  4147d7:	8b 4d 10             	mov    ecx,DWORD PTR [ebp+0x10]
  4147da:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  4147de:	8b 17                	mov    edx,DWORD PTR [edi]
  4147e0:	41                   	inc    ecx
  4147e1:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  4147e5:	8b 85 d4 fe ff ff    	mov    eax,DWORD PTR [ebp-0x12c]
  4147eb:	83 c3 58             	add    ebx,0x58
  4147ee:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  4147f2:	89 4c 24 0c          	mov    DWORD PTR [esp+0xc],ecx
  4147f6:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  4147fa:	8b 94 b7 8c 06 00 00 	mov    edx,DWORD PTR [edi+esi*4+0x68c]
  414801:	46                   	inc    esi
  414802:	89 14 24             	mov    DWORD PTR [esp],edx
  414805:	e8 96 ae 00 00       	call   41f6a0 <manualradiobutton::CreateManualRadiobutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  41480a:	8b 95 dc fe ff ff    	mov    edx,DWORD PTR [ebp-0x124]
  414810:	01 55 10             	add    DWORD PTR [ebp+0x10],edx
  414813:	83 fe 02             	cmp    esi,0x2
  414816:	7e bc                	jle    4147d4 <bixby110control::Bixby110DialogSetupQuickCal(int, int, int, int)+0x1b4>
  414818:	8b 5f 18             	mov    ebx,DWORD PTR [edi+0x18]
  41481b:	8d 04 52             	lea    eax,[edx+edx*2]
  41481e:	b9 82 00 00 00       	mov    ecx,0x82
  414823:	8d 54 00 01          	lea    edx,[eax+eax*1+0x1]
  414827:	b8 49 05 44 00       	mov    eax,0x440549
  41482c:	89 5c 24 1c          	mov    DWORD PTR [esp+0x1c],ebx
  414830:	8b 37                	mov    esi,DWORD PTR [edi]
  414832:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  414836:	8b 5d 10             	mov    ebx,DWORD PTR [ebp+0x10]
  414839:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  41483d:	89 74 24 18          	mov    DWORD PTR [esp+0x18],esi
  414841:	8b b5 d8 fe ff ff    	mov    esi,DWORD PTR [ebp-0x128]
  414847:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  41484b:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  41484f:	89 74 24 08          	mov    DWORD PTR [esp+0x8],esi
  414853:	8b 97 d8 06 00 00    	mov    edx,DWORD PTR [edi+0x6d8]
  414859:	89 14 24             	mov    DWORD PTR [esp],edx
  41485c:	e8 af bb 00 00       	call   420410 <staticborder::CreateStaticborder(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  414861:	8b 4f 18             	mov    ecx,DWORD PTR [edi+0x18]
  414864:	b8 78 00 00 00       	mov    eax,0x78
  414869:	8b 55 10             	mov    edx,DWORD PTR [ebp+0x10]
  41486c:	8b b5 dc fe ff ff    	mov    esi,DWORD PTR [ebp-0x124]
  414872:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  414876:	8b 1f                	mov    ebx,DWORD PTR [edi]
  414878:	42                   	inc    edx
  414879:	89 54 24 0c          	mov    DWORD PTR [esp+0xc],edx
  41487d:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  414880:	89 74 24 14          	mov    DWORD PTR [esp+0x14],esi
  414884:	89 5c 24 18          	mov    DWORD PTR [esp+0x18],ebx
  414888:	bb f9 cc 43 00       	mov    ebx,0x43ccf9
  41488d:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  414891:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  414895:	bb 19 a8 43 00       	mov    ebx,0x43a819
  41489a:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  41489e:	8b b7 c0 05 00 00    	mov    esi,DWORD PTR [edi+0x5c0]
  4148a4:	89 34 24             	mov    DWORD PTR [esp],esi
  4148a7:	e8 54 ba 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  4148ac:	89 9d c8 fe ff ff    	mov    DWORD PTR [ebp-0x138],ebx
  4148b2:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  4148b5:	31 d2                	xor    edx,edx
  4148b7:	89 95 c4 fe ff ff    	mov    DWORD PTR [ebp-0x13c],edx
  4148bd:	8b 75 10             	mov    esi,DWORD PTR [ebp+0x10]
  4148c0:	8b 85 dc fe ff ff    	mov    eax,DWORD PTR [ebp-0x124]
  4148c6:	83 c1 12             	add    ecx,0x12
  4148c9:	89 8d d0 fe ff ff    	mov    DWORD PTR [ebp-0x130],ecx
  4148cf:	01 c6                	add    esi,eax
  4148d1:	eb 0d                	jmp    4148e0 <bixby110control::Bixby110DialogSetupQuickCal(int, int, int, int)+0x2c0>
  4148d3:	90                   	nop
  4148d4:	90                   	nop
  4148d5:	90                   	nop
  4148d6:	90                   	nop
  4148d7:	90                   	nop
  4148d8:	90                   	nop
  4148d9:	90                   	nop
  4148da:	90                   	nop
  4148db:	90                   	nop
  4148dc:	90                   	nop
  4148dd:	90                   	nop
  4148de:	90                   	nop
  4148df:	90                   	nop
  4148e0:	8b 47 18             	mov    eax,DWORD PTR [edi+0x18]
  4148e3:	ba 4a 05 44 00       	mov    edx,0x44054a
  4148e8:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  4148eb:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  4148ef:	8b 1f                	mov    ebx,DWORD PTR [edi]
  4148f1:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  4148f5:	8b 85 c4 fe ff ff    	mov    eax,DWORD PTR [ebp-0x13c]
  4148fb:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  4148ff:	89 5c 24 10          	mov    DWORD PTR [esp+0x10],ebx
  414903:	8d 5e 01             	lea    ebx,[esi+0x1]
  414906:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  41490a:	8b 8c 87 98 06 00 00 	mov    ecx,DWORD PTR [edi+eax*4+0x698]
  414911:	89 0c 24             	mov    DWORD PTR [esp],ecx
  414914:	e8 87 ad 00 00       	call   41f6a0 <manualradiobutton::CreateManualRadiobutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  414919:	8b 57 18             	mov    edx,DWORD PTR [edi+0x18]
  41491c:	8b 8d d0 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x130]
  414922:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  414926:	8b 07                	mov    eax,DWORD PTR [edi]
  414928:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  41492c:	8b 9d c8 fe ff ff    	mov    ebx,DWORD PTR [ebp-0x138]
  414932:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  414936:	8b 95 c4 fe ff ff    	mov    edx,DWORD PTR [ebp-0x13c]
  41493c:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  414940:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  414944:	8b 84 97 ac 06 00 00 	mov    eax,DWORD PTR [edi+edx*4+0x6ac]
  41494b:	89 04 24             	mov    DWORD PTR [esp],eax
  41494e:	e8 4d ad 00 00       	call   41f6a0 <manualradiobutton::CreateManualRadiobutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  414953:	ff 85 c4 fe ff ff    	inc    DWORD PTR [ebp-0x13c]
  414959:	8b 8d dc fe ff ff    	mov    ecx,DWORD PTR [ebp-0x124]
  41495f:	83 85 c8 fe ff ff 58 	add    DWORD PTR [ebp-0x138],0x58
  414966:	01 ce                	add    esi,ecx
  414968:	83 bd c4 fe ff ff 04 	cmp    DWORD PTR [ebp-0x13c],0x4
  41496f:	0f 8e 6b ff ff ff    	jle    4148e0 <bixby110control::Bixby110DialogSetupQuickCal(int, int, int, int)+0x2c0>
  414975:	8b 57 18             	mov    edx,DWORD PTR [edi+0x18]
  414978:	8b 9d dc fe ff ff    	mov    ebx,DWORD PTR [ebp-0x124]
  41497e:	89 54 24 1c          	mov    DWORD PTR [esp+0x1c],edx
  414982:	8b 07                	mov    eax,DWORD PTR [edi]
  414984:	8d 4c 1b 01          	lea    ecx,[ebx+ebx*1+0x1]
  414988:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  41498c:	ba 82 00 00 00       	mov    edx,0x82
  414991:	bb 49 05 44 00       	mov    ebx,0x440549
  414996:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  41499a:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  41499e:	8b 85 d8 fe ff ff    	mov    eax,DWORD PTR [ebp-0x128]
  4149a4:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  4149a8:	31 db                	xor    ebx,ebx
  4149aa:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  4149ae:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  4149b2:	8b 8f dc 06 00 00    	mov    ecx,DWORD PTR [edi+0x6dc]
  4149b8:	89 0c 24             	mov    DWORD PTR [esp],ecx
  4149bb:	e8 50 ba 00 00       	call   420410 <staticborder::CreateStaticborder(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  4149c0:	ba a1 a5 43 00       	mov    edx,0x43a5a1
  4149c5:	89 95 cc fe ff ff    	mov    DWORD PTR [ebp-0x134],edx
  4149cb:	8b 4f 18             	mov    ecx,DWORD PTR [edi+0x18]
  4149ce:	8d 46 01             	lea    eax,[esi+0x1]
  4149d1:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  4149d5:	8b 17                	mov    edx,DWORD PTR [edi]
  4149d7:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  4149db:	8b 8d d4 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x12c]
  4149e1:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  4149e5:	8b 95 cc fe ff ff    	mov    edx,DWORD PTR [ebp-0x134]
  4149eb:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  4149ef:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  4149f3:	8b 84 9f c0 06 00 00 	mov    eax,DWORD PTR [edi+ebx*4+0x6c0]
  4149fa:	43                   	inc    ebx
  4149fb:	89 04 24             	mov    DWORD PTR [esp],eax
  4149fe:	e8 9d ac 00 00       	call   41f6a0 <manualradiobutton::CreateManualRadiobutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  414a03:	83 85 cc fe ff ff 58 	add    DWORD PTR [ebp-0x134],0x58
  414a0a:	8b 8d dc fe ff ff    	mov    ecx,DWORD PTR [ebp-0x124]
  414a10:	01 ce                	add    esi,ecx
  414a12:	83 fb 01             	cmp    ebx,0x1
  414a15:	7e b4                	jle    4149cb <bixby110control::Bixby110DialogSetupQuickCal(int, int, int, int)+0x3ab>
  414a17:	8b 4f 18             	mov    ecx,DWORD PTR [edi+0x18]
  414a1a:	8b 9d dc fe ff ff    	mov    ebx,DWORD PTR [ebp-0x124]
  414a20:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  414a23:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  414a27:	8b 17                	mov    edx,DWORD PTR [edi]
  414a29:	d1 fb                	sar    ebx,1
  414a2b:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  414a2f:	8d 5c 33 02          	lea    ebx,[ebx+esi*1+0x2]
  414a33:	be 4c 05 44 00       	mov    esi,0x44054c
  414a38:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  414a3c:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  414a40:	89 74 24 04          	mov    DWORD PTR [esp+0x4],esi
  414a44:	8b 8f e8 06 00 00    	mov    ecx,DWORD PTR [edi+0x6e8]
  414a4a:	89 0c 24             	mov    DWORD PTR [esp],ecx
  414a4d:	e8 de ae 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  414a52:	8b 47 18             	mov    eax,DWORD PTR [edi+0x18]
  414a55:	8b 95 dc fe ff ff    	mov    edx,DWORD PTR [ebp-0x124]
  414a5b:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  414a5e:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  414a62:	8b 37                	mov    esi,DWORD PTR [edi]
  414a64:	01 d3                	add    ebx,edx
  414a66:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  414a6a:	ba 5a 05 44 00       	mov    edx,0x44055a
  414a6f:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  414a73:	89 74 24 10          	mov    DWORD PTR [esp+0x10],esi
  414a77:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  414a7b:	8b 87 ec 06 00 00    	mov    eax,DWORD PTR [edi+0x6ec]
  414a81:	89 04 24             	mov    DWORD PTR [esp],eax
  414a84:	e8 a7 ae 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  414a89:	8b 4f 18             	mov    ecx,DWORD PTR [edi+0x18]
  414a8c:	8b b5 dc fe ff ff    	mov    esi,DWORD PTR [ebp-0x124]
  414a92:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  414a95:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  414a99:	8b 17                	mov    edx,DWORD PTR [edi]
  414a9b:	01 f3                	add    ebx,esi
  414a9d:	89 5c 24 0c          	mov    DWORD PTR [esp+0xc],ebx
  414aa1:	bb 6b 05 44 00       	mov    ebx,0x44056b
  414aa6:	89 5c 24 04          	mov    DWORD PTR [esp+0x4],ebx
  414aaa:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  414aae:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  414ab2:	8b b7 f0 06 00 00    	mov    esi,DWORD PTR [edi+0x6f0]
  414ab8:	89 34 24             	mov    DWORD PTR [esp],esi
  414abb:	e8 70 ae 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  414ac0:	8d 65 f4             	lea    esp,[ebp-0xc]
  414ac3:	5b                   	pop    ebx
  414ac4:	5e                   	pop    esi
  414ac5:	5f                   	pop    edi
  414ac6:	5d                   	pop    ebp
  414ac7:	c3                   	ret
  414ac8:	90                   	nop
  414ac9:	8d b4 26 00 00 00 00 	lea    esi,[esi+eiz*1+0x0]

# source=Bixby110dlg.cpp
# va=0x00414AD0 size=0x340
0x00414AD0 <bixby110control::Bixby110DialogSetupDebug(int, int, int, int)>:
  414ad0:	55                   	push   ebp
  414ad1:	b9 6d 65 74 72       	mov    ecx,0x7274656d
  414ad6:	89 e5                	mov    ebp,esp
  414ad8:	57                   	push   edi
  414ad9:	ba 79 00 00 00       	mov    edx,0x79
  414ade:	bf 54 65 6c 65       	mov    edi,0x656c6554
  414ae3:	56                   	push   esi
  414ae4:	53                   	push   ebx
  414ae5:	81 ec 5c 01 00 00    	sub    esp,0x15c
  414aeb:	8b 5d 08             	mov    ebx,DWORD PTR [ebp+0x8]
  414aee:	89 bd e8 fe ff ff    	mov    DWORD PTR [ebp-0x118],edi
  414af4:	8b 75 10             	mov    esi,DWORD PTR [ebp+0x10]
  414af7:	8d bd e8 fe ff ff    	lea    edi,[ebp-0x118]
  414afd:	89 8d ec fe ff ff    	mov    DWORD PTR [ebp-0x114],ecx
  414b03:	66 89 95 f0 fe ff ff 	mov    WORD PTR [ebp-0x110],dx
  414b0a:	8b 03                	mov    eax,DWORD PTR [ebx]
  414b0c:	89 04 24             	mov    DWORD PTR [esp],eax
  414b0f:	e8 7c aa 01 00       	call   42f590 <GetDC@4>
  414b14:	89 85 d8 fe ff ff    	mov    DWORD PTR [ebp-0x128],eax
  414b1a:	83 ec 04             	sub    esp,0x4
  414b1d:	89 f9                	mov    ecx,edi
  414b1f:	90                   	nop
  414b20:	8b 01                	mov    eax,DWORD PTR [ecx]
  414b22:	83 c1 04             	add    ecx,0x4
  414b25:	8d 90 ff fe fe fe    	lea    edx,[eax-0x1010101]
  414b2b:	f7 d0                	not    eax
  414b2d:	21 c2                	and    edx,eax
  414b2f:	89 d0                	mov    eax,edx
  414b31:	25 80 80 80 80       	and    eax,0x80808080
  414b36:	74 e8                	je     414b20 <bixby110control::Bixby110DialogSetupDebug(int, int, int, int)+0x50>
  414b38:	81 e2 80 80 00 00    	and    edx,0x8080
  414b3e:	75 06                	jne    414b46 <bixby110control::Bixby110DialogSetupDebug(int, int, int, int)+0x76>
  414b40:	c1 e8 10             	shr    eax,0x10
  414b43:	83 c1 02             	add    ecx,0x2
  414b46:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  414b4a:	00 c0                	add    al,al
  414b4c:	8d 85 e0 fe ff ff    	lea    eax,[ebp-0x120]
  414b52:	83 d9 03             	sbb    ecx,0x3
  414b55:	29 f9                	sub    ecx,edi
  414b57:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  414b5b:	8b 8d d8 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x128]
  414b61:	89 44 24 0c          	mov    DWORD PTR [esp+0xc],eax
  414b65:	89 0c 24             	mov    DWORD PTR [esp],ecx
  414b68:	e8 73 a9 01 00       	call   42f4e0 <GetTextExtentPoint32A@16>
  414b6d:	8b 95 d8 fe ff ff    	mov    edx,DWORD PTR [ebp-0x128]
  414b73:	83 ec 10             	sub    esp,0x10
  414b76:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  414b7a:	8b 03                	mov    eax,DWORD PTR [ebx]
  414b7c:	89 04 24             	mov    DWORD PTR [esp],eax
  414b7f:	e8 1c aa 01 00       	call   42f5a0 <ReleaseDC@8>
  414b84:	0f b6 bb 30 19 00 00 	movzx  edi,BYTE PTR [ebx+0x1930]
  414b8b:	31 d2                	xor    edx,edx
  414b8d:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  414b90:	89 95 d0 fe ff ff    	mov    DWORD PTR [ebp-0x130],edx
  414b96:	83 ec 08             	sub    esp,0x8
  414b99:	47                   	inc    edi
  414b9a:	89 bd dc fe ff ff    	mov    DWORD PTR [ebp-0x124],edi
  414ba0:	83 c1 3c             	add    ecx,0x3c
  414ba3:	31 ff                	xor    edi,edi
  414ba5:	89 8d d4 fe ff ff    	mov    DWORD PTR [ebp-0x12c],ecx
  414bab:	90                   	nop
  414bac:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
  414bb0:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  414bb6:	0f b6 82 16 ac 43 00 	movzx  eax,BYTE PTR [edx+0x43ac16]
  414bbd:	3c 01                	cmp    al,0x1
  414bbf:	74 79                	je     414c3a <bixby110control::Bixby110DialogSetupDebug(int, int, int, int)+0x16a>
  414bc1:	3c 02                	cmp    al,0x2
  414bc3:	0f 84 1e 01 00 00    	je     414ce7 <bixby110control::Bixby110DialogSetupDebug(int, int, int, int)+0x217>
  414bc9:	3c 03                	cmp    al,0x3
  414bcb:	0f 84 b0 01 00 00    	je     414d81 <bixby110control::Bixby110DialogSetupDebug(int, int, int, int)+0x2b1>
  414bd1:	0f b6 93 30 19 00 00 	movzx  edx,BYTE PTR [ebx+0x1930]
  414bd8:	47                   	inc    edi
  414bd9:	83 85 d0 fe ff ff 58 	add    DWORD PTR [ebp-0x130],0x58
  414be0:	01 d6                	add    esi,edx
  414be2:	83 ff 03             	cmp    edi,0x3
  414be5:	7e c9                	jle    414bb0 <bixby110control::Bixby110DialogSetupDebug(int, int, int, int)+0xe0>
  414be7:	b9 00 08 00 00       	mov    ecx,0x800
  414bec:	8b 95 dc fe ff ff    	mov    edx,DWORD PTR [ebp-0x124]
  414bf2:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  414bf6:	8b 43 18             	mov    eax,DWORD PTR [ebx+0x18]
  414bf9:	b9 64 00 00 00       	mov    ecx,0x64
  414bfe:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  414c02:	8b 3b                	mov    edi,DWORD PTR [ebx]
  414c04:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  414c08:	8b 45 0c             	mov    eax,DWORD PTR [ebp+0xc]
  414c0b:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  414c0f:	89 7c 24 18          	mov    DWORD PTR [esp+0x18],edi
  414c13:	bf 49 05 44 00       	mov    edi,0x440549
  414c18:	89 7c 24 04          	mov    DWORD PTR [esp+0x4],edi
  414c1c:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  414c20:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  414c24:	8b b3 80 06 00 00    	mov    esi,DWORD PTR [ebx+0x680]
  414c2a:	89 34 24             	mov    DWORD PTR [esp],esi
  414c2d:	e8 ee b1 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  414c32:	8d 65 f4             	lea    esp,[ebp-0xc]
  414c35:	5b                   	pop    ebx
  414c36:	5e                   	pop    esi
  414c37:	5f                   	pop    edi
  414c38:	5d                   	pop    ebp
  414c39:	c3                   	ret
  414c3a:	8b 4b 18             	mov    ecx,DWORD PTR [ebx+0x18]
  414c3d:	8b 85 dc fe ff ff    	mov    eax,DWORD PTR [ebp-0x124]
  414c43:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  414c47:	8b 13                	mov    edx,DWORD PTR [ebx]
  414c49:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  414c4d:	8b 85 d0 fe ff ff    	mov    eax,DWORD PTR [ebp-0x130]
  414c53:	b9 32 00 00 00       	mov    ecx,0x32
  414c58:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  414c5c:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  414c60:	8b 55 0c             	mov    edx,DWORD PTR [ebp+0xc]
  414c63:	05 c1 ab 43 00       	add    eax,0x43abc1
  414c68:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  414c6c:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  414c70:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  414c74:	8b 8c bb 54 06 00 00 	mov    ecx,DWORD PTR [ebx+edi*4+0x654]
  414c7b:	89 0c 24             	mov    DWORD PTR [esp],ecx
  414c7e:	e8 7d b6 00 00       	call   420300 <statictext::CreateStatictext(char const*, int, int, int, int, HWND__*, HINSTANCE__*)>
  414c83:	ba 00 08 00 00       	mov    edx,0x800
  414c88:	89 54 24 20          	mov    DWORD PTR [esp+0x20],edx
  414c8c:	8b 43 18             	mov    eax,DWORD PTR [ebx+0x18]
  414c8f:	8b 95 dc fe ff ff    	mov    edx,DWORD PTR [ebp-0x124]
  414c95:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  414c99:	8b 0b                	mov    ecx,DWORD PTR [ebx]
  414c9b:	b8 32 00 00 00       	mov    eax,0x32
  414ca0:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  414ca4:	ba 49 05 44 00       	mov    edx,0x440549
  414ca9:	89 4c 24 18          	mov    DWORD PTR [esp+0x18],ecx
  414cad:	8b 8d d4 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x12c]
  414cb3:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  414cb7:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  414cbb:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  414cbf:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  414cc3:	8b 84 bb 74 06 00 00 	mov    eax,DWORD PTR [ebx+edi*4+0x674]
  414cca:	89 04 24             	mov    DWORD PTR [esp],eax
  414ccd:	e8 4e b1 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  414cd2:	8b 8d d0 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x130]
  414cd8:	0f b6 81 16 ac 43 00 	movzx  eax,BYTE PTR [ecx+0x43ac16]
  414cdf:	3c 02                	cmp    al,0x2
  414ce1:	0f 85 e2 fe ff ff    	jne    414bc9 <bixby110control::Bixby110DialogSetupDebug(int, int, int, int)+0xf9>
  414ce7:	8b 43 18             	mov    eax,DWORD PTR [ebx+0x18]
  414cea:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
  414ced:	89 44 24 14          	mov    DWORD PTR [esp+0x14],eax
  414cf1:	8b 85 d0 fe ff ff    	mov    eax,DWORD PTR [ebp-0x130]
  414cf7:	8b 13                	mov    edx,DWORD PTR [ebx]
  414cf9:	89 4c 24 08          	mov    DWORD PTR [esp+0x8],ecx
  414cfd:	05 c1 ab 43 00       	add    eax,0x43abc1
  414d02:	89 54 24 10          	mov    DWORD PTR [esp+0x10],edx
  414d06:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  414d0a:	89 44 24 04          	mov    DWORD PTR [esp+0x4],eax
  414d0e:	8b 94 bb 64 06 00 00 	mov    edx,DWORD PTR [ebx+edi*4+0x664]
  414d15:	89 14 24             	mov    DWORD PTR [esp],edx
  414d18:	e8 13 ac 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  414d1d:	b9 80 00 00 00       	mov    ecx,0x80
  414d22:	89 4c 24 20          	mov    DWORD PTR [esp+0x20],ecx
  414d26:	8b 43 18             	mov    eax,DWORD PTR [ebx+0x18]
  414d29:	8b 8d dc fe ff ff    	mov    ecx,DWORD PTR [ebp-0x124]
  414d2f:	89 44 24 1c          	mov    DWORD PTR [esp+0x1c],eax
  414d33:	8b 13                	mov    edx,DWORD PTR [ebx]
  414d35:	b8 32 00 00 00       	mov    eax,0x32
  414d3a:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  414d3e:	b9 49 05 44 00       	mov    ecx,0x440549
  414d43:	89 54 24 18          	mov    DWORD PTR [esp+0x18],edx
  414d47:	8b 95 d4 fe ff ff    	mov    edx,DWORD PTR [ebp-0x12c]
  414d4d:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  414d51:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  414d55:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  414d59:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  414d5d:	8b 84 bb 74 06 00 00 	mov    eax,DWORD PTR [ebx+edi*4+0x674]
  414d64:	89 04 24             	mov    DWORD PTR [esp],eax
  414d67:	e8 b4 b0 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  414d6c:	8b 95 d0 fe ff ff    	mov    edx,DWORD PTR [ebp-0x130]
  414d72:	0f b6 82 16 ac 43 00 	movzx  eax,BYTE PTR [edx+0x43ac16]
  414d79:	3c 03                	cmp    al,0x3
  414d7b:	0f 85 50 fe ff ff    	jne    414bd1 <bixby110control::Bixby110DialogSetupDebug(int, int, int, int)+0x101>
  414d81:	8b 4b 18             	mov    ecx,DWORD PTR [ebx+0x18]
  414d84:	8b 55 0c             	mov    edx,DWORD PTR [ebp+0xc]
  414d87:	89 4c 24 14          	mov    DWORD PTR [esp+0x14],ecx
  414d8b:	8b 8d d0 fe ff ff    	mov    ecx,DWORD PTR [ebp-0x130]
  414d91:	8b 03                	mov    eax,DWORD PTR [ebx]
  414d93:	89 54 24 08          	mov    DWORD PTR [esp+0x8],edx
  414d97:	81 c1 c1 ab 43 00    	add    ecx,0x43abc1
  414d9d:	89 4c 24 04          	mov    DWORD PTR [esp+0x4],ecx
  414da1:	89 44 24 10          	mov    DWORD PTR [esp+0x10],eax
  414da5:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  414da9:	8b 84 bb 64 06 00 00 	mov    eax,DWORD PTR [ebx+edi*4+0x664]
  414db0:	89 04 24             	mov    DWORD PTR [esp],eax
  414db3:	e8 78 ab 00 00       	call   41f930 <pushbutton::CreatePushbutton(char const*, int, int, HWND__*, HINSTANCE__*)>
  414db8:	ba 00 08 00 00       	mov    edx,0x800
  414dbd:	89 54 24 20          	mov    DWORD PTR [esp+0x20],edx
  414dc1:	8b 4b 18             	mov    ecx,DWORD PTR [ebx+0x18]
  414dc4:	8b 95 dc fe ff ff    	mov    edx,DWORD PTR [ebp-0x124]
  414dca:	89 4c 24 1c          	mov    DWORD PTR [esp+0x1c],ecx
  414dce:	8b 03                	mov    eax,DWORD PTR [ebx]
  414dd0:	b9 32 00 00 00       	mov    ecx,0x32
  414dd5:	89 54 24 14          	mov    DWORD PTR [esp+0x14],edx
  414dd9:	ba 49 05 44 00       	mov    edx,0x440549
  414dde:	89 44 24 18          	mov    DWORD PTR [esp+0x18],eax
  414de2:	8b 85 d4 fe ff ff    	mov    eax,DWORD PTR [ebp-0x12c]
  414de8:	89 4c 24 10          	mov    DWORD PTR [esp+0x10],ecx
  414dec:	89 74 24 0c          	mov    DWORD PTR [esp+0xc],esi
  414df0:	89 44 24 08          	mov    DWORD PTR [esp+0x8],eax
  414df4:	89 54 24 04          	mov    DWORD PTR [esp+0x4],edx
  414df8:	8b 8c bb 74 06 00 00 	mov    ecx,DWORD PTR [ebx+edi*4+0x674]
  414dff:	89 0c 24             	mov    DWORD PTR [esp],ecx
  414e02:	e8 19 b0 00 00       	call   41fe20 <edit::CreateEdit(char const*, int, int, int, int, HWND__*, HINSTANCE__*, unsigned long)>
  414e07:	e9 c5 fd ff ff       	jmp    414bd1 <bixby110control::Bixby110DialogSetupDebug(int, int, int, int)+0x101>
  414e0c:	8d 74 26 00          	lea    esi,[esi+eiz*1+0x0]
